### ISSUE TITLE
使用 nohup 后台运行，关闭会话下载就停止

### ISSUE THREAD

**Issue by tstts** [houtianze/bypy#101]
我是在 树莓派上用的。
nohup python ~/soft/bypy/bypy.py downfile "xxxx"
下载正常
但关闭会话后
[=============_______] 66% (200.0MB/300.518MB) ETA: 4m27s (385KB/s, 8m51s gone) /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Signal 1 received, Abort
Frame:
<frame object at 0x1208338>
Signal 1 received, Abort
Frame:
<frame object at 0x1208338>

请问有更好的方法么。

**Comment by ivo-wang** [comment]
nohup bypy syncdown >/dev/null 2>&1 &
