### ISSUE TITLE
关于token刷新问题。

### ISSUE THREAD

**Issue by jhdxr** [houtianze/bypy#103]
由于在伟大的墙内，今天刷新token的时候卡了很久，直到最后一个京东的JAE的时候才刷新成功。不知道是否方便将这个server端的程序也开放出来，然后我们自己来架刷新的server？
如果是有appkey/appsecret之类的问题的话，那能否给一个通用版，然后我们自己申请key/secret好了。这样子既能减轻你的服务器压力，也能提高服务稳定性。

btw，现在的readme.MD看着好乱，根据语言&功能，拆分出一个doc目录或者到wiki上如何。。。

**Comment by houtianze** [comment]
现在的heroku服务器算是够稳定的了，也没被墙，先关了。
