### ISSUE TITLE
下载位置的问题

### ISSUE THREAD

**Issue by liyiecho** [houtianze/bypy#107]
首先赞一下这个软件，真的很不错。就是不知道如何修改下载位置，因为是用树莓派，不想下载到tf卡，怕影响tf的寿命。望告知，谢谢了。

**Comment by houtianze** [comment]
@liyiecho 不好意思，现在才回复：

```
downdir <remotedir> [localdir] - download a remote directory (recursively)
downfile <remotefile> [localpath] - download a remote file.
```

下载时加多一个参数就可以指定本地下载位置，比如:
`bypy.py downfile /remotefile /mnt/hdd/localfile`
