### ISSUE TITLE
其他下载工具的支持？

### ISSUE THREAD

**Issue by petronny** [houtianze/bypy#110]
我个人对urllib的request没什么好感。
request健壮性不是很好的样子。。尤其是在国内各式各样的网络环境下

我见过很多次request下不了但是curl aria2都能下的情况。

能不能把downloader的API整理出来，就是说新建个downloader文件夹，下面有urllib.py curl.py什么的。  
然后bypy.py中从里面调下载工具。

可以不着急写命令行参数，把API整理一下，downloader下面的curl.py什么的接口留好。  
建好以后我们来填坑。至少我会把curl的填了。。。

**Comment by houtianze** [comment]
谢谢建议。
现在程序所有的http请求都是通过`__request_work()`来完成的，只要把里面调用`request`部分替换实现了了，按理应该可以工作。做成下载后端可替换的可能以后再说：）

**Comment by duekdhx** [comment]
其他都很好就是真的非常有必要支持aria2……前几周还好最近速度很难1mb以上，几十mb的下载都要重试好几次……望改进谢谢！

**Comment by houtianze** [comment]
考虑一下，不过多线程下载改动很大，真的要做也会需要一段时间。谢谢建议。

**Comment by petronny** [comment]
我觉得像`ls`或者其他获取少量信息的这些命令就还用`__request_work()`了吧
仅仅把__需要在本地创建文件__的相关函数替换了就好？
比如downfile,__downfile,downfile_act,downchunk等等。。。

//不过看起来相关的函数有点多。。。究竟哪一个才是我要改的呢。。。

**Comment by petronny** [comment]
话说什么外部工具都不用，仅仅使用python的并行和文件拼接就能用urllib或者pycurl做个多线程下载。
* 可以认为urllib和pycurl是等价替代
bcloud好像就是这么做的。

不过这样的话，现有的断点续传策略就需要更改了，比如：
* 方案一：新建一个文件记录哪些块下载完了，下次读这个文件来继续下载
* 方案二：把每个下好的块存成一个文件，然后再把这些块拼起来

你们觉得那个好？挑一个我去试试。

**Comment by houtianze** [comment]
嗯，可以试试。代码已经分路走，我就不merge了。
才知道[bcloud](../../../LiuLang/bcloud)项目，比我这个高大上多了，要是早点明白百度验证的方法，就不这么费事搞PCS授权之类的了，还没目录权限限制。

**Comment by petronny** [comment]
别泄气，咱只要专心做好CLI就行了。。
也可以借鉴一下bcloud的登陆方式，改进改进

**Comment by houtianze** [comment]
登陆方式确实值得改进，直接登陆就可以拿到全部的权限了，而不是受限于`/apps`目录。

**Comment by houtianze** [comment]
嗯，多线程下载还是很实用了。

**Comment by dukedhx** [comment]
可以参考bcloud的下载实现和PCS授权恩，下载性能和目录限制取消的话和bcloud很互补的，毕竟bcloud没有shell，我想直接用在pi或nas上就行不通了toka

**Comment by houtianze** [comment]
嗯，取消目录限制这个很实用，否则老感觉别扭。

**Comment by ibegyourpardon** [comment]
我倒是觉得虽然说起来限制目录好像有一些麻烦，但其实是好事。像Dropbox一 
样，专心同步好自己目录下的文件就可以，不用操心别的目录的事。 我没洁癖， 
但我相信肯定有些人不愿意放开所有的目录给一个app随意读取——虽然百度自己都 
能看遍，但心理上还是不愿意给第三方的全部放开的。

**Comment by houtianze** [comment]
@ibegyourpardon 取消目录限制的实现是抛弃pcs接口（不需要再走oauth），而是直接通过用户名密码登陆的，这一切都是只跟百度打交道，没有第三方参与（也就不会有任何隐私问题），从而“真正意义”上实现一个完全功能的客户端：）

**Comment by houtianze** [comment]
aria2算是粗略的支持了，先关了。

**Comment by petronny** [comment]
手动赞一个，回来参与测试
