### ISSUE TITLE
第一次运行出错

### ISSUE THREAD

**Issue by yu-yuxuan** [houtianze/bypy#117]
出错信息如下
python bypy.py info
  File "*****/bypy/bypy.py", line 124
    __version__ = 1.0.6
                      ^
SyntaxError: invalid syntax

**Comment by GoldCome** [comment]
编辑下bypy.py这个文件 把<code>version = 1.06</code> 改为 <code>version = ‘1.06’</code>就行了

**Comment by yu-yuxuan** [comment]
确实如此，学习

**Comment by houtianze** [comment]
大意了，感谢 @GoldCome  指正，已经修改 checked-in.
