### ISSUE TITLE
关于upload问题

### ISSUE THREAD

**Issue by ywandy** [houtianze/bypy#123]
最近用bypy.py upload上传时无法上传出现 <E> [08:14:11] Waiting 10 seconds before retrying...
<E> [08:14:21] Request Try #2 / 5
<E> [08:14:21] Waiting 20 seconds before retrying...

调试信息是：
 root@yewei:/yyw# bypy.py upload work /work -d
Token file: '/root/.bypy.json'
Hash Cache file: '/root/.bypy.pickle'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
----

<D> Token loaded:
<D> {u'access_token': u'21.828a435f0d7c874e73a3bc55834fe900.2592000.1426231222.3324810012-1572671', u'expires_in': 2592000, u'session_secret': u'4e0e56298c9297915656a09aeff276e9', u'scope': u'basic netdisk', u'session_key': u'9mnRfCAFY7TX4kj15XViIu3acM7Y4Pz/9Oi27+Va6jOPhwzuXfD86nqQ3gd/FmqhVANfkLYdOfSWRQ3tlgzyNjuW5oNlHDMQTQ==', u'refresh_token': u'22.2ca68f64bac3838f25ee53119442f263.315360000.1738999222.3324810012-1572671'}
<D> Uploading directory 'work' recursively
<D> Uploading directory 'work' to '/apps/bypy/work'
<D> Making remote directory '/apps/bypy/work'
<D> POST https://pcs.baidu.com/rest/2.0/pcs/file<D> actargs: None
<D> Params: {u'path': u'/apps/bypy/work', u'method': u'mkdir'}
<D> HTTP Status Code: 400
<D> __get_file_info(): rdir : /apps/bypy/work | rfile: a.c
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/work/a.c
<D> Params: {u'path': u'/apps/bypy/work', u'order': u'asc', u'method': u'list', u'by': u'name'}
<D> HTTP Status Code: 200
<D> Request OK, processing action
<D> List json: {u'list': [], u'request_id': 2513486647L}
<D> 'work/a.c' is small and being non-slicing uploaded.
<D> POST https://c.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/work/a.c
<D> Params: {u'path': u'/apps/bypy/work/a.c', u'ondup': u'overwrite', u'method': u'upload'}
<E> [08:14:57] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [08:14:57] Exception: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bypy-1.0.3-py2.7.egg/EGG-INFO/scripts/bypy.py", line 1023, in __request_work
    params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

<E> [08:14:57] Function: __upload_one_file_act
<E> [08:14:57] Website parameters: {u'path': u'/apps/bypy/work/a.c', u'ondup': u'overwrite', u'method': u'upload'}
<E> [08:14:57] Waiting 10 seconds before retrying...
<E> [08:15:07] Request Try #2 / 5
<D> POST https://c.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/work/a.c
<D> Params: {u'path': u'/apps/bypy/work/a.c', u'ondup':

貌似跟ssl有关，望作者解答。谢谢

 u'overwrite', u'method': u'upload'}

**Comment by houtianze** [comment]
这个是因为最近百度的证书在Linux下无法通过验证，暂时可以通过加`--disable-ssl-check`方法来解决。我尽快找一个号的方法把这个问题解决。
