### ISSUE TITLE
首次运行出现如下错误，请帮忙看看。

### ISSUE THREAD

**Issue by chovan** [houtianze/bypy#124]
You Python Requests Library version is to lower than 1.
You can run 'pip install requests' to upgrade it.
Traceback (most recent call last):
  File "/usr/bin/bypy.py", line 249, in <module>
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

运行了pip install requests 后的输出是：
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages
Cleaning up...

运行环境：
python -V
Python 2.7.3
pip --version
pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
uname -a 
Linux HomeServer 3.2.0-4-686-pae #1 SMP Debian 3.2.63-2+deb7u2 i686 GNU/Linux

**Comment by ywandy** [comment]
执行sudo apt-get remove python-requests  删掉旧版本的requests然后sudo pip install request 来安装新版本的

**Comment by chovan** [comment]
可以了。谢谢！
