### ISSUE TITLE
新人问问bypy对cron的支持是怎样的？

### ISSUE THREAD

**Issue by chovan** [houtianze/bypy#125]
现在我设定bypy在我的Dabian下载机上运行。因为在一定时段内需要留出带宽给网络内的其他用户，需要定时对bypy暂停或者限速。
查了一下bypy似乎没有类似的命令参数。请问有没有可能实现？

难道要用Kill -9 python?

**Comment by houtianze** [comment]
有对signal的支持，所以`kill -HUP`应该是可行的。可能要写个脚本来通过pid来kill吧。

**Comment by chovan** [comment]
查了一下，下面的命令可以逐个Kill Python的进程：
ps aux | grep python | grep -v "grep python" | awk '{print $2}' | xargs kill -9
但这样Kill了以后，再次使用syncup指令的话，会不会重新上传已经传完的文件呢？

**Comment by houtianze** [comment]
不会。sycnup会先做一个远程和本地的比较再上传，只传不同的，所以唯一会重新上传的就是被kill是还未传完的那个文件。
新年快乐~

**Comment by chovan** [comment]
Great! 谢谢！新年快乐！
