### ISSUE TITLE
特性请求：指定PCS节点

### ISSUE THREAD

**Issue by septs** [houtianze/bypy#127]
指定PCS节点 可以提高下载速度

see http://ritzonex.co/?p=38
see https://github.com/ly0/baidupcsapi/blob/master/baidupcsapi/api.py#L137-L152
see https://github.com/ly0/baidupcsapi/blob/master/baidupcsapi/api.py#L154-L160
#61

**Comment by houtianze** [comment]
感谢建议。不好意思才回复。
我想想怎么放进去。

**Comment by houtianze** [comment]
看了一下那些结点，有个小问题是证书都是设置pcs.baidu.com，跟结点的域名不符，会有警告。可能加入后就一定要禁用SSL check了。

**Comment by houtianze** [comment]
最先的版本加入了--mirror switch可以用来选择结点。

**Comment by Septembers** [comment]
希望加入mirror-test命令以方便测试最快节点

**Comment by houtianze** [comment]
加了个`--select-fastest-server`命令行参数，自动选择最快镜像。
