### ISSUE TITLE
特性请求：并行 上传/下载

### ISSUE THREAD

**Issue by septs** [houtianze/bypy#128]
我的思路：
1. 大文件（大于10MiB）：
        利用request header - range对文件切片
        经过测试单文件最大可以有8个线程同时下载(UserAgent似乎需要为"netdisk")
        单线程最大下载速度2MiB/s
        多线程并发单文件最大下载速度8MiB/s
2. 小文件（小于10MiB）：
        直接并行 上传/下载

然后利用[multiprocessing.Pool.map_async](https://docs.python.org/2/library/multiprocessing.html#multiprocessing.pool.multiprocessing.Pool.map_async)进行异步并行 上传/下载

see https://docs.python.org/2/library/multiprocessing.html#using-a-pool-of-workers
#61

**Comment by houtianze** [comment]
感谢建议和指出Python库。我想想怎么做吧，不过现有code改成并行应该需要些时间。

**Comment by TerrorJack** [comment]
@houtianze 请问bypy是否可以多进程使用？谢谢！

**Comment by houtianze** [comment]
@TerrorJack ，多线程和rate limit现在都没有，估计我一时半会儿也弄不出来。。。抱歉。

**Comment by houtianze** [comment]
这个希望也许我以后有时间能加上（也许。。。）

**Comment by houtianze** [comment]
实现了多**进**程并发(`--processes`)。但没有实现大文件切片上传下载。上传下载有很多文件的目录应该会有提速，大文件下载可以用`aria2`来凑合提速，（不可秒传的）大文件上传还是单进程。
