### ISSUE TITLE
下载文件权限

### ISSUE THREAD

**Issue by notyet** [houtianze/bypy#130]
你好，下载云盘文件时会遇到 Permission denied 的错误，下载的文件只有其它用户（Other）有执行权限 （- - - - - - - - x）。请问怎么解决？

**Comment by Chunlin-Li** [comment]
我在使用的时候也遇到类似问题.
OS :ubuntu 14.04
使用 downdir 命令下载文件夹时, 发现下载下来的文件夹 其权限是  d--------- 因此继续下载该文件夹下的文件时会报错无法下载. 
看了代码, 创建本地文件夹使用的是  os.makedirs , 其中传入的默认 mode 应该是 0777.  但是在调用该方法的时候, 传入的实际参数是 self.Verbose . 
不太清楚这个参数是做什么用的. 我目前使用的  workaround 就是将 makedir function中的 mode 写死为 0777 , 而不是由参数设置.  
请问 houtianze 大人, 这是我使用不当还是代码中确实有混淆的地方呢?

**Comment by Septembers** [comment]
https://github.com/houtianze/bypy/blob/master/bypy.py#L2259
https://github.com/houtianze/bypy/blob/master/bypy.py#L2378
https://github.com/houtianze/bypy/blob/master/bypy.py#L2784
https://github.com/houtianze/bypy/blob/master/bypy.py#L2785
https://github.com/houtianze/bypy/blob/master/bypy.py#L2802

makedir的签名是makedir(path, mode, verbose)
请问这里是否是失误
建议修改为makedir(path, verbose)
https://github.com/houtianze/bypy/blob/master/bypy.py#L1014
修改为makedir(ConfigDir, mode = 0700)

**Comment by houtianze** [comment]
刚刚修复，下最新版试试吧。

@notyet 感谢反馈。
@Chunlin-Li @Septembers 感谢找到问题。嗯，就是参数传递问题-_-

@Chunlin-Li ，确实是代码里弄混淆了，你说的没错。self.Verbose就是决定是否让程序输出一下创建过程。另，叫我名/id就好了，实在不是啥“大人”：）
