### ISSUE TITLE
能支持上传种子文件进行离线下载么？

### ISSUE THREAD

**Issue by jackywu** [houtianze/bypy#132]
能支持上传种子文件进行离线下载么？

**Comment by ibegyourpardon** [comment]
百度云都快被玩坏了，bt下载也越来越不靠谱了。
而且话说种子离线下载的话有对应的api么。。

**Comment by houtianze** [comment]
这个文档：
http://developer.baidu.com/wiki/index.php?title=docs/pcs/rest/file_data_apis_list

貌似没有bt离线下载接口。。
