### ISSUE TITLE
出错？  InsecurePlatformWarning

### ISSUE THREAD

**Issue by hejunhui** [houtianze/bypy#135]
# bypy list

Token file: '/root/.bypy/bypy.json'
Hash Cache file: '/root/.bypy/bypy.pickle'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
## sys.stderr.encoding = UTF-8

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/apps/bypy ($t $f $s $m $d):

**Comment by houtianze** [comment]
https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning

看这个文档，貌似这个是最新版的urllib3引起的，解决方案有两个：
- 升级Python2到最新版本(2.7.9或以上）
或：
- 运行时加上`--disable-ssl-check `参数，禁用ssl检查。

看来又得升级下异常处理代码了。

**Comment by houtianze** [comment]
改了一下，暂时强制禁用ssl检查。

**Comment by houtianze** [comment]
最新版强制`requests` 2.10或以上，这个问题应该已经解决。
