### ISSUE TITLE
特性请求：环境可用性检查

### ISSUE THREAD

**Issue by septs** [houtianze/bypy#136]
检查环境可用性 可以用于规避类似这样 #135 #103 #10 #105 #104 #82 #109 #5 的问题
- [ ] 当前操作系统
- [ ] 当前Python版本
- [ ] 是否有权限操作`$HOME/.bypy`
- [ ] 当前urllib3版本
- [ ] 当前requests版本
- [ ] 当前requests必要功能检查
- [ ] 环境编码
- [ ] 检查`token`是否过期
- [ ] 检查授权服务是否可用
- [ ] 检查PCS服务是否可用

这样做的好处
1. 方便部署 自查问题
2. 方便生成报告以便于问题分析
3. 另外一方面可以减小`bypy.py`对环境兼容判断的代码

**Comment by petronny** [comment]
我强烈建议把这个部分单独列成一个文件，chkenv.py这样
模块化总要从一个时刻开始吧？


On Sun, Mar 22, 2015 at 04:59:35AM -0700, Sept wrote:
> 1. 检查环境可用性 可以用于规避类似这样 #109, #5 的问题
> ```
> 当前Python版本
> 是否有权限操作$HOME/.bypy
> 当前urllib3版本
> 当前requests版本
> 等等
> ```
> 2. 检查`token`是否过期
> 3. 检查PCS服务是否可用
> 这样做好处
> 1. 方便部署 自查问题
> 2. 方便生成报告以便于问题分析
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/houtianze/bypy/issues/136

-- 
Jingbei Li
Department Of Computer Science, Tsinghua University
Emails:	i@jingbei.li
Homepage: http://jingbei.li/
TEL:+86-13389921221
Addr: Room 611A, Building No.2, Zijing Dormitory, Tsinghua University, Beijing, China
ZIP Code:100084

**Comment by houtianze** [comment]
@Septembers 感谢建议。这段时间有点忙，一直没啥时间弄这个（包括之前的两个特性），抱歉。等闲了我来改改。

**Comment by houtianze** [comment]
@petronny 感谢建议。我考虑一下，当初做成一个文件的想法是尽可能简单，一个文件随便在哪就能用 ：）

**Comment by Septembers** [comment]
这个特性提议可作为 自检 存在

**Comment by Septembers** [comment]
#153 这样的问题你玩下去不是事啊，一问一答，**各种锁碎的环境信息和跟用户要起来各自都烦**。

**Comment by houtianze** [comment]
嗯，现在自检已经有一部分了（Python版本等等），看来还得加强一些，只是最近一段时间一直没静下心来搞。

**Comment by Septembers** [comment]
启动自检失败不让用

**Comment by houtianze** [comment]
感谢建议。

现在经过重构后，环境检测做得差不多了。（主要是`setup.py`里添加了`requests`依赖和最低版本要求）。
