### ISSUE TITLE
性能优化：使用gdbm代替cPickle可提高缓存处理性能

### ISSUE THREAD

**Issue by septs** [houtianze/bypy#137]
https://docs.python.org/2/library/gdbm.html

性能参考：
https://www.v2ex.com/t/85981#r_805098
http://semidbm.readthedocs.org/en/latest/benchmarks.html

**Comment by houtianze** [comment]
感谢建议。

**Comment by Septembers** [comment]
请问什么时候可应用该特性，缓存加载速度真的比较慢。

**Comment by houtianze** [comment]
我看看下周吧（不过不保证，经常犯懒，见谅 :smile: ），月底有点忙。
确认一下：加载速度慢是指程序启动时的时间教久对吧？有多慢？几秒？

**Comment by houtianze** [comment]
现在是用json做缓存，性能上也还可以，所以gbdm估计就不加了，抱歉。
