### ISSUE TITLE
【特性请求】允许设置针对硬盘的读/写缓存

### ISSUE THREAD

**Issue by memoz** [houtianze/bypy#139]
用了2天，发现优于bcloud的地方是能够断线自动重试，中间也不会卡住，没有内存泄露的问题，好棒~
不过看过下面的统计后略心疼硬盘呵~
![latency](https://cloud.githubusercontent.com/assets/11746178/6932636/d9bca23c-d84e-11e4-870b-33ce140182f2.png)
![throughput](https://cloud.githubusercontent.com/assets/11746178/6932635/d9bc81f8-d84e-11e4-8f99-092415e25750.png)
下载保存位置在sdb上，下载速度大概是1M/s。从上图可见应该是每下载一块就flush到硬盘的吧......租的VPS之类咱就不考虑了，但是自己的电脑还是比较爱惜的说......所以可以考虑加个类似BT客户端的读/写缓存什么的吗？

**Comment by Septembers** [comment]
1. 建议预分配空间
2. 建议4K写入（有利于提高性能且对SSD友好）

**Comment by petronny** [comment]
但是我觉得现在代码里就是打算一个chunk(20mb)一写的啊。。
为什么还会出现这种情况呢。。。

**Comment by houtianze** [comment]
对啊，当初想过这个事情，现在默认是20mb一写（只有一个线程），所以硬盘io应该还好吧。不太懂问题在哪。

**Comment by houtianze** [comment]
@Septembers 感谢建议，我看看相关文档。

**Comment by jimmyye** [comment]
如果代码没有问题，我觉得只是是监控图的显示粒度大而已。
两张图都是一个星期的数据，所以显示时不会显示小粒度数据（而且还要看监控的频率）。
假设下载速度是1m/s，则20秒才写硬盘一次，如果监控图的每个点是5分钟的数据，每5分钟下载300m，同时当然也写入300m，所以每5分钟硬盘写入速度都是1m/s，所以监控图上的点会一直保持在高位。

**Comment by houtianze** [comment]
感谢 @jimmyye 的解释，感觉应该是这个原因了。
