### ISSUE TITLE
有没有办法把web版云盘离线下载的文件放到/apps/bypy目录里来，让树莓派来下载？

### ISSUE THREAD

**Issue by jackywu** [houtianze/bypy#141]
你好，tianze，没办法找到你的直接联系方式，所以不好意思在这里咨询你一个问题。
有没有办法把web版云盘BT离线下载的文件放到/apps/bypy目录里来，让树莓派来下载？

**Comment by houtianze** [comment]
你好。
可以啊，只要文件在/apps/bypy目录下，用bypy.py就可以下载。
bypy.py没法存取/apps/bypy目录下任何文件，所以这个移动过程要手动（或者其他程序）来做。

**Comment by petronny** [comment]
@houtianze 主要问题是pan.baidu.com使用bt离线的文件根本不在/下
链接的可以存到路径里，但是bt的不行。
你可以试试。

**Comment by houtianze** [comment]
@petronny 额，没太看懂。刚试了一下，下载的文件是可以移动到任何目录的。

**Comment by petronny** [comment]
额。。。现在有存放路径的选项了。。好吧。

**Comment by jackywu** [comment]
@petronny @houtianze , 比如我在云盘页面版里，用bt种子下来了一个电影到了 "Movie" 目录里，我怎么用bypy下载到自己的笔记本上？

**Comment by houtianze** [comment]
@jackywu 放到/apps/bypy就可以下载了，和其他文件一样。

**Comment by jackywu** [comment]
@houtianze 我找了好久都没有研究出来怎么上传一个bt种子，然后把种子离线下载的文件放到/apps/bypy里去。能否指点我一下？

**Comment by houtianze** [comment]
@jackywu 去 pan.baidu.com，找到离线下载完成的文件，右键，“移动到。。。“，然后目标目录选择/apps/bypy就可以了。

**Comment by ibegyourpardon** [comment]
他的意思可能是想自动移动文件。。。。。
这个做不到吧。。。

**Comment by jackywu** [comment]
@houtianze 右键，“移动到。。。“，出来的对话框里，/apps/bypy 是不可见的，无法选择。

**Comment by Septembers** [comment]
由于百度PCS API权限限制，程序只能存取百度云端/apps/bypy目录下面的文件和目录。

**Comment by houtianze** [comment]
@jackywu ，这个/apps目录对应的对话框里叫”我的应用数据“ :smile:

**Comment by jackywu** [comment]
@houtianze 原来如此，多谢。
