### ISSUE TITLE
暂停/续存

### ISSUE THREAD

**Issue by chouex** [houtianze/bypy#142]
上传和下载時用什么方法暂停,另外中途退出后可以续存吗

**Comment by houtianze** [comment]
下载可以Ctrl-C强行中断，再下载时默认是断点续传的。
上传中断就，那个正在上传是未传完的文件现在就只能从头再传了。

**Comment by chouex** [comment]
如果上传也可以断点续传就更好了

**Comment by Septembers** [comment]
百度云PCS API不支持断点续传

**Comment by houtianze** [comment]
嗯，上传不支持断点续传。不过大文件也许可以考虑分片上传之后记录下分片的MD5值，只传余下部分再合并。不过不知道分片上传的临时文件会保存多久，真要加上也要先试试是否可行先。

**Comment by houtianze** [comment]
忘记是谁贡献的pr，现在分片上传是有`json`记录的了，如果分片没过期（貌似一天以内？），已经上传的分片中断后不会再次上传。请用`pip -U`安装最新版。
