### ISSUE TITLE
云端解压

### ISSUE THREAD

**Issue by violetcherry** [houtianze/bypy#145]
在百度云网页端提供了在线解压的功能，能否在这个客户度添加解压功能呢？

**Comment by Septembers** [comment]
bypy是基于PCS API实现的
PCS API不提供该API因此目前无法实现

**Comment by fanghuan** [comment]
原来如此~

**Comment by houtianze** [comment]
@xslidian 加入了这个功能（我未测试）。

**Comment by xslidian** [comment]
重构后的 bypy，如果还存在 bduss 相关的代码，麻烦作者清理一下吧～

我的主账号被百度云限制使用了，客服不给正面答复，不知道是否与使用网页端 API 有关。
为了保险起见，建议从 master 分支移除相关代码，以免误伤他人🤐

**Comment by houtianze** [comment]
那个class以前已经分离了（现在是`ByPy`一个子类），在代码中并没有启用 😄 
感谢告知 😀
