### ISSUE TITLE
请在更稳定的服务器比如heroku上搭建oauth服务...

### ISSUE THREAD

**Issue by roylez** [houtianze/bypy#151]
其实我是盗用了你的key写了另外一个客户端 [yuncli](http://github.com/roylez/yuncli)。我试过 rhcloud 和 jd-app 两个服务器，都很不稳定。希望能够在 heroku 搭建一个新的服务器。heroku免费级别的服务已经足够。

**Comment by ibegyourpardon** [comment]
真不行我赞助台。。。。

2015-05-03 22:19 GMT+08:00 Roy Zuo <notifications@github.com>:

**Comment by houtianze** [comment]
还可以这么玩儿 :grinning: 
我看看Heroku，JD的不行，没想到红帽的也不稳定，我尽快再搭一个Heroku的。

**Comment by houtianze** [comment]
Heroku server来了，作为Openshift的后备。拿掉JAE了，根本没有稳定性。
3d110a9c422576e42679c6f3c72f0a00d90bedc9

**Comment by roylez** [comment]
```
I, [2015-05-25T06:51:08.957920 #82128]  INFO -- : REQUEST: https://bypyoauth.herokuapp.com?code=d5fff2499d6293dbe60f48fff6a8af9f&redirect_uri=oob
W, [2015-05-25T06:51:09.260258 #82128]  WARN -- : AUTHENTICATION:
W, [2015-05-25T06:51:09.260385 #82128]  WARN -- : "bypyoauth\nUpdated: Sun May 24 22:49:10 2015\n"
```
不知道是不是只有我一个人遇到这样的

**Comment by houtianze** [comment]
url错了吧，应该是下面这个这个吧？：
`https://bypyoauth.herokuapp.com/auth?code=d5fff2499d6293dbe60f48fff6a8af9f&redirect_uri=oob`

**Comment by roylez** [comment]
确实是我弄错了 :satisfied:
