### ISSUE TITLE
[ltnetcase]关于无法获得授权码的问题

### ISSUE THREAD

**Issue by petronny** [houtianze/bypy#154]
@ltnetcase 把这个问题发到wiki页面去了。。。
我搬运了一下

--------

在首次运行bypy.py info后报如下信息：

> Please visit:

> https://openapi.baidu.com/oauth/2.0/authorize?scope=basic+netdisk&redirect_uri=oob&response_type=code&client_id=q8WE4EpCsau1oS0MplgMKNBn

> And authorize this app

> Paste the Authorization Code here within 10 minutes.

> Press [Enter] when you are done

打开这个URL，报如下错误：

> 您遇到了错误！
>
>    错误代码：invalid_scope

>    错误信息：scope is invalid

>    详细描述：所请求的扩展权限尚未开放，关于权限的具体信息请开发者参考“权限列表”

这个不知道应该如何破？

**Comment by ltnetcase** [comment]
Sorry, 是否还需要提供其他debug信息？我可以补充。这个现在可以破掉么？

**Comment by houtianze** [comment]
- 是不是授权时不消息勾掉了`在您的百度云创建文件夹并读写数据`选项，造成权限不够？应该可以去百度的 [账号关联](https://passport.baidu.com/accountbind) 页面里把 `百度个人云存储Python客户端` 解除关联，再去那个链接授权试试？
- 是不是cookie问题？试着退出百度登陆再打开这个链接或者开多一个隐身的浏览器窗口再授权。

**Comment by ltnetcase** [comment]
我原来弄过一个测试的APP，把那个APP的关联解除了就授权成功了，多谢。回头晚些时候试试能不能传文件。

**Comment by ltnetcase** [comment]
已测，很好用，多谢。
