### ISSUE TITLE
版本号与升级

### ISSUE THREAD

**Issue by chovan** [houtianze/bypy#158]
问一个傻傻的问题：如何判断我现在的程序是哪个版本呢？ 如何升级更新过的程序，只需要覆盖pypy.py?

**Comment by houtianze** [comment]
这个问题不傻 ：）

1. 现在在`bypy.py`里有个`__version__`变量来标记版本（不过我经常忘记更新），所以现在最可靠的版本盘底就是从github这里下载 -_-!
2. 嗯，直接覆盖bypy.py（或下载zip解压覆盖）就行。或者`git pull`。

**Comment by chovan** [comment]
OK. 谢谢！

**Comment by houtianze** [comment]
不客气，这个我考虑改进一下。

**Comment by houtianze** [comment]
好吧，现在正式版都发布到 https://pypi.python.org/pypi/bypy
这里有两个branch，`dev`是活跃修改的那条，`master`是修改差不多merge过去的。
