### ISSUE TITLE
上传上去了，但是百度盘中没有显示出来？

### ISSUE THREAD

**Issue by TangMonk** [houtianze/bypy#159]
谢谢你的项目。:D

我在使用syncup的时候，同步一些从国外下载下来的视频，然后syncup到百度盘，但是不知道怎么会事，有些目录他就是再怎么样也传不上去，虽然命令行显示传上去了

**Comment by chovan** [comment]
百度盘有时候会是这样，不是这个程序的问题。 我曾经通过 multcloud.com同步也有同样问题，要等一段时间再刷新才会出现。

**Comment by TangMonk** [comment]
这个过一段时间一般是过多久阿。。过了一天貌似都还没好

**Comment by houtianze** [comment]
这样的啊，第一次听说有这样的问题，重新传也没有？

**Comment by TangMonk** [comment]
@houtianze ，嗯，对阿，重新传也没有，文件大约有4g, 最后我传到dropbox上去了。 我用的是vultr.com的vps，日本机房

**Comment by houtianze** [comment]
能帮忙贴下整个`bypy.py -dv ...`的输出吗？（如果之前上传成功，应该是可以秒传，很快的）

**Comment by TangMonk** [comment]
@houtianze 没问题，不过估计要等一天了。。速度太慢。。

**Comment by TangMonk** [comment]
这个是log:

Token file: '/root/.bypy/bypy.json'
Hash Cache file: '/root/.bypy/bypy.pickle'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = None
sys.stderr.encoding = UTF-8
----

Combining the following MD5 slices:
e90f96f16cde542fa1688def304a53f2
c042934202965aa332eb7df5e87acde8
918a59623a7f8108dfc276e10a89d243
bc5e69b086d53031e7604f4d669f9f2a
a4491bd0a17ba94770081dde20abae02
b264d0eadcb167598a6e8fc93e15e6b8
340b92fc6802e1777bbfa01fe8ffcb6a
dead51696ba6a83cd91226321c6dfac9
95d8e58b809a69b0a0f1b382b3fbbd62
1e15e7e7fa516af5a7992ac1c768a268
119b786ee507eb3b456a36e810f82864
910184ad592b858df68252d6f2a3a29a
6c23979fa6ca02407a21eac7c5ec9038
ddcd15286628c8fdd352b96414e07a51
e29f8f0127b73653f785fa3e7b6cbb33
3648b9f70b830cb10ff09b193d032621
d8a1c5d6a1a0adb00bea6ce670853e99
341d72f6ef1129ceb642395d9db6c4e7
de61ae18920d761facc4fcdada3d2924
82dd1865803ca57df7b35bba9b5168ac
7519cecb6de38195c4980e94af034b1b
4f951688074b119598c327dd781bf5d4
9604cf24627c559326a6eb3dceba0f24
8ea5495313354957acbd8fc3195b1c74
e1cdcddba6d3c647bc41d5104b5542cc
ebf6857c71e8b3f83b4dd808abaef6c0
00ef6065656f23cdb4cfc2c4ff920b24
2a4ca68bffe21da8e9bb353e57cbe082
cdaa04c31094ad8e0914a6ee54ee81f5
<E> [08:57:03] Waiting 10 seconds before retrying...
<E> [08:57:13] Request Try #2 / 5
<E> [08:57:17] Waiting 10 seconds before retrying...
<E> [08:57:27] Request Try #2 / 5
<E> [08:57:34] Waiting 10 seconds before retrying...
<E> [08:57:44] Request Try #2 / 5
Combining the following MD5 slices:
e90f96f16cde542fa1688def304a53f2
c042934202965aa332eb7df5e87acde8
918a59623a7f8108dfc276e10a89d243
bc5e69b086d53031e7604f4d669f9f2a
a4491bd0a17ba94770081dde20abae02
b264d0eadcb167598a6e8fc93e15e6b8
340b92fc6802e1777bbfa01fe8ffcb6a
dead51696ba6a83cd91226321c6dfac9
95d8e58b809a69b0a0f1b382b3fbbd62
1e15e7e7fa516af5a7992ac1c768a268
119b786ee507eb3b456a36e810f82864
910184ad592b858df68252d6f2a3a29a
6c23979fa6ca02407a21eac7c5ec9038
ddcd15286628c8fdd352b96414e07a51
e29f8f0127b73653f785fa3e7b6cbb33
3648b9f70b830cb10ff09b193d032621
d8a1c5d6a1a0adb00bea6ce670853e99
341d72f6ef1129ceb642395d9db6c4e7
de61ae18920d761facc4fcdada3d2924
82dd1865803ca57df7b35bba9b5168ac
7519cecb6de38195c4980e94af034b1b
4f951688074b119598c327dd781bf5d4
9604cf24627c559326a6eb3dceba0f24
8ea5495313354957acbd8fc3195b1c74
e1cdcddba6d3c647bc41d5104b5542cc
ebf6857c71e8b3f83b4dd808abaef6c0
00ef6065656f23cdb4cfc2c4ff920b24
2a4ca68bffe21da8e9bb353e57cbe082
cdaa04c31094ad8e0914a6ee54ee81f5
bc1713b35dc13b352d3a9c1663c9eca6
9cf92917b59146f769347a9d3c7a1a15
7f1ca12ddc085be180c7a60ad3e087fd
51b8a538e3e591b86ab10f113a22fd29
5b349e42d33134ad26fbb8633288b2c8
05b8e2c4407b72844532e0dcf11a40a1
094545729b2aab201bc709e73e2e641e
0ce06d680227866e07fe663976c19020
25f444abbf3b673e8aa999e6a8516f0f
9c4b8922a465332aed44c38b2c38bec5
880e037ce6e41c5724cb5f5d99a3f3aa
4a1c97aa0081ce02ba9baaff8476df39
d181455857e56877dda6331bd291d3a9
7de5b012ab26864671cc5e6281127681
cb2d09dcc34248f998b855408e4dfe19
9af2d179236c24dc335c5cf9f6748567
158271f26b3c006e3ef612b51a47691c
bbb0072f91fe48c0b5e0bbeabd113a64
ed06a33838f647bde07b9352365700f9
130f0521d13fa86c6978dbeb9e7ff5ad
<E> [09:23:06] Waiting 10 seconds before retrying...
<E> [09:23:16] Request Try #2 / 5
<E> [09:23:20] Waiting 10 seconds before retrying...
<E> [09:23:30] Request Try #2 / 5
Combining the following MD5 slices:
e90f96f16cde542fa1688def304a53f2
c042934202965aa332eb7df5e87acde8
918a59623a7f8108dfc276e10a89d243
bc5e69b086d53031e7604f4d669f9f2a
a4491bd0a17ba94770081dde20abae02
b264d0eadcb167598a6e8fc93e15e6b8
340b92fc6802e1777bbfa01fe8ffcb6a
dead51696ba6a83cd91226321c6dfac9
95d8e58b809a69b0a0f1b382b3fbbd62
1e15e7e7fa516af5a7992ac1c768a268
119b786ee507eb3b456a36e810f82864
910184ad592b858df68252d6f2a3a29a
6c23979fa6ca02407a21eac7c5ec9038
ddcd15286628c8fdd352b96414e07a51
e29f8f0127b73653f785fa3e7b6cbb33
3648b9f70b830cb10ff09b193d032621
d8a1c5d6a1a0adb00bea6ce670853e99
341d72f6ef1129ceb642395d9db6c4e7
de61ae18920d761facc4fcdada3d2924
82dd1865803ca57df7b35bba9b5168ac
7519cecb6de38195c4980e94af034b1b
4f951688074b119598c327dd781bf5d4
9604cf24627c559326a6eb3dceba0f24
8ea5495313354957acbd8fc3195b1c74
e1cdcddba6d3c647bc41d5104b5542cc
ebf6857c71e8b3f83b4dd808abaef6c0
00ef6065656f23cdb4cfc2c4ff920b24
2a4ca68bffe21da8e9bb353e57cbe082
cdaa04c31094ad8e0914a6ee54ee81f5
bc1713b35dc13b352d3a9c1663c9eca6
9cf92917b59146f769347a9d3c7a1a15
7f1ca12ddc085be180c7a60ad3e087fd
51b8a538e3e591b86ab10f113a22fd29
5b349e42d33134ad26fbb8633288b2c8
05b8e2c4407b72844532e0dcf11a40a1
094545729b2aab201bc709e73e2e641e
0ce06d680227866e07fe663976c19020
25f444abbf3b673e8aa999e6a8516f0f
9c4b8922a465332aed44c38b2c38bec5
880e037ce6e41c5724cb5f5d99a3f3aa
4a1c97aa0081ce02ba9baaff8476df39
d181455857e56877dda6331bd291d3a9
7de5b012ab26864671cc5e6281127681
cb2d09dcc34248f998b855408e4dfe19
9af2d179236c24dc335c5cf9f6748567
158271f26b3c006e3ef612b51a47691c
bbb0072f91fe48c0b5e0bbeabd113a64
ed06a33838f647bde07b9352365700f9
130f0521d13fa86c6978dbeb9e7ff5ad
c23e760a1556ef4bea61d79806829726
cceb71d1b6cdd8ec01012e329509b307
66417a92837e9f2439f9409622b0d49b
10c45afb8da202a2dbf7aeed1309400e
701f840a80aed4c3ca52c7270257d403
057037e4d66bd650f33711dd2c8835cf
ec5bac7abe5c5e35ffa6c7a96443a871
77b4ec40914f7468e634ab18d0196166
86334ac7adff00bfe2206e2dc2ec34c0
5b888d92e2ce2f36ba0c65d3a11ac258
56b8a7d9600266fff4c8ad317d649aca
0b3dbb04d6b272bf0adb04e82fa5e98f
<E> [09:41:48] Waiting 10 seconds before retrying...
<E> [09:41:58] Request Try #2 / 5

**Comment by houtianze** [comment]
谢谢日志，这个貌似是合并文件出错，我看看。

**Comment by houtianze** [comment]
应该是文件没有上传成功。

怀疑情形是：由于上传速度比较慢，上传的文件分片可能在合并前已经被百度端删除了（具体文件分片多久会被删除，这个没找到相应文档。我以前以为百度把上传的临时分片和普通文件等同看待，不会删除。貌似百度可能不是这样处理的），然后后面自然就无法合并了。

你的VPS内存够大吗？如果够大，可以试试增加上传分片大小，比如200M（或更大），看看能不能解决问题：
`bypy.py -dv -s 200M syncup ...`

**Comment by TangMonk** [comment]
@houtianze 我的vps是512m的，那我只有再增加点swap，再上传试试，谢谢 :D

**Comment by houtianze** [comment]
顾客器，希望能解决问题 ：）

**Comment by houtianze** [comment]
感觉是已上传的分片失效造成的，这个除了更快的上传速度或百度增加分片保留时间也没有什么其他办法。
