### ISSUE TITLE
总是不断retry,重试5次之后失败，能下到部分文件

### ISSUE THREAD

**Issue by oglops** [houtianze/bypy#163]
```
<E> [20:11:16] Function: __downchunks_act
<E> [20:11:16] Website parameters: {u'path': u'/apps/bypy/movies/xyz.mkv', u'method': u'download'}
<E> [20:11:16] HTTP Response Status Code: 403
<E> [20:11:16] Error code: 31326
Error Description: anti hotlinking
<E> [20:11:16] Website returned: {
    "error_code":31326,
    "error_msg":"anti hotlinking"
}

<E> [20:11:16] Waiting 30 seconds before retrying...
<E> [20:11:47] Request Try #4 / 5
```

这是为何？是我使用姿势不对么，刚clone的最新版，授权正常，bypy.py list也正常，因为xyz.mkv很大，又总是断，所以下了很久也没下好，后来基本就没法下了，总是卡很久以后提示anti hotlinking，我在墙外,200mb光纤，不是因为我网速卡，系统是centos 7

**Comment by houtianze** [comment]
额，看你的log，貌似百度那边又加东西（好像是防盗链），这个我看看吧。谢谢反馈。

**Comment by xslidian** [comment]
不知道这个错误是针对单个文件，还是针对楼主的 ip。
方便分享一下文件的 md5 吗？（如果是公共文件的话）

**Comment by gy199445** [comment]
@xslidian 
Mad.Max.Fury.Road.2015.720p.WEB-DL.X264.AC3-EVO.mkv 2845850186 2015-07-15, 13:00:42 982fe9e342d82086a70c23558be3226a
<D> GET https://d.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/movies/Mad.Max.Fury.Road.2015.720p.WEB-DL.X264.AC3-EVO/Mad.Max.Fury.Road.2015.720p.WEB-DL.X264.AC3-EVO.mkv', 20971520L, 2845850186L, 1436967367.468525)
<D> Params: {u'path': u'/apps/bypy/movies/Mad.Max.Fury.Road.2015.720p.WEB-DL.X264.AC3-EVO/Mad.Max.Fury.Road.2015.720p.WEB-DL.X264.AC3-EVO.mkv', u'method': u'download'}
<D> HTTP Status Code: 403
<E> [21:36:08] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
None

<E> [21:36:08] Function: __downchunks_act
<E> [21:36:08] Website parameters: {u'path': u'/apps/bypy/movies/Mad.Max.Fury.Road.2015.720p.WEB-DL.X264.AC3-EVO/Mad.Max.Fury.Road.2015.720p.WEB-DL.X264.AC3-EVO.mkv', u'method': u'download'}
<E> [21:36:08] HTTP Response Status Code: 403
<E> [21:36:08] Error code: 31326
Error Description: anti hotlinking
<E> [21:36:08] Website returned: {
    "error_code":31326,
    "error_msg":"anti hotlinking"
}

<E> [21:36:08] Waiting 10 seconds before retrying...
<E> [21:36:18] Request Try #2 / 5

小文件（目前下载过的200MB左右）还好，大文件基本没戏。

**Comment by xslidian** [comment]
@gy199445 试试这个版本（按右边的“download zip”按钮可以下载压缩包）
https://github.com/xslidian/bypy/tree/be8472f1701fc66dab63a13cde05f801465654be
不敢说能否起作用，因为是下载过于频繁触发的...

如果问题仍然存在，只能反复重试了。
bypy 支持下次运行时自动续传，可以试试加上这样的参数：`--retry 20 --slice 2MB`

**Comment by houtianze** [comment]
搜了一下这个错误：
http://tieba.baidu.com/p/2756174930

不过找不出根本原因，不知道百多那边做了什么。我看看 @xslidian 的改动是不是好用，好用就和合并了。

除了楼上说的减小下载的slice size，增加重试的次数，还可以试试一个hack，增加重试的间隔时间：
查找`RetryDelayInSec = 10`，替换成更长的时间（比如30秒）

**Comment by houtianze** [comment]
百度那边的措施，貌似在客户端没有什么有效应对办法。

**Comment by Aubin1024** [comment]
我也遇到了这个问题，现在这个问题解决了吗？
网上搜索是防盗链导致的，这个好像是针对单个文件来限制的
