### ISSUE TITLE
授权勉强成功，然后不能list出文件

### ISSUE THREAD

**Issue by lilarcor** [houtianze/bypy#168]
首先是授权
Please visit:
https://openapi.baidu.com/oauth/2.0/authorize?scope=basic+netdisk&redirect_uri=oob&response_type=code&client_id=q8WE4EpCsau1oS0MplgMKNBn
And authorize this app
Paste the Authorization Code here within 10 minutes.
Press [Enter] when you are done
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Authorizing, please be patient, it may take upto 60.0 seconds...
Authorizing with the GAE server ...
<E> [13:59:04] Maximum number (1) of tries failed.
I think you are WALLed, so let's authorize with the OpenShift server ...
Successfully authorized
/apps/bypy ($t $f $s $m $d):

list没有内容

joey@Joey-Debian:/tmp/bypy$ ./bypy.py list
Token file: '/home/joey/.bypy/bypy.json'
Hash Cache file: '/home/joey/.bypy/bypy.pickle'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
sys.stderr.encoding = UTF-8
----

/apps/bypy ($t $f $s $m $d):

**Comment by lilarcor** [comment]
原来只能同步bypy里的文件，了解了。请关闭

**Comment by houtianze** [comment]
好的。
