### ISSUE TITLE
是不是可以增加离线下载功能

### ISSUE THREAD

**Issue by ReZELChan** [houtianze/bypy#169]
可不可以增加离线下载功能呢

**Comment by houtianze** [comment]
嗯，查了一下，PCS API有这个接口，加上很容易，以后会加上，谢谢建议。

**Comment by zqfsdek** [comment]
我自己加了离线下载的功能，最近不能用了，报错“用户未授权，错误码 36007”，不知道在授权应用的时候能把离线的权限加上可不可行（可能百度以前接口有 bug，我之前也报错，但重试几次还是能用，现在完全用不了了）？谢谢~

**Comment by houtianze** [comment]
哦，我看看（希望这两天能弄上）。感谢反馈，圣诞快乐 :santa:

**Comment by zqfsdek** [comment]
迟来的圣诞快乐，麻烦您了~

**Comment by houtianze** [comment]
不客气，已经加上去了。`cdl_addmon`。不过测试下载大文件到最后97%就会卡住 :disappointed:
