### ISSUE TITLE
下载速度偏慢

### ISSUE THREAD

**Issue by flyingtimes** [houtianze/bypy#170]
首先感谢作者的贡献，使我的树莓派终于可以顺利同步百度云的资源了。美中不足是下载速率偏慢，是否可以考虑程序中选择调用类似“wget”这样的外部多线程工具来进行下载？

**Comment by houtianze** [comment]
不好意思才回复。
谢谢反馈。下载速度貌似是百度那面对使用PCS API的限制，有时间我看看能不能加入并行或者多线程下载（如果百度端不限制的话）。如果只是下载时调用wget / curl，估计速度变化不大，并且重试等逻辑会失效。

**Comment by houtianze** [comment]
已经支持`aria2`，不过速度问题好像也没有太大的提升。这个还是取决于百度限制与否，先关了。

**Comment by alswl** [comment]
我现在速度是 50kb/s，感觉限速了。

有会员遇到这个问题么，如果升级会员可以解决，我可以买一个。

**Comment by houtianze** [comment]
还没听过有会员反映速度是否有提升，不知道PCS API后台是否会查询会员身份再决定限速与否。

**Comment by feelsad** [comment]
我是会员，用bypy感觉下载速度也慢，所以我搜索到这里

**Comment by wds315** [comment]
我也是会员，还是bypy速度很慢。
