### ISSUE TITLE
软件已过期，无法使用

### ISSUE THREAD

**Issue by kashuorg** [houtianze/bypy#173]
软件已过期，无法使用

<D> Error loading BDUSS:
<D> Traceback (most recent call last):
  File "./bypy.py", line 1537, in __load_local_bduss
    with open(BDUSSPath, 'rb') as infile:
IOError: [Errno 2] No such file or directory: u'/home/kashu/.bypy/bypy.bduss'

<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy', u'$t $f $s $m $d')
<D> Params: {u'path': u'/apps/bypy', u'order': u'asc', u'method': u'list', u'by': u'name'}
<D> HTTP Status Code: 200
<D> Request OK, processing action
/apps/bypy ($t $f $s $m $d):
<D> Request all goes fine

**Comment by houtianze** [comment]
这个输出貌似没什么问题啊。
