### ISSUE TITLE
处理exception会再次出错导致程序挂掉

### ISSUE THREAD

**Issue by onlyxuyang** [houtianze/bypy#174]
log见文末，看起来是code中这一行导致问题：
if isinstance(ex, requests.exceptions.SSLError):
                and re.match(r'^[Errno 1]._error:14090086._:certificate verify failed$', str(ex), re.I):
I do not know why str(ex) return a "SysCallError“.
In my local,I just comment the line "and re.match....",and seem work fine.

Thank you

[===_________________] 15% (180.0MB/1.2GB) ETA: 31m49s (546kB/s, 5m37s gone) <D> Uploading MD5 slice: d500acc84af936f11dad2c89038c0daa, #10 / 60
<D> POST https://c.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/system_backup_20150810.tar.xz
<D> Params: {u'type': u'tmpfile', u'method': u'upload'}
<E> [22:02:52] Exception occurred:
Traceback (most recent call last):
  File "./bypy.py", line 3452, in main
    result = getattr(by, args.command[0])(_uargs)
  File "./bypy.py", line 2286, in upload
    return self.__upload_file(lpath, rpath, ondup)
  File "./bypy.py", line 2237, in __upload_file
    result = self.__upload_file_slices(localpath, remotepath, ondup)
  File "./bypy.py", line 2070, in __upload_file_slices
    ec = self.__upload_slice(remotepath)
  File "./bypy.py", line 2039, in __upload_slice
    files = { 'file' : ('file', self.__current_slice) } )
  File "./bypy.py", line 1445, in __post
    return self.__request(url, pars, act, 'POST', actargs, retry, addtoken, dumpex, *_kwargs)
  File "./bypy.py", line 1421, in **request
    result = self.__request_work(url, pars, act, method, actargs, addtoken, dumpex, *_kwnew)
  File "./bypy.py", line 1352, in __request_work
    and re.match(r'^[Errno 1]._error:14090086.*:certificate verify failed$', str(ex), re.I):
TypeError: __str** returned non-string (type SysCallError)

**Comment by houtianze** [comment]
感谢反馈，那个re是处理老版本pyopenssl还是requests的敷衍办法，可能要清理一下。

**Comment by houtianze** [comment]
最新版强制`requests` 2.10以上版本，应该修正了这个问题。
