### ISSUE TITLE
Why not Python3?

### ISSUE THREAD

**Issue by fox0001** [houtianze/bypy#176]
好奇问下，问什么不用Python3？

**Comment by chovan** [comment]
估计大多数发行版本都只是默认Python 2.7吧。个人觉得除非有特殊需要，暂时没必要硬伤P3.

**Comment by houtianze** [comment]
这个。。因为当初是给树莓派用的，打了一下python发现是2.7.x的，就想当然的认为树莓派只有Python 2，所以就拿Python 2来做了。后来才知道Python 3在树莓派上也是没问题的。
Python 2的Unicode搞得我头大（特别是os.walk()没有完美解决方案），开始后悔。有时间我会弄个Python 3的版本，可以拿掉不少hack。

**Comment by septs** [comment]
see https://docs.python.org/3.5/library/zipapp.html
使用这个方法似乎可以将requests依赖内置

**Comment by houtianze** [comment]
@septs 感谢提供参考资料。嗯，我也考虑打包程序了，要不然requests和openSSL版本的问题挺烦的。

**Comment by linux0ne** [comment]
@houtianze 就条命令的事儿
SSL : pip isntall -U requests[security]

**Comment by zif2016** [comment]
终于找到一个 linux下还在更新的客户端~
感谢 @houtianze

**Comment by houtianze** [comment]
现在已经是2 & 3 universal了，直接pip安装。
