### ISSUE TITLE
[enhence]syncup/syncdown是否支持添加ignore文件，目前是手动写.sh配置dir来做的，是否有直接添加ignore的方法

### ISSUE THREAD

**Issue by ryanemax** [houtianze/bypy#178]
syncup/syncdown是否支持添加ignore文件，
目前是手动写.sh配置dir来做的，是否有直接添加ignore的方法

**Comment by houtianze** [comment]
感谢反馈。
这个我考虑过 #39 也有人提过，不过我不太喜欢向git那样的.ignore文件形式来实现：
- 如果按git的风格，ignore一般是逐层放置的，这样做有时候可能要一层层查下去看文件排除的设置，个人觉得不是那么方便。
- 场景方面和git有点不同，.gitingore可以算是git配置的一部分，但是ignore文件对于用户来讲就完全是多加的一个文件，不是很喜欢这种做法。
- 现在命令行有个参数`--include-regex`可以通过正则表达式来顾虑，不过会考虑加一个带文件参数来读取一个总的过滤配置。
- 还有一个办法是通过`find`命令之类的来做过滤工作，再调用·bypy·，当然这个办法比较敷衍。

**Comment by ryanemax** [comment]
--include-regex 在尝试用alias来实现了
