### ISSUE TITLE
WebUI

### ISSUE THREAD

**Issue by malsony** [houtianze/bypy#180]
First of all, thanks for your efforts and the cool app!

I am using a headless Raspberry Pi 2, and is a WebUI (like mldonkey or transmission) listed in your road map? Thanks!

**Comment by houtianze** [comment]
OK, as I commented, this will be tracked in #96 , closing this.

**Comment by dukedhx** [comment]
加个method或者参数让返回格式输出json的话，我可以写个ui，这样同时亦可以加强互换性和模块化恩？

下载进度可以用从tty转到fifo或临时文件之类的方法迅速搞定？
