### ISSUE TITLE
"error_code":31079,"error_msg":"file md5 not found, you should use upload api to upload the whole file."

### ISSUE THREAD

**Issue by zasdza** [houtianze/bypy#187]
----
Verbose level = 1
Debug level = 1
Token file: '/home/###/.bypy/bypy.json'
Hash Cache file: '/home/###/.bypy/bypy.pickle'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
sys.stderr.encoding = UTF-8
----

<D> Token loaded:
<D> {u'access_token': u'', u'expires_in': 2592000, u'session_secret': u'', u'session_key': u'', u'refresh_token': u''}
<D> localpath not set, set it to current directory ''
<D> Uploading directory '/home/drive/Download/rar2' recursively
<D> Uploading directory '/home/drive/Download/rar2' to '/apps/bypy'
<D> Making remote directory '/apps/bypy'
<D> POST https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: None
<D> Params: {u'path': u'/apps/bypy', u'method': u'mkdir'}
<D> HTTP Status Code: 400
<D> __get_file_info(): rdir : /apps/bypy | rfile: ####.rar
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/####.rar
<D> Params: {u'path': u'/apps/bypy', u'order': u'asc', u'method': u'list', u'by': u'name'}
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> List json: {u'list': [], u'request_id': 2603484753}
<D> '/home/drive/Download/rar2/####.rar' is being RapidUploaded.
<D> [19:13:35] Cache hit for file '/home/drive/Download/rar2/####.rar',
md5: 05c617e931a45707a9efbd3ffa6866fc
size: 2298637638
mtime: 1444532929
<D> [19:13:35] Cache hit for file '/home/drive/Download/rar2/####.rar',
slice_md5: 95beb5bc4a5a916315d9936dd1c2cffd
size: 2298637638
mtime: 1444532929
<D> [19:13:35] Cache hit for file '/home/drive/Download/rar2/####.rar',
crc32: 1202021383
size: 2298637638
mtime: 1444532929
<D> RapidUploading Length: 2298637638 MD5: 05c617e931a45707a9efbd3ffa6866fc, Slice-MD5: 95beb5bc4a5a916315d9936dd1c2cffd, CRC: 0x47a56407
<D> POST https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: None
<D> Params: {u'slice-md5': '95beb5bc4a5a916315d9936dd1c2cffd', u'content-length': 2298637638, u'ondup': u'overwrite', u'content-md5': '05c617e931a45707a9efbd3ffa6866fc', u'content-crc32': '0x47a56407', u'path': u'/apps/bypy/####.rar', u'method': u'rapidupload'}
<D> HTTP Status Code: 404
<E> [19:13:35] Error accessing 'https://pcs.baidu.com/rest/2.0/pcs/file'
<E> [19:13:35] Exception:
__handle_more_response_error() takes exactly 6 arguments (7 given)
Traceback (most recent call last):
  File "/usr/bin/bypy.py", line 1414, in __request_work
    result = self.__handle_more_response_error(self, r, sc, ec, act, actargs)
TypeError: __handle_more_response_error() takes exactly 6 arguments (7 given)

<E> [19:13:35] Function: __rapidupload_file_act
<E> [19:13:35] Website parameters: {u'slice-md5': '95beb5bc4a5a916315d9936dd1c2cffd', u'content-length': 2298637638, u'ondup': u'overwrite', u'content-md5': '05c617e931a45707a9efbd3ffa6866fc', u'content-crc32': '0x47a56407', u'path': u'/apps/bypy/####.rar', u'method': u'rapidupload'}
<E> [19:13:35] HTTP Response Status Code: 404
<I> [19:13:35] file md5 not found, you should use upload api to upload the whole file.
<E> [19:13:35] Website returned: {"error_code":31079,"error_msg":"file md5 not found, you should use upload api to upload the whole file.","request_id":3682384931}

尝试过删除 .bypy重新验证，依旧这样

**Comment by houtianze** [comment]
谢谢反馈。又是代码重构引入的问题，现在修正。

**Comment by houtianze** [comment]
Fixed 34f655378e46d70063a49cfe40bcc2a269e3af7e

**Comment by zasdza** [comment]
$ bypy.py -v -d upload
Loading Hash Cache File '/home/usr/.bypy/bypy.pickle'...
Hash Cache File loaded.
<E> [14:16:20] Failed to disable warnings for Urllib3.
<E> [14:16:20] Exception:
Traceback (most recent call last):
  File "/usr/bin/bypy.py", line 1071, in disable_warnings
    ul3.disable_warnings()
AttributeError: 'module' object has no attribute 'disable_warnings'

----
Verbose level = 1
Debug level = 1
Token file: '/home/usr/.bypy/bypy.json'
Hash Cache file: '/home/usr/.bypy/bypy.pickle'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
sys.stderr.encoding = UTF-8
----

<D> Token loaded:
<D> {u'access_token': u'', u'expires_in': 2592000, u'session_secret': u'', u'scope': u'basic netdisk', u'session_key': u'', u'refresh_token': u''}
<D> localpath not set, set it to current directory ''
<D> Uploading directory '/home/drive/Download/rar2' recursively
<D> Uploading directory '/home/drive/Download/rar2' to '/apps/bypy'
<D> Making remote directory '/apps/bypy'
<D> POST https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: None
<D> Params: {u'path': u'/apps/bypy', u'method': u'mkdir'}
<D> HTTP Status Code: 400
<D> __get_file_info(): rdir : /apps/bypy | rfile: abc.rar
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/abc.rar
<D> Params: {u'path': u'/apps/bypy', u'order': u'asc', u'method': u'list', u'by': u'name'}
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> List json: {u'list': [], u'request_id': 4059190608}
<D> '/home/drive/Download/rar2/abc.rar' is being RapidUploaded.
<D> [14:16:21] Cache hit for file '/home/drive/Download/rar2/abc.rar',
md5: 05c617e931a45707a9efbd3ffa6866fc
size: 2298637638
mtime: 1444532929
<D> [14:16:21] Cache hit for file '/home/drive/Download/rar2/abc.rar',
slice_md5: 95beb5bc4a5a916315d9936dd1c2cffd
size: 2298637638
mtime: 1444532929
<D> [14:16:21] Cache hit for file '/home/drive/Download/rar2/abc.rar',
crc32: 1202021383
size: 2298637638
mtime: 1444532929
<D> RapidUploading Length: 2298637638 MD5: 05c617e931a45707a9efbd3ffa6866fc, Slice-MD5: 95beb5bc4a5a916315d9936dd1c2cffd, CRC: 0x47a56407
<D> POST https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: None
<D> Params: {u'slice-md5': '95beb5bc4a5a916315d9936dd1c2cffd', u'content-length': 2298637638, u'ondup': u'overwrite', u'content-md5': '05c617e931a45707a9efbd3ffa6866fc', u'content-crc32': '0x47a56407', u'path': u'/apps/bypy/abc.rar', u'method': u'rapidupload'}
<D> HTTP Status Code: 404
<E> [14:16:21] Error accessing 'https://pcs.baidu.com/rest/2.0/pcs/file'
None

<E> [14:16:21] Function: __rapidupload_file_act
<E> [14:16:21] Website parameters: {u'slice-md5': '95beb5bc4a5a916315d9936dd1c2cffd', u'content-length': 2298637638, u'ondup': u'overwrite', u'content-md5': '05c617e931a45707a9efbd3ffa6866fc', u'content-crc32': '0x47a56407', u'path': u'/apps/bypy/abc.rar', u'method': u'rapidupload'}
<E> [14:16:21] HTTP Response Status Code: 404
<I> [14:16:21] file md5 not found, you should use upload api to upload the whole file.
<E> [14:16:21] Website returned: {"error_code":31079,"error_msg":"file md5 not found, you should use upload api to upload the whole file.","request_id":1027799735}
<E> [14:16:21] Waiting 10 seconds before retrying...
^CSignal 2 received, Abort

问题还有另一半的样子

**Comment by houtianze** [comment]
:flushed: 嗯，应该是我重构时把`MD5 nout found`的处理给弄没了，现在去修正

**Comment by houtianze** [comment]
Fixed. 感谢再次反馈 :smile: 

03c713baaf8dbfc474feca0d24f0709477c88924

**Comment by zasdza** [comment]
$ bypy.py -v -d upload
Loading Hash Cache File '/home/usr/.bypy/bypy.pickle'...
Hash Cache File loaded.
<E> [15:44:26] Failed to disable warnings for Urllib3.
<E> [15:44:26] Exception:
Traceback (most recent call last):
  File "/usr/bin/bypy.py", line 1071, in disable_warnings
    ul3.disable_warnings()
AttributeError: 'module' object has no attribute 'disable_warnings'

----
Verbose level = 1
Debug level = 1
Token file: '/home/usr/.bypy/bypy.json'
Hash Cache file: '/home/usr/.bypy/bypy.pickle'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
sys.stderr.encoding = UTF-8
----

<D> Token loaded:
<D> {u'access_token': u' ', u'expires_in': 2592000, u'session_secret': u' ', u'scope': u'basic netdisk', u'session_key': u' ', u'refresh_token': u' '}
<D> localpath not set, set it to current directory ''
<D> Uploading directory '/home/drive/Download/rar2' recursively
<D> Uploading directory '/home/drive/Download/rar2' to '/apps/bypy'
<D> Making remote directory '/apps/bypy'
<D> POST https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: None
<D> Params: {u'path': u'/apps/bypy', u'method': u'mkdir'}
<D> HTTP Status Code: 400
<D> __get_file_info(): rdir : /apps/bypy | rfile: abc.rar
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/abc.rar
<D> Params: {u'path': u'/apps/bypy', u'order': u'asc', u'method': u'list', u'by': u'name'}
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> List json: {u'list': [{u'isdir': 0, u'ctime': 1444721925, u'fs_id': 580036629661758, u'mtime': 1444721925, u'path': u'/apps/bypy/bypy.cacerts.pem', u'md5': u'960dc34cf2f961cfbce7e4df9265cd70', u'size': 312971}, {u'isdir': 0, u'ctime': 1444721949, u'fs_id': 1019544669611795, u'mtime': 1444721949, u'path': u'/apps/bypy/description', u'md5': u'a0a7c3fff21f2aea3cfa1d0316dd816c', u'size': 73}, {u'isdir': 0, u'ctime': 1444721951, u'fs_id': 610658939926850, u'mtime': 1444721951, u'path': u'/apps/bypy/HEAD', u'md5': u'4cf2d64e44205fe628ddd534e1151b58', u'size': 23}, {u'isdir': 0, u'ctime': 1444721950, u'fs_id': 3525271984635, u'mtime': 1444721950, u'path': u'/apps/bypy/packed-refs', u'md5': u'224da42fad631dfb73a8f3bc6b445d29', u'size': 259}, {u'isdir': 0, u'ctime': 1444721925, u'fs_id': 531275281302932, u'mtime': 1444721925, u'path': u'/apps/bypy/requirements.txt', u'md5': u'3794cf73b4c85996552639f2874d3081', u'size': 18}], u'request_id': 2734699793}
<D> '/home/drive/Download/rar2/abc.rar' is being RapidUploaded.
<D> [15:44:26] Cache hit for file '/home/drive/Download/rar2/abc.rar',
md5: 05c617e931a45707a9efbd3ffa6866fc
size: 2298637638
mtime: 1444532929
<D> [15:44:26] Cache hit for file '/home/drive/Download/rar2/abc.rar',
slice_md5: 95beb5bc4a5a916315d9936dd1c2cffd
size: 2298637638
mtime: 1444532929
<D> [15:44:26] Cache hit for file '/home/drive/Download/rar2/abc.rar',
crc32: 1202021383
size: 2298637638
mtime: 1444532929
<D> RapidUploading Length: 2298637638 MD5: 05c617e931a45707a9efbd3ffa6866fc, Slice-MD5: 95beb5bc4a5a916315d9936dd1c2cffd, CRC: 0x47a56407
<D> POST https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: None
<D> Params: {u'slice-md5': '95beb5bc4a5a916315d9936dd1c2cffd', u'content-length': 2298637638, u'ondup': u'overwrite', u'content-md5': '05c617e931a45707a9efbd3ffa6866fc', u'content-crc32': '0x47a56407', u'path': u'/apps/bypy/abc.rar', u'method': u'rapidupload'}
<D> HTTP Status Code: 404
<D> MD5 not found, rapidupload failed
<D> '/home/drive/Download/rar2/abc.rar' can't be RapidUploaded, now trying normal uploading.
<D> '/home/drive/Download/rar2/abc.rar' is being slicing uploaded.
<D> Slice size: 20971520, Pieces: 110
<D> Uploading MD5 slice: b7f4e9e1bfefae1e77b2e7e3966bbe9d, #1 / 110
<D> POST https://c.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/abc.rar
<D> Params: {u'type': u'tmpfile', u'method': u'upload'}
<E> [15:44:27] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [15:44:27] Exception:
'ascii' codec can't decode byte 0xb8 in position 147: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/bin/bypy.py", line 1352, in __request_work
    r = self.__requester.request(method, url, params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "/usr/bin/bypy.py", line 1063, in request
    return requests.request(method, url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.0.0-py2.7.egg/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.0.0-py2.7.egg/requests/sessions.py", line 357, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.0.0-py2.7.egg/requests/sessions.py", line 460, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.0.0-py2.7.egg/requests/adapters.py", line 319, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests-2.0.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 541, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.0.0-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 366, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 966, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1000, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 962, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 820, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb8 in position 147: ordinal not in range(128)

<E> [15:44:27] Function: __upload_slice_act
<E> [15:44:27] Website parameters: {u'type': u'tmpfile', u'method': u'upload'}
<E> [15:44:27] Fatal Exception, no way to continue.
Quitting...

<E> [15:44:27] If the error is reproducible, run the program with `-dv` arguments again to get more info.

Not saving Hash Cache since 'dirty' is 'False' and 'force_saving' is 'False'


这下好像是编码错了？

**Comment by houtianze** [comment]
看上去是编码问题，不过这个按理不应该出现，暂时没细究。
你的`requests`是2.0?升级到最新的`pip install -U requests[security]`试试呢？

**Comment by zasdza** [comment]
requests已经是2.8了

sudo pip install -U requests[security]这个命令出错

c/_cffi_backend.c:13:17: 致命错误： ffi.h：没有那个文件或目录
    编译中断。
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-bh8gyl/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-7diia3-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-bh8gyl/cffi

**Comment by houtianze** [comment]
感谢尝试。
只是奇怪你的log怎么显示是2.0.0？
```
/usr/local/lib/python2.7/dist-packages/requests-2.0.0-py2.7.egg/
```
另外，你用的是Python 3的pip？可能要改成：
`pip2 install -U requests[security]`

**Comment by zasdza** [comment]
嗯 我发现了
pip默认装到py3去了……
pip2这个命令没找到，我去查查怎么回事

**Comment by zasdza** [comment]
原来之前一直用的 py3-pip，这次重构后py3-pip下的requests看来不兼容了。

refer: http://stackoverflow.com/questions/26266437/how-to-use-python2-7-pip-instead-of-default-pip

昨天有遇到传完了并且显示文件成功合并，结果文件在web页面没有、重新运行程序上传的时候也显示不存在。和这次重构有关吗？

**Comment by houtianze** [comment]
额？听起来不像是这次重构的问题，但我也不十分确定，我哪天试一试。
程序用Python 3可以直接跑的？还一直没试过能用不。

**Comment by zasdza** [comment]
没有问题了，py3能不能跑我也不清楚……估计上个版本2.0的库能用，调用的应该还是py2的。
刚试了下，重构后的上传没问题了。

**Comment by houtianze** [comment]
好的，这我就放心了 :smile:

**Comment by zasdza** [comment]
我发现问题了……传不上去的
文件名中还有符号英文冒号 “  :  ” 
显示上传成功，但实际没有。

要不加个提示？

**Comment by houtianze** [comment]
显示上传成功？能帮忙贴下log吗？
