### ISSUE TITLE
小白问题

### ISSUE THREAD

**Issue by pengwon** [houtianze/bypy#188]
downfile -v 提示 Loading Hash Cache File '/home/pwon/.bypy/bypy.pickle'...
Hash Cache File not found, no caching
Not saving Hash Cache since 'dirty' is 'False' and 'force_saving' is 'False'

**Comment by houtianze** [comment]
`downfile <remotefile> [localpath]`
你要加上百度云端的文件路径（可以先用`list`命令查看），比如：
`downfile /some/movie.avi`

**Comment by pengwon** [comment]
哦，原来是这样，谢谢
