### ISSUE TITLE
隐藏文件夹会报错啊

### ISSUE THREAD

**Issue by baowenbo** [houtianze/bypy#189]
![qq 20151026214401](https://cloud.githubusercontent.com/assets/7220760/10730398/b0eddd50-7c2a-11e5-9def-8734bd660567.jpg)

**Comment by houtianze** [comment]
感谢反馈。
搜了一下，应该是`S.gpg-agent`是Socket file，所以没法读取。我看看要怎么改排除这些特殊文件。

**Comment by baowenbo** [comment]
哈，我搞错了，不是隐藏文件夹的问题。工具很好，非常感谢～

**Comment by linux0ne** [comment]
那是怎么个事儿？  这个问题总得有个原因吧？
