### ISSUE TITLE
没有urllib3报错

### ISSUE THREAD

**Issue by alairs** [houtianze/bypy#190]
<E> [14:59:50] Failed to disable warnings for Urllib3.
<E> [14:59:50] Exception:
Traceback (most recent call last):
  File "/usr/bin/bypy.py", line 1068, in disable_warnings
    import requests.packages.urllib3 as ul3
ImportError: No module named packages.urllib3

但是我已经安装了 python-urllib3和python3-urllib3 ，仍旧报错

**Comment by krizex** [comment]
我碰到这个问题的时候，把requests升级到最新版本就解决了，你试试呢。

**Comment by alairs** [comment]
@krizex thanks,如你所说已经解决了

**Comment by krizex** [comment]
@alairs  解决了就close吧  :)

**Comment by JoeyZhu** [comment]
小白弱问如何升级requests，为啥按照提示pip3 install 却提示：Cannot fetch index base URL https://pypi.python.org/simple/
Could not find any downloads that satisfy the requirement requests[security] in /usr/lib/python3/dist-packages
Downloading/unpacking requests[security]
Cleaning up...
No distributions at all found for requests[security] in /usr/lib/python3/dist-packages
Storing debug log for failure in /home/linaro/.pip/pip.log

**Comment by houtianze** [comment]
貌似在Linux下，urllib3的位置不固定，已经加入多一个检查，谢谢反馈。
