### ISSUE TITLE
Fail to import the 'requests' library

### ISSUE THREAD

**Issue by weyless** [houtianze/bypy#191]
./bypy.py  

Fail to import the 'requests' library
You need to install the Requests library
You can install it by running 'pip install requests[security]'
Traceback (most recent call last):
  File "./bypy.py", line 141, in <module>
    import requests
ImportError: No module named requests

已经执行了
pip install requests 
结果：
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python3.4/dist-packages
请问还缺什么。

**Comment by krizex** [comment]
昨天已经有人问过同样的问题了，把requests升级到最新版本就好了

**Comment by weyless** [comment]
额，我明白我错在哪里了，之前装了pip3结果pip默认为pip3 ，用pip2然后升级一下就好了
