### ISSUE TITLE
Not saving Hash Cache since 'dirty' is 'False' and 'force_saving' is 'False'

### ISSUE THREAD

**Issue by messyidea** [houtianze/bypy#193]
能给一些关键字的说明吗？在wiki里面没找到相关参数可以force_saving.
谢谢~

**Comment by houtianze** [comment]
1. 这个是个“无害”的提示信息:smile: 。就是你执行的操作没有上传新的大文件（>256K)，cache是不用更新的。
2. 暂时没有直接强制保存cache的命令行参数，如果非要改，只能把调用`savecache()`改成`savecache(True)`。不过基于1，这个基本没必要。
