### ISSUE TITLE
os.walk的编码问题

### ISSUE THREAD

**Issue by Jayatubi** [houtianze/bypy#195]
在最新的1.2.1版本里面，因为需要同步的目录里面有中文目录（尚且无法知道关于这些文件名具体是utf-8还是gbk的编码）。会导致os.walk出现类似：
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 1`
的错误。
如果我直接在该目录执行`python -c "import os; os.walk('.')"` 则不会产生这个编码错误。
之后发现在`bypy.py`对`os.walk`传递的参数均为`unicode`类型，这个便是导致上面的错误的原因。
目前我没有找到更好的办法，只是在本地将所有进入`os.walk`之前的参数都做了类型转换例如在`__upload_dir`里面

``` python
def __upload_dir(self, localpath, remotepath, ondup = 'overwrite'):
    self.pd("Uploading directory '{}' to '{}'".format(localpath, remotepath))
    # it's so minor that we don't care about the return value
    self.__mkdir(remotepath, dumpex = False)
    localpath = str(localpath) # Convert `localpath` to `str`
    for walk in os.walk(localpath, followlinks=self.__followlink):
        self.__walk_upload(localpath, remotepath, ondup, walk)
```

因为目前只是用了`upload`的功能，尚未测试其他功能是否有类似的问题。

**Comment by Jayatubi** [comment]
其实并不是`os.walk`的问题，而是在python 2.x里面所有IO相关的接口（例如stat，open等）都对`unicode`承载的路径支持有问题。如果一个中文路径使用的是`str`作为载体，这些IO接口实际是可以工作的。

但是因为`bypy`加入了`from __future__ import unicode_literals`，所以代码里面所有的字符串的字面量（例如print等使用的）都是`unicode`这会与上面提到的IO接口产生冲突。

目前我找到的解决办法是在以整个运行环境是`unicode`的环境下（即bypy本身的一些设定），对所有传递给IO接口的路径做`unistr.encode('utf-8')`的操作，然后对这些接口返回的路径做`anistr.decode('utf-8')`的操作。

**Comment by houtianze** [comment]
感谢感谢。:smile:
这个问题我一直没搞太明白，一直以为是Python 2.7天生编码缺陷，你这个估计是正解（前两天 #11 上 @muziling 也给出了几乎一样的解决方法）。我尽快整合进去。

**Comment by Jayatubi** [comment]
代码里面的普通字符串处理（比如print等）并不需要处理，只需要对传给IO接口的参数做`unicode`到`ansi`的转换即可。对`os.walk`这种会传回的参数在做一次反向的`ansi`到`unicode`，因为你的代码其他地方都是使用`unicode`

**Comment by houtianze** [comment]
好的，感谢指点。

**Comment by houtianze** [comment]
后来总结了一下[Python & Filesystem Unicode](https://houtianze.github.io/python/unicode/2015/12/07/python-unicode.html)，感觉没有一个完美解决方案（如果文件名是一串没法解码成string的字节）。
