### ISSUE TITLE
无法增量同步

### ISSUE THREAD

**Issue by goldcome** [houtianze/bypy#196]
每次传输都要从头开始上传所有文件 这个问题是不是 #47 这个问题 但我同步2次的第二次也是从头再来 还是 #85 的md5的问题

**Comment by houtianze** [comment]
你是用的`syncup`命令吗？如果是用这个命令，程序会先做一个目录比较，然后只会选择上传不同和百度云上面没有的文件。

**Comment by goldcome** [comment]
是的 是用syncup来传输 但每次都是全部都传输

**Comment by houtianze** [comment]
方便贴一下log吗？（注意屏蔽掉token部分）
