### ISSUE TITLE
两个比较困扰的问题

### ISSUE THREAD

**Issue by chovan** [houtianze/bypy#198]
1. 每次启动程序后，都会删除掉一些已经上传好的文件，重新上传。浪费不少时间

比如：

Token file: '/root/.bypy/bypy.json'
Hash Cache file: '/root/.bypy/bypy.pickle'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = None
sys.stdout.encoding = None
Verbose level = 1
##  Debug = 0

Loading Hash Cache File '/root/.bypy/bypy.pickle'...
Hash Cache File loaded.
Gathering local directory ...
Done
Gathering remote directory ...
Refreshing, please be patient, it may take upto 60.0 seconds...
Refreshing with the GAE server ...
Token successfully refreshed
Done
Comparing ...
Done
Deletion request '3811324273' OK
Usage 'list' command to confirm
'xxxxxxx.MTS' >>==> '/xxxxxxx.MTS' OK.

[==__________________] 10% (20.0MB/193.816MB) ETA: 13m36s (218KB/s, 
1.   我是FTTN连接，上传带宽只有2Mb, 所以每次上传都占满上传带宽，全家人上网都会很慢。能够加入限速的参数吗？

谢谢！

**Comment by chovan** [comment]
好吧，第一个问题在wiki里找到答案了。Syncup 两次是不是：

bypy.py syncup -v && bypy.py syncup -v

**Comment by houtianze** [comment]
嗯，对的，是这样。
貌似这个`syncup`现在可能又有问题了，我再看看。
以后我看看能不能加入限速功能，谢谢建议。

**Comment by houtianze** [comment]
限速这个我先记下了，issue先关了。
