### ISSUE TITLE
Heroku server failed. Last resort: authorizing/refreshing with the GAE server ...

### ISSUE THREAD

**Issue by kozora** [houtianze/bypy#199]
全是这个的错误，开始我以为是我国内服务器的问题，又换到国外的还是这个错误。。。

**Comment by houtianze** [comment]
谢谢反馈。
这个听起来很严重，能贴下`bypy.py info -dv`的输出吗？

**Comment by kozora** [comment]
Loading Hash Cache File '/root/.bypy/bypy.pickle'...
Hash Cache File not found, no caching
<E> [13:09:14] Failed to disable warnings for Urllib3.
<E> [13:09:14] Exception:
Traceback (most recent call last):
  File "/usr/bin/bypy.py", line 1068, in disable_warnings
    import requests.packages.urllib3 as ul3
ImportError: No module named packages.urllib3

----
Verbose level = 1
Debug level = 1
Token file: '/root/.bypy/bypy.json'
Hash Cache file: '/root/.bypy/bypy.pickle'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
sys.stderr.encoding = UTF-8
----

<E> [13:09:14] Error while loading baidu pcs token:
<E> [13:09:14] Traceback (most recent call last):
  File "/usr/bin/bypy.py", line 1571, in __load_local_json
    with open(TokenFilePath, 'rb') as infile:
IOError: [Errno 2] No such file or directory: u'/root/.bypy/bypy.json'

Please visit:
https://openapi.baidu.com/oauth/2.0/authorize?scope=basic+netdisk&redirect_uri=oob&response_type=code&client_id=q8WE4EpCsau1oS0MplgMKNBn
And authorize this app
Paste the Authorization Code here within 10 minutes.
Press [Enter] when you are done

<D> auth_code: 
Authorizing, please be patient, it may take upto 60.0 seconds...
Authorizing/refreshing with the OpenShift server ...
<D> GET https://bypy-tianze.rhcloud.com/auth
<D> actargs: None
<D> Params: {u'code': '', u'redirect_uri': u'oob'}
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<E> [13:09:32] Failed to decode JSON:
Exception:
Traceback (most recent call last):
  File "/usr/bin/bypy.py", line 1603, in __store_json
    j = r.json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

<E> [13:09:32] Error response:
ERROR: Invalid OAuth request, please retry.
Request:
<LocalRequest: GET https://bypy-tianze.rhcloud.com/auth?code=&redirect_uri=oob>
<I> [13:09:32] ----------------------------------------------------------------
<I> [13:09:32] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.
OpenShift server failed, authorizing/refreshing with the Heroku server ...
<D> GET https://bypyoauth.herokuapp.com/auth
<D> actargs: None
<D> Params: {u'code': '', u'redirect_uri': u'oob'}
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<E> [13:09:33] Failed to decode JSON:
Exception:
Traceback (most recent call last):
  File "/usr/bin/bypy.py", line 1603, in __store_json
    j = r.json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

<E> [13:09:33] Error response:
ERROR: Invalid OAuth request, please retry.
Request:
<LocalRequest: GET https://bypyoauth.herokuapp.com/auth?code=&redirect_uri=oob>
<I> [13:09:33] ----------------------------------------------------------------
<I> [13:09:33] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.
Heroku server failed. Last resort: authorizing/refreshing with the GAE server ...
<D> GET https://bypyoauth.appspot.com/auth
<D> actargs: None
<D> Params: {u'code': '', u'redirect_uri': u'oob'}
<E> [13:10:34] Error accessing 'https://bypyoauth.appspot.com/auth'
<E> [13:10:34] Exception:
HTTPSConnectionPool(host='bypyoauth.appspot.com', port=443): Max retries exceeded with url: /auth?code=&redirect_uri=oob (Caused by <class 'socket.error'>: [Errno 101] Network is unreachable)
Traceback (most recent call last):
  File "/usr/bin/bypy.py", line 1352, in __request_work
    r = self.__requester.request(method, url, params = parsnew, timeout = self.__timeout, verify = self.__checkssl, **kwargs)
  File "/usr/bin/bypy.py", line 1063, in request
    return requests.request(method, url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='bypyoauth.appspot.com', port=443): Max retries exceeded with url: /auth?code=&redirect_uri=oob (Caused by <class 'socket.error'>: [Errno 101] Network is unreachable)

<E> [13:10:34] Function: __server_auth_act
<E> [13:10:34] Website parameters: {u'code': '', u'redirect_uri': u'oob'}
<E> [13:10:34] Maximum number (1) of tries failed.
<E> [13:10:34] Fatal: All server authorizations failed.
<E> [13:10:34] Program authorization FAILED.
You need to authorize this program before using any PCS functions.
Quitting...

Not saving Hash Cache since 'dirty' is 'False' and 'force_saving' is 'False'

**Comment by houtianze** [comment]
哦，你有去这个地方授权吗？：
https://openapi.baidu.com/oauth/2.0/authorize?scope=basic+netdisk&redirect_uri=oob&response_type=code&client_id=q8WE4EpCsau1oS0MplgMKNBn

**Comment by kozora** [comment]
去了啊，授权管理里面有这个应用了

**Comment by houtianze** [comment]
是不是之前授权过超过一个月没用过了？如果是这样可以按顺序执行如下步骤：
1. 运行`bypy.py -c`，删除令牌文件，然后重新授权一次。
2. 如果还不行，去百度应用授权（https://passport.baidu.com/accountbind） 里删除`bypy`再重新授权。

**Comment by baoyankun** [comment]
我也遇到了这个问题，用楼上的方法成功了。
谢谢！

**Comment by Edragon** [comment]
ganxie
