### ISSUE TITLE
2 InsecurePlatformWarning

### ISSUE THREAD

**Issue by chovan** [houtianze/bypy#200]
刚下载了最近的bypy.py覆盖了原来的文件。再执行bypy.py syncup 或者syncdown 就会出现下面的提示。

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

bypy.py list还能够列出网盘文件。
请问是哪里有问题呢？

**Comment by houtianze** [comment]
这个是`requests`库里面的`urllib3`的问题，可以有两个方法解决：
- 升级`Python 2`到`2.7.9`或更高
- 运行`bypy.py`时加` --disable-ssl-check`参数。

**Comment by chovan** [comment]
OK, 谢谢！ 试着编译2.7.10失败，暂时没时间折腾了，按你说的价格参数算了。

**Comment by renweizhukov** [comment]
除了上面提到的两种方法外还有第三种方法：

`$ pip install urllib3[secure]`

见：https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2

我在Ubuntu 14.04LTS + python 2.7.6上验证了可以去除  InsecurePlatformWarning
