### ISSUE TITLE
【问题】上传和下载的文件排序

### ISSUE THREAD

**Issue by gadget1999** [houtianze/bypy#204]
问个问题，比如我有文件file.001到file.100，好像上传下载时处理的文件顺序是随机的？有没有办法进行排序，这样容易跟踪进度。谢谢！

**Comment by gadget1999** [comment]
好像是文件系统的问题，给__walk_normal_file函数里加上下面一行就好了：
normalfiles.sort()

**Comment by houtianze** [comment]
嗯，应该是要自己`sort`一下，我尽快加上去。感谢反馈，圣诞快乐 :santa:
