### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by jacwl** [houtianze/bypy#209]
重试了几次发现已经可以传完了，中途多次出错，甚至网络连接断开若干次，都没导致进程终止

感谢作者的给力更新!

**Comment by houtianze** [comment]
后来那个`WSAECONNABORTED`也加了处理。

新年快乐 :fireworks:

**Comment by jacwl** [comment]
感谢作者的跟进更新
新年快乐  \xF0\x9F\x98\x89
