### ISSUE TITLE
下载文件有问题

### ISSUE THREAD

**Issue by martinsun** [houtianze/bypy#214]
<E> [20:39:54] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [20:39:54] Function: __downchunks_act
<E> [20:39:54] Website parameters: {u'path': u'/apps/bypy/qe.png', u'method': u'download', u'ru': 'MC0xOTg3OTU='}

**Comment by houtianze** [comment]
能贴个去完整的log吗？如果只是这个错误输出，程序没有中断，属正常的。

**Comment by martinsun** [comment]
这个就是完整的log，这个错误输出说明了什么问题？我操作有误？我这个是在windows下运行的

**Comment by houtianze** [comment]
加上`-dv`参数再运行一遍呢？

**Comment by martinsun** [comment]
3q 看了详细报错 原因还是我代理的问题 一开始只设置了 https的，加了http的代理问题解决
