### ISSUE TITLE
分片上传过的文件第二次传无法秒传

### ISSUE THREAD

**Issue by jacwl** [houtianze/bypy#215]
11月份曾用bypy分片上传若干1GB-10GB的个人文件到度盘，昨天换了一个帐号重新传，结果那些个人文件全部不能rapidupload

奇怪的是测试了发现原文件，第一次分片上传的文件，二次分片上传的文件这3者的MD5值一致

**Comment by houtianze** [comment]
感谢反馈~

看描述不确定是不是百度那边的问题，还是我之前改动又弄进了bug。。。

如果有空，可以帮忙试一下同一个文件上传三次，（`bypy.py -dv upload <yourfile>`），看下最后秒传有成功吗？

**Comment by jacwl** [comment]
如作者所说，可以秒传成功了

我顺便试了几个昨天分片上传的文件发现都可以正常秒传

看来用新版本的bypy新传的文件应该是不会出现这个问题了

有可能是老版本的问题

**Comment by houtianze** [comment]
哦，那就好，可能是hash缓存的问题（因为`Pickle`格式不通用，又不是纯文本格式，最主要的是Python 2和Python 3下的格式竟然不完全一致。。。，前段时间改成用JSON了，可能转换上没弄利索，但是扫了一下，又没看出具体问题）。如果最新版没问题就还问题不大。
