### ISSUE TITLE
问题好多啊……

### ISSUE THREAD

**Issue by fy0** [houtianze/bypy#216]
首先感谢作者的辛勤工作，然后我想说用得好想哭……

代码也很难下手，君不见 Code Climate 只有 0.1

另外说好的py3资慈呢，作者君你这样会不会给人一种钦定的感觉

而且 master 的编译状态是 error，好难愉快玩耍

**Comment by houtianze** [comment]
欢迎吐槽 :grinning:

嗯，Code Climate的评分是非常低，还没仔细看，不过自认为代码不算特别乱，基本结构就是每个功能函数拼凑HTTP请求数据，然后调用`__request()`来实现对应的功能的。当然还有一些其他的逻辑/帮助函数。

Python3前几个版本已经就支持了，现在的文件都是2，3下可跑的。`钦定`是啥意思？

travis的error是我比较郁闷的问题——本地跑测试多数时间没问题，不过到了travis就会卡住（貌似Python 3.5不卡），这个我就不知道怎么搞定了，它卡了就啥信息也没有。。。

**Comment by fy0** [comment]
@houtianze  我看了一下你setup有个import没过，Travis点进去就可以看到执行结果的。
py3我是在windows下测试的，chcp 65001之后又hack了一下，脚本跑了起来，但发现在上传的时候，文件哈希有问题，报的错误明显是str和bytes的兼容问题。
所以py3肯定是过不去的。

**Comment by houtianze** [comment]
哦，那个import的我知道，要先装pandoc，已经解决，只是还没push。但主要问题不是这个，是最后跑ByPy测试的最后一行会没有输出，然后travis就超时了，这个现在也不知道问题在哪。

Windows chcp下我试过，不好使的，Windows Console Unicode有问题，我也没去看。你如果有Linux环境跑一下未hack的版本就知道Python 3可以不可以了。如果哈希还是有问题，那估计是一个Python 2或3下都有的还未发现的bug。

**Comment by fy0** [comment]
@houtianze 其实就是编码判断，判断的是 'utf-8'，然而windows下取到的编码是 'cp65001'，我觉得这个hack不会影响到功能。
你那里linux下py3能过吗？

**Comment by houtianze** [comment]
哦。我这里Linux下Py3能过的，本地测试每次都是跑两边（一个py2，一个py3），包含了中文文件名的测试，没发现什么问题。不过改了py2兼容后，还没有跑过很多中文目录的情形。

**Comment by fy0** [comment]
呃，你测试的文件是多大的？有没有试过秒传

**Comment by houtianze** [comment]
很小，几十个字节吧。秒传有测试过，不过不是中文文件名。

**Comment by fy0** [comment]
那看来就是OS的锅了

**Comment by houtianze** [comment]
有可能，之前考虑过Windows下直接退出。。不过想到纯英文的目录/文件名还是（应该）没问题的，就只加了个警告。

**Comment by fy0** [comment]
尽量还是做做兼容呀，我自己完全在linux下混没问题，有个shell就行。
但是给小伙伴做点工具，他们还是需要windows的

**Comment by houtianze** [comment]
我也想，但是填平了Python 2/3下str / unicode的坑后，搜搜网上貌似Python在Windows下unicode转码很麻烦，就没敢再趟。另外个原因是当时做这个的起因是没找到Linux下比较省事的工具来备份到百度云，考虑到Windows下有个云管家，也没怎么重视Windows这边。然后就是考虑到Windows下英文/中文的系统，默认系统编码的设定要做的测试。。。

**Comment by fy0** [comment]
不需要转码吧，直接像py3那样用unicode当作字符串print就好了？

**Comment by houtianze** [comment]
没试过，希望如此。。

**Comment by fy0** [comment]
好吧 试了一下。随便输了个字：
>>> print(u'\u4aff')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'gbk' codec can't encode character '\u4aff' in position 0: illegal multibyte sequence

2、3皆崩

linux：
>>> print(u'\u4aff')
䫿

不过一般文件名没这么奇葩吧，不console打印还是好朋友

**Comment by houtianze** [comment]
谢谢测试。如果随便找几个汉字/非拉丁字符呢？最怕的是用到最后发现系统库也是一堆堆UEE/UDE的吐。。。然后就没什么好办法了。

**Comment by fy0** [comment]
@houtianze 我最近了解到一个新姿势，你可以这样：

u'测试\U0000FFFF123'.encode('cp936', errors='ignore').decode('cp936')
重新 encode 一下过滤掉有问题的字符就行了！

**Comment by houtianze** [comment]
@fy0 谢谢提供的信息。考虑过这个，但这个解决方法太过hacky。而且我觉得引入的问题比解决的还多——不支持的文件名上传下载后的名字变了，如果两个文件名过滤掉后是一样的就会丢失文件，等等。
