### ISSUE TITLE
稳定版1.2.9 bypy.py 代码1313行有误

### ISSUE THREAD

**Issue by martinsun** [houtianze/bypy#218]
self.__certpath, formatex(ex)))

应该是self.__certspath, formatex(ex)))，少了一个字母s

**Comment by houtianze** [comment]
好犀利的眼神 :grinning: 

好的，下个commit会改正，谢。还好这行代码运行的概率很小。

**Comment by martinsun** [comment]
恰巧被我遇到了，我debug才发现的。。。

**Comment by houtianze** [comment]
墨菲定律 :grin:

**Comment by houtianze** [comment]
修正了。

**Comment by raphaeltao** [comment]
多谢，打了补丁ok了
