### ISSUE TITLE
Windows 下 ,python3无法运行.

### ISSUE THREAD

**Issue by sickHamm** [houtianze/bypy#221]
python3  bypy.py -ddd list
Encoding for stdout / stderr: cp936
直接退出.
python2 正常. 

--------------------------------------------
Python 3.4.3,

**Comment by houtianze** [comment]
感谢反馈。回复有点晚。

我试了一下，应该是Windows下Python 3对Unicode的支持问题，现在改了一下，Window Python 3下可以用了，不过非英文字符的文件名会出错。
