### ISSUE TITLE
Remote disk empty

### ISSUE THREAD

**Issue by hkalexling** [houtianze/bypy#222]
I've authorised the app but when I use `bypy list` I got `/apps/bypy ($t $f $s $m $d):`, and when I tried `bypy compare` the **remote only** section was empty. I am 100% sure my BaiduYun is not empty and I've used the correct account to authorise. 

Did I miss something? Thanks in advance.

**Comment by houtianze** [comment]
Oh, due to app restrictions, bypy can _only_ access the `/apps/bypy/` directory at Baidu Yun, so the "root" there refers to that directory, and only the contents inside can be listed (in fact, any operations are restricted to be within that directory) :smile:

**Comment by hkalexling** [comment]
Ah I see, thanks for the explanation :)
