### ISSUE TITLE
cent原来python2.6，升级2.7.11后有异常

### ISSUE THREAD

**Issue by raphaeltao** [houtianze/bypy#223]
> <E> [16:37:58] Exception occurred:
Exception:
<type 'exceptions.AttributeError'> - 'ByPy' object has no attribute '_ByPy__certpath'
Stack:  File "/usr/bin/bypy.py", line 4016, in <module>
    main()
  File "/usr/bin/bypy.py", line 4009, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/bin/bypy.py", line 433, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))
Abort

以上

**Comment by houtianze** [comment]
感谢反馈。

看上去是这个问题： #218 升级下最新版应该可以了。
