### ISSUE TITLE
请问你的pcs权限是什么时候申请的呢？

### ISSUE THREAD

**Issue by ycy1164656** [houtianze/bypy#224]
我看网上说现在的pcs权限申请都通不过的啊，你这个是很早申请的？

**Comment by houtianze** [comment]
嗯，是挺早的，至少有两年了。

**Comment by ycy1164656** [comment]
可否共享下呢，我们希望做java开发，做视频网站

**Comment by ycy1164656** [comment]
你使用了gae。。。国内都用不了呢。。。

**Comment by houtianze** [comment]
不要意思，因为这个key是连着百度账号的，附带责任的，所以不便共享，见谅 :flushed: 

GAE是最后一个服务器，前两个OpenShift和Heroku的国内都可以访问的。

**Comment by ycy1164656** [comment]
哦哦对，昨天我是前面的连失败了再看就是gae了，没事哈，我们再想办法

**Comment by houtianze** [comment]
百度好像有个BCS，是面向商业开发的，不过应该是要付费的，我也没用过。其他家的网盘有没有开放程序接口就不清楚了。

**Comment by ycy1164656** [comment]
已经变为bos了，我们几个小伙子想做视频网站，在前期没有投资的情况下，用这个的话费用太高，，无法承担，，，

**Comment by houtianze** [comment]
嗯，做视频对空间和带宽要求都很高，祝你们好运  :smile:

2016-01-27 10:56 GMT+08:00 ycy1164656 <notifications@github.com>:

**Comment by ycy1164656** [comment]
谢谢
