### ISSUE TITLE
如何通过代理上传/下载。

### ISSUE THREAD

**Issue by xJogger** [houtianze/bypy#227]
有什么好方法么，还是需要等其成为一个功能在程序中出现？

**Comment by septs** [comment]
'''
export HTTP_PROXY=http://your-http-proxy-serve:port
bypy .......
'''

See http://docs.python-requests.org/en/latest/user/advanced/#proxies

**Comment by septs** [comment]
@houtianze 由于requests支持HTTP_PROXY设置代理因此建议在检测到用户设置了HTTP_PROXY在日志的首行写上"the user has setup a PROXY"之类的描述来进行判断是非是因用户设置的代理导致的问题

**Comment by houtianze** [comment]
@septs 感谢解答，嗯，这个描述加上去比较好。

:monkey: 年快乐 :smile:

**Comment by houtianze** [comment]
加入提示了。
7ba1d093c6e8119e200b98710797de5ad6372435
