### ISSUE TITLE
稳定版安装 pypandoc出错

### ISSUE THREAD

**Issue by lhzlhzvip** [houtianze/bypy#229]
首先感谢作者大大.我正在学python和树莓派,这码帮了我不少

其实这个问题可以解决,
现在把bypy.py 和 bypygui.pyw放进usr/bin里面.加权755后 在任何文件夹用命令都可以上传.

但是用稳定版安装,会出现下面的提示(我已经用apt-get instsll pandoc装了一遍pandoc,仍然会提示缺少pandoc模块.)

Downloading/unpacking bypy
  Downloading bypy-1.2.16.tar.gz (50Kb): 50Kb downloaded
  Running setup.py egg_info for package bypy
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    WARNING: StdOut encoding is 'None'.
    Files with non-ASCII names may not be handled correctly.
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    Error: PanDoc not found
    No module named pypandoc
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/etc/baiduyun/upload/build/bypy/setup.py", line 14, in <module>
        with open('HISTORY.md') as f:
    IOError: [Errno 2] No such file or directory: 'HISTORY.md'
    Complete output from command python setup.py egg_info:
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

WARNING: StdOut encoding is 'None'.

Files with non-ASCII names may not be handled correctly.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Error: PanDoc not found

No module named pypandoc

Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/etc/baiduyun/upload/build/bypy/setup.py", line 14, in <module>

```
with open('HISTORY.md') as f:
```

IOError: [Errno 2] No such file or directory: 'HISTORY.md'

---

Command python setup.py egg_info failed with error code 1 in /etc/baiduyun/upload/build/bypy
Storing complete log in /root/.pip/pip.log

另外我想问问import的问题.这里面的self是什么意思呢?
def syncup(self, localdir = '', remotedir = '', deleteremote = False):

```
    ''' Usage: syncup [localdir] [remotedir] [deleteremote] - \
```

sync up from the local directory to the remote directory
  localdir - the local directory to sync from if not specified, it defaults to the current directory.
  remotedir - the remote directory at Baidu Yun (after app's directory) to sync to. \
if not specified, it defaults to the root directory
  deleteremote - delete remote files that are not inside the local directory, default is False
        '''

**Comment by houtianze** [comment]
谢谢反馈。俺是小码农，不是大大 :grinning: 

- 你的这个错误是怎么出现的？找不到`HISTORY.md`貌似是执行的目录不在`setup.py`那里？出现`PanDoc`的错误，你应该还要安装`pypandoc` (`sudo pip install pypandoc`)

- `self`是Python里写`class`的方法里面约定俗成的用法，类似于Java / C++里面的`this`，指向实例本身。

**Comment by lhzlhzvip** [comment]
啊.可能我是装了pandoc,但不是pypandoc的原因.

关于这个self,我用了另外一种方法来调用syncup :)
shell = "cd /etc/baiduyun/upload && sudo bypy.py syncup -v "
a = os.system(shell)

不过谢谢啦

**Comment by houtianze** [comment]
这是我之前`setup.py`的问题，最新版已经修复，请用`pip -U`直接安装。
