### ISSUE TITLE
sync 后没有把文件时间也上传

### ISSUE THREAD

**Issue by ipyleaf** [houtianze/bypy#232]
上传到百度云后，文件名变成「神秘时间」。对于图片的影响比较大

**Comment by houtianze** [comment]
感谢反馈。
能帮着贴个日志，描述一下具体问题吗？

**Comment by houtianze** [comment]
如果我没理解错，这个好像是百度的API限制，文件时间好像是以上传的时间为准，所以原始时间戳就没了。因为这个，双相同步好像也没法做。暂时关了。
