### ISSUE TITLE
更新了一下新版的，上传速度好像又慢下来了

### ISSUE THREAD

**Issue by raphaeltao** [houtianze/bypy#233]
如题，之前应该是百度云限制了上传，只有几十k的上传速度。然后办了个VIP，速度就上去了，基本上稳定在1兆吧，但是现在更新了一下最新版本发现速度又变成几十k了。想问下是百度那面的问题吗？我vps在国外

**Comment by houtianze** [comment]
额，这个我也不是很确定，不过按理不应该是最新版的问题，上传下载的部分基本没什么改动。
