### ISSUE TITLE
请问你是如何抓包的？特别是上传的功能

### ISSUE THREAD

**Issue by wojiaojiao** [houtianze/bypy#237]
我想用qt做一个自动上传本地文件到百度云的功能
我是用火狐浏览器抓包的，当点击百度网盘的上传按钮，会出现post方法，然后会返回JSON响应。
用到post和get，但是不知道怎么get到网页返回的json,因为返回的json不直接到html页面上。
post方法也不会用，
反正折腾了好久是搞不定post文件到服务器，也get不到json响应
望指导

**Comment by wojiaojiao** [comment]
我不是用PCS API的，因为现在已经用不了了

**Comment by houtianze** [comment]
额，我其实没抓过包，都是依照PCS的文档来的。。
http://developer.baidu.com/wiki/index.php?title=docs/pcs/rest/file_data_apis_list#.E8.8E.B7.E5.8F.96.E7.9B.AE.E5.BD.95.E4.B8.8B.E7.9A.84.E6.96.87.E4.BB.B6.E5.88.97.E8.A1.A8

有些其他的代码提交者可能抓过包。应该是用Wireshark之类的来做吧？

**Comment by wojiaojiao** [comment]
好的，谢谢，我已经抓包出来了

**Comment by Beenking** [comment]
不是说百度的pcs API 不可以用了吗，@houtuanze 还可以依据文档？

**Comment by houtianze** [comment]
@Beenking 楼主的意思我觉得是：PCS API现在不开放申请了，所以她没法用。
