### ISSUE TITLE
Import 失败……

### ISSUE THREAD

**Issue by XIAZY** [houtianze/bypy#238]
想要作为包来使用 `bypy`，但是 import 失败，无论是 Python 2 还是 Python 3
很奇怪，`bypy` 是用 `pip` 安装的，系统是 `OS X 10.11`

**Comment by houtianze** [comment]
感谢提出。

很不好意思回答这个问题——现在的代码是没法import的 -_-!
我当初想当然的以为Python Path上的单个文件也可以import，后来才知道这种情况下必须要做成目录形式的Package，改动较大，一直没腾下手来弄完（主要是担心regression，所以改动时比较小心），然后也没更新文档。。。

如果想用，有个hack的方法是吧bypy.py放到你的项目当前目录下就可以import了。

**Comment by XIAZY** [comment]
�������������������������������������������������� import ��������������������
����������������������������������������������������������������

**Comment by XIAZY** [comment]
发现了……由于没有文档，但是现在的问题是放在同目录 import 后并不知道该怎么写。
如果能提供一点文档或者最基本的逻辑就好了（验证，上传，下载）……

**Comment by houtianze** [comment]
哦，你可以看下bypy里面的main函数，基本上是构造一个ByPy实例，然后调用upload()函数等等。也可以看下test/ test.py

**Comment by XIAZY** [comment]
谢谢
✉ Bill Xia
> 在 2016年3月22日，下午2:13，Hou Tianze <notifications@github.com> 写道：
> 
> 哦，你可以看下bypy里面的main函数，基本上是构造一个ByPy实例，然后调用upload()函数等等。也可以看下test/ test.py
