### ISSUE TITLE
有没有可能采用多线程的Aria2c进行下载或上传

### ISSUE THREAD

**Issue by ltpeach** [houtianze/bypy#243]
这里有一个将百度云内容到处到aria2c的插件：https://github.com/acgotaku/BaiduExporter

如果能用的话，就完美了。

**Comment by houtianze** [comment]
谢谢建议。不好意思才回复。

你的意思是增加输出下载链接功能？

**Comment by ltpeach** [comment]
BaiduExporter是可以将云盘中的文件链接导出来，然后采用aria2c进行多线程下载，下载速度可以达到几M，非常好用。你有没有可能把这两个功能组合到你的bypy程序中，因为我在用bypy的时候，速度只有100k左右。如果可以将aria2c耦合到程序中，就能极大的提高下载和上传速度。不知道这样是不是可行？

**Comment by fangdingjun** [comment]
如果能用aria2c替换现有的http传输模块或者输出下载链接都非常好

**Comment by jtliaw** [comment]
最新版本增加了aria2下载，下载速度提升了，而且aria2下载有显示目前速度！
安装aria2后即可使用，以下指令：
bypy.py downdir / --downloader aria2

或者

bypy.py syncdown --downloader aria2

**Comment by houtianze** [comment]
嗯，merge了 Dingjun的 #255

**Comment by ltpeach** [comment]
哇 太给力了 谢谢原作者
