### ISSUE TITLE
refreshtoken好像不起作用，是因为墙的原因吗？

### ISSUE THREAD

**Issue by saltyang** [houtianze/bypy#245]
access_toke每1个月都会过期，需要自己手动去web上面拿授权码重新做auth来跟新，看到bypy里面有refreshtoken, 是否可以调用这个自动更新？每次调用这个都fail。

`Authorizing/refreshing with the OpenShift server ...
<E> [22:58:23] Maximum number (1) of tries failed.
OpenShift server failed, authorizing/refreshing with the Heroku server ...
<E> [22:58:24] Failed to decode JSON:
Exception:
Traceback (most recent call last):
  File "bypy.py", line 1515, in **store_json
    j = r.json()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/json/__init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

<E> [22:58:24] Error response:
ERROR: Invalid OAuth request, please retry.
Request:
<LocalRequest: GET https://bypyoauth.herokuapp.com/auth?grant_type=refresh_token&refresh_token=22.760c99739bd8f6ccaeb6b08bbf138840.315360000.1775660145.1715909053-1572671>
<I> [22:58:24] ----------------------------------------------------------------
<I> [22:58:24] This is most likely caused by authorization errors.
Possible causes:
- You didn't run this program for a long time (more than a month).
- You changed your Baidu password after authorizing this program.
- You didn't give this program the 'netdisk' access while authorizing.
- ...
  Possible fixes:
- Remove the authorization token by running with the parameter '-c', and then re-run this program.
- If (1) still doesn't solve the problem, you may have to go to:
  https://passport.baidu.com/accountbind
  and remove the authorization of this program, and then re-run this program.
  Heroku server failed. Last resort: authorizing/refreshing with the GAE server ...
  <E> [22:59:24] Maximum number (1) of tries failed.
  <E> [22:59:24] Token-refreshing on all the servers failed`

**Comment by houtianze** [comment]
这个不是墙的问题，（如果我的调用没有错的话）我觉得是百度PCS API的问题——文档里说access_token一个月过期，但是十年内调用refresh_token就可以再拿到新的access_token，不过现在是这样做的（而且逻辑是如果access_token过期，就会自动刷新），但是超过一个月不用这个程序，refresh_token也没法调用成功。。。

**Comment by saltyang** [comment]
所以access_token一个月过期之后，我们只有再去拿到授权码重先做一个auth来拿到新的access_token.

**Comment by houtianze** [comment]
嗯，貌似现在只能这样。

**Comment by kxxoling** [comment]
删掉重来也不行。日志：

```
Please visit:
https://openapi.baidu.com/oauth/2.0/authorize?scope=basic+netdisk&redirect_uri=oob&response_type=code&client_id=xxxx
And authorize this app
Paste the Authorization Code here within 10 minutes.
Press [Enter] when you are done
a239b5xxxx
Authorizing, please be patient, it may take upto 60.0 seconds...
Authorizing/refreshing with the OpenShift server ...
Successfully authorized
// 这里等很长时间
<E> [17:43:28] Waiting 10 seconds before retrying...
<E> [17:43:38] Request Try #2 / 5
```

**Comment by houtianze** [comment]
@kxxoling 运行`bypy -c`再试试？

**Comment by kxxoling** [comment]
@houtianze 试过，我重新试下。

**Comment by kxxoling** [comment]
这回不报错了，不知道是不是因为重启了一下的缘故。但是有一些同步失败的文件没法继续同步：

```
Statistics:
--------------------------------
Same: 720
Different: 170
Local only: 105
Remote only: 0
```

我应该怎样继续或者重新同步这些没有同步完成的文件？

**Comment by houtianze** [comment]
@kxxoling 哦，有些传输错误，再试着syncdown / syncup多几次，直到两边都一样吧。

**Comment by kxxoling** [comment]
@houtianze syncdown 没有反应，syncup 会不会用本地错误文件覆盖掉远程的？

**Comment by houtianze** [comment]
`sycndown -dv`有什么输出呢？你想要的是下载，那不要用`syncup`，是会覆盖远程文件的。

**Comment by kxxoling** [comment]
我写了个脚本把 different 的文件都删除了，然后 compare 一下：

```
Statistics:
--------------------------------
Same: 720
Different: 0
Local only: 8
Remote only: 170
```

输出的东西有点多，大部分都是 JSON，我摘一下最后的：

```
<D> File info json: {u'isdir': 0, u'ctime': 1376897421, u'fs_id': 831268317859654, u'mtime': 1460713173, u'path': u'/apps/bypy/Within Temptation - Discography (1997-2013) [FLAC]/2008 - Black Symphony CD1/11 - The Swan Song(1).flac', u'md5': u'0a467671fbc66c29c802299a6a842682', u'size': 26637294}
<D> Request all goes fine
<D> Checking if we already have the copy locally
<D> headers['Range'][6:]: 0-20971519 MC0yMDk3MTUxOQ==
<D> GET https://d.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/Within Temptation - Discography (1997-2013) [FLAC]/2008 - Black Symphony CD1/11 - The Swan Song(1).flac', 0, 26637294, 1465384578.467129)
<D> Params: {u'path': u'/apps/bypy/Within Temptation - Discography (1997-2013) [FLAC]/2008 - Black Symphony CD1/11 - The Swan Song(1).flac', u'method': u'download'}
<D> Full URL: http://125.39.134.46/r/cdn.baidupcs.com/file/0a467671fbc66c29c802299a6a842682?bkt=p-db583403be696abc5e1e002d72081cfd&xcode=59e4e0a1c07ca2967972314d25526d090d3788e8220cea469717ec4418c70769&fid=3775067569-1572671-831268317859654&time=1465384579&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-MvtfxQh7PLyYLh6%2BeLseZz8KrRs%3D&to=cb&fm=Qin,B,T,nc&sta_dx=25&sta_cs=80&sta_ft=flac&sta_ct=7&fm2=Qingdao,B,T,nc&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400fc1e227a3244111bfca805f5abb81f973b1aefae0000019673ee&sl=71041102&expires=8h&rt=pr&r=592691734&mlogid=3706282687055656131&vuk=-&vbdid=-&fin=11%20-%20The%20Swan%20Song%281%29.flac&slt=pm&uta=3&rtype=1&iv=0&isw=0&dp-logid=3706282687055656131&dp-callid=0.1.1
<D> HTTP Status Code: 206
<D> 206 Partial Content (this is OK), processing action
[===============_____] 78% (20.0MB/25.4MB) ETA: 25s (219kB/s, 1m33s gone) <D> Request all goes fine
<D> headers['Range'][6:]: 20971520- MjA5NzE1MjAt
<D> GET https://d.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/Within Temptation - Discography (1997-2013) [FLAC]/2008 - Black Symphony CD1/11 - The Swan Song(1).flac', 20971520, 26637294, 1465384578.467129)
<D> Params: {u'path': u'/apps/bypy/Within Temptation - Discography (1997-2013) [FLAC]/2008 - Black Symphony CD1/11 - The Swan Song(1).flac', u'method': u'download'}

这里我回车了几次

<D> Full URL: http://125.39.134.46/r/cdn.baidupcs.com/file/0a467671fbc66c29c802299a6a842682?bkt=p-db583403be696abc5e1e002d72081cfd&xcode=4a3c27c5daf2582c1fdbc7bd01ffc8490d3788e8220cea469717ec4418c70769&fid=3775067569-1572671-831268317859654&time=1465384672&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-VRPTuUxUMf5XUpBYdqZVG3fZ9Es%3D&to=cb&fm=Qin,B,T,nc&sta_dx=25&sta_cs=80&sta_ft=flac&sta_ct=7&fm2=Qingdao,B,T,nc&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400fc1e227a3244111bfca805f5abb81f973b1aefae0000019673ee&sl=79102030&expires=8h&rt=pr&r=303911177&mlogid=3706307842349189391&vuk=-&vbdid=-&fin=11%20-%20The%20Swan%20Song%281%29.flac&slt=pm&uta=3&rtype=1&iv=0&isw=0&dp-logid=3706307842349189391&dp-callid=0.1.1
<D> HTTP Status Code: 206
<D> 206 Partial Content (this is OK), processing action
[====================] 100% (25.4MB/25.4MB) ETA:  (177kB/s, 2m27s gone) <D> Request all goes fine
'Within Temptation - Discography (1997-2013) [FLAC]/2008 - Black Symphony CD1/11 - The Swan Song(1).flac' <== '/apps/bypy/Within Temptation - Discography (1997-2013) [FLAC]/2008 - Black Symphony CD1/11 - The Swan Song(1).flac' OK
<D> Downloading '/apps/bypy/Within Temptation - Discography (1997-2013) [FLAC]/2005 - The Silent Force Tour/06 - Angels(1).flac' as 'Within Temptation - Discography (1997-2013) [FLAC]/2005 - The Silent Force Tour/06 - Angels(1).flac'
```

似乎是下载完了一个文件。然后我 compare 了一下：

```
Statistics:
--------------------------------
Same: 720
Different: 1
Local only: 8
Remote only: 169
```

少了一个 Remote only，多了一个 Different。

**Comment by houtianze** [comment]
也就是syncdown几次完成后百度云和本地目录的也还都不完全一样？

**Comment by kxxoling** [comment]
是的，最早期正常完成的都没问题，剩下的这些试了很多次一直有问题。

**Comment by houtianze** [comment]
会有错误提示吗？还是没有任何错误，但就是不会下载？所有为文件夹都会出现这种问题还是只有文件比较的时候才会出现这个问题？那些没同步的网页端能下载吧？

**Comment by kxxoling** [comment]
没有错误提示，有的文件只有 ``[===============_____] 78%`` 没有 ``[====================] 100%``，有的文件都有。猜测这里是输出进度的问题，为了防止任务中断，我都是在 tmux 中运行的 bypy。

**Comment by houtianze** [comment]
但是程序会正常结束还是卡住不动？

现在想不出原因是什么，更新`requests`试试？
```
sudo pip install -U requests
```

**Comment by kxxoling** [comment]
@houtianze 程序都是正常结束的，requests 更新到最新依旧有问题。上面的 log 中有一些状态码是 206，不知道是不是跟这个有关系。

**Comment by houtianze** [comment]
如果是到最后只有`Different`，没有`Remote only`的可能是都下完了，不同的那些有可能是因为百度给出的哈希值不正确。（一个解决方法是你把你整个本地目录上传到百度云另外一个目录，然后再比较一遍，看是否一致）

206代码正常，是在续传，没有问题。

**Comment by houtianze** [comment]
现在refresh token过一个月也失效，除非弄个cron job来二十多天`bypy refreshtoken`一下，好像也没有别的解决方法。
