### ISSUE TITLE
bypy能否自动判断syncdown，还是syncup？

### ISSUE THREAD

**Issue by weeeeeee** [houtianze/bypy#246]
**我的使用情境时这样：**
在多台电脑上都有bypy，而且在crontab里面添加了bypy syncup local remote。
也就是每台机器每隔5分钟会自动上传本地文件到云端，都是用bypy syncup。
**问题是这样：**
在电脑A上，修改文件保存之后，系统自动bypy syncup。
在电脑B上，文件是旧版本的，但是也自动bypy syncup了，导致旧版本覆盖了新版本。

bypy能否自动判断syncdown还是syncup？根据文件修改时间什么的
那样就可以直接bypy sync。

**Comment by houtianze** [comment]
感谢建议。不要意思才回复。
有道理，我看看什么时候加上去。我能想到的就是凭时间戳来判断同步时保留哪一方。

**Comment by weeeeeee** [comment]
xmarks同步书签时，除了时间戳之外，每一个版本都有版本号。
bypy里面能否维护一个版本号呢，这似乎取决于百度云？

**Comment by linweilian03** [comment]
凭时间戳来判断，存在着一个问题。百度云网盘中文件的时间戳是取决于上传时间，本地文件的时间戳一定早于网盘中的时间。

**Comment by houtianze** [comment]
@linweilian03 感谢提醒，这样看来逻辑上比较复杂，比较难以实现。

我觉得这个情况是不是可以用其他办法来解决，比如：两台电脑用rsync或者其他专门的备份/同步软件保持一致，然后用bypy来定时上传其中一份就好了？

**Comment by linweilian03** [comment]
有一个不完美的解决方案。就是第一次上传文件时，修改本地文件时间与网盘一致。之后再判断两者时间戳的问题。

**Comment by houtianze** [comment]
明白。不过这样做有个副作用，本地文件被修改了，会影响其它做同步/备份软件的判断。另外用户也可能会不满意软件随便该文件的时间。
