### ISSUE TITLE
bypy.py syncup & Abort

### ISSUE THREAD

**Issue by zengsn** [houtianze/bypy#249]
[root@li82-76 www]# bypy.py syncup &
[1] 2078
[root@li82-76 www]# <E> [02:22:30] Exception occurred:
Exception:
<type 'exceptions.UnicodeDecodeError'> - 'ascii' codec can't decode byte 0xca in position 1: ordinal not in range(128)
Stack:
  File "/usr/local/bin/bypy.py", line 4368, in <module>
    main()
  File "/usr/local/bin/bypy.py", line 4361, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/local/bin/bypy.py", line 476, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Abort

PS：最新版本。

**Comment by zengsn** [comment]
请问是我操作不对还是什么问题呢？求解决方法。谢谢

**Comment by zengsn** [comment]
bypy.py upload & 目前正常的，改用这个命令了。

**Comment by kenweini** [comment]
我也现了这个问题，到现在还没有解决呀。

手动上传一切正常，但cron时syncup 和upload均是无法上传，Abort....
在crontab中bypy.py upload 也不行呀！


大家怎么处理的，能告知不，谢谢。

**Comment by houtianze** [comment]
感谢反馈。

@zengsn 这个问题还在吗？如果有时间能用最新版运行然后提供下log和运行环境吗？之前的代码在出错打印堆栈有些问题，看不出问题出在哪里。UnicodeDecodeError，是openwrt的系统吗？

**Comment by houtianze** [comment]
感觉又是系统编码问题。
