### ISSUE TITLE
bypy 为什么不能自动创建父级目录

### ISSUE THREAD

**Issue by everhopingandwaiting** [houtianze/bypy#250]
bypy 为什么不能自动创建父级目录， 在上传时 只能 同步当前 文件下的所有 文件到  pcs 的 对应 bypy 下，这样 就会感觉太乱 啊 ，  是  百度云 那边 的限制 还是 没有 考虑这个 呢？   

有空 我试着完成这个功能。

**Comment by houtianze** [comment]
这个没看太懂，现在的上传是支持自动创建父级目录的啊。
