### ISSUE TITLE
下载速度好慢啊, 一直卡着不动

### ISSUE THREAD

**Issue by goxxx** [houtianze/bypy#256]
现在的head版本

**Comment by goxxx** [comment]
没人回复吗

**Comment by goxxx** [comment]
难道要学习一遍代码才行?

**Comment by jtliaw** [comment]
最新版本增加了aria2下载，下载速度提升了，而且aria2下载有显示目前速度！

**Comment by houtianze** [comment]
现在传输都是单线程的，有时候会很慢。并行/多线程我有考虑加入，但是工作量不是很小，可能很久也不会动工/实现。

如果只是下载的的话，可以按 jtliaw 说的用`aria2`做下载后端，应该可以提高一些速度（我还没比较过）。

**Comment by jtliaw** [comment]
我的网线是小水管（1M），aria2下载能提高速度的原因在于稳定速度下载！
我有使用conky manager的network panel来对比，发现原本的下载速度大约在10秒左右会跌到0然后再回升，不断的重复！速度稳定在85kb～120kb（多数在低位）
aria2下载就很长时间才会出现一次跌到0然后再回升，不断的重复！速度稳定在115kb～125kb

**Comment by houtianze** [comment]
看来还是aria2的下载强大啊。
