### ISSUE TITLE
同步失败啊

### ISSUE THREAD

**Issue by jiangjiangflies** [houtianze/bypy#257]
Error accessing 'https://pcs.baidu.com/rest/2.0/pcs/file'
<E> [08:00:16] Function: __walk_remote_dir_act
<E> [08:00:16] Website parameters: {u'path': u'/apps/bypy', u'order': u'asc', u'method': u'list', u'by': u'name'}
<E> [08:00:16] Waiting 10 seconds before retrying...

**Comment by houtianze** [comment]
如果只是出现这个错误，只是网络不通，程序会重试的，可以忽略。
同步最后成功了吗？
