### ISSUE TITLE
home dir下的文件被清空

### ISSUE THREAD

**Issue by shendeshuitan** [houtianze/bypy#259]
在home dir 下执行bypygui.pyw后通过授权，之后log中显示将home dir 中所有文件删除了

**Comment by houtianze** [comment]
这个听起来有点恐怖，但是只是授权应该不会清空账号目录吧。授权之后你进行了什么操作吗？还有，你可以帮着把显示删除home dir中所有文件的log贴一下吗？

**Comment by houtianze** [comment]
我推测应该是这样的情形：

在之前的代码下，你运行了bypygui.pyw授权之后，未选择任何远程或本地目录，然后直接点了Sync Down。因为之前sync是默认删除多余文件的，在未选择远程和本地目录的情况下，远程目录默认是`/apps/bypy`（未作任何上传之前是空的），本地目录是程序当前目录（你反应的情况下是home dir），Sync Down就会把本地目录（home dir）比远程目录（`/apps/bypy`）多出的任何文件都删除。

为了防止类似的误操作发生，现在修改了默认行为：
- 本地目录缺省为`/tmp`
- Sync默认不删除多余文件

感谢反馈，希望此次误操作没有给你带来太大的损失。

**Comment by shendeshuitan** [comment]
你好，当时的log还没来得及保存出来，情况基本上和你说的一样，当时点了几下Sync Down 下载同步， Sync Del也是默认勾选，当时在听歌没有太在意，然后突然桌面全部消失了我才注意到，log里的内容大致是删除home dir 下某个文件（夹），包括.*的隐藏文件。我最重要的文件都是git同步所以只是损失了本地的一些文件，配置文件索性从别的电脑拷过来了，对系统也没有影响，总体来说损失不是太大

**Comment by houtianze** [comment]
之前没有考虑的默认下的存在的危险性，还好损失不是特别大，抱歉 :flushed:
