### ISSUE TITLE
上传(upload)目录时出现如下错误(目录有多级，单个文件大于100M)

### ISSUE THREAD

**Issue by dotmark** [houtianze/bypy#260]
456 <E> [09:43:01] Exception occurred:
457 Exception:
458 <type 'exceptions.AttributeError'> - 'dict' object has no attribute 'remove'
459 Stack:
460   File "/usr/local/bin/bypy.py", line 4467, in <module>
461     main()
462   File "/usr/local/bin/bypy.py", line 4460, in main
463     perr("Exception occurred:\n{}".format(formatex(ex)))
464   File "/usr/local/bin/bypy.py", line 488, in formatex
465     type(ex), ex, ''.join(traceback.format_stack()))
466
467 Abort
468 Saving Hash Cache...

**Comment by houtianze** [comment]
感谢反馈。
这是之前改动不小心带入的bug，应该已经修正。
