### ISSUE TITLE
想问下有没有计划增加webui？

### ISSUE THREAD

**Issue by eromoe** [houtianze/bypy#262]
readme里的是bcloud是gui的。。。其实我想做个界面管理vps哪些文件夹需要备份
有webui会方便不少，有接口的话，我也可以自己弄个

**Comment by houtianze** [comment]
计划是有的，但是。。。我实在不确定什么时候会去加。。。一样同意WebUI方便很多。
没有REST/PRC之类的接口，但是如果用Python写WebUI的话，可以直接`import bypy`，然后直接调用`ByPy`的函数，可以参考`test/test.py`里面的用法。

**Comment by houtianze** [comment]
Tracked under #180
