### ISSUE TITLE
手动可以上传，Crontab无响应

### ISSUE THREAD

**Issue by kenweini** [houtianze/bypy#265]
如果在命令行下直接执行的话，没有任何问题，上传成功。
放到 crontab 中定时执行的时候，却没有任何响应，上传失败。

crontab代码如下
#vi /etc/crontab
#在最后一行中加入：
`01 5 * * * root /home/kit/autobackup.sh `

autobackup.sh代码如下
#vi autobackup.sh
`/usr/bin/python /usr/bin/bypy.py syncup /home/kit/backuptmp`

在命令行下直接执行的话，上传成功，无任何错误，正常。
`cd  /home/kit/`
`./autobackup.sh`

放到 crontab 中定时执行的时候，时间到了却没有任何反映（查过权限等等，没有任何问题）。

为了查找问题，修改crontab如下：
`01 5 * * * root /home/kit/autobackup.sh >> /home/kit/traceerror.log 2>&1`

运行corntab后查看日志：
https://openapi.baidu.com/oauth/2.0/authorize?scope=basic+netdisk&redirect_uri=oob&response_type=code&client_id=qdfg8WfE4EfdgerpCfgsaufrl1omn
And authorize this app
Paste the Authorization Code here within 10 minutes.
Press [Enter] when you are done
<E> [23:38:02] Exception occurred:
Exception:
<type 'exceptions.EOFError'> - EOF when reading a line
Stack:
  File "/usr/bin/bypy.py", line 4481, in <module>
    main()
  File "/usr/bin/bypy.py", line 4474, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/bin/bypy.py", line 494, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Abort
Traceback (most recent call last):
  File "/usr/bin/bypy.py", line 4481, in <module>
    main()
  File "/usr/bin/bypy.py", line 4453, in main
    verbose = args.verbose, debug = args.debug)

这个问题折腾了我好几天了，请大侠帮忙看看，问题出在哪里，如何解决，谢谢。

注：bypy.py为最新版本：1.2.21

**Comment by kenweini** [comment]
我的环境：
1、Centos 6.5
2、python2.7.11（Python 2.6.6 升级而来）
3、bypy.py：1.2.21

**Comment by kenweini** [comment]
我感觉是缺少了CACERTS的相关参数，即在cron时无法读取认证的相关参数，可是我要怎么写才能让cron正确运行呢？

目前还是一头雾水。

**Comment by houtianze** [comment]
看log我觉得应该是因为crontab是以root身份运行的，所以你之前做的授权之类的并不会读取（在当前用户的主目录），所以会要你输入token，因为是非交互式运行，直接就EOF了。

你的cron脚本用`su <your username>`之类的以你的用户身份运行应该可以解决。

**Comment by jtliaw** [comment]
我觉得把crontab脚本放在/usr/local/bin内试试！
我的Lubuntu crontab 执行的脚本写法（noip的自动重启）20分钟！
*/20 * * * * root sync
*/20 * * * * root /usr/local/src/noip-2.1.9-1/debian.noip2.sh restart

**Comment by kenweini** [comment]
@houtianze 
谢谢您，解决了，可以正常上传了。

我的具体的办法是：使用crontab -e来创建的crontab ，而不是使用vi /etc/crontab。
使用crontab -e来创建百度已经认证的tooken的用户的crontab，就会读取已经认证的tooken，就能上传了。


#crontab -e
`01 5 * * *  /home/kit/autobackup.sh`

#vi autobackup.sh
`/usr/bin/python /usr/bin/bypy.py syncup /home/kit/backuptmp`

**Comment by houtianze** [comment]
客气了，解决就好 :+1:
