### ISSUE TITLE
bypy gui问题

### ISSUE THREAD

**Issue by jtliaw** [houtianze/bypy#266]
bypygui.pyw下不能使用（download下载）功能！
出现的错误：
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/bin/bypygui.pyw", line 455, in downloadproc
    if rpath[-1] == '/':
IndexError: string index out of range

还有bypy gui没有显示下载进度，终端的bypy反而有显示下载进度，希望gui的bypy也能够有显示下载进度！感谢作者的开发！

**Comment by houtianze** [comment]
感谢反馈，我看看。

**Comment by houtianze** [comment]
刚刚更新了，现在应该好了吧？

下载/syncdown没有进度条的吗？我已经实现了，除非有bug。。

**Comment by jtliaw** [comment]
感谢更新！确实是没有错误信息了！
下载/syncdown是有进度条的，但是Log日记内没有显示目前下载速度（像aria2下载时那样有显示目前速度）
bypygui.pyw 如何使用aria2下载呢？
非常抱歉！太多问题麻烦你了！

**Comment by houtianze** [comment]
不客气。嗯，是没有显示下载速度的，因为gui直接“劫持”了显示进度的函数，改为用进度条显示，速度显示部分还没有加上去。当初只是想做个非常简单的GUI，所以也么有提供命令行那些参数的设置，如果想用aria2下载，暂时的解决办法是改代码，搜索：
`self.byp = bypy.ByPy(verbose = 1)`
换成：
`self.byp = bypy.ByPy(verbose = 1, downloader='aria2')`

**Comment by jtliaw** [comment]
非常感谢您的指导！谢谢！
