### ISSUE TITLE
提供多用户登陆

### ISSUE THREAD

**Issue by starzou** [houtianze/bypy#269]
你好，我看到 ~/.bypy/bypy.json  文件
存储了用户的session 相关信息，
是否能提供多个用户登陆，按照不同的用户操作。

**Comment by starzou** [comment]
what do you think? @houtianze

**Comment by N46AN** [comment]
自己包装一下 使用不同的 ~/.bypy/ 目录试试看？

**Comment by mengxd** [comment]
直接改一行code让bypy使用当前目录下的配置即可。看
https://github.com/mengxd/bypy/blob/master/bypy.py#L315

**Comment by houtianze** [comment]
感谢建议和回答。

之前代码里已经有支持，只是没放出命令行的参数接口。现在可以用`--config-dir`来指定配置目录（默认的是`~/.bypy`）

由于PCS API并不能拿到用户账号的任何信息，所以好像也没办法按登录名来区分。这个配置目录的接口算是勉强凑合支持多用户登录吧。
