### ISSUE TITLE
上传运行前报错，然后正常上传，文件未上传

### ISSUE THREAD

**Issue by Wolfsin** [houtianze/bypy#270]
<E> [18:40:38] Error accessing 'https://pcs.baidu.com/rest/2.0/pcs/file'
<E> [18:40:38] Function: __combine_file_act
<E> [18:40:38] Website parameters: {u'path': u'/apps/bypy/Overwatch Animated Short 2 | "Alive".mp4', u'ondup': u'overwrite', u'method': u'createsuperfile'}
<E> [18:40:38] Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=21.fab1b21da34f444e405b2d0f3e93ef9e.2592000.1468597195.1897126010-1572671&path=%2Fapps%2Fbypy%2FOverwatch+Animated+Short+2+%7C+%22Alive%22.mp4&ondup=overwrite&method=createsuperfile
<E> [18:40:38] HTTP Response Status Code: 400
<E> [18:40:38] Error JSON returned:{u'error_code': 31062, u'error_msg': u'file name is invalid', u'request_id': 4076791846732271452}
Error code: 31062
Error Description: file name is invalid
<E> [18:40:38] Website returned: {"error_code":31062,"error_msg":"file name is invalid","request_id":4076791846732271452}

检测授权还是没问题的

**Comment by houtianze** [comment]
感谢反馈。

从错误代码上来看，应该是文件名里含有百度不接受的字符（估计是双引号），改名应该就可以解决了。
因为这个限制是百度方面的，也没有什么好的解决方案，只能避免用这些可能不被百度接受的字符来命名文件了。
