### ISSUE TITLE
file is not authorized

### ISSUE THREAD

**Issue by sechacking** [houtianze/bypy#271]
授权完，list后提示

file is not authorized

**Comment by jtliaw** [comment]
试试看把.bypy内的bypy.json文件删除后再重新授权过看看！（ubuntu位置是在/home/user/.bypy/bypy.ison）

**Comment by houtianze** [comment]
感谢 jtliaw 的解答。

这个错误貌似是百度认为是违禁文件，不让上传下载吧。
