### ISSUE TITLE
bypy对大文件下载的支持不友善啊~

### ISSUE THREAD

**Issue by QGB** [houtianze/bypy#272]
Loading Hash Cache File 'D:\Program Files\Git\.bypy\bypy.hashcache.json'...
Hash Cache File 'D:\Program Files\Git\.bypy\bypy.hashcache.json' not found, no caching
<I> [23:12:45] Local file and remote file sizes DON'T match
<E> [00:41:56] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [00:41:56] Function: __downchunks_act
<E> [00:41:56] Website parameters: {u'path': u'/apps/bypy/Server2012R2.GHO', u'method': u'download'}
<E> [00:41:56] Waiting 10 seconds before retrying...
<E> [00:42:06] Request Try #2 / 5
<E> [00:42:23] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [00:42:23] Function: __downchunks_act
<E> [00:42:23] Website parameters: {u'path': u'/apps/bypy/Server2012R2.GHO', u'method': u'download'}
<E> [00:42:23] Waiting 20 seconds before retrying...
<E> [00:42:43] Request Try #3 / 5
<E> [00:43:00] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [00:43:00] Function: __downchunks_act
<E> [00:43:00] Website parameters: {u'path': u'/apps/bypy/Server2012R2.GHO', u'method': u'download'}
<E> [00:43:00] Waiting 30 seconds before retrying...
<E> [00:43:30] Request Try #4 / 5
<E> [00:43:48] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [00:43:48] Function: __downchunks_act
<E> [00:43:48] Website parameters: {u'path': u'/apps/bypy/Server2012R2.GHO', u'method': u'download'}
<E> [00:43:48] Waiting 40 seconds before retrying...
<E> [00:44:28] Request Try #5 / 5
<E> [00:44:45] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [00:44:45] Function: __downchunks_act
<E> [00:44:45] Website parameters: {u'path': u'/apps/bypy/Server2012R2.GHO', u'method': u'download'}
<E> [00:44:45] Maximum number (5) of tries failed.

可以加个大文件断点续传功能吗，下次打开继续下载。。。

**Comment by jtliaw** [comment]
可以使用aria2下载啊！（电脑先安装aria2）
bypy.py downdir / --downloader aria2

如果不使用aria2下载，可以修改(bypy.py)
找到：
dest="retry", default=5
改为：
dest="retry", default=99

**Comment by houtianze** [comment]
感谢反馈和 @jtliaw 的回答。

是的，默认就是断点续传，重新运行`bypy`就回接着下载。

重试值也可以通过`--retry`命令行参数来修改。
