### ISSUE TITLE
内层子文件夹被创建至外层

### ISSUE THREAD

**Issue by N46AN** [houtianze/bypy#273]
网盘中 "/apps/bypy/transfer/书籍" 中有若干子文件夹
使用 downdir /transfer/书籍 /local/doc 下载时，“书籍”中的子文件夹不仅会在“书籍”中创建，且会在上一层，即与“书籍”平行的一层中创建，但其中最终为空。

例 最终类似下面的样子：

```
doc/
├── allan-de-botton
│   ├── a-week-at-the-airport
│   ├── the-art-of-travel
│   └── the-pleasures-and-sorrows-of-work
├── a-week-at-the-airport
├── the-art-of-travel
└── the-pleasures-and-sorrows-of-work
```

a-week-at-the-airport  the-art-of-travel  the-pleasures-and-sorrows-of-work 
这三个文件夹被创建了两次，其中一次位置错误。

补充：另有一定概率在上两层的位置错误创建文件夹

**Comment by houtianze** [comment]
感谢反馈。

有些奇怪，之前还未有人反映有这样的问题。如果方便，可否：
- 升级到最新版`pip install bypy`
- `bypy -dv downdir /transfer/书籍 /local/doc | tee /tmp/bypy.log`

然后贴下`/tmp/bypy.log`的内容（比如放到pastebin之类的粘贴网站）?

**Comment by jtliaw** [comment]
确实有这个问题！
只要是下载的文件夹内有多重文件夹就会如此！

**Comment by houtianze** [comment]
感谢确认。看来文件夹下载逻辑有问题，我看看l

**Comment by houtianze** [comment]
应该修复了，在用这个命令的可以再试一试。

**Comment by houtianze** [comment]
pip 安装最新版1.3.6

**Comment by jtliaw** [comment]
感谢作者修复！证实没此问题了！

**Comment by N46AN** [comment]
抱歉回复晚了，非常高兴看到作者还在更新此项目。感谢作者的付出！感谢楼上帮助确认此问题！

**Comment by houtianze** [comment]
没问题，感谢回复。
