### ISSUE TITLE
syncdown not work since 25JUL 2016

### ISSUE THREAD

**Issue by HXDAI** [houtianze/bypy#276]
syncdown not work since 25JUL 2016
---------------------------------------
<E> [time] Waiting 10 seconds before retrying ..........
<E> [time] Request Try #2 / 5 .........
<E>..........
<E>..........
<E>..........Maximum number (5) of tries failed. 

Exit without any message.

Is Baidu changed something back end?

**Comment by N46AN** [comment]
Works fines here apart from minor issues. Might be an ISP/Internet connection issue.

**Comment by HXDAI** [comment]
Don't think this is  ISP/Internet connection issue.  I can view  content in my browser without any issue.

**Comment by HXDAI** [comment]
Reason founded:  some baidu IP in host file not working. After deleted all the Baidu IP. It works.
