### ISSUE TITLE
syncup的时候deleteremote参数加不上

### ISSUE THREAD

**Issue by goxxx** [houtianze/bypy#277]
加上了, 也没反应, 要代码里面把deleteremote变成True才行, fix一下

**Comment by goxxx** [comment]
或者命令行出个例子

**Comment by goxxx** [comment]
这个问题怎么没人回复呢

**Comment by houtianze** [comment]
感谢反馈。

你试试这样（装最新版：`pip install bypy`）：
`bypy syncup . / 0` ?
