### ISSUE TITLE
Unhandled exception while getting the help info about a command.

### ISSUE THREAD

**Issue by renweizhukov** [houtianze/bypy#278]
$ bypy.py help search
<E> [15:42:43] Exception occurred:
Exception:
<type 'exceptions.AttributeError'> - type object 'ByPy' has no attribute 'HelpMarker'
Stack:
  File "/usr/local/bin/bypy.py", line 4469, in <module>
    main()
  File "/usr/local/bin/bypy.py", line 4462, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/local/bin/bypy.py", line 494, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Abort
Traceback (most recent call last):
  File "/usr/local/bin/bypy.py", line 4469, in <module>
    main()
  File "/usr/local/bin/bypy.py", line 4448, in main
    result = getattr(by, args.command[0])(*uargs)
  File "/usr/local/bin/bypy.py", line 2080, in help
    pos = help.find(ByPy.HelpMarker)
AttributeError: type object 'ByPy' has no attribute 'HelpMarker'

**Comment by houtianze** [comment]
感谢反馈。

下最新版试试（`pip install bypy`）。我刚试过`bypy help search`没问题的：
```
Usage: search <keyword> [remotepath] [recursive] - search for a file using keyword at Baidu Yun
  keyword - the keyword to search
  remotepath - remote path at Baidu Yun, if not specified, it's app's root directory
  resursive - search recursively or not. default is true
```

**Comment by renweizhukov** [comment]
谢谢你的建议！发现是之前安装的问题，没有装上最新版，现在没问题了。
