### ISSUE TITLE
 Error accessing 'https://pcs.baidu.com/rest/2.0/pcs/file

### ISSUE THREAD

**Issue by very99** [houtianze/bypy#279]
持续传了很多文件，然后发现就出error了 。
info等可以显示云盘剩余大小， 但是好像连不过去了。
<E> [17:14:08] Error accessing 'https://pcs.baidu.com/rest/2.0/pcs/file'
<E> [17:14:08] Function: __walk_remote_dir_act
<E> [17:14:08] Website parameters: {u'path': u'/apps/bypy/seafile', u'order': u'asc', u'method': u'list', u'by': u'name'}
<E> [17:14:08] Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=xxxxxxxxxxxxx
<E> [17:14:08] HTTP Response Status Code: 404
<E> [17:14:08] Error JSON returned:{u'error_code': 31066, u'error_msg': u'file does not exist', u'request_id': xxxxxxxxxx}
Error code: 31066
Error Description: file does not exist
<E> [17:14:08] Website returned: {"error_code":31066,"error_msg":"file does not exist","request_id":xxxxxxxx}

**Comment by jtliaw** [comment]
我曾经也有出现过一次这个现象，把/home/xxx/.bypy/内的bypy.json删除，再次换过一个token看看！

**Comment by hardywu** [comment]
没用。还是出问题

**Comment by houtianze** [comment]
感谢反馈。

我还从来没遇见过这个问题。你是用什么命令时出现的这个错误？
听起来像是你上传时目录或文件被删除了？
