### ISSUE TITLE
同步到本地时报错，程序中断

### ISSUE THREAD

**Issue by MosesHe** [houtianze/bypy#280]
中断前的最后输出是TypeError: **str** returned non-string (type SysCallError)
下载的文件名包含繁体字。
如果需要更多log，请问如何获得？

**Comment by houtianze** [comment]
感谢反馈。

感觉是`requests`库的问题（ https://github.com/kennethreitz/requests/issues/2524 ）。升级下最新版`pip install bypy`应该可以解决问题（会一并安装 `requests` 至少 `2.10`或以上的版本）

若想贴log：
`bypy -dv command | tee /tmp/bypy.log`，然后把`/tmp/bypy.log`内容贴在这里（如果太长，可以考虑pastebin之类的网站）
