### ISSUE TITLE
希望增加ftp/webdav服务支持

### ISSUE THREAD

**Issue by cbwang2016** [houtianze/bypy#284]
如题。国内网盘都不支持FTP/webdav访问，2T的空间基本就浪费了。如果给bypy接一个FTP/webdav访问，然后放到服务器上之类的，应该会很好玩

**Comment by snakevil** [comment]
随意搭一个 ftp/webdav 指向同步目录不就可以了么？

**Comment by houtianze** [comment]
感谢建议。

嗯，我也觉得ftp/webdav支持可以交给系统做，mount成一个目录，然后操作就没区别了。
