### ISSUE TITLE
`bypy list` capped at 1000 files maximum per directory?

### ISSUE THREAD

**Issue by eiNgoh5R** [houtianze/bypy#285]
`bypy list` only shows 1000 files if the directory has more than 1000. Also, `bypy compare` always thinks the remote directory has only 1000 files when there's more than 1000, therefore it lies about there being bunch of local only files. If you look at the web UI at http://pan.baidu.com, it allows more than 1000 files in a directory.

**Comment by houtianze** [comment]
Thanks for feeding back this.

I never tested such a big number of files before, `bypy` itself never adds this limitation. If this is really the case, I think it is a limitation of the Baidu PCS API ( http://developer.baidu.com/wiki/index.php?title=docs/pcs/rest/file_data_apis_list#.E8.8E.B7.E5.8F.96.E7.9B.AE.E5.BD.95.E4.B8.8B.E7.9A.84.E6.96.87.E4.BB.B6.E5.88.97.E8.A1.A8 ) However, it was not mentioned there.

**Comment by Asoo8ice** [comment]
Yes, the limitation seems to be part of the API, but I think `bypy` can work around it with:

|参数名称|类型|是否必需|描述|
|---|---|---|---|
|limit | string | 否 | 返回条目控制，参数格式为：n1-n2。返回结果集的[n1, n2)之间的条目，缺省返回所有条目；n1从0开始。|

by first getting "0-999", then "1000-1999", then "2000-2999", and so on until a list with fewer than 1000 elements is returned, appending each new list to the existing one.

**Comment by houtianze** [comment]
@Asoo8ice 

Thanks for the information. I should add this sometimes later when I have time.

**Comment by colourful-land** [comment]
I can confirm this problem with a folder of mine that has more than 1000 files. bypy only shows the first 1000.

**Comment by houtianze** [comment]
@colourful-land Thanks for the confirmation.

I will probably fix this when I have some time (but don't expect this to happen any time soon...)
