### ISSUE TITLE
登入了作者的百度账户

### ISSUE THREAD

**Issue by hotea** [houtianze/bypy#290]
直接bypy info回车，生成地址打开浏览器复制token时，显示的是 “系命的xxx”这个帐号，应该是作者的 :), 网盘使用量2g多，应该是作者把自己的百度帐号奉献出来了，在此确认一下。
复制token前切换成自己的帐号，设置才对

**Comment by houtianze** [comment]
感谢反馈。

那个“系命的xxx”是浏览器当前登录用户的账号 😄 用哪个账户授权，程序就会读取哪个账户的信息。
