### ISSUE TITLE
可以并发吗

### ISSUE THREAD

**Issue by ghostry** [houtianze/bypy#293]
我做网页的用百度盘备份项目，小文件特别多，大概有30万小文件。
用bypy上传看着是每秒一个文件，估算得3天-4天才能传完。
如果打包的话最少需要有双倍磁盘空间，而实际上磁盘没那么多，只能直接传。

**Comment by Ning-Ning** [comment]
Screen? 我是开了很多screen upload 文件的。

**Comment by houtianze** [comment]
感谢反馈和回答。

并行/多线程需要比较大的工作量，目前看可能很久都不会加入。
像 @Ning-Ning 说的： screen / tmux 也许可以凑合一下。
或者你分段/分目录打包再上传？小文件多传起来是很费时间。

**Comment by houtianze** [comment]
Tracked under #128
