### ISSUE TITLE
Cloud download not support torrent/magnet.

### ISSUE THREAD

**Issue by metalbrick** [houtianze/bypy#295]
It seems not implement some resolve mechanism, and keeps getting the error & retry info.

``` shell
<E> [10:21:02] Waiting 10 seconds before retrying...
<E> [10:21:12] Request Try #2 / 5
<E> [10:21:12] Waiting 20 seconds before retrying...
```

**Comment by houtianze** [comment]
Thanks for feeding back.

I think Baidu recently changed something and broke the `cloude_dl` API (  http://developer.baidu.com/wiki/index.php?title=docs/pcs/rest/file_data_apis_list#.E6.B7.BB.E5.8A.A0.E7.A6.BB.E7.BA.BF.E4.B8.8B.E8.BD.BD.E4.BB.BB.E5.8A.A1 ). It used to work, but now my tests also failed at these APIs. (I think it returns HTTP 502 now).

If possible, can you please add some log here `bypy -dv ...` ? Thanks.

**Comment by cron410** [comment]
Was this ever fixed?

**Comment by houtianze** [comment]
@cron410 I have no idea. As I said, it used to work, but then apparently Baidu broke the API and I probably never worked ever since.
