### ISSUE TITLE
上传好慢，几兆的东西也上传不上去

### ISSUE THREAD

**Issue by raycraft** [houtianze/bypy#296]
上传好慢，几兆的东西也上传不上去，是否其他人也这样？

**Comment by starzou** [comment]
[============________] 60% (320.0MB/532.5MB) ETA: 2h52m (21kB/s, 1h5m gone)

同上，我还以为是某台VPS的问题，于是试了3台都是这样

**Comment by bt7-vip** [comment]
我的也是，上传被卡在150kb以下，时间点正好在百度云改版后，不知道是不是百度作的限制，本地没有linux，无法测试本地bypy上传接口是被限速还是国际宽待问题。

**Comment by ketop** [comment]
开始的时候一直连不上，于是我用网页上的百度云上传，上传之后又连上了

**Comment by houtianze** [comment]
感谢反馈。

这个应该只能靠百度那边解决，`bypy`里也做不了什么能改进。

**Comment by bt7-vip** [comment]
目前已知的:百度方面在服务器端限速，同时限制线程，即使在windows下，多线程依然无法保证高速，bypy所用的接口，在这次改版时，已经在速度上做了限制。同时有消息传出，百度方面在做黑名单，名单账号下载锁在100k以下。有人反应普通账号每日限制流量，超出额定以后，限制速度。消息部分来源网络，本人只做复述！
