### ISSUE TITLE
超过20M的大文件上传无法正确建立文件夹

### ISSUE THREAD

**Issue by mengskysama** [houtianze/bypy#297]
可能是API发生了改动，之前是可以的

root@fr-online:/home/bt/xxx# bypy upload 14.mp4 lll/14.mp4 -vvv
Loading Hash Cache File '/root/.bypy/bypy.hashcache.json'...
/root/.bypy/bypy.hashcache.json
Hash Cache File loaded.
/root/.bypy/bypy.json
<E> [02:11:15] Error accessing 'https://pcs.baidu.com/rest/2.0/pcs/file'
<E> [02:11:15] Function: __get_file_info_act
<E> [02:11:15] Website parameters: {u'path': u'/apps/bypy/lll/14.mp4', u'order': u'asc', u'method': u'list', u'by': u'name'}
<E> [02:11:15] Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=21.60bb80e3ec32506d3cf22dfe70379cf7.2592000.1478786784.1402303208-1572671&path=%2Fapps%2Fbypy%2Flll%2F14&by=name&order=asc&method=list
<E> [02:11:15] HTTP Response Status Code: 404
<E> [02:11:15] Error JSON returned:{u'error_code': 31066, u'error_msg': u'file does not exist', u'request_id': 6681647085414748815}
Error code: 31066
Error Description: file does not exist
<E> [02:11:15] Website returned: {"error_code":31066,"error_msg":"file does not exist","request_id":6681647085414748815}

**Comment by houtianze** [comment]
感谢反馈。

这个错误是说`/apps/bypy/lll`这个文件夹在你上传前不存在，所以可以忽略。重点是文件后来是否正确上传并建立目录？
