### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by Ning-Ning** [houtianze/bypy#299]
OS: CentOS 6.6
升级Python 2.7.12
升级pip 8.1.2
我记得原先明明可以用的，不知为何：
`<E> [04:58:59] Exception occurred:`
`Exception:`
`<type 'exceptions.ValueError'> - No JSON object could be decoded`
`Stack:`
`File "/usr/bin/bypy.py", line 4469, in <module>`
`main()`
`File "/usr/bin/bypy.py", line 4462, in main`
`perr("Exception occurred:\n{}".format(formatex(ex)))`
`File "/usr/bin/bypy.py", line 494, in formatex`
`type(ex), ex, ''.join(traceback.format_stack()))`

**Comment by Ning-Ning** [comment]
CentOS 6下Python2.7+的安装老出问题，心累。已准备升级CentOS 7。
谢谢作者。

**Comment by Ning-Ning** [comment]
对于此问题，出现的前因应该为：磁盘空间不足，导致的下载上传有误。
解决方法：删除.bypy/bypy.json 与 .bypy/bypy.parts.json
我刚才还重新pip install bypy, 应该是无需重装的.

**Comment by houtianze** [comment]
感谢反馈和解释。

这个错误看起来有点奇怪。最近刚重构了代码，`pip install -U bypy`不知道会有所帮助。
