### ISSUE TITLE
bypy upload not working with file name begin with -

### ISSUE THREAD

**Issue by miaomi** [houtianze/bypy#301]
The error message: ` error: argument -` and one char after -

bypy.py v1.2.22

**Comment by houtianze** [comment]
Thanks for feeding back.

Can you please give more info (command run, file names and full / relative log)?

**Comment by miaomi** [comment]
Sorry, I don't have the original environment available.
It seems the two command below all return the same error as I can remember:

`bypy upload "-somefile.txt"`
`bypy upload -somefile.txt`

"error: argument -s"

**Comment by houtianze** [comment]
I think it's due to how shell parses the command line arguments. To pass a file argument with a leading dash, you can use [this double dash trick](http://unix.stackexchange.com/questions/11376/what-does-double-dash-mean-also-known-as-bare-double-dash):
`bypy upload -- -somefile.txt`
