### ISSUE TITLE
无法下载稍稍大一点的文件.(例如 10 兆左右), 但是小文件可以

### ISSUE THREAD

**Issue by zw963** [houtianze/bypy#302]
请看示例:

```sh
bypy -d -v downfile /bcompare-4.1.8.21575.x86_64.rpm
Loading Hash Cache File '/home/zw963/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
----
Verbose level = 2
Debug level = 1
Config directory: '/home/zw963/.bypy'
Token file: '/home/zw963/.bypy/bypy.json'
Hash Cache file: '/home/zw963/.bypy/bypy.hashcache.json'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
sys.stderr.encoding = UTF-8
----

<D> Token loaded:
<D> {u'access_token': u'21.ed3688b4f81de6d095f8466f4221752e.2592000.1481046255.973343409-1572671', u'expires_in': 2592000, u'session_secret': u'f1e7e4d9299c62bb5d9601783c3ad2a8', u'scope': u'basic netdisk', u'session_key': u'9mnRIVaoeZPMOXpF7miYiIhe+jg40yyjMPTsiZDDZOZ2/DPQleGHRce/+bksly6icmIZoKdbXPcmKGkYkpFjlF4WOPNmwRlA', u'refresh_token': u'22.38cb129303497bcf685b1c17ed5adc58.315360000.1793814255.973343409-1572671'}
<D> Downloading '/apps/bypy/bcompare-4.1.8.21575.x86_64.rpm' as 'bcompare-4.1.8.21575.x86_64.rpm'
<D> Getting info of remote file '/apps/bypy/bcompare-4.1.8.21575.x86_64.rpm' for later verification
<D> __get_file_info(): rdir : /apps/bypy | rfile: bcompare-4.1.8.21575.x86_64.rpm
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/bcompare-4.1.8.21575.x86_64.rpm
<D> Params: {u'path': u'/apps/bypy', u'order': u'asc', u'method': u'list', u'by': u'name'}
<D> Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=21.ed3688b4f81de6d095f8466f4221752e.2592000.1481046255.973343409-1572671&path=%2Fapps%2Fbypy&by=name&order=asc&method=list
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> List json: {u'list': [{u'isdir': 1, u'ctime': 1478454374, u'fs_id': 156664359798380, u'mtime': 1478454374, u'path': u'/apps/bypy/bin', u'md5': u'', u'size': 0}, {u'isdir': 1, u'ctime': 1478455117, u'fs_id': 248518033264672, u'mtime': 1478455117, u'path': u'/apps/bypy/postgresql-9.6.0', u'md5': u'', u'size': 0}, {u'isdir': 1, u'ctime': 1478454385, u'fs_id': 317764738354148, u'mtime': 1478454385, u'path': u'/apps/bypy/site-packages', u'md5': u'', u'size': 0}, {u'isdir': 0, u'ctime': 1478454382, u'fs_id': 371666825729404, u'mtime': 1478454382, u'path': u'/apps/bypy/.bypy.~undo-tree~', u'md5': u'6ad28b8bcb872d28fd2d0391cff5ac98', u'size': 24711}, {u'isdir': 0, u'ctime': 1478456291, u'fs_id': 568959417422473, u'mtime': 1478456291, u'path': u'/apps/bypy/bcompare-4.1.8.21575.x86_64.rpm', u'md5': u'3aa7811709fc6ace1baaec8c0f7e3a24', u'size': 13341865}, {u'isdir': 0, u'ctime': 1478454511, u'fs_id': 15299963050585, u'mtime': 1478454511, u'path': u'/apps/bypy/bypy', u'md5': u'bc186cf7df69fc5cfb0b34f71c602727', u'size': 190}, {u'isdir': 0, u'ctime': 1478454383, u'fs_id': 456862886554943, u'mtime': 1478454383, u'path': u'/apps/bypy/bypy.bat', u'md5': u'22223023af6d78a10b99eda63cb48062', u'size': 144}, {u'isdir': 0, u'ctime': 1478454509, u'fs_id': 861597124597174, u'mtime': 1478454509, u'path': u'/apps/bypy/bypy.cacerts.pem', u'md5': u'960dc34cf2f961cfbce7e4df9265cd70', u'size': 312971}, {u'isdir': 0, u'ctime': 1478454514, u'fs_id': 243204813445523, u'mtime': 1478454514, u'path': u'/apps/bypy/bypy.py', u'md5': u'8d1b4de1dae8e80a1b7bc7440c2da4d9', u'size': 149374}, {u'isdir': 0, u'ctime': 1478454513, u'fs_id': 932688053148875, u'mtime': 1478454513, u'path': u'/apps/bypy/bypy.pyc', u'md5': u'e51fb738975d31c5af6329e9be086df3', u'size': 144671}, {u'isdir': 0, u'ctime': 1478454381, u'fs_id': 1089077939853759, u'mtime': 1478454381, u'path': u'/apps/bypy/bypygui.pyw', u'md5': u'b9ee6db7b8f74a890a21733eef6b0ab0', u'size': 15516}, {u'isdir': 0, u'ctime': 1478454378, u'fs_id': 520772401846996, u'mtime': 1478454378, u'path': u'/apps/bypy/CONTRIBUTING.md', u'md5': u'f5e8a568937039e5853613ff0fe296ee', u'size': 683}, {u'isdir': 0, u'ctime': 1478454384, u'fs_id': 106467779677429, u'mtime': 1478454384, u'path': u'/apps/bypy/HISTORY.md', u'md5': u'0d641184d30243a76edd8c3a533e2b02', u'size': 1433}, {u'isdir': 0, u'ctime': 1478454380, u'fs_id': 65022210655988, u'mtime': 1478454380, u'path': u'/apps/bypy/LICENSE', u'md5': u'02789781744b75091515ac09a474065e', u'size': 1078}, {u'isdir': 0, u'ctime': 1478454383, u'fs_id': 560194111860046, u'mtime': 1478454383, u'path': u'/apps/bypy/MANIFEST.in', u'md5': u'c363860efd731e1d483e49a6c7bff813', u'size': 77}, {u'isdir': 0, u'ctime': 1478454717, u'fs_id': 740792106220909, u'mtime': 1478454717, u'path': u'/apps/bypy/openSUSE-Leap-42.2-NET-x86_64-Build0109-Media.iso', u'md5': u'09a097c46e5812eb3592847e73b7db06', u'size': 97517568}, {u'isdir': 0, u'ctime': 1478455116, u'fs_id': 694560377603909, u'mtime': 1478455116, u'path': u'/apps/bypy/postgresql-9.6.0.tar.bz2', u'md5': u'c5af6ebb790ab877e1d2e56e19cebb29', u'size': 19157472}, {u'isdir': 0, u'ctime': 1478454515, u'fs_id': 800077796749133, u'mtime': 1478454515, u'path': u'/apps/bypy/README.md', u'md5': u'55015551ebcc0b0207e7374b54a81875', u'size': 6631}, {u'isdir': 0, u'ctime': 1478454381, u'fs_id': 949318776625907, u'mtime': 1478454381, u'path': u'/apps/bypy/release.sh', u'md5': u'a3e3e3acf8fc4143ae236acf452574ff', u'size': 1423}, {u'isdir': 0, u'ctime': 1478454379, u'fs_id': 700262981971582, u'mtime': 1478454379, u'path': u'/apps/bypy/requirements.txt', u'md5': u'85436a582a595ff6ce5bd825d55aa53f', u'size': 29}, {u'isdir': 0, u'ctime': 1478454379, u'fs_id': 794439732226714, u'mtime': 1478454379, u'path': u'/apps/bypy/setup.cfg', u'md5': u'eef8154b211107c711bbb5d97780682e', u'size': 69}, {u'isdir': 0, u'ctime': 1478454512, u'fs_id': 345760650276767, u'mtime': 1478454512, u'path': u'/apps/bypy/setup.py', u'md5': u'66cbdb4a4193a5c6870cec99a98c8675', u'size': 1795}], u'request_id': 7215220027105617955}
<D> File info json: {u'isdir': 0, u'ctime': 1478456291, u'fs_id': 568959417422473, u'mtime': 1478456291, u'path': u'/apps/bypy/bcompare-4.1.8.21575.x86_64.rpm', u'md5': u'3aa7811709fc6ace1baaec8c0f7e3a24', u'size': 13341865}
<D> Request all goes fine
<D> Checking if we already have the copy locally
<D> headers['Range'][6:]: 0-13341864 MC0xMzM0MTg2NA==
<D> GET https://d.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/bcompare-4.1.8.21575.x86_64.rpm', 0, 13341865, 1478456386.479247)
<D> Params: {u'path': u'/apps/bypy/bcompare-4.1.8.21575.x86_64.rpm', u'method': u'download'}

```

下载功能是可用的, 如果下载一个几 kb 的文件, 还是瞬间下载下来的, 但是像这个 10 多兆的, 
直接卡死在 ``<D> Params: {u'path': u'/apps/bypy/bcompare-4.1.8.21575.x86_64.rpm', u'method': u'download'}`` 这里没反映了, 好像根本没有工作.

**Comment by zw963** [comment]
这是加了  -ddd 的输出信息.

NFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): d.pcs.baidu.com
send: 'GET /rest/2.0/pcs/file?access_token=21.ed3688b4f81de6d095f8466f4221752e.2592000.1481046255.973343409-1572671&path=%2Fapps%2Fbypy%2Fbcompare-4.1.8.21575.x86_64.rpm&method=download HTTP/1.1\r\nHost: d.pcs.baidu.com\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: netdisk;5.2.7.2;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia\r\nRange: bytes=0-13341864\r\n\r\n'
reply: 'HTTP/1.1 302 Moved Temporarily\r\n'
header: Date: Sun, 06 Nov 2016 18:25:36 GMT
header: Content-Type: text/html
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: x-bs-client-ip: MTgzLjE5My4xODIuMTcw
header: x-bs-request-id: MTAuNTIuMzMuNTE6ODY0Mjo3MjE1MzEzMjg4MDM0OTExNDA3OjIwMTYtMTEtMDcgMDI6MjU6MzY=
header: x-pcs-member: 0
header: location: http://shcm09.baidupcs.com/file/3aa7811709fc6ace1baaec8c0f7e3a24?bkt=p3-00006fbc4e9b3cc287c864f0125a175a7269&fid=973343409-1572671-568959417422473&time=1478456736&sign=FDTAXGERBH-DCb740ccc5511e5e8fedcff06b081203-8lhn6iXkfchBdSweJiHGSQ9UmgQ%3D&to=sh09vb&fm=Yan,B,M,mn&sta_dx=13341865&sta_cs=3&sta_ft=rpm&sta_ct=0&sta_mt=0&fm2=Yangquan,B,M,mn&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=00006fbc4e9b3cc287c864f0125a175a7269&expires=8h&rt=pr&r=198284165&mlogid=7215313288034911407&vuk=-&vbdid=-&fin=bcompare-4.1.8.21575.x86_64.rpm&slt=pm&uta=3&rtype=1&iv=0&isw=0&dp-logid=7215313288034911407&dp-callid=0.1.1&csl=0&csign=TEXbDriRnvOMXarAK5QemFHKJf8%3D
header: x-poms-key: 00006fbc4e9b3cc287c864f0125a175a7269
header: Server: POMS/CloudUI 1.0
DEBUG:requests.packages.urllib3.connectionpool:"GET /rest/2.0/pcs/file?access_token=21.ed3688b4f81de6d095f8466f4221752e.2592000.1481046255.973343409-1572671&path=%2Fapps%2Fbypy%2Fbcompare-4.1.8.21575.x86_64.rpm&method=download HTTP/1.1" 302 None
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): shcm09.baidupcs.com
send: 'GET /file/3aa7811709fc6ace1baaec8c0f7e3a24?bkt=p3-00006fbc4e9b3cc287c864f0125a175a7269&fid=973343409-1572671-568959417422473&time=1478456736&sign=FDTAXGERBH-DCb740ccc5511e5e8fedcff06b081203-8lhn6iXkfchBdSweJiHGSQ9UmgQ%3D&to=sh09vb&fm=Yan,B,M,mn&sta_dx=13341865&sta_cs=3&sta_ft=rpm&sta_ct=0&sta_mt=0&fm2=Yangquan,B,M,mn&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=00006fbc4e9b3cc287c864f0125a175a7269&expires=8h&rt=pr&r=198284165&mlogid=7215313288034911407&vuk=-&vbdid=-&fin=bcompare-4.1.8.21575.x86_64.rpm&slt=pm&uta=3&rtype=1&iv=0&isw=0&dp-logid=7215313288034911407&dp-callid=0.1.1&csl=0&csign=TEXbDriRnvOMXarAK5QemFHKJf8%3D HTTP/1.1\r\nHost: shcm09.baidupcs.com\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: netdisk;5.2.7.2;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia\r\nRange: bytes=0-13341864\r\n\r\n'
reply: 'HTTP/1.1 206 Partial Content\r\n'
header: Date: Sun, 06 Nov 2016 18:25:37 GMT
header: Content-Type: application/octet-stream
header: Connection: keep-alive
header: x-bs-file-size: 13341865
header: Content-Length: 13341865
header: x-bs-meta-crc32: 782004203
header: Cache-Control: max-age=259200
header: ETag: 3aa7811709fc6ace1baaec8c0f7e3a24
header: x-bs-client-ip: MTgzLjE5My4xODIuMTcw
header: Content-Range: bytes 0-13341864/13341865
header: x-bs-request-id: MTAuMjAxLjY2LjM3Ojg2NjA6NzIxNTMxMzI4ODAzNDkxMTQwNzoyMDE2LTExLTA3IDAyOjI1OjM2
header: Content-Disposition: attachment;filename="bcompare-4.1.8.21575.x86_64.rpm"
header: Content-MD5: 3aa7811709fc6ace1baaec8c0f7e3a24
header: superfile: 2
header: Accept-Ranges: bytes
header: Last-Modified: Mon, 29 Aug 2016 14:53:47 GMT
header: Server: POMS/CloudUI 1.0
DEBUG:requests.packages.urllib3.connectionpool:"GET /file/3aa7811709fc6ace1baaec8c0f7e3a24?bkt=p3-00006fbc4e9b3cc287c864f0125a175a7269&fid=973343409-1572671-568959417422473&time=1478456736&sign=FDTAXGERBH-DCb740ccc5511e5e8fedcff06b081203-8lhn6iXkfchBdSweJiHGSQ9UmgQ%3D&to=sh09vb&fm=Yan,B,M,mn&sta_dx=13341865&sta_cs=3&sta_ft=rpm&sta_ct=0&sta_mt=0&fm2=Yangquan,B,M,mn&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=00006fbc4e9b3cc287c864f0125a175a7269&expires=8h&rt=pr&r=198284165&mlogid=7215313288034911407&vuk=-&vbdid=-&fin=bcompare-4.1.8.21575.x86_64.rpm&slt=pm&uta=3&rtype=1&iv=0&isw=0&dp-logid=7215313288034911407&dp-callid=0.1.1&csl=0&csign=TEXbDriRnvOMXarAK5QemFHKJf8%3D HTTP/1.1" 206 13341865

**Comment by zw963** [comment]
顺便问一句, 我刚岗为了试这个, 专门开通了超级百度会员, 对于这个下载, 是否会有加速?

谢谢

**Comment by zw963** [comment]
添加了 `--downloader aria2` 参数, 貌似开始工作了, 但是速度真心慢, 超级会员根本没有起作用啊.

而且, 速度也远远没有另一个有名的项目, BaiduExplorer 速度快,

请问, 有何策略让我的会员加速起作用? 我专门为此申请开通的,  谢谢.

**Comment by zw963** [comment]
12 兆的文件, 平均下载速度  31KiB/s, 还是半夜的时候, 我真的呵呵了.

请问超级会员有何解决办法?

**Comment by zw963** [comment]
在公司速度貌似还可以.

**Comment by Beenking** [comment]
我也想知道开通百度网盘会员是否会加速？

**Comment by alswl** [comment]
@zw963 能告诉你公司什么网络，能达到多少速度么？

结论上面，你认为会员/超级会员有帮助么？

**Comment by zw963** [comment]
不确定啊, 应该没有帮助吧.
