### ISSUE TITLE
Program authorization FAILED.

### ISSUE THREAD

**Issue by xingshaocheng** [houtianze/bypy#303]
运行命令之后有如下提示，请问怎么解决？谢谢

<E> [21:17:00] Maximum number (5) of tries failed.
Heroku server failed. Last resort: authorizing/refreshing with the GAE server ...
<E> [21:18:01] Maximum number (1) of tries failed.
<E> [21:18:01] Fatal: All server authorizations failed.
<I> [21:18:01] ----------------------------------------------------------------
<I> [21:18:01] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.
<E> [21:18:01] Program authorization FAILED.
You need to authorize this program before using any PCS functions.
Quitting...

**Comment by houtianze** [comment]
已知问题。

`pip install bypy`
`bypy -c`后重新授权。

**Comment by zinking** [comment]
works perfectly. awesome.
