### ISSUE TITLE
我想在笔记本上面跑，怎么跑步起来呀。（我是一小白，求科普，系统是Ubuntu16.04）

### ISSUE THREAD

**Issue by miss13** [houtianze/bypy#307]
希望大神告诉我该怎么在笔记本上面跑这个程序，谢谢！

**Comment by miss13** [comment]
nobaby

**Comment by Ning-Ning** [comment]
apt-get update
apt-get -y install python-pip
pip install requests
pip2 install -U requests
pip install bypy
bypy.py list
授权完成后
bypy.py upload -v

**Comment by miss13** [comment]
谢谢

在 2016年12月08日 22:34, Ning-Ning 写道:

apt-get update
apt-get -y install python-pip
pip install requests
pip2 install -U requests
pip install bypy
bypy.py list
授权完成后
bypy.py upload -v
