### ISSUE TITLE
HISTORY.rst不见了

### ISSUE THREAD

**Issue by petronny** [houtianze/bypy#310]
但是[setup.py](https://github.com/houtianze/bypy/blob/master/setup.py#L41)中仍有提及

**Comment by houtianze** [comment]
感谢反馈。

本来想着因为`HISTORY.rst`是由`HISTORY.md`生成的，就没有加进git（pypi包里面是有的）。但是再想想这样会给直接想`git clone`来弄代码的带来不便，所以还是加回来比较好。
