### ISSUE TITLE
用bypy syncdown之后再用bypy compare老是说有文件不同

### ISSUE THREAD

**Issue by lcgogo** [houtianze/bypy#311]
我把本地文件夹先清空了，然后用bypy syncdown下载，再用bypy compare比较。
结果老是说在一个子文件夹下的文件不同。我只有2个文件，一个在bypy根目录下，一个在pp的子文件夹下。

是我的操作不对么？

lichao@lichao-virtual-machine:~/plain$ ls
lichao@lichao-virtual-machine:~/plain$ bypy compare
==== Same files ===
==== Different files ===
==== Local only ====
==== Remote only ====
D - qq
F - qq/2015-06-27 174553.jpg
F - 2015-06-22 211222.jpg

Statistics:
--------------------------------
Same: 0
Different: 0
Local only: 0
Remote only: 3
lichao@lichao-virtual-machine:~/plain$ bypy syncdown
[====================] 100% (89.8kB/89.8kB) ETA:  (35kB/s, 2s gone) lichao@lichao-virtual-machine:~/plain$
lichao@lichao-virtual-machine:~/plain$ bypy compare
==== Same files ===
D - qq
F - 2015-06-22 211222.jpg
==== Different files ===
F - qq/2015-06-27 174553.jpg
==== Local only ====
==== Remote only ====

Statistics:
--------------------------------
Same: 2
Different: 1
Local only: 0
Remote only: 0
lichao@lichao-virtual-machine:~/plain$ ls qq/2015-06-27\ 174553.jpg
qq/2015-06-27 174553.jpg
lichao@lichao-virtual-machine:~/plain$ ls qq/2015-06-27\ 174553.jpg -l
-rw-rw-r-- 1 lichao lichao 4237137 1月   5 09:38 qq/2015-06-27 174553.jpg
lichao@lichao-virtual-machine:~/plain$

**Comment by houtianze** [comment]
感谢反馈。

`syncdown`没出错？再做多一次`syncdown`再比较呢？

**Comment by lcgogo** [comment]
还是这样，

lichao@lichao-virtual-machine:~$ cd plain/
lichao@lichao-virtual-machine:~/plain$ ls -l
总用量 0
lichao@lichao-virtual-machine:~/plain$ bypy -v syncdown
Loading Hash Cache File '/home/lichao/.bypy/bypy.hashcache.json'...
Hash Cache File '/home/lichao/.bypy/bypy.hashcache.json' not found, no caching
Gathering local directory ...
Done
Gathering remote directory ...
Done
Comparing ...
Done
[====================] 100% (4.0MB/4.0MB) ETA:  (50kB/s, 1m22s gone) 'qq/2015-06-27 174553.jpg' <== '/apps/bypy/qq/2015-06-27 174553.jpg' OK
[====================] 100% (89.8kB/89.8kB) ETA:  (29kB/s, 3s gone) '2015-06-22 211222.jpg' <== '/apps/bypy/2015-06-22 211222.jpg' OK
lichao@lichao-virtual-machine:~/plain$ bypy compare
==== Same files ===
D - qq
F - 2015-06-22 211222.jpg
==== Different files ===
F - qq/2015-06-27 174553.jpg
==== Local only ====
==== Remote only ====

Statistics:
--------------------------------
Same: 2
Different: 1
Local only: 0
Remote only: 0
lichao@lichao-virtual-machine:~/plain$

**Comment by lcgogo** [comment]
我发现和这个文件有关系
2015-06-27 174553.jpg
换个其它文件就没问题。

**Comment by houtianze** [comment]
这个应该是百度的那个第一次上传的文件md5哈希值不准的问题。解决办法就是再上传那个文件一次，再比较就应该一致了。

如果还是不一样，可以贴下`bypy downdir -dv`和`bypy comare -dv`的输出。

**Comment by lcgogo** [comment]
谢了，好了。你的意思是百度在它那端算的md5不准是吗？我这个文件是在百度网盘上从另一个文件夹下面复制到bypy下面的。不知道和这有没关系。

**Comment by houtianze** [comment]
> 谢了，好了。你的意思是百度在它那端算的md5不准是吗？我这个文件是在百度网盘上从另一个文件夹下面复制到bypy下面的。不知道和这有没关系。

之前发现的是：有时候第一次上传的文件，再调用PCS API查询md5值，有时候这个值是错的。临时解决办法就是再上传一次，大多数的时候这个md5值就对了。
