### ISSUE TITLE
我在VPS上把文件压缩为zip包后无法正常上传原因是什么？

### ISSUE THREAD

**Issue by korykim** [houtianze/bypy#313]
HTTP Status Code: 404
Website returned JSON: {u'error_code': 31079, u'error_msg': u'file md5 not found, you should use upload api to upload the whole file.', u'request_id': 106263124664880962}
MD5 not found, rapidupload failed
'Exercise.zip' can't be RapidUploaded, now trying normal uploading.
'Exercise.zip' is being slicing uploaded.
Slice size: 20971520, Pieces: 10
Uploading MD5 slice: 82fce56269ca25354066dbe9b234c45c, #1 / 10
POST https://c.pcs.baidu.com/rest/2.0/pcs/file
actargs: /apps/bypy/Exercise.zip
Params: {u'type': u'tmpfile', u'method': u'upload'}

**Comment by houtianze** [comment]
感谢反馈。

这个不是错误信息，只是提示文件无法”秒传“，改用普通的分片上传。
