### ISSUE TITLE
下载总是红色字体报错

### ISSUE THREAD

**Issue by lvhailong** [houtianze/bypy#314]
root@sfo1-2016823changeip:~/bypy# bypy syncdown --disable-ssl-check -v
Loading Hash Cache File '/root/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
Gathering local directory ...
Done
Gathering remote directory ...
Done
Comparing ...
Done
<E> [01:54:32] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [01:54:32] Function: __downchunks_act
<E> [01:54:32] Website parameters: {u'path': u'/apps/bypy/\u5851\u6599\u738b\u56fd\u5a92\u4f53\u7248-\u738b\u4e45\u826f.mp4', u'method': u'download'}
<E> [01:54:32] Waiting 10 seconds before retrying...
<E> [01:54:42] Request Try #2 / 5

**Comment by houtianze** [comment]
感谢反馈。

这段是在重试，如果最后没有出现#5 / 5的话没有问题。如果还有问题你加下`-dv`参数看有什么输出？

**Comment by lvhailong** [comment]
还是一直重试 到最后失败

**Comment by lvhailong** [comment]
返回如下
`root@sfo1-2016823changeip:~/Downloads# bypy syncdown --disable-ssl-check -dv
Loading Hash Cache File '/root/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
----
Verbose level = 1
Debug level = 1
Config directory: '/root/.bypy'
Token file: '/root/.bypy/bypy.json'
Hash Cache file: '/root/.bypy/bypy.hashcache.json'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
sys.stderr.encoding = UTF-8
----

<D> Token loaded:
<D> {u'access_token': u'21.0af0f9732cd146db4233f0355c47a0d5.2592000.1486363591.1714525435-1572671', u'expires_in': 2592000, u'session_secret': u'0c76136f4ef748ebcda627df0fcc6afc', u'scope': u'basic netdisk', u'session_key': u'9mnRdOoPXo82Fb3MV3ktHJX0viEDySKcmzY/Fwy3Xl0yE3qQJzjpAwA5OO/5OXUq8OzTAmfxMAtkawhRu1pJS2u6aVSjpjXtuA==', u'refresh_token': u'22.4abcbf9ec4500d1a64a5039f234e8eea.315360000.1799131591.1714525435-1572671'}
Gathering local directory ...
<D>
Done
Gathering remote directory ...
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: ([], [])
<D> Params: {u'path': u'/apps/bypy', u'order': u'asc', u'method': u'list', u'by': u'name'}
<E> [03:35:51] Error accessing 'https://pcs.baidu.com/rest/2.0/pcs/file'
<E> [03:35:51] Exception:
<class 'requests.exceptions.ReadTimeout'> - HTTPSConnectionPool(host='pcs.baidu.com', port=443): Read timed out. (read timeout=60.0)
Stack:
  File "/usr/local/bin/bypy", line 9, in <module>
    load_entry_point('bypy==1.3.3', 'console_scripts', 'bypy')()
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 3117, in main
    result = getattr(by, args.command[0])(*uargs)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2344, in syncdown
    same, diff, local, remote = self.__compare(rpath, localdir)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2249, in __compare
    self.__gather_remote_dir(remotedir, skip_remote_only_dirs)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2237, in __gather_remote_dir
    self.__walk_remote_dir(rdir, self.__proceed_remote_gather, rdir, skip_remote_only_dirs)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 1885, in __walk_remote_dir
    return self.__walk_remote_dir_recur(remotepath, proceed, remotepath, args, skip_remote_only_dirs)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 1860, in __walk_remote_dir_recur
    result = self.__get(pcsurl + 'file', pars, self.__walk_remote_dir_act, (dirjs, filejs))
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 663, in __get
    return self.__request(url, pars, act, 'GET', actargs, retry, addtoken, dumpex, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 638, in __request
    result = self.__request_work(url, pars, act, method, actargs, addtoken, dumpex, **kwnew)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 592, in __request_work
    self.__dump_exception(ex, url, pars, r, act)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 407, in __dump_exception
    perr(formatex(ex))
  File "/usr/local/lib/python2.7/dist-packages/bypy/util.py", line 70, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

<E> [03:35:51] Function: __walk_remote_dir_act
<E> [03:35:51] Website parameters: {u'path': u'/apps/bypy', u'order': u'asc', u'method': u'list', u'by': u'name'}
<E> [03:35:51] Waiting 10 seconds before retrying...
<E> [03:36:01] Request Try #2 / 5
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: ([], [])
<D> Params: {u'path': u'/apps/bypy', u'order': u'asc', u'method': u'list', u'by': u'name'}
<D> Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=21.0af0f9732cd146db4233f0355c47a0d5.2592000.1486363591.1714525435-1572671&path=%2Fapps%2Fbypy&by=name&order=asc&method=list
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> Request all goes fine
<D> Remote dirs: []
<D> Remote files: [{u'isdir': 0, u'ctime': 1447078558, u'fs_id': 211154771292524, u'mtime': 1475299505, u'path': u'/apps/bypy/2-2 \u5361\u8d1e\u5fb7Dog Days Are Over.mov', u'md5': u'0881144d590704d32c61730c2057a4c3', u'size': 516256432}, {u'isdir': 0, u'ctime': 1481093717, u'fs_id': 244516221628889, u'mtime': 1483770650, u'path': u'/apps/bypy/\u5851\u6599\u738b\u56fd\u5a92\u4f53\u7248-\u738b\u4e45\u826f.mp4', u'md5': u'61e7a875c141cd2efcb4cb7abe5c86bd', u'size': 2676446707}]
<D> ---- Remote Dir Contents ---
<D> F - /塑料王国媒体版-王久良.mp4 - size: 2676446707 - md5: 61e7a875c141cd2efcb4cb7abe5c86bd
F - /2-2 卡贞德Dog Days Are Over.mov - size: 516256432 - md5: 0881144d590704d32c61730c2057a4c3

Done
Comparing ...
Done
<D> Downloading '/apps/bypy/塑料王国媒体版-王久良.mp4' as '塑料王国媒体版-王久良.mp4'
<D> Getting info of remote file '/apps/bypy/塑料王国媒体版-王久良.mp4' for later verification
<D> __get_file_info(): rdir : /apps/bypy | rfile: 塑料王国媒体版-王久良.mp4
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/塑料王国媒体版-王久良.mp4
<D> Params: {u'path': u'/apps/bypy', u'order': u'asc', u'method': u'list', u'by': u'name'}
<D> Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=21.0af0f9732cd146db4233f0355c47a0d5.2592000.1486363591.1714525435-1572671&path=%2Fapps%2Fbypy&by=name&order=asc&method=list
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> List json: {u'list': [{u'isdir': 0, u'ctime': 1447078558, u'fs_id': 211154771292524, u'mtime': 1475299505, u'path': u'/apps/bypy/2-2 \u5361\u8d1e\u5fb7Dog Days Are Over.mov', u'md5': u'0881144d590704d32c61730c2057a4c3', u'size': 516256432}, {u'isdir': 0, u'ctime': 1481093717, u'fs_id': 244516221628889, u'mtime': 1483770650, u'path': u'/apps/bypy/\u5851\u6599\u738b\u56fd\u5a92\u4f53\u7248-\u738b\u4e45\u826f.mp4', u'md5': u'61e7a875c141cd2efcb4cb7abe5c86bd', u'size': 2676446707}], u'request_id': 155201344334785031}
<D> File info json: {u'isdir': 0, u'ctime': 1481093717, u'fs_id': 244516221628889, u'mtime': 1483770650, u'path': u'/apps/bypy/\u5851\u6599\u738b\u56fd\u5a92\u4f53\u7248-\u738b\u4e45\u826f.mp4', u'md5': u'61e7a875c141cd2efcb4cb7abe5c86bd', u'size': 2676446707}
<D> Request all goes fine
<D> Checking if we already have the copy locally
<D> headers['Range'][6:]: 0-20971519 MC0yMDk3MTUxOQ==
<D> GET https://d.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/\u5851\u6599\u738b\u56fd\u5a92\u4f53\u7248-\u738b\u4e45\u826f.mp4', 0, 2676446707, 1483778171.41886)
<D> Params: {u'path': u'/apps/bypy/\u5851\u6599\u738b\u56fd\u5a92\u4f53\u7248-\u738b\u4e45\u826f.mp4', u'method': u'download'}
<E> [03:37:20] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [03:37:20] Exception:
<class 'requests.exceptions.ReadTimeout'> - HTTPSConnectionPool(host='d.pcs.baidu.com', port=443): Read timed out. (read timeout=60.0)
Stack:
  File "/usr/local/bin/bypy", line 9, in <module>
    load_entry_point('bypy==1.3.3', 'console_scripts', 'bypy')()
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 3117, in main
    result = getattr(by, args.command[0])(*uargs)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2372, in syncdown
    subresult = self.__downfile(rcpath, lcpath)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 1768, in __downfile
    return self.__downchunks(rfile, offset)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 1683, in __downchunks
    self.__downchunks_act, (rfile, offset, rsize, start_time), headers = headers, cookies = self.__cookies)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 663, in __get
    return self.__request(url, pars, act, 'GET', actargs, retry, addtoken, dumpex, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 638, in __request
    result = self.__request_work(url, pars, act, method, actargs, addtoken, dumpex, **kwnew)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 592, in __request_work
    self.__dump_exception(ex, url, pars, r, act)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 407, in __dump_exception
    perr(formatex(ex))
  File "/usr/local/lib/python2.7/dist-packages/bypy/util.py", line 70, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

<E> [03:37:20] Function: __downchunks_act
<E> [03:37:20] Website parameters: {u'path': u'/apps/bypy/\u5851\u6599\u738b\u56fd\u5a92\u4f53\u7248-\u738b\u4e45\u826f.mp4', u'method': u'download'}
<E> [03:37:20] Waiting 10 seconds before retrying...
<E> [03:37:30] Request Try #2 / 5
<D> GET https://d.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/\u5851\u6599\u738b\u56fd\u5a92\u4f53\u7248-\u738b\u4e45\u826f.mp4', 0, 2676446707, 1483778171.41886)
<D> Params: {u'path': u'/apps/bypy/\u5851\u6599\u738b\u56fd\u5a92\u4f53\u7248-\u738b\u4e45\u826f.mp4', u'method': u'download'}
`

**Comment by houtianze** [comment]
这个错误
`<class 'requests.exceptions.ReadTimeout'> - HTTPSConnectionPool(host='d.pcs.baidu.com', port=443): Read timed out. (read timeout=60.0)` 貌似没啥办法了，网络超时。。

**Comment by lvhailong** [comment]
是我网络的问题吗? 我是装在了美国的VPS上运行的

**Comment by houtianze** [comment]
可能有些关系，国内的话估计好些。不过百度pcs也是时不时就出些错误，好在有时候程序重试会解决问题（但有时候也会重试全部失败，只能再运行几遍）。有时候我build test也会卡掉（貌似网络没有返回数据），也有的说是百度对于免费用户有些速度限制。

**Comment by lvhailong** [comment]
我在VPS上用aria2 下载百度网盘 速度基本在200kb/S 但是你这个工具里不是慢的问题是根本连不上 其实我想做的就是用VPS离线下载百度网盘的东西，然后用IPV6高速从VPS拖回本地，这样在校园网可以免流量。

**Comment by houtianze** [comment]
工具也支持调用aria2下载，可以试试。
aria2直接下载链接又不需要做一堆api call，当然出错的几率要小。

**Comment by lvhailong** [comment]
具体怎么调用？有说明文档吗？

**Comment by houtianze** [comment]
`bypy -h`

**Comment by bdus** [comment]
我也是一样的操作 然后发现是ip被墙了
