### ISSUE TITLE
bypy error

### ISSUE THREAD

**Issue by lcgogo** [houtianze/bypy#316]
Hi houtianze,

I met an error after run bypy at the first time.

I install bypy by “pip install bypy”

root@WDMyCloud:/# bypy
<W> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
<W> Encoding for StdOut: ANSI_X3.4-1968
<W> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
<E> [10:19:35] Exception occurred:
Exception:
<type 'exceptions.UnicodeEncodeError'> - 'ascii' codec can't encode characters in position 509-511: ordinal not in range(128)
Stack:
  File "/usr/local/bin/bypy", line 9, in <module>
    load_entry_point('bypy==1.3.3', 'console_scripts', 'bypy')()
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 3131, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/local/lib/python2.7/dist-packages/bypy/util.py", line 70, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Abort
Traceback (most recent call last):
  File "/usr/local/bin/bypy", line 9, in <module>
    load_entry_point('bypy==1.3.3', 'console_scripts', 'bypy')()
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 3084, in main
    parser.print_help()
  File "/usr/lib/python2.7/argparse.py", line 2340, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python2.7/argparse.py", line 2354, in _print_message
    file.write(message)
  File "/usr/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 509-511: ordinal not in range(128)

**Comment by houtianze** [comment]
Hi,

Seems it's due system encoding / locale output. What is your output of the `locale` command?

**Comment by lcgogo** [comment]
root@WDMyCloud:/# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

**Comment by houtianze** [comment]
This should be the cause, `bypy` only runs properly if the locale is set to `utf-8`, you can refer the link in README.md for instructions.
