### ISSUE TITLE
调用syncup时报错了

### ISSUE THREAD

**Issue by cai3178940** [houtianze/bypy#317]
<D> local type: F
<D> '/mnt/myDrive/seafile-data/storage/commits/31aa7baf-7223-4fea-ad99-7e45f4e5d8a6/aa/4274b9b22088a44534b707a16fbe45a24c3b8e' is small and being non-slicing uploaded.
<D> POST https://c.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/seafile-data/storage/commits/31aa7baf-7223-4fea-ad99-7e45f4e5d8a6/aa/4274b9b22088a44534b707a16fbe45a24c3b8e
<D> Params: {u'path': u'/apps/bypy/seafile-data/storage/commits/31aa7baf-7223-4fea-ad99-7e45f4e5d8a6/aa/4274b9b22088a44534b707a16fbe45a24c3b8e', u'ondup': u'overwrite', u'method': u'upload'}
<E> [13:58:52] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [13:58:52] Exception:
<class 'requests.exceptions.SSLError'> - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
Stack:
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 3212, in main
    result = getattr(by, args.command[0])(*uargs)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 2470, in syncup
    subresult = self.__upload_file(lcpath, rcpath)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 1478, in __upload_file
    return self.__upload_one_file(localpath, remotepath, ondup)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 1374, in __upload_one_file
    files = { 'file' : ('file', f) })
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 688, in __post
    return self.__request(url, pars, act, 'POST', actargs, retry, addtoken, dumpex, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 663, in __request
    result = self.__request_work(url, pars, act, method, actargs, addtoken, dumpex, **kwnew)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 617, in __request_work
    self.__dump_exception(ex, url, pars, r, act)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 432, in __dump_exception
    perr(formatex(ex))
  File "/usr/local/lib/python2.7/dist-packages/bypy/util.py", line 70, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

<E> [13:58:52] Function: __upload_one_file_act
<E> [13:58:52] Website parameters: {u'path': u'/apps/bypy/seafile-data/storage/commits/31aa7baf-7223-4fea-ad99-7e45f4e5d8a6/aa/4274b9b22088a44534b707a16fbe45a24c3b8e', u'ondup': u'overwrite', u'method': u'upload'}
<E> [13:58:52] Waiting 10 seconds before retrying...
<E> [13:59:02] Request Try #2 / 5

**Comment by houtianze** [comment]
感谢反馈。

- 这个重试一直出错直到退出？版本是多少？
- 升级`requests`: `pip install -U requests`能解决问题吗？
- 还不行就加`--disable-ssl-check`参数

**Comment by cai3178940** [comment]
@houtianze 谢谢，加上--disable-ssl-check就可以了。
requests是最新版本，requests==2.12.4

**Comment by cai3178940** [comment]
@houtianze bypy==1.3.4

**Comment by houtianze** [comment]
不客气。

有点奇怪，我测试的时候SSL验证是没问题的。所以后来把SSL验证默认开启了。你的环境下浏览器访问：https://pcs.baidu.com/rest/2.0/pcs/file?method=locateupload 证书没有报错吧？

**Comment by houtianze** [comment]
这个错误是一直有还是间歇性出现？

**Comment by cai3178940** [comment]
本地浏览器和服务器访问https://pcs.baidu.com/rest/2.0/pcs/file?method=locateupload
都没报错，浏览器返回信息：
{"client_ip":"112.225.59.102","server":["c3.pcs.baidu.com","c3.pcs.baidu.com","c3.pcs.baidu.com"],"host":"c.pcs.baidu.com","expire":600,"request_id":202598084380846044}

只要不加--disable-ssl-check ， 这个错误就一直出现

**Comment by houtianze** [comment]
不知道是不是真的证书不一样，能帮忙贴下这个命令的输出吗？
`openssl s_client -showcerts -connect c.pcs.baidu.com:443 </dev/null 2>/dev/null | openssl x509 -outform pem`

我这里的输出：

```
-----BEGIN CERTIFICATE-----
MIIGMjCCBRqgAwIBAgIQHGc+BzkAQXyHzC5WEBMbkjANBgkqhkiG9w0BAQsFADB+
MQswCQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAd
BgNVBAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxLzAtBgNVBAMTJlN5bWFudGVj
IENsYXNzIDMgU2VjdXJlIFNlcnZlciBDQSAtIEc0MB4XDTE2MDYyODAwMDAwMFoX
DTE3MDYyNTIzNTk1OVowga0xCzAJBgNVBAYTAkNOMRAwDgYDVQQIDAdiZWlqaW5n
MRAwDgYDVQQHDAdiZWlqaW5nMTkwNwYDVQQKDDBCZWlKaW5nIEJhaWR1IE5ldGNv
bSBTY2llbmNlIFRlY2hub2xvZ3kgQ28uLCBMdGQxJTAjBgNVBAsMHHNlcnZpY2Ug
b3BlcmF0aW9uIGRlcGFydG1lbnQxGDAWBgNVBAMMDyoucGNzLmJhaWR1LmNvbTCC
ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM/q2XOCimmHz0avAsCdUx9y
7KpDB2hd47fX9NpMp9pxDgc+exlhUOg/wQiNOt7Db0Qq/OHxu7EKCyvv6LMW6dnm
u5U1QHdXCLuY3iVmGakW9WSDOKhNHDjl8+JhC22w6JUmaF7OfZmrLoCCp+ZhabyU
bHNGwwvwk5vwYUUzGnizD6dCv+r0R/s70O0X7dCA4ANE3iRyHl+z3AmPjXW//f+J
WGxA0vidqzt73UliI4uWg5/a768keR3i0LlFogUNxas0ZyWm8/WkkNpJfv4e1Flm
cIt5Jaq32dHtl3nCoVruwxtOUO7zmtnqjL0hpsXKupphnqqmenvpJ+zz+ChzHQkC
AwEAAaOCAnowggJ2MCkGA1UdEQQiMCCCDyoucGNzLmJhaWR1LmNvbYINcGNzLmJh
aWR1LmNvbTAJBgNVHRMEAjAAMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggr
BgEFBQcDAQYIKwYBBQUHAwIwYQYDVR0gBFowWDBWBgZngQwBAgIwTDAjBggrBgEF
BQcCARYXaHR0cHM6Ly9kLnN5bWNiLmNvbS9jcHMwJQYIKwYBBQUHAgIwGQwXaHR0
cHM6Ly9kLnN5bWNiLmNvbS9ycGEwHwYDVR0jBBgwFoAUX2DPYZBV34RDFIpgKrL1
evRDGO8wKwYDVR0fBCQwIjAgoB6gHIYaaHR0cDovL3NzLnN5bWNiLmNvbS9zcy5j
cmwwVwYIKwYBBQUHAQEESzBJMB8GCCsGAQUFBzABhhNodHRwOi8vc3Muc3ltY2Qu
Y29tMCYGCCsGAQUFBzAChhpodHRwOi8vc3Muc3ltY2IuY29tL3NzLmNydDCCAQMG
CisGAQQB1nkCBAIEgfQEgfEA7wB2AN3rHSt6DU+mIIuBrYFocH4ujp0B1VyIjT0R
xM227L7MAAABVZSr310AAAQDAEcwRQIhAMwBsgoYbWvLvD0KrEZlAD9gr9AcSfC9
GQHvdks72lGOAiB8or27X3zXwRqUz9sntuww6hD/NJgA/QANP+DwIqQWQQB1AKS5
CZC0GFgUh7sTosxncAo8NZgE+RvfuON3zQ7IDdwQAAABVZSr35YAAAQDAEYwRAIg
U7BYLJnEuG7ZbZy6yZSTLBLN2WUvTWzPWCyYazQ90nICIF6cdZXnAW4GMJQJ5j0N
fRXX7hz8bS1WxfX/REA3iJkzMA0GCSqGSIb3DQEBCwUAA4IBAQCu6Ptm7wUMra/4
eDo+8t8j8024ek1IvexmtO5Y1zzktd55h9kfoHaStHTn0hAPZBRyxyj5Hxj71JIW
WLJ/eS4mZ16XpGEOPJBQrloSPNXROLHo/mpELYzafGUsSy/7wRN8DbxEE6iwUo/2
Kw2pwwpm3o7e8hV99R6CzhrH4GEGxoQuEQgKMPrv0XM4g67p5cj6bAdGhcoW1oIO
+TnnIbVg7kF0PAb7t3mqjYfMLNaNc4akhn5fm3iPxj6vf/DyhwwPKVdik7ir3pAV
bqj+1AbPDdx+RbacQ/yV0/NS4u22kOegdTiD6v09vRdiS13RHUxAjJ2uWgfcvIe5
GTam/yqP
-----END CERTIFICATE-----
```

**Comment by BohrShaw** [comment]
以上命令的输出我跟你的结果是一样的。
我在`bypy upload`(pip3)的时候也遇到这个问题，但是`bypy rm`则没有错误。

**Comment by BohrShaw** [comment]
刚刚在测试一下`bypy download dir dir`的时候出现了这个Error:

    <E> [15:56:12] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
    <E> [15:56:12] Exception:
    <class 'UnboundLocalError'> - local variable 'current_batch_percent' referenced before assignment
    Stack:
      File "/home/bohr/.local/bin/bypy", line 11, in <module>
        sys.exit(main())
      File "/home/bohr/.local/lib/python3.5/site-packages/bypy/bypy.py", line 3225, in main
        result = getattr(by, args.command[0])(*uargs)
      File "/home/bohr/.local/lib/python3.5/site-packages/bypy/bypy.py", line 1979, in download
        return self.downdir(remotepath, localpath)
      File "/home/bohr/.local/lib/python3.5/site-packages/bypy/bypy.py", line 1967, in downdir
        return self.__downdir(rpath, lpath)
      File "/home/bohr/.local/lib/python3.5/site-packages/bypy/bypy.py", line 1954, in __downdir
        return self.__walk_remote_dir(rpath, self.__proceed_downdir, (rpath, lpath))
      File "/home/bohr/.local/lib/python3.5/site-packages/bypy/bypy.py", line 1911, in __walk_remote_dir
        return self.__walk_remote_dir_recur(remotepath, proceed, remotepath, args, skip_remote_only_dirs)
      File "/home/bohr/.local/lib/python3.5/site-packages/bypy/bypy.py", line 1890, in __walk_remote_dir_recur
        subresult = proceed(remotepath, dirjs, filejs, args)
      File "/home/bohr/.local/lib/python3.5/site-packages/bypy/bypy.py", line 1949, in __proceed_downdir
        self.__downfile(rfile, lfile)
      File "/home/bohr/.local/lib/python3.5/site-packages/bypy/bypy.py", line 1794, in __downfile
        return self.__downchunks(rfile, offset)
      File "/home/bohr/.local/lib/python3.5/site-packages/bypy/bypy.py", line 1704, in __downchunks
        self.__downchunks_act, (rfile, offset, rsize, start_time), headers = headers, cookies = self.__cookies)
      File "/home/bohr/.local/lib/python3.5/site-packages/bypy/bypy.py", line 685, in __get
        return self.__request(url, pars, act, 'GET', actargs, retry, addtoken, dumpex, **kwargs)
      File "/home/bohr/.local/lib/python3.5/site-packages/bypy/bypy.py", line 663, in __request
        result = self.__request_work(url, pars, act, method, actargs, addtoken, dumpex, **kwnew)
      File "/home/bohr/.local/lib/python3.5/site-packages/bypy/bypy.py", line 641, in __request_work
        self.__request_work_die(ex, url, pars, r, act)
      File "/home/bohr/.local/lib/python3.5/site-packages/bypy/bypy.py", line 470, in __request_work_die
        self.__dump_exception(ex, url, pars, r, act)
      File "/home/bohr/.local/lib/python3.5/site-packages/bypy/bypy.py", line 432, in __dump_exception
        perr(formatex(ex))
      File "/home/bohr/.local/lib/python3.5/site-packages/bypy/util.py", line 70, in formatex
        type(ex), ex, ''.join(traceback.format_stack()))

    <E> [15:56:12] Function: __downchunks_act
    <E> [15:56:12] Website parameters: {'method': 'download', 'path': '/apps/bypy/t/a'}
    <E> [15:56:12] Full URL: http://shcm09.baidupcs.com/file/d41d8cd98f00b204e9800998ecf8427e?bkt=p3-1400d41d8cd98f00b204e9800998ecf8427e00000000000000000000&fid=3709908886-
    1572671-380697301733135&time=1484034971&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-b588V%2BMxxklnPBnjxSTPR8tTb%2FI%3D&to=sh09vb&fm=Bei,B,M,mn&sta_dx=21609&sta_cs=
    -998576&sta_ft=a&sta_ct=0&sta_mt=0&fm2=Beijing,B,M,mn&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400d41d8cd98f00b204e9800998ecf8427e00000000000000000000&sl=76480590&expir
    es=8h&rt=pr&r=706322136&mlogid=224135944622136054&vuk=-&vbdid=-&fin=a&slt=pm&uta=0&rtype=1&iv=0&isw=0&dp-logid=224135944622136054&dp-callid=0.1.1&hps=1&csl=80&csign=Sifz
    gOpEehTVCHSIhJGNfccMClU%3D
    <E> [15:56:12] HTTP Response Status Code: 200
    <E> [15:56:12] Fatal Exception, no way to continue.
    Quitting...

**Comment by openpy** [comment]
@cai3178940 请问下载的百度云数据如何同步到seafile中的？是自己写的脚本吗？

**Comment by houtianze** [comment]
@BohrShaw 感谢反馈。可能是ssl版本问题？不过不管了，还是换回disable SSL by default吧，这个问题有点闹心。
第二个问题应该是bug，我看看。

**Comment by houtianze** [comment]
SSL verification disabled by default now.

**Comment by cai3178940** [comment]
@openpy 只是用来定时增量备份，如果本地硬盘坏了就从百度云手动恢复回来

**Comment by openpy** [comment]
@cai3178940 哦哦，seafile官方的mount只能读不能写，想直接讲bypy下载的数据写入seafile中看来没有现成的东西可以用了
