### ISSUE TITLE
最近有一部份的资源有如此的状况！（errorCode=22 状态响应不成功. 状态=403）

### ISSUE THREAD

**Issue by jtliaw** [houtianze/bypy#319]
最近有一部份的资源有如此的状况！才刚开始下载就出现以下讯息，然后就跳去下载另一个文件，甚至重复restart bypy好几次都是如此！

请问这是百度云的服务器问题吗？

[#1013db 0B/0B CN:1 DL:0B]                                                     
01/10 15:28:01 [ERROR] CUID#6 - Download aborted. URI=https://d.pcs.baidu.com/rest/2.0/pcs/file?access_token=21.18242330cf85e43ac2f14d01b0c39031.2592000.1486045051.692306136-1572671&path=%2Fapps%2Fbypy%2F%E9%94%A6%E7%BB%A3%E8%89%AF%E7%BC%98%2F01.mkv&method=download
Exception: [AbstractCommand.cc:350] errorCode=22 URI=http://58.222.46.35/d1.baidupcs.com/file/47c93a9d8605cbeea8e91219e61de28e?bkt=p2-qd-719&xcode=2b770a8139a0c5cc7df0806fc3d7c51607ea74349d04ea5e0b2977702d3e6764&fid=692306136-1572671-203020477469117&time=1484033279&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-QBfCMLU96GbI2CYXw%2FYvTVaS%2Fl4%3D&to=lc&fm=Nan,B,U,ny&sta_dx=461436433&sta_cs=865&sta_ft=mkv&sta_ct=7&sta_mt=0&fm2=Nanjing02,B,U,ny&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=140047c93a9d8605cbeea8e91219e61de28eb1a5abba00001b80f611&sl=76480590&expires=8h&rt=pr&r=394925070&mlogid=223681667826155044&vuk=-&vbdid=-&fin=01.mkv&slt=pm&uta=0&rtype=1&iv=0&isw=0&dp-logid=223681667826155044&dp-callid=0.1.1&hps=1&csl=80&csign=SifzgOpEehTVCHSIhJGNfccMClU%3D&wshc_tag=0&wsts_tag=58748d01&wsid_tag=3c302b60&wsiphost=ipdbm
  -> [HttpSkipResponseCommand.cc:228] errorCode=22 状态响应不成功. 状态=403

01/10 15:28:01 [NOTICE] GID为1013dbfbabc07a92的下载项并未全部完成: /home/user/锦绣良缘/01.mkv

**Comment by houtianze** [comment]
感谢反馈。

依据这个链接： https://github.com/aria2/aria2/issues/502
感觉是百度那面返回错误导致aria2无法继续下载了，做不了什么，除了忍。。。 😓

**Comment by jtliaw** [comment]
感谢通知！

**Comment by jtliaw** [comment]
最近我这里使用bypy下载总是无法下载一直retry，而使用bypy aria2还能下载，但不久就出现（errorCode=22 状态响应不成功. 状态=403）！
不久前我发现了一个油猴脚本，它能显示出百度资源的所有链接，有些链接是可以高速下载有些不能！
不知作者是否要看看！
[https://greasyfork.org/zh-CN/scripts/23635-百度网盘直接下载助手](url)

**Comment by houtianze** [comment]
感谢提供链接。

看了一下，应该是基于浏览器获得的数据做的，比较难借用过来（`bypy`是基于PCS Rest API）。而且也在页面顶端张榜公示说百度开始限制，速度不稳定，看来也要同病相怜。

感觉根源还是在于百度要限制，毕竟地主也要吃饭，免费服务最终还得靠付费用户群撑起来，要不然KPI老板脸色都不会太好看，倒是可以理解。除了忍好像也没啥办法。

**Comment by jtliaw** [comment]
不知道会不会得罪你！先说声：抱歉！
经过测试将DPcsUrl = 'https://d.pcs.baidu.com/rest/2.0/pcs/' 换成：DPcsUrl = 'https://allall01.baidupcs.com/rest/2.0/pcs/'
本来不能下载的资源变成能下载了，而且速度相当不错！

**Comment by houtianze** [comment]
何谈得罪，感谢提供信息 :grinning: 

`d.pcs...`是百度文档提供的。这个`allall01`镜像倒是第一次听说，挖得够深 :grinning: 

有个不用改代码的方法使用镜像：`--mirro allall01.baidupcs.com` （你可以通过 `-dv`来看是否已经使用这个镜像来传输）

**Comment by jtliaw** [comment]
感谢你提供方法！
我的测试：
<D> call: aria2c --user-agent='None' -c -k1M -s8 -x16 -m90 --retry-wait=6  --file-allocation=none -o '來自喵喵星的妳/TVBOXNOW 來自喵喵星的妳 EP07.rmvb1' 'https://allall01.baidupcs.com/rest/2.0/pcs/file?access_token=21.b1223a5bfc510026e09e1e5de9784211.2592000.1486683237.692306136-1572671&path=%2Fapps%2Fbypy%2F%E4%BE%86%E8%87%AA%E5%96%B5%E5%96%B5%E6%98%9F%E7%9A%84%E5%A6%B3%2FTVBOXNOW+%E4%BE%86%E8%87%AA%E5%96%B5%E5%96%B5%E6%98%9F%E7%9A%84%E5%A6%B3+EP07.rmvb1&method=download'

**Comment by jtliaw** [comment]
我家的网速只有1M！

**Comment by houtianze** [comment]
发现你的留言里面没把`access_token`打码，可能屏蔽掉比较好。
