### ISSUE TITLE
Can't work

### ISSUE THREAD

**Issue by kba977** [houtianze/bypy#320]
![](https://ww1.sinaimg.cn/large/006tKfTcjw1fbllzx8syvj31k80h0dsb.jpg)

**Comment by jtliaw** [comment]
（支持Python 2.7+, 3.3+)

**Comment by kba977** [comment]
谢谢 Got it~

**Comment by houtianze** [comment]
感谢帮助解答。我会稍微改进下Python 2.6下这个错误提示的输出。
