### ISSUE TITLE
能否显示上传的进度和剩余时间 以及实时的速度情况?

### ISSUE THREAD

**Issue by GhostChild** [houtianze/bypy#321]
在linux CLI下能获取的信息太少
传输大文件的时候 都不知道什么时候可以传完 以及传输的速度是多少

**Comment by houtianze** [comment]
感谢反馈。

理解，就是我不知道有没有时间做。。

**Comment by GhostChild** [comment]
谢谢你能看到这个issues
其实 能有个linux上的客户端已经很不错了
我现在通过监控网卡获取程序的出入流量来判断上传的进度
总之还是谢谢了

**Comment by houtianze** [comment]
不客气。现在如果加`-d`参数可以看到这句`ploading MD5 slice:`，能知道上传了多少个分片，但是开了`-d`就会有一堆调试信息，那条会淹没其中，不太理想。确实是有个进图条会比较直观。

**Comment by GhostChild** [comment]
受限于PCS的API局限的话 我建议从外部入手
通过监控网卡 统计这个程序本身的出入流量计算上传量 和实时的速度
这样的话 仅仅可以监控全局的数据 但是目前就是单线程的不是吗
我只是表达一下我的想法 因为我就是利用第三方软件来监控数据情况的

**Comment by houtianze** [comment]
倒也不算受限PCS API——上传按块读文件是就可以计算打印进度条，只是没有实现。
对，现在上传下载都是单线程，多线程遥遥无期，而且担心百度会现在，做了也未必有用，也就没什么想做的动力。

另外发现已经有个类似的issue #179 ，关了这个用那个来跟踪了。

**Comment by houtianze** [comment]
看了一下，单个大文件上传如果没有加`-dv`参数，应该是已经有上传进度条了（没传完一个分片更新一次进度条）
