### ISSUE TITLE
如果能做一个网页界面就好了。

### ISSUE THREAD

**Issue by chovan** [houtianze/bypy#322]
类似Duplicati那样的。比纯CLI要User Friendly一些。

另外，能否把同步功能延伸到其他网络存储，比如Onedrive。 没准哪天百度网盘也就关了，鸡蛋不能只放在一个篮子里阿... :)

**Comment by houtianze** [comment]
感谢反馈。

这个不止一个人提过了，主要是没时间。。

**Comment by houtianze** [comment]
用一个issue来跟踪吧。

Tracked under #180

**Comment by chovan** [comment]
回得这么快？！
那下面这个是不是也可以建一个issue来跟踪？：）

能否把同步功能延伸到其他网络存储，比如Onedrive。 没准哪天百度网盘也就关了，鸡蛋不能只放在一个篮子里阿... :)

**Comment by houtianze** [comment]
更新了下我第一个回复 ，那个我很难有时间去做 😄 
睡了，晚安 🌃
