### ISSUE TITLE
加密

### ISSUE THREAD

**Issue by frleong** [houtianze/bypy#325]
请问可否sync up syncdown加入加密，解密的功能？普通的密码也可以啦，放在运终是不太放心！谢谢！

**Comment by houtianze** [comment]
感谢建议。

这个应该不会实现的 😄 。PCS API没有提供加密接口。加密是另外一个任务，交由别的程序来做就好。

具体的加密你是指？
- 传输加密？PCS走的是https，令牌之类的不会被人盗取。但是还是不放心的话，可以考虑VPN，SSH Tunnel等等。
- 文件加密？你可以通过EncFS / EcryptFS / GPG之类先将文件夹加密，再上传加密后的文件夹就好了。（极其敏感的内容，个人不建议上云，多处备份可能会好点）

**Comment by frleong** [comment]
谢谢！我现在测试encfs,效果可以接受！
