### ISSUE TITLE
增加低流量自动timeout和重试

### ISSUE THREAD

**Issue by frleong** [houtianze/bypy#328]
我需要把一些较大的资料上存云储存, bypy很合适, 但有时候, 不知具体原因, 但会无故hang, 好像是连线还在, 但很慢, 可否加入若throughput低于某数值一段长时间(如3份钟)便自动timeout和重试. 可以吗? 谢!

**Comment by houtianze** [comment]
感谢建议。

其实早就有timeout实现在里面的（直接用`requests`的timeout参数），但是hang的时候`requests`也不会timeout（怀疑是百度服务器端设置/问题)。。。而且出现hang的症状时，好像即使重试也是一样的龟速/继续hang。(据报告这种情况下用`aria2`下载也是会出错）

所以暂时好像也没有什么好的解决办法。
