### ISSUE TITLE
默认user-agent为none 

### ISSUE THREAD

**Issue by openpy** [houtianze/bypy#329]
你好，更新后发现user-agent默认为none，之前好像是netdisk。为什么要用none呢？
修改为netdisk会存在其他问题吗？
# TODO: Does the following User-Agent emulation help?
UserAgent = None # According to xslidian, User-Agent affects download.
#UserAgent = 'Mozilla/5.0'
#UserAgent = "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)"
#UserAgent = 'netdisk;5.2.7.2;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia'

**Comment by houtianze** [comment]
你好。

之前改过几次User-Agent，据说可能会对提升速度有所帮助，但一切都是黑盒，没法验证。后来觉得既然没法证明改这个有任何帮助，改回'None'会比较安全。

如果对速度有帮助，我觉得改回netdisk不会有问题吧？只是不知道百度端如何处理这个，所以谁也没法给确定答案，但我觉得改个User-Agent出现问题的可能性不是很大。
