### ISSUE TITLE
多账号自动下载大文件解决方案咨询

### ISSUE THREAD

**Issue by Beenking** [houtianze/bypy#331]
hello, 首先非常感谢 @houtianze 提供这么好的项目，而且还尽心尽责的维护着，是我等学习的榜样。
   我的需求是这样的，公司有20个普通百度网盘账号，1个VIP网盘账号，20个普通网盘每天不固定时间上传几个压缩的ZIP文件，大小1G左右，超级VIP账号负责收集所以上传的压缩文件然后加速下载。
       现在的做法是传统的方法手动登录每个账号，如果上传成功则分享给VIP账号，然后用VIP账号手动下载，可想而知，工作非常重复繁琐。
       所以，想运用这个项目自动化实现。20个普通账号的上传我这边不需要管理，希望实现的是自动登录每个普通账号，然后查看有没有新的压缩文件上传成功，如果有未下载的新文件就自动用VIP账号下载。
       近日，我看了部分的代码和所有的Issues，基本肯定bypy可以实现该功能，但有几个疑问:
   1. VIP账号是否可以实现加速下载。
   2. 是直接登录20普通网盘分别异步下载比较合理还是集中让VIP一个账号下载更快。
   3. Issues中有比较多的问题是大文件下载失败的案例，latest version是否解决了。
   4. 有没有其他的更加合适的解决方案适合此场景，包括付费的。
提前感谢所有评论以及提供帮助的牛牛们，祝大家春节快乐。

**Comment by houtianze** [comment]
不客气。

1. 不知。。
2. 不知。。
3. 没有仔细测试，但是如果是百多那边有严重限速，这个最新版估计也解决不了，因为根据反馈，貌似`requests`库在这种情况下就hang掉（亦或传输太慢假死？），`aria2`也会报错。
4. 如果，我是说如果付费用户不限速的话，应该一个vip账号上传下载都没问题。但是没人反馈过会员对PCS速度是否有很明显的帮助。

🐔年大吉。
