### ISSUE TITLE
目前crontab的脚本该如何写？

### ISSUE THREAD

**Issue by jtliaw** [houtianze/bypy#333]
系统是：ubuntu 16.04
之前的crontab脚本是：/usr/bin/python /usr/bin/bypy.py syncup /home/user
但是现在bypy并不在/usr/bin内，我指定：/usr/local/lib/python2.7/dist-packages/bypy/bypy.py却不行！
该如何写呢？

**Comment by houtianze** [comment]
下面两种方法应该都可以：
- `python -m bypy syncup /your/dir`
or
- `bypy syncup /your/dir`

（如果不行，用`which python`或`which bypy`找出python或bypy的绝对路径，替换一下应该就可以了。

**Comment by jtliaw** [comment]
感谢您！
