### ISSUE TITLE
search api 查询出来的数据，需要如何获取到变量

### ISSUE THREAD

**Issue by payne-huang** [houtianze/bypy#335]
我采用的import bypy 模式使用的，现在不能获取到search api获取的数据

**Comment by houtianze** [comment]
没太看懂，什么意思？有log贴一下吗？

**Comment by payne-huang** [comment]
红色框的数据，怎么接收
我使用的脚本代码部分截图给你


调用这个方法只能返回一个请求状态，但是没法接收到需要查询出来的数据。


hspml@163.com
 
发件人： Hou Tianze
发送时间： 2017-02-20 14:12
收件人： houtianze/bypy
抄送： payne-huang; Author
主题： Re: [houtianze/bypy] search api 查询出来的数据，需要如何获取到变量 (#335)
没太看懂，什么意思？有log贴一下吗？

**Comment by houtianze** [comment]
没看到截图。。

**Comment by payne-huang** [comment]
[root@centos6 hs]# python testsearch.py 
Found:
F /apps/bypy/test/ScreenShots/b.txt 0 2017-02-19, 15:30:03 2017-02-19, 15:30:03 d41d8cd98f00b204e9800998ecf8427e
0


Found:
F /apps/bypy/test/ScreenShots/b.txt 0 2017-02-19, 15:30:03 2017-02-19, 15:30:03 d41d8cd98f00b204e9800998ecf8427e    这个数据是查询出来的现在我变量接收不到，

我的测试脚本

import bypy

client = bypy.ByPy()
print client.search('b.txt', '/')

我现在就是需要这个查找的数据接收








hspml@163.com
 
发件人： Hou Tianze
发送时间： 2017-02-20 15:36
收件人： houtianze/bypy
抄送： payne-huang; Author
主题： Re: [houtianze/bypy] search api 查询出来的数据，需要如何获取到变量 (#335)
没看到截图。。

**Comment by payne-huang** [comment]
谢谢你的代码，我已经修改了下代码，如果需要我可以提交上git

我修改方式：
def print_pcs_list(json, foundmsg = "Found:", notfoundmsg = "Nothing found."):
        list = json['list']
        data = []
        if list:
                pr(foundmsg)
                for f in list:
                        pr("{} {} {} {} {} {}".format(
                                ls_type(f['isdir']),
                                f['path'],
                                f['size'],
                                ls_time(f['ctime']),
                                ls_time(f['mtime']),
                                f['md5']))
                        data.append("{} {} {} {} {} {}".format(
                                ls_type(f['isdir']),
                                f['path'],
                                f['size'],
                                ls_time(f['ctime']),
                                ls_time(f['mtime']),
                                f['md5']))
        else:
                pr(notfoundmsg)
        return data

def __search_act(self, r, args):
                data = print_pcs_list(r.json())  
                return const.ENoError, data

这样就可以在方法返回查询到的数据了。

[root@centos6 bypy]# python /home/hs/testsearch.py 
Found:
F /apps/bypy/test/ScreenShots/b.txt 0 2017-02-19, 15:30:03 2017-02-19, 15:30:03 d41d8cd98f00b204e9800998ecf8427e
(0, [u'F /apps/bypy/test/ScreenShots/b.txt 0 2017-02-19, 15:30:03 2017-02-19, 15:30:03 d41d8cd98f00b204e9800998ecf8427e'])



hspml@163.com
 
发件人： Hou Tianze
发送时间： 2017-02-20 15:36
收件人： houtianze/bypy
抄送： payne-huang; Author
主题： Re: [houtianze/bypy] search api 查询出来的数据，需要如何获取到变量 (#335)
没看到截图。。
―

**Comment by houtianze** [comment]
不客气。

原来的代码只有打印而没有返回数据（没考虑到这个），改`pr`函数也能实现类似的功能（可以参见`bypy/test/test.py`的做法。

**Comment by payne-huang** [comment]
建议在源码版本也做下修改，我抽空看看你的test代码



hspml@163.com
 
发件人： Hou Tianze
发送时间： 2017-02-20 23:44
收件人： houtianze/bypy
抄送： payne-huang; Author
主题： Re: [houtianze/bypy] search api 查询出来的数据，需要如何获取到变量 (#335)
Closed #335.

**Comment by houtianze** [comment]
当初设计函数的时候没有考虑到返回的JSON应该也传递出来，现在改函数签名的话会比较多，所以弄了个勉强能用的解决办法：
如果相关函数会接收PCS JSON，那么久把它丢进`self.jsonq`里面去。现在你调用完这个函数，再去`jsonq`里面去查就可以拿到之前的JSON了。

**Comment by payne-huang** [comment]
谢谢 我后来也发现了，仔细读了代码之后



hspml@163.com
 
发件人： Hou Tianze
发送时间： 2017-03-14 02:07
收件人： houtianze/bypy
抄送： payne-huang; Author
主题： Re: [houtianze/bypy] search api 查询出来的数据，需要如何获取到变量 (#335)
当初设计函数的时候没有考虑到返回的JSON应该也传递出来，现在改函数签名的话会比较多，所以弄了个勉强能用的解决办法：
如果相关函数会接收PCS JSON，那么久把它丢进self.jsonq里面去。现在你调用完这个函数，再去jsonq里面去查就可以拿到之前的JSON了。
