### ISSUE TITLE
syncdown 报证书错误但是不影响下载

### ISSUE THREAD

**Issue by pylemon** [houtianze/bypy#337]
同步的时候会报错 貌似是百度云的api发生了变化. 看看需不需要修复.
```
~$ bypy syncdown -v
<E> [08:53:39] Fail download CA Certs to '/home/user/.bypy/bypy.cacerts.pem'.
Exception:
<class 'urllib2.HTTPError'> - HTTP Error 404: Not Found
Stack:
  File "/usr/local/bin/bypy.py", line 4469, in <module>
    main()
  File "/usr/local/bin/bypy.py", line 4441, in main
    verbose = args.verbose, debug = args.debug)
  File "/usr/local/bin/bypy.py", line 1432, in __init__
    self.getcertfile()
  File "/usr/local/bin/bypy.py", line 1362, in getcertfile
    self.__certspath, formatex(ex)))
  File "/usr/local/bin/bypy.py", line 494, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Loading Hash Cache File '/home/user/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
Gathering local directory ...
Done
Gathering remote directory ...
<E> [08:53:39] Error accessing 'https://pcs.baidu.com/rest/2.0/pcs/file'
<E> [08:53:39] Function: __walk_remote_dir_act
<E> [08:53:39] Website parameters: {u'path': u'/apps/bypy/deletelocal', u'order': u'asc', u'method': u'list', u'by': u'name'}
<E> [08:53:39] Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=21.fe3a32f44abad755cc5079c7e3114c23.2592000.1490335218.2449883021-1572671&path=%2Fapps%2Fbypy%2Fdeletelocal&method=list&by=name&order=asc
<E> [08:53:39] HTTP Response Status Code: 404
<E> [08:53:39] Error JSON returned:{u'error_code': 31066, u'error_msg': u'file does not exist', u'request_id': 1469743087208422215}
Error code: 31066
Error Description: file does not exist
<E> [08:53:39] Website returned: {"error_code":31066,"error_msg":"file does not exist","request_id":1469743087208422215}
Done
```

**Comment by pylemon** [comment]
好像是我命令敲错了 抱歉

**Comment by buhuipao** [comment]
def getcertfile(self):
                result = ENoError
                if not os.path.exists(self.__certspath):
                        if os.path.exists(ByPyCertsFileName):
                                result = copyfile(ByPyCertsFileName, self.__certspath)
                        else:
                                try:
                                        # perform a simple download from github
                                        CACertUrl = 'https://raw.githubusercontent.com/houtianze/bypy/master/bypy.cacerts.pem'
                                        resp = ulr.urlopen(CACertUrl)
                                        with io.open(self.__certspath, 'wb') as f:
                                                f.write(resp.read())
                                except IOError as ex:
                                        perr("Fail download CA Certs to '{}'.\n{}".format(self.__certspath, formatex(ex)))

                                        result = EDownloadCerts


这个文件在他的github下载不到了，所以报错了，我直接pass了这个error

**Comment by houtianze** [comment]
哦，这是旧版的代码，升级到最新版，已经不需要再下载这个pem文件了。
