### ISSUE TITLE
不需要中文支持，是否还是需要修改系统locale设置

### ISSUE THREAD

**Issue by zinking** [houtianze/bypy#339]
中文和英文翻译内容也并不同步：
中文部分说：如果需要中文支持，则需要修改系统locale
英文部分说：系统locale是必选的
在远程机器上进行同步的时候并不需要支持中文，因此是不是有某一选项不需要中文支持？

目前错误：
<E> [18:00:23] Exception occurred:
Exception:
<type 'exceptions.UnicodeEncodeError'> - 'ascii' codec can't encode characters in position 612-614: ordinal not in range(128)
Stack:
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 3282, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/local/lib/python2.7/dist-packages/bypy/util.py", line 70, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

**Comment by houtianze** [comment]
如果上传/下载文件夹都是ASCII字符，应该是可以工作的（没有实测）。出现这个错误，你的目录或文件应该是有非ASCII字符吧？

**Comment by zinking** [comment]
然而并没有， 都还没有到sync那一步。 anyway你都关掉了

**Comment by houtianze** [comment]
如果确定没有ASCII字符，贴下这几个命令的输出吧：
- `hostname`
- `locale`
- 你用的是`syncup`吧？在上传目录下`tree`的完整输出
- `bypy`命令加上`-dv`参数的完整命令
- 命令的完整输出
