### ISSUE TITLE
rapidupload问题

### ISSUE THREAD

**Issue by lsy323** [houtianze/bypy#341]
hi, houtianze and everyone
    我之前使用bypy非常顺利，从vps上上传文件到云盘，然后通过百度云盘下载速度也很快。但是最近用bypy upload一个3G的文件，就默认rapidupload了，查了一下是秒传，然后我再百度云下载速度就特别特别慢，我猜测和rapidupload有关，请问有办法强制使用传统的上传吗？而不是使用rapidload
thx

**Comment by houtianze** [comment]
这个其实和秒传没有关系的 :smile:  ，能秒传成功的文件就在百度PCS服务器上了。下载慢就真的是下载慢的问题。

作为测试，你可以下载一个其他的大文件，应该速度也是一样的。如果非要不用秒传，你可以用hex editor随便改你那个文件几个字节（建议文件改名以免弄混），再上传，就不会秒传了。上传完了你可以再试试下载速度是不是一样慢。

**Comment by lsy323** [comment]
买了会员，我想多了...非常感谢tianze

**Comment by houtianze** [comment]
不客气。
买了会员bypy下载会加快吗？还是百度官方客户端才会提速？
