### ISSUE TITLE
在美国的vps上用，输出一些信息后就没然后了,等了挺长时间也是一样，也没啥提示

### ISSUE THREAD

**Issue by cnrting** [houtianze/bypy#343]
命令：bypy -vv --select-fastest-mirror downfile example.ts example1.ts
输出信息：
/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Selecting fastest mirror
List of PCS mirrors:
{'list': [{'host': 'www.baidupcs.com', 'id': 1},
          {'host': 'nj.baidupcs.com', 'id': 2},
          {'host': 'bj.baidupcs.com', 'id': 4},
          {'host': 'qd.baidupcs.com', 'id': 8}],
 'path': '/monitor.jpg?xcode=1a81b0bbd448fc36f65202d7e8f159404c932f26aaa77f9c&t=1489937611',
 'request_id': 1808613798724373896,
 'rev': 3}

等了挺长时间也是一样，也没啥提示，在本地电信网络试了可以下载，vps ping是个百度服务器大多在270ms左右，nj最差，www最好

**Comment by houtianze** [comment]
感谢反馈。

我本地试了一下最新版（1.4.3），`--select-fastest-mirror`是能用的啊。测试时间有点久（半分钟到一分钟）。你看看你在vps上能连到`https://www.baidupc.com/`不？升级到最新版再试试？
另外，其实我觉得`--select-fastest-mirr`帮助不是很大，上传下载和使用默认服务器地址没觉得有很明显的区别。貌似下载（上传不确定）都是返回跳转到百度选的cdn的。

**Comment by YuSuu** [comment]
同美国vps，peer1线路，开了BBR后能满速

**Comment by cnritng** [comment]
升级到最新版1.5.2后可以正常使用了,但上传一直是467KBPS,是百度云限速了吗?换VIP号也是这个速度,而且很是稳定.

**Comment by houtianze** [comment]
听起来应该是百度限速了吧，可能百度服务器那边并没有检查token是不是vip号。

**Comment by oscar-c** [comment]
请问这个有没有办法写到`bypy.setting.json`里面？我试过加了一行
```
"downloader": "aria2"
```
但是好像没有什么效果
