### ISSUE TITLE
报InsecureRequestWarning但不影响上传

### ISSUE THREAD

**Issue by YuSuu** [houtianze/bypy#345]
/usr/lib/python3.6/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
上传文件时都会出现。
网上搜了下，说certifi包呀什么的，也都装了，
可以怎么解决呢，

**Comment by mountainguan** [comment]
同样的问题

**Comment by houtianze** [comment]
感谢反馈。

这个我这里没有出现，而且程序里已经做了相应处理，应该不会出现才对。怀疑是`urllib3`版本有点旧？`pip2 install -U urllib3`（python 2）/ `pip3 install -U urllib3`（python 3）能解决问题吗？
在这个warning之有”Failed to disable warnings for Urllib3"这样的错误字样吗？
即使这个警告清除不掉，也影响使用，可以忽略.

**Comment by houtianze** [comment]
发现问题所在了，更新到最新版`1.5.4` (`pip install -U bypy`)应该可以解决问题。

**Comment by bitliuxm** [comment]
@houtianze 
same issue with option --processes PROCESS
version 1.5.7

>  pip3 install -U urllib3
Requirement already up-to-date: urllib3 in c:\users\bitliupc\appdata\local\programs\python\python36-32\lib\site-packages

log shows:

  InsecureRequestWarning)                                                                                                                               
c:\users\bitliupc\appdata\local\programs\python\python36-32\lib\site-packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS re
quest is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

**Comment by houtianze** [comment]
@bitliuxm 

I just checked, the problem seems to be Windows-specific again - *nix doesn't this issue.

I guess the reason may be Windows doesn't handle `warning` correctly when running `multiprocess`, so the warnings are not suppressed.

I don't think this can be easily fixed, and as the issue doesn't really affect functions except being a bit annoying, I will leave it as it is.
