### ISSUE TITLE
文件名含有特殊字符上传失败 (Special Characters  in file name)

### ISSUE THREAD

**Issue by Ning-Ning** [houtianze/bypy#346]
文件名中含有特殊字符，比如: 🏆 👍，导致上传失败。
是否可以将特殊字符略去，或用“_”等替代，然后再上传？
对于特殊字符invalid filename的文件，是否可以忽略上传，并生成report？

In some cases, special characters in file name, such as 🏆 👍, cause the upload failed. 
Error: Invalid file name

**Comment by houtianze** [comment]
感谢反馈。

这个问题我考虑过一些，替换的解决方案不是很严谨：如果两个文件名字前面都完全一致，只是最后一个字符一个是🏆 ，一个是👍，这时候替代的解决方法就没法兼顾了（如果还有一个文件前面一致，最后一个支付是替换字符"_"，就更复杂了）。而且还会影响到下载，比较，同步等其他功能。所以最后决定对此不做任何处理，只是报错。用户看到错误之后自行决定如何改名或处理。

I've thought about this before, imagine 3 files: a🏆 .jpg, a👍.jpg a_.jpg all present,, the handling will be quite complicated, and it affect download, compare, sync etc. So I decided to just report the error and let the user deal with it.
