### ISSUE TITLE
最近10天上传速度一直被锁在470kb/s左右

### ISSUE THREAD

**Issue by tobads** [houtianze/bypy#347]
命令:  bypy upload

我大概是在2月10号开始使用bypy，那时候的上传速度基本能稳定2MB/s，时不时还能飙到3MB/s
这10天突然发现被限速了

[====________________] 21% (220.0MB/1023.3MB) ETA: 29m9s (470kB/s, 7m59s gone)
[==================__] 92% (240.0MB/260.8MB) ETA: 45s (468kB/s, 8m45s gone)
[===================_] 95% (820.0MB/861.4MB) ETA: 1m30s (471kB/s, 29m41s gone)
[=================___] 89% (80.0MB/89.4MB) ETA: 20s (473kB/s, 2m53s gone)

在新加坡、美国的VPS上试了，都是被锁在470kb/s，我自己的本机也是被锁470kb/s
已经开通了SVIP，不过依旧被锁，本机用百度云管家倒是能稳定1.1MB/s的上传速度(已经占满了我的上传带宽)
尝试新开VPS，换一个账号进行认证，结果一样被锁470kb/s
不知道是不是百度那边又做了什么限制

**Comment by houtianze** [comment]
感谢反馈。

看描述应该是百度那边做了些限制，貌似只能忍。。。
