### ISSUE TITLE
突然无法使用，重新授权不通过

### ISSUE THREAD

**Issue by dfj3302695** [houtianze/bypy#349]
突然无法使用，重新授权不通过
使用了两种方式都没有办法修复。

Authorizing, please be patient, it may take upto 60.0 seconds...
Authorizing/refreshing with the OpenShift server ...
<E> [06:36:33] Maximum number (1) of tries failed.
OpenShift server failed, authorizing/refreshing with the Heroku server ...
Heroku server failed. Last resort: authorizing/refreshing with the GAE server ...
<E> [06:36:34] Fatal: All server authorizations failed.
<I> [06:36:34] ----------------------------------------------------------------
<I> [06:36:34] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.
<E> [06:36:34] Program authorization FAILED.
You need to authorize this program before using any PCS functions.
Quitting...

**Comment by dfj3302695** [comment]
升到最新版本后解决了，谢谢

**Comment by houtianze** [comment]
谢谢反馈。

因为之前版本有一个一直无效重试的大bug，所以授权改了一下，升级到最新版就可以了。
