### ISSUE TITLE
InsecurePlatformWarning

### ISSUE THREAD

**Issue by jiangjiangflies** [houtianze/bypy#351]
这个好气啊 认证不了 有解吗？
InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Heroku server failed. Last resort: authorizing/refreshing with the GAE server ...

**Comment by houtianze** [comment]
升级一下试试：pip install-U bypy

**Comment by jiangjiangflies** [comment]
已经最新了 最后提示都是Heroku server failed. Last resort: authorizing/refreshing with the GAE server ...

**Comment by houtianze** [comment]
帮忙贴下输出？
`bypy version`

`bypy -dv info`

**Comment by jiangjiangflies** [comment]
成功了，谢谢你。执行了bypy version之后，发现确实不是最新版。。
可能是我用pip install -U bypy升级不成功？
刚刚我收到下载了源码 然后 python setup.py install 然后就成功啦

**Comment by houtianze** [comment]
好的。

是因为没有`sudo`吗？还是报错？

**Comment by jiangjiangflies** [comment]
我本来就是root用户呀，需要sudo吗? 貌似没有报错呢

**Comment by houtianze** [comment]
那不需要sudo啊，按理应该升级成功啊。不过问题解决了就好。

**Comment by jiangjiangflies** [comment]
嗯嗯 非常感谢你！这对于我数据同步非常重要！

**Comment by houtianze** [comment]
不客气 😄

**Comment by jiangjiangflies** [comment]
问题又来了。 我刚刚顺手在另一个VPS上升级bypy（centos），明明提示安装成功，运行却报错
Traceback (most recent call last):
  File "/usr/local/bin/bypy", line 9, in <module>
    load_entry_point('bypy==1.4.3', 'console_scripts', 'bypy')()
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 305, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 2244, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 1954, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named bypy

**Comment by houtianze** [comment]
挺奇怪，`pip list`输出是什么？

**Comment by jiangjiangflies** [comment]
各种升级方式都用上了 pip install -U bypy 还有下载源码用python setup.py
pip list输出为
beautifulsoup4 (4.5.1)
bypy (1.4.3)
cffi (1.8.3)
cymysql (0.8.9)
distribute (0.6.14)
enum34 (1.1.6)
futures (3.1.1)
idna (2.1)
ipaddress (1.0.17)
livestreamer (1.12.2)
lxml (3.6.4)
meld3 (1.0.2)
pip (9.0.1)
pyasn1 (0.1.9)
pycparser (2.17)
PyInstaller (3.2)
pyOpenSSL (16.2.0)
requests (2.13.0)
setuptools (28.8.0)
singledispatch (3.4.0.3)
six (1.10.0)
speedtest-cli (1.0.1)
supervisor (3.3.1)
update (0.4.4)
wheel (0.29.0)
[root@localhost ~]#

**Comment by houtianze** [comment]
`pip check`有效吗？

**Comment by jiangjiangflies** [comment]
pip check
pyOpenSSL 16.2.0 requires cryptography, which is not installed.
我尝试pip install cryptography
distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-R7UVOx/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-82znRa-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-R7UVOx/cryptography/

**Comment by houtianze** [comment]
`python -m bypy` 也不行？

**Comment by jiangjiangflies** [comment]
`python -m bypy` 可以哎！ 不过这是什么意思？ 每次启动都要用这个命令才可以吗

**Comment by houtianze** [comment]
应该是配置问题。也许重装`pip`能解决问题。（`yum uninstall python-pip && yum install python-pip`）
`python -m bypy`是直接运行`bypy` module，（在正常系统上）和直接跑`bypy`是一样的。

**Comment by jiangjiangflies** [comment]
重装pip也不行。 不过`python -m bypy` 挺好用的  谢谢啦 非常感谢！
