### ISSUE TITLE
能不能指定一个url 然后执行下载任务

### ISSUE THREAD

**Issue by ljhzds** [houtianze/bypy#352]
文件本身不在云盘上的
比如：
https://pan.baidu.com/s/1pLplVEr

**Comment by houtianze** [comment]
感谢反馈。

能详细描述下是要做什么吗？

**Comment by ljhzds** [comment]
文件本身不存在/app/bypy ，就是我在网上搜到一个pan资源的链接
怎么加入下载队列？
我试过
bypy cdl_add <url> 
但是好像不行

**Comment by houtianze** [comment]
`cdl_add`以前是可以的，但是现在`502 Bad Gateway`错误，暂时无解。
PCS API也就`cdl_add`这个可以实现类似功能，所以现在没啥办法。大概只能存到自己的网盘再下载了。
