### ISSUE TITLE
授权一直过不去

### ISSUE THREAD

**Issue by charry** [houtianze/bypy#353]
之前每天都用，上周突然不能用了，我就执行 bypy -c 清空了授权信息。然后一直就无法授权了。错误信息如下：

老是提示我bypy的版本太低，要升级到1.4.3，我升级了，也是报这样的错误。请问有什么建议？

Authorizing, please be patient, it may take upto 60.0 seconds...
Authorizing/refreshing with the OpenShift server ...
<D> GET https://bypy-tianze.rhcloud.com/auth
<D> actargs: None
<D> Params: {u'code': 'ea36b4951b99966fc5dc96a62b108b15', u'redirect_uri': u'oob'}
<D> Full URL: https://bypy-tianze.rhcloud.com/auth?code=ea36b4951b99966fc5dc96a62b108b15&redirect_uri=oob
<D> HTTP Status Code: 400
<D> Website returned JSON: {u'error_code': 31062, u'error_msg': u'need to update bypy to at leaset v1.4.3 (pip install -U bypy)'}
<E> [13:29:58] Error accessing 'https://bypy-tianze.rhcloud.com/auth'
<E> [13:29:58] 
<E> [13:29:58] Function: __server_auth_act
<E> [13:29:58] Website parameters: {u'code': 'ea36b4951b99966fc5dc96a62b108b15', u'redirect_uri': u'oob'}
<E> [13:29:58] Full URL: https://bypy-tianze.rhcloud.com/auth?code=ea36b4951b99966fc5dc96a62b108b15&redirect_uri=oob
<E> [13:29:58] HTTP Response Status Code: 400
<E> [13:29:58] Error JSON returned:{u'error_code': 31062, u'error_msg': u'need to update bypy to at leaset v1.4.3 (pip install -U bypy)'}
Error code: 31062
Error Description: need to update bypy to at leaset v1.4.3 (pip install -U bypy)
<E> [13:29:58] Website returned: {"error_code": 31062, "error_msg": "need to update bypy to at leaset v1.4.3 (pip install -U bypy)"}
OpenShift server failed, authorizing/refreshing with the Heroku server ...
<D> GET https://bypyoauth.herokuapp.com/auth
<D> actargs: None
<D> Params: {u'code': 'ea36b4951b99966fc5dc96a62b108b15', u'redirect_uri': u'oob'}
<D> Full URL: https://bypyoauth.herokuapp.com/auth?code=ea36b4951b99966fc5dc96a62b108b15&redirect_uri=oob
<D> HTTP Status Code: 400
<D> Website returned JSON: {u'error_code': 31062, u'error_msg': u'need to update bypy to at leaset v1.4.3 (pip install -U bypy)'}
<E> [13:30:00] Error accessing 'https://bypyoauth.herokuapp.com/auth'
<E> [13:30:00] 
<E> [13:30:00] Function: __server_auth_act
<E> [13:30:00] Website parameters: {u'code': 'ea36b4951b99966fc5dc96a62b108b15', u'redirect_uri': u'oob'}
<E> [13:30:00] Full URL: https://bypyoauth.herokuapp.com/auth?code=ea36b4951b99966fc5dc96a62b108b15&redirect_uri=oob
<E> [13:30:00] HTTP Response Status Code: 400
<E> [13:30:00] Error JSON returned:{u'error_code': 31062, u'error_msg': u'need to update bypy to at leaset v1.4.3 (pip install -U bypy)'}
Error code: 31062
Error Description: need to update bypy to at leaset v1.4.3 (pip install -U bypy)
<E> [13:30:00] Website returned: {"error_msg": "need to update bypy to at leaset v1.4.3 (pip install -U bypy)", "error_code": 31062}
Heroku server failed. Last resort: authorizing/refreshing with the GAE server ...
<D> GET https://bypyoauth.appspot.com/auth
<D> actargs: None
<D> Params: {u'code': 'ea36b4951b99966fc5dc96a62b108b15', u'redirect_uri': u'oob'}

**Comment by charry** [comment]
原因找到了，执行sudo pip install -U bypy不能升级到1.4.3，只能升级一个旧的版本，大概是1.3.x的样子。我git下载了，然后手动安装。然后问题就解决了。

**Comment by houtianze** [comment]
感谢反馈和提供log。
最近强制升级到1.4.3或以上了，因为之前发现个bug导致刷新令牌失败，而且会一直连授权服务器，然后服务器就经常挂掉。
这个`pip install -U`不能升级有点怪，我自己升级最新版一直没问题的。升级会出错吗？还是没错误就是不会升级到最新版？

**Comment by charry** [comment]
我原来的安装到系统路径的版本很旧，应该是1.x，通过`pip install -u`可以升级，但是升级到的是一个中间的版本1.3.x，再次执行该命令就一直是这个版本。所以我手动下载源码安装，然后解决问题。

看起来很奇怪的，不过好在我现在可以用了，多谢回复。
