### ISSUE TITLE
总说授权失败

### ISSUE THREAD

**Issue by cnritng** [houtianze/bypy#355]
[root@rosd]# bypy ls
Please visit:
https://openapi.baidu.com/oauth/2.0/authorize?client_id=q8WE4EpCsau1oS0MplgMKNBn&response_type=code&redirect_uri=oob&scope=basic+netdisk
And authorize this app
Paste the Authorization Code here within 10 minutes.
Press [Enter] when you are done
18ae5af20135df71b****************
Authorizing, please be patient, it may take upto None seconds...
Authorizing/refreshing with the OpenShift server ...
OpenShift server failed, authorizing/refreshing with the Heroku server ...
Heroku server failed. Last resort: authorizing/refreshing with the GAE server ...
<E> [03:53:28] Fatal: All server authorizations failed.
<I> [03:53:28] ----------------------------------------------------------------
<I> [03:53:28] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.
<E> [03:53:28] Program authorization FAILED.
You need to authorize this program before using any PCS functions.
Quitting...

[root@rosd .bypy]# bypy -c
<E> [03:55:20] Fail to remove local fle '/root/.bypy/bypy.json'.
Exception:
<class 'FileNotFoundError'> - [Errno 2] No such file or directory: '/root/.bypy/bypy.json'
Stack:
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/bypy/bypy.py", line 3217, in main
    return clean_prog_files(args.clean, args.verbose, args.configdir)
  File "/usr/local/lib/python3.6/site-packages/bypy/bypy.py", line 3141, in clean_prog_files
    result = removefile(tokenpath, verbose)
  File "/usr/local/lib/python3.6/site-packages/bypy/util.py", line 135, in removefile
    path, formatex(ex)))
  File "/usr/local/lib/python3.6/site-packages/bypy/util.py", line 70, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

<E> [03:55:20] Failed to remove the token file '/root/.bypy/bypy.json'
<E> [03:55:20] You need to remove it manually
<E> [03:55:20] Fail to remove local fle '/root/.bypy/bypy.parts.json'.
Exception:
<class 'FileNotFoundError'> - [Errno 2] No such file or directory: '/root/.bypy/bypy.parts.json'
Stack:
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/bypy/bypy.py", line 3217, in main
    return clean_prog_files(args.clean, args.verbose, args.configdir)
  File "/usr/local/lib/python3.6/site-packages/bypy/bypy.py", line 3150, in clean_prog_files
    subresult = removefile(prgrpath, verbose)
  File "/usr/local/lib/python3.6/site-packages/bypy/util.py", line 135, in removefile
    path, formatex(ex)))
  File "/usr/local/lib/python3.6/site-packages/bypy/util.py", line 70, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

<E> [03:55:20] Failed to remove the progress file '/root/.bypy/bypy.parts.json'

**Comment by houtianze** [comment]
感谢反馈。

应该是版本有点旧(`bypy --version`），`1.4`之前的前段时间发现一个大bug，要升级1.4以后的才能使用。`pip install -U bypy`应该能解决问题。

**Comment by ricky820422** [comment]
完全相同的问题，已是1.5.7版本

**Comment by houtianze** [comment]
@ricky820422 如果授权还是失败：
- 运行 `bypy -c`重新授权
- 还不行的话去 https://passport.baidu.com/accountbind 解除以前授权 再运行。

这两个都坐下来几乎一定可以的。

**Comment by my4399** [comment]
我试过了下面这两个操作，也解决不了问题。版本是 bypy v1.5.11  ，python3 ,pip 安装最新的。【我电脑之前授权过，使用过的，可是今天就不能用了。在别的电脑上也用不了。】
运行 bypy -c重新授权
还不行的话去 https://passport.baidu.com/accountbind 解除以前授权 再运行。

**Comment by YYY-1124** [comment]
两种方法都试了，还是不行啊

**Comment by YYY-1124** [comment]
bypy 1.8.5，python3.12，

**Comment by YYY-1124** [comment]
运行bypy -c,显示：Failed to remove the progress file '/home/l/.bypy/bypy.parts.json'

**Comment by houtianze** [comment]
应该是权限问题，你手动删除`/home/l/.bypy`看看有没有错误提示？
