### ISSUE TITLE
授权一直失败,升级 也报错,请教

### ISSUE THREAD

**Issue by liuzedong** [houtianze/bypy#356]
[liuzedong@lzd 17:00:35 bypy]$ ./bypy list
Please visit:
https://openapi.baidu.com/oauth/2.0/authorize?scope=basic+netdisk&redirect_uri=oob&response_type=code&client_id=q8WE4EpCsau1oS0MplgMKNBn
And authorize this app
Paste the Authorization Code here within 10 minutes.
Press [Enter] when you are done
3abba94b5a84030ac9954a365d8bafc2
Authorizing, please be patient, it may take upto 60.0 seconds...
Authorizing/refreshing with the OpenShift server ...
OpenShift server failed, authorizing/refreshing with the Heroku server ...
Heroku server failed. Last resort: authorizing/refreshing with the GAE server ...
<E> [17:01:59] Maximum number (1) of tries failed.
<E> [17:01:59] Fatal: All server authorizations failed.
<I> [17:01:59] ----------------------------------------------------------------
<I> [17:01:59] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.
<E> [17:01:59] Program authorization FAILED.
You need to authorize this program before using any PCS functions.
Quitting...

[liuzedong@lzd 17:01:59 bypy]$ ./bypy -V
bypy.py v1.2.17

先前是好使的,  因为,先前都是,脚本 晚上自动备份, 最近, 没及时   ./bypy -c 删掉令牌, 现在 不行啦

我下载最新的
[liuzedong@lzd 17:10:54 bypy]$ pwd
/home/liuzedong/tools/baiduyunbypy/bypy/bypy
[liuzedong@lzd 17:10:55 bypy]$ ./bypy.py list
Traceback (most recent call last):
  File "./bypy.py", line 42, in <module>
    import json
  File "/usr/lib/python2.7/json/__init__.py", line 108, in <module>
    from .decoder import JSONDecoder
  File "/usr/lib/python2.7/json/decoder.py", line 5, in <module>
    import struct
  File "/home/liuzedong/tools/baiduyunbypy/bypy/bypy/struct.py", line 10, in <module>
    from .util import iswindows
ValueError: Attempted relative import in non-package

不是特别清楚Python, 求教

**Comment by houtianze** [comment]
应该是版本太旧了。试试运行如下命令：
```
sudo pip uninstall bypy
sudo pip install -U bypy
```
然后`bypy list`看看是不是正常？

**Comment by liuzedong** [comment]
我刚才, 下载最新的勒, 然后,下面的 动作,  还是出错啦
git clone https://github.com/houtianze/bypy.git
正克隆到 'bypy'...
remote: Counting objects: 1610, done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 1610 (delta 31), reused 0 (delta 0), pack-reused 1541
接收对象中: 100% (1610/1610), 1.72 MiB | 325.00 KiB/s, done.
处理 delta 中: 100% (992/992), done.
检查连接... 完成。
[liuzedong@lzd 17:27:19 baiduyunbypy]$ ll
总用量 12
drwxrwxr-x  3 liuzedong liuzedong 4096  5月  8 17:27 ./
drwxrwxr-x 24 liuzedong liuzedong 4096  4月 24 12:55 ../
drwxrwxr-x  6 liuzedong liuzedong 4096  5月  8 17:27 bypy/
[liuzedong@lzd 17:27:21 baiduyunbypy]$ cd bypy/
[liuzedong@lzd 17:27:22 bypy]$ ll
总用量 84
drwxrwxr-x 6 liuzedong liuzedong 4096  5月  8 17:27 ./
drwxrwxr-x 3 liuzedong liuzedong 4096  5月  8 17:27 ../
drwxrwxr-x 2 liuzedong liuzedong 4096  5月  8 17:27 baidudoc/
drwxrwxr-x 3 liuzedong liuzedong 4096  5月  8 17:27 bypy/
-rw-rw-r-- 1 liuzedong liuzedong  683  5月  8 17:27 CONTRIBUTING.md
-rw-rw-r-- 1 liuzedong liuzedong  277  5月  8 17:27 .editorconfig
-rwxrwxr-x 1 liuzedong liuzedong  129  5月  8 17:27 genrst.py*
drwxrwxr-x 8 liuzedong liuzedong 4096  5月  8 17:27 .git/
-rw-rw-r-- 1 liuzedong liuzedong  484  5月  8 17:27 .gitignore
-rw-rw-r-- 1 liuzedong liuzedong 2369  5月  8 17:27 HISTORY.md
-rw-rw-r-- 1 liuzedong liuzedong 2460  5月  8 17:27 HISTORY.rst
-rw-rw-r-- 1 liuzedong liuzedong 1078  5月  8 17:27 LICENSE
-rw-rw-r-- 1 liuzedong liuzedong  116  5月  8 17:27 MANIFEST.in
-rw-rw-r-- 1 liuzedong liuzedong 6276  5月  8 17:27 README.md
-rwxrwxr-x 1 liuzedong liuzedong 1800  5月  8 17:27 release.sh*
-rw-rw-r-- 1 liuzedong liuzedong   42  5月  8 17:27 requirements.txt
-rw-rw-r-- 1 liuzedong liuzedong   70  5月  8 17:27 setup.cfg
-rwxrwxr-x 1 liuzedong liuzedong 2342  5月  8 17:27 setup.py*
-rw-rw-r-- 1 liuzedong liuzedong  628  5月  8 17:27 .travis.yml
drwxrwxr-x 2 liuzedong liuzedong 4096  5月  8 17:27 update/
[liuzedong@lzd 17:27:22 bypy]$ cd bypy/
[liuzedong@lzd 17:27:25 bypy]$ ll
总用量 544
drwxrwxr-x 3 liuzedong liuzedong   4096  5月  8 17:27 ./
drwxrwxr-x 6 liuzedong liuzedong   4096  5月  8 17:27 ../
-rw-rw-r-- 1 liuzedong liuzedong 312971  5月  8 17:27 bypy.cacerts.pem
-rwxrwxr-x 1 liuzedong liuzedong 124466  5月  8 17:27 bypy.py*
-rw-rw-r-- 1 liuzedong liuzedong   8413  5月  8 17:27 cached.py
-rwxrwxr-x 1 liuzedong liuzedong   2258  5月  8 17:27 chkreq.py*
-rwxrwxr-x 1 liuzedong liuzedong   7372  5月  8 17:27 const.py*
-rwxrwxr-x 1 liuzedong liuzedong  11993  5月  8 17:27 gui.py*
-rw-rw-r-- 1 liuzedong liuzedong    875  5月  8 17:27 gvar.py
-rw-rw-r-- 1 liuzedong liuzedong    602  5月  8 17:27 __init__.py
-rwxrwxr-x 1 liuzedong liuzedong    385  5月  8 17:27 __main__.py*
-rw-rw-r-- 1 liuzedong liuzedong   1264  5月  8 17:27 monkey.py
-rw-rw-r-- 1 liuzedong liuzedong   7107  5月  8 17:27 panapi.py
-rw-rw-r-- 1 liuzedong liuzedong   2479  5月  8 17:27 printer_console.py
-rw-rw-r-- 1 liuzedong liuzedong   2368  5月  8 17:27 printer_gui.py
-rw-rw-r-- 1 liuzedong liuzedong   1562  5月  8 17:27 printer.py
-rw-rw-r-- 1 liuzedong liuzedong   3034  5月  8 17:27 printer_util.py
-rw-rw-r-- 1 liuzedong liuzedong   4002  5月  8 17:27 requester.py
-rw-rw-r-- 1 liuzedong liuzedong   1938  5月  8 17:27 struct.py
-rw-rw-r-- 1 liuzedong liuzedong    594  5月  8 17:27 termcolor.py
drwxrwxr-x 4 liuzedong liuzedong   4096  5月  8 17:27 test/
-rw-rw-r-- 1 liuzedong liuzedong   2088  5月  8 17:27 tkutil.py
-rwxrwxr-x 1 liuzedong liuzedong   8002  5月  8 17:27 util.py*
[liuzedong@lzd 17:27:26 bypy]$ sudo pip uninstall bypy
The directory '/home/liuzedong/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling bypy-1.5.0:
  /usr/local/bin/bypy
  /usr/local/bin/bypygui
  /usr/local/lib/python2.7/dist-packages/bypy-1.5.0.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/dist-packages/bypy-1.5.0.dist-info/INSTALLER
  /usr/local/lib/python2.7/dist-packages/bypy-1.5.0.dist-info/METADATA
  /usr/local/lib/python2.7/dist-packages/bypy-1.5.0.dist-info/RECORD
  /usr/local/lib/python2.7/dist-packages/bypy-1.5.0.dist-info/WHEEL
  /usr/local/lib/python2.7/dist-packages/bypy-1.5.0.dist-info/entry_points.txt
  /usr/local/lib/python2.7/dist-packages/bypy-1.5.0.dist-info/metadata.json
  /usr/local/lib/python2.7/dist-packages/bypy-1.5.0.dist-info/top_level.txt
  /usr/local/lib/python2.7/dist-packages/bypy/__init__.py
  /usr/local/lib/python2.7/dist-packages/bypy/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/__main__.py
  /usr/local/lib/python2.7/dist-packages/bypy/__main__.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/bypy.cacerts.pem
  /usr/local/lib/python2.7/dist-packages/bypy/bypy.py
  /usr/local/lib/python2.7/dist-packages/bypy/bypy.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/cached.py
  /usr/local/lib/python2.7/dist-packages/bypy/cached.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/chkreq.py
  /usr/local/lib/python2.7/dist-packages/bypy/chkreq.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/const.py
  /usr/local/lib/python2.7/dist-packages/bypy/const.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/gui.py
  /usr/local/lib/python2.7/dist-packages/bypy/gui.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/gvar.py
  /usr/local/lib/python2.7/dist-packages/bypy/gvar.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/monkey.py
  /usr/local/lib/python2.7/dist-packages/bypy/monkey.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/panapi.py
  /usr/local/lib/python2.7/dist-packages/bypy/panapi.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/printer.py
  /usr/local/lib/python2.7/dist-packages/bypy/printer.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/printer_console.py
  /usr/local/lib/python2.7/dist-packages/bypy/printer_console.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/printer_gui.py
  /usr/local/lib/python2.7/dist-packages/bypy/printer_gui.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/printer_util.py
  /usr/local/lib/python2.7/dist-packages/bypy/printer_util.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/requester.py
  /usr/local/lib/python2.7/dist-packages/bypy/requester.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/struct.py
  /usr/local/lib/python2.7/dist-packages/bypy/struct.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/termcolor.py
  /usr/local/lib/python2.7/dist-packages/bypy/termcolor.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/test/__init__.py
  /usr/local/lib/python2.7/dist-packages/bypy/test/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/test/__main__.py
  /usr/local/lib/python2.7/dist-packages/bypy/test/__main__.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/test/test.py
  /usr/local/lib/python2.7/dist-packages/bypy/test/test.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/tkutil.py
  /usr/local/lib/python2.7/dist-packages/bypy/tkutil.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/unified_func.py
  /usr/local/lib/python2.7/dist-packages/bypy/unified_func.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/util.py
  /usr/local/lib/python2.7/dist-packages/bypy/util.pyc
Proceed (y/n)? y
  Successfully uninstalled bypy-1.5.0
The directory '/home/liuzedong/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
[liuzedong@lzd 17:27:36 bypy]$ sudo pip install -U bypy
The directory '/home/liuzedong/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/liuzedong/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting bypy
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading bypy-1.5.0-py2.py3-none-any.whl (235kB)
    100% |████████████████████████████████| 235kB 495kB/s 
Requirement already up-to-date: requests>=2.10.0 in /usr/local/lib/python2.7/dist-packages (from bypy)
Requirement already up-to-date: multiprocess>=0.70.0 in /usr/local/lib/python2.7/dist-packages (from bypy)
Requirement already up-to-date: dill>=0.2.6 in /usr/local/lib/python2.7/dist-packages (from multiprocess>=0.70.0->bypy)
Installing collected packages: bypy
Successfully installed bypy-1.5.0
[liuzedong@lzd 17:27:52 bypy]$ ./bypy.py --version
Traceback (most recent call last):
  File "./bypy.py", line 42, in <module>
    import json
  File "/usr/lib/python2.7/json/__init__.py", line 108, in <module>
    from .decoder import JSONDecoder
  File "/usr/lib/python2.7/json/decoder.py", line 5, in <module>
    import struct
  File "/home/liuzedong/tools/baiduyunbypy/bypy/bypy/struct.py", line 10, in <module>
    from .util import iswindows
ValueError: Attempted relative import in non-package

**Comment by liuzedong** [comment]
我刚才,下载最新的啦, 还是出错, 麻烦帮我看下, 谢谢
**git clone https://github.com/houtianze/bypy.git**
正克隆到 'bypy'...
remote: Counting objects: 1610, done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 1610 (delta 31), reused 0 (delta 0), pack-reused 1541
接收对象中: 100% (1610/1610), 1.72 MiB | 325.00 KiB/s, done.
处理 delta 中: 100% (992/992), done.
检查连接... 完成。
**[liuzedong@lzd 17:27:19 baiduyunbypy]$ ll**
总用量 12
drwxrwxr-x  3 liuzedong liuzedong 4096  5月  8 17:27 ./
drwxrwxr-x 24 liuzedong liuzedong 4096  4月 24 12:55 ../
drwxrwxr-x  6 liuzedong liuzedong 4096  5月  8 17:27 bypy/
**[liuzedong@lzd 17:27:21 baiduyunbypy]$ cd bypy/**
**[liuzedong@lzd 17:27:22 bypy]$ ll**
总用量 84
drwxrwxr-x 6 liuzedong liuzedong 4096  5月  8 17:27 ./
drwxrwxr-x 3 liuzedong liuzedong 4096  5月  8 17:27 ../
drwxrwxr-x 2 liuzedong liuzedong 4096  5月  8 17:27 baidudoc/
drwxrwxr-x 3 liuzedong liuzedong 4096  5月  8 17:27 bypy/
-rw-rw-r-- 1 liuzedong liuzedong  683  5月  8 17:27 CONTRIBUTING.md
-rw-rw-r-- 1 liuzedong liuzedong  277  5月  8 17:27 .editorconfig
-rwxrwxr-x 1 liuzedong liuzedong  129  5月  8 17:27 genrst.py*
drwxrwxr-x 8 liuzedong liuzedong 4096  5月  8 17:27 .git/
-rw-rw-r-- 1 liuzedong liuzedong  484  5月  8 17:27 .gitignore
-rw-rw-r-- 1 liuzedong liuzedong 2369  5月  8 17:27 HISTORY.md
-rw-rw-r-- 1 liuzedong liuzedong 2460  5月  8 17:27 HISTORY.rst
-rw-rw-r-- 1 liuzedong liuzedong 1078  5月  8 17:27 LICENSE
-rw-rw-r-- 1 liuzedong liuzedong  116  5月  8 17:27 MANIFEST.in
-rw-rw-r-- 1 liuzedong liuzedong 6276  5月  8 17:27 README.md
-rwxrwxr-x 1 liuzedong liuzedong 1800  5月  8 17:27 release.sh*
-rw-rw-r-- 1 liuzedong liuzedong   42  5月  8 17:27 requirements.txt
-rw-rw-r-- 1 liuzedong liuzedong   70  5月  8 17:27 setup.cfg
-rwxrwxr-x 1 liuzedong liuzedong 2342  5月  8 17:27 setup.py*
-rw-rw-r-- 1 liuzedong liuzedong  628  5月  8 17:27 .travis.yml
drwxrwxr-x 2 liuzedong liuzedong 4096  5月  8 17:27 update/
**[liuzedong@lzd 17:27:22 bypy]$ cd bypy/**
**[liuzedong@lzd 17:27:25 bypy]$ ll**
总用量 544
drwxrwxr-x 3 liuzedong liuzedong   4096  5月  8 17:27 ./
drwxrwxr-x 6 liuzedong liuzedong   4096  5月  8 17:27 ../
-rw-rw-r-- 1 liuzedong liuzedong 312971  5月  8 17:27 bypy.cacerts.pem
-rwxrwxr-x 1 liuzedong liuzedong 124466  5月  8 17:27 bypy.py*
-rw-rw-r-- 1 liuzedong liuzedong   8413  5月  8 17:27 cached.py
-rwxrwxr-x 1 liuzedong liuzedong   2258  5月  8 17:27 chkreq.py*
-rwxrwxr-x 1 liuzedong liuzedong   7372  5月  8 17:27 const.py*
-rwxrwxr-x 1 liuzedong liuzedong  11993  5月  8 17:27 gui.py*
-rw-rw-r-- 1 liuzedong liuzedong    875  5月  8 17:27 gvar.py
-rw-rw-r-- 1 liuzedong liuzedong    602  5月  8 17:27 __init__.py
-rwxrwxr-x 1 liuzedong liuzedong    385  5月  8 17:27 __main__.py*
-rw-rw-r-- 1 liuzedong liuzedong   1264  5月  8 17:27 monkey.py
-rw-rw-r-- 1 liuzedong liuzedong   7107  5月  8 17:27 panapi.py
-rw-rw-r-- 1 liuzedong liuzedong   2479  5月  8 17:27 printer_console.py
-rw-rw-r-- 1 liuzedong liuzedong   2368  5月  8 17:27 printer_gui.py
-rw-rw-r-- 1 liuzedong liuzedong   1562  5月  8 17:27 printer.py
-rw-rw-r-- 1 liuzedong liuzedong   3034  5月  8 17:27 printer_util.py
-rw-rw-r-- 1 liuzedong liuzedong   4002  5月  8 17:27 requester.py
-rw-rw-r-- 1 liuzedong liuzedong   1938  5月  8 17:27 struct.py
-rw-rw-r-- 1 liuzedong liuzedong    594  5月  8 17:27 termcolor.py
drwxrwxr-x 4 liuzedong liuzedong   4096  5月  8 17:27 test/
-rw-rw-r-- 1 liuzedong liuzedong   2088  5月  8 17:27 tkutil.py
-rwxrwxr-x 1 liuzedong liuzedong   8002  5月  8 17:27 util.py*
**[liuzedong@lzd 17:27:26 bypy]$ sudo pip uninstall bypy**
The directory '/home/liuzedong/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling bypy-1.5.0:
  /usr/local/bin/bypy
  /usr/local/bin/bypygui
  /usr/local/lib/python2.7/dist-packages/bypy-1.5.0.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/dist-packages/bypy-1.5.0.dist-info/INSTALLER
  /usr/local/lib/python2.7/dist-packages/bypy-1.5.0.dist-info/METADATA
  /usr/local/lib/python2.7/dist-packages/bypy-1.5.0.dist-info/RECORD
  /usr/local/lib/python2.7/dist-packages/bypy-1.5.0.dist-info/WHEEL
  /usr/local/lib/python2.7/dist-packages/bypy-1.5.0.dist-info/entry_points.txt
  /usr/local/lib/python2.7/dist-packages/bypy-1.5.0.dist-info/metadata.json
  /usr/local/lib/python2.7/dist-packages/bypy-1.5.0.dist-info/top_level.txt
  /usr/local/lib/python2.7/dist-packages/bypy/__init__.py
  /usr/local/lib/python2.7/dist-packages/bypy/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/__main__.py
  /usr/local/lib/python2.7/dist-packages/bypy/__main__.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/bypy.cacerts.pem
  /usr/local/lib/python2.7/dist-packages/bypy/bypy.py
  /usr/local/lib/python2.7/dist-packages/bypy/bypy.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/cached.py
  /usr/local/lib/python2.7/dist-packages/bypy/cached.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/chkreq.py
  /usr/local/lib/python2.7/dist-packages/bypy/chkreq.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/const.py
  /usr/local/lib/python2.7/dist-packages/bypy/const.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/gui.py
  /usr/local/lib/python2.7/dist-packages/bypy/gui.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/gvar.py
  /usr/local/lib/python2.7/dist-packages/bypy/gvar.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/monkey.py
  /usr/local/lib/python2.7/dist-packages/bypy/monkey.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/panapi.py
  /usr/local/lib/python2.7/dist-packages/bypy/panapi.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/printer.py
  /usr/local/lib/python2.7/dist-packages/bypy/printer.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/printer_console.py
  /usr/local/lib/python2.7/dist-packages/bypy/printer_console.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/printer_gui.py
  /usr/local/lib/python2.7/dist-packages/bypy/printer_gui.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/printer_util.py
  /usr/local/lib/python2.7/dist-packages/bypy/printer_util.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/requester.py
  /usr/local/lib/python2.7/dist-packages/bypy/requester.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/struct.py
  /usr/local/lib/python2.7/dist-packages/bypy/struct.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/termcolor.py
  /usr/local/lib/python2.7/dist-packages/bypy/termcolor.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/test/__init__.py
  /usr/local/lib/python2.7/dist-packages/bypy/test/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/test/__main__.py
  /usr/local/lib/python2.7/dist-packages/bypy/test/__main__.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/test/test.py
  /usr/local/lib/python2.7/dist-packages/bypy/test/test.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/tkutil.py
  /usr/local/lib/python2.7/dist-packages/bypy/tkutil.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/unified_func.py
  /usr/local/lib/python2.7/dist-packages/bypy/unified_func.pyc
  /usr/local/lib/python2.7/dist-packages/bypy/util.py
  /usr/local/lib/python2.7/dist-packages/bypy/util.pyc
**Proceed (y/n)? y**
  Successfully uninstalled bypy-1.5.0
The directory '/home/liuzedong/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
**[liuzedong@lzd 17:27:36 bypy]$ sudo pip install -U bypy**
The directory '/home/liuzedong/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/liuzedong/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting bypy
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading bypy-1.5.0-py2.py3-none-any.whl (235kB)
    100% |████████████████████████████████| 235kB 495kB/s 
Requirement already up-to-date: requests>=2.10.0 in /usr/local/lib/python2.7/dist-packages (from bypy)
Requirement already up-to-date: multiprocess>=0.70.0 in /usr/local/lib/python2.7/dist-packages (from bypy)
Requirement already up-to-date: dill>=0.2.6 in /usr/local/lib/python2.7/dist-packages (from multiprocess>=0.70.0->bypy)
Installing collected packages: bypy
Successfully installed bypy-1.5.0
**[liuzedong@lzd 17:27:52 bypy]$ ./bypy.py --version**
Traceback (most recent call last):
  File "./bypy.py", line 42, in <module>
    import json
  File "/usr/lib/python2.7/json/__init__.py", line 108, in <module>
    from .decoder import JSONDecoder
  File "/usr/lib/python2.7/json/decoder.py", line 5, in <module>
    import struct
  File "/home/liuzedong/tools/baiduyunbypy/bypy/bypy/struct.py", line 10, in <module>
    from .util import iswindows
ValueError: Attempted relative import in non-package

**Comment by houtianze** [comment]
`bypy --version`不是`./bypy.py --version`
用pip安装其实是完全不用克隆代码库的。

**Comment by liuzedong** [comment]
谢谢, 明白啦,  我一直以为, 是需要下载源码, 进行编译使用的, 谢谢, 原来直接安装就行

**Comment by houtianze** [comment]
不客气 :smile:
