### ISSUE TITLE
不影响正常运行,但是 有报错

### ISSUE THREAD

**Issue by liuzedong** [houtianze/bypy#357]
**[dong@aaa 18:29:28 shellnote]$ bypy list**
<E> [18:30:03] Failed to disable warnings for Urllib3.
Possibly the requests library is out of date?
You can upgrade it by running 'pip2 install -U requests'.
Exception:
<type 'exceptions.AttributeError'> - 'module' object has no attribute 'disable_warnings'
Stack:
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 3504, in main
    by = ByPy(**bypyopt)
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 375, in __init__
    requester.disable_warnings(self.debug)
  File "/usr/local/lib/python2.7/dist-packages/bypy/requester.py", line 126, in disable_warnings
    const.PipUpgradeCommand, formatex(ex)))
  File "/usr/local/lib/python2.7/dist-packages/bypy/util.py", line 73, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

/apps/bypy ($t $f $s $m $d):
D aaaaa 0 2016-07-17, 16:33:19

**Comment by liuzedong** [comment]
[dong@aaa 18:30:03 shellnote]$ sudo pip2 install -U requests
Downloading/unpacking requests from https://pypi.python.org/packages/7e/ac/a80ed043485a3764053f59ca92f809cc8a18344692817152b0e8bd3ca891/requests-2.13.0-py2.py3-none-any.whl#md5=5e432dcf5bd1e3402ea1656700d99365
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB): 584kB downloaded
Installing collected packages: requests
  Found existing installation: requests 2.2.1
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed requests
Cleaning up...

**Comment by houtianze** [comment]
感谢反馈。

看了一下，应该是`requests`版本太低了。可以：
- 卸掉系统安装的`python-requests`包（如果是debian ubuntu，运行：sudo apt-get uninstall -y python-requests）
- 用pip安装最新的`requests`（`sudo pip install -U requests`)
