### ISSUE TITLE
请问MultCloud中百度网盘的图片/文档/视频/音乐视图是调用的是什么api?

### ISSUE THREAD

**Issue by hzj629206** [houtianze/bypy#360]
![image](https://cloud.githubusercontent.com/assets/1644620/26149122/a846cf7e-3b2b-11e7-942f-90fe412e0de1.png)

http://developer.baidu.com/wiki/index.php?title=docs/pcs/rest/file_data_apis_list
是这个文档里的哪个api呢？
我用 https://pcs.baidu.com/rest/2.0/pcs/stream 查不出来，结果是空列表。

**Comment by houtianze** [comment]
看了一下，应该是`/stream`吧，PCS API只能存取`/apps/xxxx`下文件（夹），是不是还是空的？

**Comment by hzj629206** [comment]
不是/stream，/stream应该也是只能作用于/app/xxx下的文件。我研究下发现旧版本的Frontia SDK里面包含了imageStream这样的接口，看文档说是需要特殊申请权限。

[2.8 以流的方式得到所有图像文件的列表](https://developer.baidu.com/wiki/index.php?title=docs/frontia/guide-android/pdata#.E4.BB.A5.E6.B5.81.E7.9A.84.E6.96.B9.E5.BC.8F.E5.BE.97.E5.88.B0.E6.89.80.E6.9C.89.E5.9B.BE.E5.83.8F.E6.96.87.E4.BB.B6.E7.9A.84.E5.88.97.E8.A1.A8)

**Comment by houtianze** [comment]
嗯，看起来挺像。

**Comment by landall** [comment]
GET https://pcs.baidu.com/rest/2.0/pcs/stream?method=list&type=image&start=50&limit=100&access_token=b778fb000c717c0ad7ea8c97c8f3a46f

**Comment by landall** [comment]
类型分为video、audio、image及doc四种。
