### ISSUE TITLE
bydy upload 上传文件，然后用bydy compare比较，很多文件提示不一致

### ISSUE THREAD

**Issue by icehong** [houtianze/bypy#361]
不知道是baidu的API的问题， 还是程序问题

作为文件管理程序，文件的一致性非常重要，   如果只是baidu md5 计算失败还好，  如果就是文件错了，就麻烦了。    
不知道能否解决， 如果没有好办法解决的话，  上传完文件， 再自动调用compare 比较一下， 不一样的话， 再重新上传一下比较可靠

**Comment by icehong** [comment]
又试了一下  重新upload 也没有用，不重新传， 在比较还是显示有不一样的，

**Comment by houtianze** [comment]
感谢反馈。

能贴出所用的命令和输出吗？（如果可能，加上`-dv`参数便于调试）

由于百度云和网络的不确定因素，这个工具本来就是没有保证一致性的。设计就是跑完所有上传/下载之后用户自行比较。如果是网络问题或百度一次返回错误代码，比较再上传没法解决，反而更浪费用户时间。出错程序会有日志输出，用户有了比较功能，至少用户验证的时候可以确信知道是否全部上传成功，自己选择再次上传。

**Comment by icehong** [comment]
好的  晚上回家 我传一下日志

2017年5月19日 下午12:03，"Hou Tianze" <notifications@github.com>写道：

**Comment by icehong** [comment]
文件太多， 我挑了其中一个文件的相关日志 ， 似乎是上传时只比较文件大小，不比较MD5值吗？ 


osmc@osmc:~/bypy$ bypy --version
bypy v1.5.2

bydy compare  时的日志

<D> [22:50:04] Cache hit for file './DV/2013-11-9/20131109122411.mpg',
md5: aed5ecd048070862d418ca4de40b1921
size: 463863808
mtime: 1383971444

F - /DV/2013-11-9/20131109122411.mpg - size: 463863808 - md5: aed5ecd048070862d418ca4de40b1921 

D> ---- Remote Dir Contents ---
<D> D - /DV - size: 0 - md5:  
F - /DV/2013-11-9/20131109122411.mpg - size: 463863808 - md5: 972c1f74ecc8fc6ab6c0b92f35ca5bfa 

文件比较时不一致。 


bydy upload   命令时的日志


<D> __get_file_info(): rdir : /apps/bypy/DV/2013-11-9 | rfile: 20131109122411.mpg
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/DV/2013-11-9/20131109122411.mpg
<D> Params: {u'path': u'/apps/bypy/DV/2013-11-9', u'order': u'asc', u'method': u'list', u'by': u'name'}
<D> Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=21.71d387dc0ba4b5c26de31a9c492ba7.2592000.1497541290.4266319319-1572671&path=%2Fapps%2Fbypy%2FDV%2F2013-11-9&by=name&order=asc&method=list
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> List json: {u'list': [{u'isdir': 0, u'ctime': 1495059884, u'fs_id': 948466483607106L, u'mtime': 1495059884, u'path': u'/apps/bypy/DV/2013-11-9/20131109121356.mpg', u'md5': u'1a74721c5b2b010edde8ea985c19ff38', u'size': 639270912}, {u'isdir': 0, u'ctime': 1495126912, u'fs_id': 215539781359093L, u'mtime': 1495126912, u'path': u'/apps/bypy/DV/2013-11-9/20131109122411.mpg', u'md5': u'972c1f74ecc8fc6ab6c0b92f35ca5bfa', u'size': 463863808}], u'request_id': 3222710614899636662L}
<D> File info json: {u'isdir': 0, u'ctime': 1495126912, u'fs_id': 215539781359093L, u'mtime': 1495126912, u'path': u'/apps/bypy/DV/2013-11-9/20131109122411.mpg', u'md5': u'972c1f74ecc8fc6ab6c0b92f35ca5bfa', u'size': 463863808}
<D> Request all goes fine
<D> Comparing local file '/home/osmc/bypy/DV/2013-11-9/20131109122411.mpg' and remote file '/apps/bypy/DV/2013-11-9/20131109122411.mpg'
<D> Local file size : 463863808
<D> Remote file size: 463863808
<D> Local and remote file size matches
Remote file '/apps/bypy/DV/2013-11-9/20131109122411.mpg' already exists, skip uploading
<I> [22:52:12] Remote file '/apps/bypy/DV/2013-11-9/20131109122411.mpg' exists and is the same, skip uploading

**Comment by icehong** [comment]
![image](https://cloud.githubusercontent.com/assets/191640/26255596/ac0d12f4-3cec-11e7-8e9d-7197ade8043f.png)

同一个目录的大于20M的文件， 都是提示MD5值不一样的，  是不是大文件算法不一样？

**Comment by houtianze** [comment]
不好意思才回复，感谢提供质料。

我去看看。是的，大文件是切片上传，看来可能是合并时出错了。你有用`--processes`这个参数吗？

**Comment by houtianze** [comment]
哦，按了一下，应该是用了`--processess`上传才出的错对吧？

**Comment by houtianze** [comment]
看了一下，合并代码最近并没有改，所以可能合并时并没有出错。

试过再次上传吗？再次上传后比较还不一致吗？（再次上传的大文件应该是秒传，应该很快的）

上传时没有比较`md5`是因为一个像是百度服务端的bug，刚刚上传的文件返回的`md5`值是错的，所以为了避免很多不必要的误报，默认是不验证md5的，如果想要，可以加上`--verify`参数，程序就会比较`md5`值了。

你上传的是视频文件，在百度盘网页端能播放不？图像是不是一致，如果图像没错，那基本是百度那边返回的`md5`值是错的。

还有一个笨方法验证：`syncup`后再`syncdown`（或者百度云盘直接下载）到另外一个目录，然后比较本地的两个文件夹看是否一致。

**Comment by icehong** [comment]
1.  我没有用  --processes 参数  
2. 针对 “试过再次上传吗？再次上传后比较还不一致吗？（再次上传的大文件应该是秒传，应该很快的）”，   直接用upload 上传， 不清楚默认为什么没有比较MD5值 ， 直接显示文件一样返回了。   如果是用 syncup , 因为我本地有删除的文件， 我担心会把我本地删除的文件在服务器上也同步删除了。 
3.  我传的是视频，  文件上传上去，看起来像是正常的， 我再下载下来， 文件看起来也正常。  但服务器上的md5值不一样， 总是很担心 ；  而且目前也没有什么快速上传更新md5的方法，   不管是raspberry pi 上用--verify重新上传，还是在windows 上用百度网盘的客户端， 都会触发重新上传文件，   我主要是上传带宽太小所以才想在PI上上传，  那样可以开一晚上。

**Comment by houtianze** [comment]
听起来应该是百度返回的`md5`的问题了。
理解你对`md5`值得担心，但百度这个`md5`不准的问题客比较难有效的妥协处方法（我觉得自动重新传2遍也是浪费用户时间）。

有时间的时候可以试试：
- 下载一个`md5`不一致的文件和你原来文件本地比较，如果一样那么基本上没有问题了。
- 还不放心的话，你可以用`--verify --rapid-upload-only`上传（`upload / syncup`都可以）。那样就：
  - 只传能够秒传的文件（你的那些大视频文件都应该可以秒传了）
  - 比较`md5`
你列的这几个大文件应该很快就可以传完（几分钟吧）。

**Comment by icehong** [comment]
昨天晚上传了一晚上，终于成功了。 
过程  ：
1. 　bypy  upload -e   （ 也就是--verify）上传一次 
2.    然后再用  bypy compare 比较，  结果还是有几个文件不一样
3.   用  bypy  upload -e   再次上传 （这一次触发了快速上传）
4.   再比较， 文件终于一样了。 

我的问题是，  -e  不应该是默认参数吗？    如果可能的话， 改成默认参数比较好。 
另外，    我用 syncup 上传的文件，   再次用 upload -e  ， 没有触发快速上传；  而用 upload -e 上传完后md5不对的文件， 再次用 upload -e  命令上传就可以快速上传了。  

不知道是必现问题还是偶发问题， 加之 #362 ，  可能是我本地的环境现在已经正常了， 不再出奇怪的问题了。

**Comment by houtianze** [comment]
好的，解决了就好。

`-e`本来是默认的行为，但是后来发现很多文件上传后会出现这种返回的md5不对的情形，导致很多没必要的上传重试。其实如果文件大小一致，基本上不会有问题。（为了确信，貌似现在只能这样重复上传到md5一致）
你说的要三次上传才能让百度md5变正确的原因我猜是因为上传之后百度内部存储的md5不对，所以没秒传，第二次后内部存储md5对了，所以第三次就可以秒传了。（这个行为只是猜测）

**Comment by thehackercat** [comment]
我似乎也遇到这个问题了，晚上回家贴个 md5 比较看下
