### ISSUE TITLE
About syncup tips 

### ISSUE THREAD

**Issue by icehong** [houtianze/bypy#362]
命令行提示说 syncup 命令在本地文件删除的情况下，不会删除远程的文件， 但看着这个提示怪吓人的， 感觉好像远程文件被删除了一样？     是否修改一下提示信息呢

osmc@osmc:~/bypy$ bypy syncup
Deletion request '3244737075775310423' OK
Usage 'list' command to confirm
Deletion request '3244737344120690305' OK
Usage 'list' command to confirm
Deletion request '3244737595651067602' OK
Usage 'list' command to confirm

这个提示信息是什么意思，  用list 命令就可以确认删除远程文件吗？ 
Usage 'list' command to confirm

**Comment by houtianze** [comment]
`bypy --version`的输出是多少？

很奇怪，按理是不应该出现这个提示信息的，你那边能重现吗？如果能，加上`-dv`参数的输出可以帮忙贴一下吗？

**Comment by icehong** [comment]
osmc@osmc:~/bypy$ bypy --version
bypy v1.5.2
我写了一个目录， 专门测试了一下，  还真没有重现这个问题 。   回头我再好好的试一下

**Comment by houtianze** [comment]
好的，那我先关了。
