### ISSUE TITLE
GUI登录不了

### ISSUE THREAD

**Issue by wszqkzqk** [houtianze/bypy#363]
如题，卡在那个界面
系统LinuxMint 18.1
能不能改造一下GUI，像BCloud一样（虽然它死了，但界面还可以）

**Comment by yan12125** [comment]
有人把bcloud fork了一份，之前的問題大部分都修好了，個人認為挺不錯用：https://github.com/Yufeikang/bcloud

**Comment by houtianze** [comment]
感谢反馈。

你版本（`bypy --version`的输出）是多少？升级最新版能解决吗？

**Comment by wszqkzqk** [comment]
@houtianze 
最新

**Comment by houtianze** [comment]
@wszqkzqk 

我刚试过，没问题。怎么登录不了你至少贴个界面和日志吧？

**Comment by wszqkzqk** [comment]
gui能不能基于GTK或Qt？

**Comment by wszqkzqk** [comment]
@houtianze
这个GUI真的很简陋。。。

**Comment by houtianze** [comment]
@wszqkzqk 现在登录问题解决了没？
`gui`本来就是随手做了一个，只有最基本功能，主要是命令行无人值守的下载上传。选择`tk`是因为“正常的”Python distribution都含有`tk`，不用担心程序依赖和运行环境。
