### ISSUE TITLE
bypy compare 在screen命令中不正常显示  

### ISSUE THREAD

**Issue by icehong** [houtianze/bypy#364]
在正常的命令终端中，  输入compare 命令， 正常显示文件比较信息。 

> osmc@osmc:~/bypy$ bypy compare -e
> ==== Same files ===
> D - DV
> D - DV/2013-11-9
> F - DV/2013-11-9/20131109121356.mpg
> D - DV/2013-11-8
> F - DV/2013-11-8/20131108081011.mpg
> D - DV/2013-12-15
> F - DV/2013-12-15/20131215101150.mpg
> D - DV/2014-11-18
> F - DV/2014-11-18/20141118081823.mpg
> D - DV/2013-12-20
> F - DV/2013-12-20/20131220121326.mpg
> F - DV/2013-12-20/20131220121132.mpg
> F - DV/2013-12-20/20131220121406.mpg
> D - DV/2013-11-7
> D - DV/2013-10-30
> F - DV/2013-10-30/20131030081038.mpg
> F - DV/2013-10-30/20131030080846.mpg
> F - DV/2013-10-30/20131030080924.mpg
> F - DV/2013-10-30/20131030150131.mpg
> F - DV/2013-10-30/20131030154820.mpg
> F - DV/2013-10-30/20131030153903.mpg
> F - DV/2013-10-30/20131030081006.mpg
> F - DV/2013-10-30/20131030154740.mpg
> F - DV/2013-10-30/20131030081316.mpg
> D - DV/2014-10-9
> F - DV/2014-10-9/20141009184446.mpg
> D - DV/20130303_romania_滑雪
> F - DV/20130303_romania_滑雪/20130303191834.mpg
> D - DV/2013-12-18
> F - DV/2013-12-18/20131218194358.mpg
> F - DV/2013-12-18/20131218194448.mpg
> D - DV/2013-10-9
> F - DV/2013-10-9/20131009081320.mpg
> F - DV/2013-10-9/20131009080449.mpg
> F - DV/2013-10-9/20131009081851.mpg
> ==== Different files ===
> F - 华为文档传出.rar
> ==== Local only ====
> F - DV/2013-11-9/20131109122411.mpg
> F - DV/2013-10-30/20131030080434.mpg
> F - DV/2013-10-30/20131030152933.mpg
> F - DV/2013-10-9/20131009080631.mpg
> F - DV/2013-10-9/20131009081413.mpg
> ==== Remote only ====
> F - DV/20130303_romania_滑雪/20130303192322.mpg
> F - DV/20130303_romania_滑雪/20130303195605.mpg
> F - DV/20130303_romania_滑雪/20130303193432.mpg
> F - DV/20130303_romania_滑雪/20130303191143.mpg
> F - DV/20130303_romania_滑雪/20130303194827.mpg
> F - DV/20130303_romania_滑雪/20130303191546.mpg
> F - DV/20130303_romania_滑雪/20130303193158.mpg
> F - DV/20130303_romania_滑雪/20130303200222.mpg
> F - DV/20130303_romania_滑雪/20130303193334.mpg
> F - DV/20130303_romania_滑雪/20130303191341.mpg
> F - DV/20130303_romania_滑雪/20130303195755.mpg
> F - DV/20130303_romania_滑雪/20130303191008.mpg
> F - DV/20130303_romania_滑雪/20130303194458.mpg
> F - DV/20130303_romania_滑雪/20130303193017.mpg
> F - DV/20130303_romania_滑雪/20130303193834.mpg
> F - DV/20130303_romania_滑雪/20130303193240.mpg
> F - DV/20130303_romania_滑雪/20130303194717.mpg
> F - DV/20130303_romania_滑雪/20130303194244.mpg
> F - DV/20130303_romania_滑雪/20130303192919.mpg
> F - DV/20130303_romania_滑雪/20130303193645.mpg
> F - DV/20130303_romania_滑雪/20130303194113.mpg
> F - DV/20130303_romania_滑雪/20130303191646.mpg
> F - DV/20130303_romania_滑雪/20130303191231.mpg
> F - DV/20130303_romania_滑雪/20130303191808.mpg
> F - DV/20130303_romania_滑雪/20130303193813.mpg
> F - DV/20130303_romania_滑雪/20130303192647.mpg
> F - DV/20130303_romania_滑雪/20130303192211.mpg
> F - DV/20130303_romania_滑雪/20130303194325.mpg
> F - DV/20130303_romania_滑雪/20130303195151.mpg
> F - DV/20130303_romania_滑雪/20130303195911.mpg
> F - DV/20130303_romania_滑雪/20130303191433.mpg
> F - DV/20130303_romania_滑雪/20130303193049.mpg
> 
> Statistics:
> --------------------------------
> Same: 35
> Different: 1
> Local only: 5
> Remote only: 32
> osmc@osmc:~/bypy$

输入 screen -r   连接到不一个不会被关闭的命令行上：  
输入 bypy compare -e
屏幕上显示的信息不正常，  很大一部分输出没有显示出来 

osmc@osmc:~$ screen -r

> F - DV/20130303_romania_滑雪/20130303194717.mpg
> F - DV/20130303_romania_滑雪/20130303194244.mpg
> F - DV/20130303_romania_滑雪/20130303192919.mpg
> F - DV/20130303_romania_滑雪/20130303193645.mpg
> F - DV/20130303_romania_滑雪/20130303194113.mpg
> F - DV/20130303_romania_滑雪/20130303191646.mpg
> F - DV/20130303_romania_滑雪/20130303191231.mpg
> F - DV/20130303_romania_滑雪/20130303191808.mpg
> F - DV/20130303_romania_滑雪/20130303193813.mpg
> F - DV/20130303_romania_滑雪/20130303192647.mpg
> F - DV/20130303_romania_滑雪/20130303192211.mpg
> F - DV/20130303_romania_滑雪/20130303194325.mpg
> F - DV/20130303_romania_滑雪/20130303195151.mpg
> F - DV/20130303_romania_滑雪/20130303195911.mpg
> F - DV/20130303_romania_滑雪/20130303191433.mpg
> F - DV/20130303_romania_滑雪/20130303193049.mpg
> 
> Statistics:
> --------------------------------
> Same: 35
> Different: 1
> Local only: 5
> Remote only: 32
> osmc@osmc:~/bypy$

**Comment by houtianze** [comment]
感谢反馈。

看你贴的输出，应该是screen的最后一屏吧？`bypy -e compare | less`呢？
