### ISSUE TITLE
Windows 10 的 bash 中，列出、上載均可，但下載回應沒有權限

### ISSUE THREAD

**Issue by raye1010** [houtianze/bypy#365]
你好，這是我在下載時得到的訊息：

<E> [12:13:52] HTTP Response Status Code: 403
<E> [12:13:52] Error JSON returned:{u'error_code': 4, u'error_msg': u'No permission to do this operation'}
Error code: 4
Error Description: No permission to do this operation
<E> [12:13:52] Website returned: {"error_code":4,"error_msg":"No permission to do this operation"}

列出、上載均可以，但似乎是沒有權限下載，要在那裡設定嗎？

** 我的版本是 bypy v1.5.2，爬文看到好像是回應的 message 大小階的問題，是嗎？

**Comment by houtianze** [comment]
感谢反馈。

请帮忙贴出所用命令（加上`-dv`）和输出，我看一下。我猜是你下载时的路径写错（无须加`/apps/bypy`前缀)

**Comment by raye1010** [comment]
真的嗎！很長耶！

raye@~$ bypy -dv download test.mkv /mnt/c/Users/Raye/Desktop/Download/
<D> [12:27:03] Using requests.packages.urllib3 to disable warnings
Loading Hash Cache File '/home/raye/.bypy/bypy.hashcache.json'...
Hash Cache File '/home/raye/.bypy/bypy.hashcache.json' not found, no caching
----
Verbose level = 1
Debug level = 1
Config directory: '/home/raye/.bypy'
Token file: '/home/raye/.bypy/bypy.json'
Hash Cache file: '/home/raye/.bypy/bypy.hashcache.json'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
sys.stderr.encoding = UTF-8
----

<D> Token loaded:
<D> {u'access_token': u'21.c75bdebafa3aec369c7f7daadb223ccd.2592000.1498276267.540396135-1572671', u'expires_in': 2592000, u'session_secret': u'e5933a6534b19fc4693a806308d1352d', u'scope': u'basic netdisk', u'session_key': u'9mnRJ9C1dHVa4RT+/gKe9f59zhWeziiEi8p+oa1efCPY4UR2tTxMBUqsNXYooX/wRRIKKLZPziOug5WPA3YI+lW5SCFK6Fdv', u'refresh_token': u'22.71304e67358b6e384f509b01fccfbc08.315360000.1811044267.540396135-1572671'}
<D> __get_file_info(): rdir : /apps/bypy | rfile: test.mkv
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/test.mkv
<D> Params: {u'path': u'/apps/bypy', u'order': u'asc', u'method': u'list', u'by': u'name'}
<D> Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=21.c75bdebafa3aec369c7f7daadb223ccd.2592000.1498276267.540396135-1572671&path=%2Fapps%2Fbypy&by=name&order=asc&method=list
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> List json: {u'list': [{u'isdir': 1, u'ctime': 1495684494, u'fs_id': 759044670678431, u'mtime': 1495684494, u'path': u'/apps/bypy/test', u'md5': u'', u'size': 0}, {u'isdir': 0, u'ctime': 1495685504, u'fs_id': 951171181508332, u'mtime': 1495685504, u'path': u'/apps/bypy/app-Eye4-VStarcam.exe', u'md5': u'b2ff8e2b8f743bb58b4543e50d59b6e3', u'size': 6553752}, {u'isdir': 0, u'ctime': 1495685462, u'fs_id': 891008279216162, u'mtime': 1495685462, u'path': u'/apps/bypy/putty.exe', u'md5': u'33c9d1e56152e212367e9c5b01671e45', u'size': 524288}, {u'isdir': 0, u'ctime': 1419429512, u'fs_id': 130388043658392, u'mtime': 1495685021, u'path': u'/apps/bypy/test.mkv', u'md5': u'04a8b8b806764ba5a7f089cfa68e8269', u'size': 326375272}], u'request_id': 3351798991678896073}
<D> File info json: {u'isdir': 0, u'ctime': 1419429512, u'fs_id': 130388043658392, u'mtime': 1495685021, u'path': u'/apps/bypy/test.mkv', u'md5': u'04a8b8b806764ba5a7f089cfa68e8269', u'size': 326375272}
<D> Request all goes fine
<D> Downloading '/apps/bypy/test.mkv' as '/mnt/c/Users/Raye/Desktop/Download/test.mkv'
<D> Getting info of remote file '/apps/bypy/test.mkv' for later verification
<D> __get_file_info(): rdir : /apps/bypy | rfile: test.mkv
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/test.mkv
<D> Params: {u'path': u'/apps/bypy', u'order': u'asc', u'method': u'list', u'by': u'name'}
<D> Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=21.c75bdebafa3aec369c7f7daadb223ccd.2592000.1498276267.540396135-1572671&path=%2Fapps%2Fbypy&by=name&order=asc&method=list
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> List json: {u'list': [{u'isdir': 1, u'ctime': 1495684494, u'fs_id': 759044670678431, u'mtime': 1495684494, u'path': u'/apps/bypy/test', u'md5': u'', u'size': 0}, {u'isdir': 0, u'ctime': 1495685504, u'fs_id': 951171181508332, u'mtime': 1495685504, u'path': u'/apps/bypy/app-Eye4-VStarcam.exe', u'md5': u'b2ff8e2b8f743bb58b4543e50d59b6e3', u'size': 6553752}, {u'isdir': 0, u'ctime': 1495685462, u'fs_id': 891008279216162, u'mtime': 1495685462, u'path': u'/apps/bypy/putty.exe', u'md5': u'33c9d1e56152e212367e9c5b01671e45', u'size': 524288}, {u'isdir': 0, u'ctime': 1419429512, u'fs_id': 130388043658392, u'mtime': 1495685021, u'path': u'/apps/bypy/test.mkv', u'md5': u'04a8b8b806764ba5a7f089cfa68e8269', u'size': 326375272}], u'request_id': 3351799193804617658}
<D> File info json: {u'isdir': 0, u'ctime': 1419429512, u'fs_id': 130388043658392, u'mtime': 1495685021, u'path': u'/apps/bypy/test.mkv', u'md5': u'04a8b8b806764ba5a7f089cfa68e8269', u'size': 326375272}
<D> Request all goes fine
<D> Checking if we already have the copy locally
<D> GET https://d.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/test.mkv', 0, 326375272, 1495686424.588251)
<D> Params: {u'path': u'/apps/bypy/test.mkv', u'method': u'download'}
<D> Full URL: http://nb.cache.baidupcs.com/file/04a8b8b806764ba5a7f089cfa68e8269?bkt=p3-0000c6e4ad6932e57e11a4cedb206a76a651&xcode=daf67b8507b686c1a04eb20ab3238080863b22d6869dab94837047dfb5e85c39&fid=540396135-1572671-130388043658392&time=1495686425&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-Wx9FvRpW91qsLgPgJiHdUH65abo%3D&to=nbc&fm=Qin,B,U,ny&sta_dx=326375272&sta_cs=69&sta_ft=mkv&sta_ct=7&sta_mt=0&fm2=Qingdao,B,U,ny&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=140004a8b8b806764ba5a7f089cfa68e8269112ab69a000013741768&sl=81657935&expires=8h&rt=pr&r=451007826&mlogid=3351799329978388564&vuk=-&vbdid=-&fin=test.mkv&slt=pm&uta=0&rtype=1&iv=0&isw=0&dp-logid=3351799329978388564&dp-callid=0.1.1&hps=1&csl=257&csign=5UComvJADCDBcxKU4Gqb%2Bbp18Bc%3D&by=flowserver
<D> HTTP Status Code: 403
<D> Website returned JSON: {u'error_code': 4, u'error_msg': u'No permission to do this operation'}
<E> [12:27:05] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [12:27:05]
<E> [12:27:05] Function: __downchunks_act
<E> [12:27:05] Website parameters: {u'path': u'/apps/bypy/test.mkv', u'method': u'download'}
<E> [12:27:05] Full URL: http://nb.cache.baidupcs.com/file/04a8b8b806764ba5a7f089cfa68e8269?bkt=p3-0000c6e4ad6932e57e11a4cedb206a76a651&xcode=daf67b8507b686c1a04eb20ab3238080863b22d6869dab94837047dfb5e85c39&fid=540396135-1572671-130388043658392&time=1495686425&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-Wx9FvRpW91qsLgPgJiHdUH65abo%3D&to=nbc&fm=Qin,B,U,ny&sta_dx=326375272&sta_cs=69&sta_ft=mkv&sta_ct=7&sta_mt=0&fm2=Qingdao,B,U,ny&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=140004a8b8b806764ba5a7f089cfa68e8269112ab69a000013741768&sl=81657935&expires=8h&rt=pr&r=451007826&mlogid=3351799329978388564&vuk=-&vbdid=-&fin=test.mkv&slt=pm&uta=0&rtype=1&iv=0&isw=0&dp-logid=3351799329978388564&dp-callid=0.1.1&hps=1&csl=257&csign=5UComvJADCDBcxKU4Gqb%2Bbp18Bc%3D&by=flowserver
<E> [12:27:05] HTTP Response Status Code: 403
<E> [12:27:05] Error JSON returned:{u'error_code': 4, u'error_msg': u'No permission to do this operation'}
Error code: 4
Error Description: No permission to do this operation
<E> [12:27:05] Website returned: {"error_code":4,"error_msg":"No permission to do this operation"}
<E> [12:27:05] Waiting 10 seconds before retrying...

**Comment by houtianze** [comment]
哦，感觉好像是文件被百度屏蔽了。你试试别的文件？

**Comment by raye1010** [comment]
網頁版是能夠下載的，會不會與地區相關？我不在中國內地。

**Comment by houtianze** [comment]
你运行`bypy`和网页下载是不是在同一个机器上面？如果是应该就不是地区问题了。
其他文件有这个问题吗？还只是这个`test.mkv`？

**Comment by raye1010** [comment]
抱歉一直麻煩你，是同一個機器，但 win 10 的 bash 似乎是 win 10 裡面的一個 vm，其他文件都回應這個訊息，我試過上載一個然後下載該個文件，也是回應相同的訊息

**Comment by houtianze** [comment]
不客气。
`全部文件 > 我的應用數據 > bypy`是百度云盘网页版上正确的路径。

所有文件都有这个问题就有点奇怪了。听起来像是百度那边的问题。你有Linux机器吗？上面跑会有这个问题吗？或者有其他地方的机器可以SSH进去？

**Comment by houtianze** [comment]
参见 #368 问题确认，暂时无解。。。 希望百度能尽快修复这个。
