### ISSUE TITLE
关于bypy upload命令疑问

### ISSUE THREAD

**Issue by icehong** [houtianze/bypy#366]
非常感谢 @houtianze  提供了这些方便的上传文件的方式， 非常感谢！
抱歉又来这里提 issue 啦， 因为是这个项目没有邮件列表， 好像没有别的可以提问题的地方.  

我用 bypy -e upload 上传整个目录的时候， 有一些疑问， 所以又来骚扰啦。 百度API 分片上传MD5可能会错误的问题就不说了，  很多其它的项目也都发现有这个问题。  我的问题是: 
1.  有的时候， 我用 bypy -e compare 命令比较， 发现有几个文件md5 不一致，  但是有时候会提示直接调用了 combine 接口，不用重新上传文件， 直接就重新生成md5， 往往这个时候远程服务器上的md5值就正确了，     但是为什么有些其它文件就没有调用combine 接口，    为什么都是在一个目录， 同时刚刚上传过的文件会有这种差异呢，  我理解如果每个差异文件都能走进这个流程， 可能就不用文件重新上传啦。 
2.  有些网站说baidu pcs api 文件分片上传完后重组的这个接口， 是异步的，  就是说那些分片文件可能没有全部存完， 另外一边就启动了md5计算， 导致md5计算错误，  @houtianze 有没有试过， 上传完分片后， 等几秒种再调用 重组接口，  那样可能就能规避这个问题了？    有没有兴趣试试？

**Comment by houtianze** [comment]
不客气，感谢提供进一步的信息。

1. `bypy -e compare`应该会触发`combine`函数，它只是遍历比较。触发`combine`的是`upload`或`syncup`。
再次`upload`或`syncup`有两种场景：
    - 百度已有正确md5但之前返回错误md5: 可以秒传，秒传后可能md5就对了。此情形下不会实际上传，也就不会触发`combine`
    - 百度没有正确的md5：无法秒传，那就会在上传一次，会触发`combine`

2. 有原链接给一下吗？谢。如果是：整个文件`md5`计算是在调用`combine` api时计算的，感觉倒真的是有这个可能。我有时间可能也去试一下（可能不会很快做）。改动很容易：把`bypy.py`的1457-1458的注释符拿掉就可以了（ https://github.com/houtianze/bypy/blob/master/bypy/bypy.py#L1457 ）。如果你有时间愿意测试，可以帮忙试试这样改动之后是不是就没有这个问题了。

**Comment by houtianze** [comment]
哦，想起来：关于2. 那个等待两秒的代码还在是因为好像之前已经试过了，解决不了问题。。。

**Comment by icehong** [comment]
经过最近几天的尝试， 我好像发现这么个规律：
如果不停的用 bypy -e upload 上传整个目录的话， 有md5差异的文件是会不断减少的。 好像是每次第一个有md5差异的总是不再重新上传文件，直接执行combine， 然后就重新生成正确的md5了。    我猜baidu的后台对于分片的临时文件， 可能只针对一个文件， 每次调用 combine（也就是crreatesuperfile接口）后， 这个子目录的其它文件的上次上传的分片文件应该就一并清除了， 所以其它文件内容只能重新上传。 

异步接口的那个描述链接， 我找了很久， 找不到了所以没有附在里面， 也可能是我记错成别的接口了。

如果改成2秒不生效的话，  我想能否改成重试几次， 每次combine 完后，把查询回来的返回值和本地文件比较， 如果md5一致就成功，  不一致的话， 就直接再调用combine接口， 设定最大重新几次， 看看能否返回正确的值。  这样不用重新上传文件，效率应该很高。 
我从来没有写过python代码，  等我看看明白想这样修改试试，  你要有时间也可以改完这样给我测试。

**Comment by houtianze** [comment]
感谢尝试。

不过那个重试`combine`的逻辑，在`bypy -e upload`时已经有了（最多重试五次，重试间隔逐次加长），你如果用`bypy -edv upload`来上传，应该看到那些md5不一致的`combine`都会重试5次（一些`Try 井1/5`这样调试日志输出），所以。。。

**Comment by icehong** [comment]
好吧  ......   
另外最后一个希望，  有关闭分片上传的接口吗？    我的文件都是小于2G的， 所以应该可以不用分片上传， 如果上传时不用这个接口，总不会出错了吧

**Comment by houtianze** [comment]
可以用这个参数：`-s 1T`，把分片设成1T，应该就可以了。不过如果网络不好或者百度那边经常断开，文件有可能5次重试也上传不成功。

**Comment by icehong** [comment]
几个失败的尝试， 仅仅是记录一下 ......  
1.   __upload_file_slices  函数里， 如果组合出来的文件md5错误的话， 等几秒，重新再调用一下组合的接口， 结果返回失败，  原因应该那些文件分片可能已经不存在了。
2.  上传完分片以后， 尝试 等待 60s 再组合文件，  仍然失败
我真实服了baidu的这些接口了。  
3.  更让我伤心的是，  在我准备了要放弃， 加了 -s 1T 参数不使用分片上传接口时， 程序直接返回告诉我raspberry pi 没内存了..........................................................

**Comment by houtianze** [comment]
最后3. 这个有stack/log输出吗？我试着上传了一下`-s 1T`，没出错啊。

**Comment by icehong** [comment]
这个我看了下日志， 是因为没有内存了，   我是要上传一个600MB左右的文件，  盒子应该是只有512M的物理内存， 直接返回失败了，   这个我认了。  

我还有一点疑问，  upload 上传的时候， 我看代码是先用 rapid upload 处理的，  看日志的话，同样是对于远端md5错误的文件， rapid upload 有的时候可以成功，  有的时候就返回文件不存在， 需要重新上传。  如果能摸清这个规律的话，  应该可以在分片上传完成后，  检测到远端md5失败的情况下， 再调用rapid upload 上传一次（在确认不会重新传文件的情况下）。

**Comment by houtianze** [comment]
哦，看了一下`requests`的资料，原来不是流上传而是整个文件载入内存后再上传的。。。 https://stackoverflow.com/q/35779879/404271

秒传这个大概就是我上面帖子说的：
> 1. 百度已有正确md5但之前返回错误md5: 可以秒传，秒传后可能md5就对了。此情形下不会实际上传，也就不会触发combine
> 2. 百度没有正确的md5：无法秒传，那就会在上传一次，会触发combine

**Comment by houtianze** [comment]
哦，还有一个情形：分片上传的分片，算是临时文件，百度那边是有保存期限的（貌似一天这样），有时候速度太慢，分片还没全部传完，可能最早的分片已经被删除了，然后就会合并失败，上传失败。

**Comment by icehong** [comment]
是的，  如果能把握住这个你说的 ‘ 百度已有正确md5但之前返回错误md5 ’ 这个状态， 再秒传一次就能解决这个问题了。  现在好像是没有好的方法检测到什么时候会进入到这个状态。 

上传文件占用内存的问题， 你会按 https://stackoverflow.com/q/35779879/404271  这个描述， 修改成流式上传吗？   到时我倒是可以试一下，   那总算是能解决我的问题了。

**Comment by houtianze** [comment]
改成流上传了，但是没有发布到pypi，你可以git clone最新版，然后在clone目录下运行
`python -m bypy -s1T ...`试试是否解决问题。

**Comment by icehong** [comment]
试了一下新版本  完美解决  wonderful.

**Comment by houtianze** [comment]
感谢测试。发布了最新版1.5.3到pypi，可以直接pip升级了。
026fd0031085c98e64fa57082965e1ea23bada46
