### ISSUE TITLE
bypy list nothing.

### ISSUE THREAD

**Issue by dragon9001** [houtianze/bypy#367]
token认证通过后。 输入bypy list 输出什么都没有

[long@superarch ~]$ bypy list
/apps/bypy ($t $f $s $m $d):
[long@superarch ~]$
[long@superarch ~]$

请问可能的原因有什么？

**Comment by houtianze** [comment]
因为百度权限设置，`bypy`只能访问`/apps/bypy`目录（相当于程序的根目录），要往里面上传东西才行。

**Comment by linux0ne** [comment]
@houtianze 
刚接触这个软件，我没有看懂，你讲得“/app/bypy”目录是哪个目录 ？

我在网页版的云盘里，也没有见到这个名字的目录哇，是需要我在“全部文件”这个目录下建一个/app/bypy名称的目录么？

**Comment by FredyVia** [comment]
我的应用数据 里面
