### ISSUE TITLE
download HTTP 403 error

### ISSUE THREAD

**Issue by dingxm** [houtianze/bypy#368]
使用
bypy -d -v downfile
下载时，出现：
<D> [08:04:02] Using requests.packages.urllib3 to disable warnings
Loading Hash Cache File '/u/home/d/dingxm/.bypy/bypy.hashcache.json'...
Hash Cache File '/u/home/d/dingxm/.bypy/bypy.hashcache.json' not found, no caching
----
Verbose level = 1
Debug level = 1
Config directory: '/u/home/d/dingxm/.bypy'
Token file: '/u/home/d/dingxm/.bypy/bypy.json'
Hash Cache file: '/u/home/d/dingxm/.bypy/bypy.hashcache.json'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
sys.stderr.encoding = UTF-8
----

<D> Token loaded:
<D> {u'access_token': u'21.22a00e45cffb55075f2760f9e64cdc0d.2592000.1498367091.3668432818-1572671', u'expires_in': 2592000, u'session_secret': u'6f99f93c865203390a9e209fe4d44d84', u'scope': u'basic netdisk', u'session_key': u'9mnRdvDF7uGbHU0ow2rCQniKyPW1l/moYlr2rqnVA8/9SChoMxUJvpXb71dXiYtoB7tl8dORt3YbTbR3sK99PNhbaUqDM5WG/A==', u'refresh_token': u'22.88c8380d736eab26d126d392a4a05f12.315360000.1811135091.3668432818-1572671'}
<D> Downloading '/apps/bypy/gaotongl/1Ca_H7V5MALXX_L4_1.fq.gz' as 'Wang_shouhua2_raw_data/1Ca_H7V5MALXX_L4_1.fq.gz'
<D> Getting info of remote file '/apps/bypy/gaotongl/1Ca_H7V5MALXX_L4_1.fq.gz' for later verification
<D> __get_file_info(): rdir : /apps/bypy/gaotongl | rfile: 1Ca_H7V5MALXX_L4_1.fq.gz
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/gaotongl/1Ca_H7V5MALXX_L4_1.fq.gz
<D> Params: {u'path': u'/apps/bypy/gaotongl', u'order': u'asc', u'method': u'list', u'by': u'name'}
<D> Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=21.22a00e45cffb55075f2760f9e64cdc0d.2592000.1498367091.3668432818-1572671&path=%2Fapps%2Fbypy%2Fgaotongl&by=name&order=asc&method=list
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> List json: {u'list': [{u'isdir': 0, u'ctime': 1483693095, u'fs_id': 970699283327990, u'mtime': 1483693095, u'path': u'/apps/bypy/gaotongl/1Ca_H7V5MALXX_L4_1.fq.gz', u'md5': u'13be96a1d0734fa3c6785ddb06dbb4c9', u'size': 73675}, {u'isdir': 0, u'ctime': 1483693095, u'fs_id': 207204666447712, u'mtime': 1483693095, u'path': u'/apps/bypy/gaotongl/1Ca_H7V5MALXX_L4_2.fq.gz', u'md5': u'11c8449ece0a52d9f2bee93f86c941f7', u'size': 85348}, {u'isdir': 0, u'ctime': 1483777319, u'fs_id': 516514071186922, u'mtime': 1483777319, u'path': u'/apps/bypy/gaotongl/1P_H7V5MALXX_L4_1.fq.gz', u'md5': u'beef459c397fdb0050bc16456aaaac59', u'size': 82144800}], u'request_id': 3385251397861065748}
<D> File info json: {u'isdir': 0, u'ctime': 1483693095, u'fs_id': 970699283327990, u'mtime': 1483693095, u'path': u'/apps/bypy/gaotongl/1Ca_H7V5MALXX_L4_1.fq.gz', u'md5': u'13be96a1d0734fa3c6785ddb06dbb4c9', u'size': 73675}
<D> Request all goes fine
<D> Checking if we already have the copy locally
<D> GET https://d.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/gaotongl/1Ca_H7V5MALXX_L4_1.fq.gz', 0, 73675, 1495811044.394337)
<D> Params: {u'path': u'/apps/bypy/gaotongl/1Ca_H7V5MALXX_L4_1.fq.gz', u'method': u'download'}
<D> Full URL: http://nb.cache.baidupcs.com/file/13be96a1d0734fa3c6785ddb06dbb4c9?bkt=p3-140013be96a1d0734fa3c6785ddb06dbb4c97f8fb2b9000000011fcb&xcode=506ff19ba707f1b632374f5226454b20f975e5c56061932c0b2977702d3e6764&fid=3668432818-1572671-970699283327990&time=1495811045&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-4ZdYxc0auh7Co027tek7F6HsXr0%3D&to=nbc&fm=Yan,B,U,ny&sta_dx=73675&sta_cs=26&sta_ft=gz&sta_ct=5&sta_mt=5&fm2=Yangquan,B,U,ny&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=140013be96a1d0734fa3c6785ddb06dbb4c97f8fb2b9000000011fcb&sl=76480590&expires=8h&rt=pr&r=197286124&mlogid=3385251803513325565&vuk=-&vbdid=-&fin=1Ca_H7V5MALXX_L4_1.fq.gz&slt=pm&uta=0&rtype=1&iv=0&isw=0&dp-logid=3385251803513325565&dp-callid=0.1.1&hps=1&csl=80&csign=SifzgOpEehTVCHSIhJGNfccMClU%3D&by=flowserver
<D> HTTP Status Code: 403
<D> Website returned JSON: {u'error_code': 4, u'error_msg': u'No permission to do this operation'}
<E> [08:04:06] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [08:04:06]
<E> [08:04:06] Function: __downchunks_act
<E> [08:04:06] Website parameters: {u'path': u'/apps/bypy/gaotongl/1Ca_H7V5MALXX_L4_1.fq.gz', u'method': u'download'}
<E> [08:04:06] Full URL: http://nb.cache.baidupcs.com/file/13be96a1d0734fa3c6785ddb06dbb4c9?bkt=p3-140013be96a1d0734fa3c6785ddb06dbb4c97f8fb2b9000000011fcb&xcode=506ff19ba707f1b632374f5226454b20f975e5c56061932c0b2977702d3e6764&fid=3668432818-1572671-970699283327990&time=1495811045&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-4ZdYxc0auh7Co027tek7F6HsXr0%3D&to=nbc&fm=Yan,B,U,ny&sta_dx=73675&sta_cs=26&sta_ft=gz&sta_ct=5&sta_mt=5&fm2=Yangquan,B,U,ny&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=140013be96a1d0734fa3c6785ddb06dbb4c97f8fb2b9000000011fcb&sl=76480590&expires=8h&rt=pr&r=197286124&mlogid=3385251803513325565&vuk=-&vbdid=-&fin=1Ca_H7V5MALXX_L4_1.fq.gz&slt=pm&uta=0&rtype=1&iv=0&isw=0&dp-logid=3385251803513325565&dp-callid=0.1.1&hps=1&csl=80&csign=SifzgOpEehTVCHSIhJGNfccMClU%3D&by=flowserver
**<E> [08:04:06] HTTP Response Status Code: 403
<E> [08:04:06] Error JSON returned:{u'error_code': 4, u'error_msg': u'No permission to do this operation'}
Error code: 4**
Error Description: No permission to do this operation
<E> [08:04:06] Website returned: {"error_code":4,"error_msg":"No permission to do this operation"}
<E> [08:04:06] Waiting 10 seconds before retrying...
<E> [08:04:16] Request Try #2 / 5

**Comment by houtianze** [comment]
感谢反馈。

是所有文件都会出现这个错误吗？

与这 #365 类似

**Comment by dingxm** [comment]
所有文件 不论大小 系统是centos7
以前下载一直没有问题 从昨天开始出现问题

**Comment by houtianze** [comment]
那感觉应该是百度那边做了些东西（希望是暂时的bug），看看过几天能恢复不。。

**Comment by ArwinLin** [comment]
我也是 4天了 依然No permission to do this operation

**Comment by houtianze** [comment]
我这里也确认了。。。
搜了一下，感觉可能是百度发布新版本，把之前（14年的）的bug滚进来了。。。：
https://tieba.baidu.com/p/3312148789

其他操作还没发现问题，但现在我也没有解决之道 😞

**Comment by houtianze** [comment]
今天试了一下，发现这个错误程序自动重试几次后是有时候是会成功的（不再返回这个错误），貌似是百度加进来限速的？

**Comment by sunnysunny3145** [comment]
我今天也遇到了这个情况。试了好几次，都没有办法下载。上传到是没有问题。 不知道是不是百度封了这个功能？

**Comment by houtianze** [comment]
这好像是一个悲伤的故事，我刚刚试过，重试5次也解决不了问题。只能等百度发善心修了这个八哥（还是故意放的看门狗？）。在这之前，下载只能用其他方法了。。

**Comment by fanwz** [comment]
近期同遇到这个问题，某些文件死活下不下来，有些就可以。

**Comment by ai-rex** [comment]
同样的问题，概率性可以下载成功

**Comment by justfortooltest** [comment]
我的也是    **No permission to do this operation**

<E> [02:02:40] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [02:02:40] 
<E> [02:02:40] Function: __downchunks_act
<E> [02:02:40] Website parameters: {u'path': u'/apps/bypy/gzl/kargo_images_v1.6.1.tar.gz', u'method': u'download'}
<E> [02:02:40] Full URL: http://qd2.cache.baidupcs.com/file/63212b017fe42cda8fe9297354b9ee55?bkt=p3-0000b356d1849deab4395b04ef6343d65528&xcode=84006b6c869bd0ed4faba90a39c4f05bc4f0b34b1d4db340316128a2cdfcce4d&fid=1781815861-1572671-507828519741737&time=1497376960&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-Q%2FARy5fYEobjvhdwRgneAeaNeKc%3D&to=qc2&fm=Yan,B,T,th&sta_dx=1649533475&sta_cs=22&sta_ft=gz&sta_ct=4&sta_mt=0&fm2=Yangquan,B,T,th&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=0000b356d1849deab4395b04ef6343d65528&sl=83034191&expires=8h&rt=pr&r=104870822&mlogid=3805598847746112446&vuk=-&vbdid=-&fin=kargo_images_v1.6.1.tar.gz&slt=pm&uta=0&rtype=1&iv=0&isw=0&dp-logid=3805598847746112446&dp-callid=0.1.1&hps=1&csl=300&csign=slSB%2FOSzazS66ymnE6TuHLwyuOA%3D&by=flowserver
<E> [02:02:40] HTTP Response Status Code: 403
<E> [02:02:40] Error JSON returned:{u'error_code': 4, u'error_msg': u'No permission to do this operation'}
Error code: 4
Error Description: No permission to do this operation
<E> [02:02:40] Website returned: {"error_code":4,"error_msg":"No permission to do this operation"}
<E> [02:02:40] Waiting 40 seconds before retrying...
<E> [02:03:20] Request Try #5 / 5
<D> GET https://d.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/gzl/kargo_images_v1.6.1.tar.gz', 0, 1649533475, 1497376897.870262)
<D> Params: {u'path': u'/apps/bypy/gzl/kargo_images_v1.6.1.tar.gz', u'method': u'download'}
<D> Full URL: http://qd2.cache.baidupcs.com/file/63212b017fe42cda8fe9297354b9ee55?bkt=p3-0000b356d1849deab4395b04ef6343d65528&xcode=a5fbbafe6c58d0736a35f26d0459ac6fc4f0b34b1d4db340316128a2cdfcce4d&fid=1781815861-1572671-507828519741737&time=1497377001&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-nUctZzXUaed%2BeMCW0ZwbCxgjnHU%3D&to=qc2&fm=Yan,B,T,th&sta_dx=1649533475&sta_cs=23&sta_ft=gz&sta_ct=4&sta_mt=0&fm2=Yangquan,B,T,th&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=0000b356d1849deab4395b04ef6343d65528&sl=83034191&expires=8h&rt=pr&r=721677069&mlogid=3805609736739501783&vuk=-&vbdid=-&fin=kargo_images_v1.6.1.tar.gz&slt=pm&uta=0&rtype=1&iv=0&isw=0&dp-logid=3805609736739501783&dp-callid=0.1.1&hps=1&csl=300&csign=slSB%2FOSzazS66ymnE6TuHLwyuOA%3D&by=flowserver
<D> HTTP Status Code: 403
<D> Website returned JSON: {u'error_code': 4, u'error_msg': u'No permission to do this operation'}
<E> [02:03:21] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [02:03:21] 
<E> [02:03:21] Function: __downchunks_act
<E> [02:03:21] Website parameters: {u'path': u'/apps/bypy/gzl/kargo_images_v1.6.1.tar.gz', u'method': u'download'}
<E> [02:03:21] Full URL: http://qd2.cache.baidupcs.com/file/63212b017fe42cda8fe9297354b9ee55?bkt=p3-0000b356d1849deab4395b04ef6343d65528&xcode=a5fbbafe6c58d0736a35f26d0459ac6fc4f0b34b1d4db340316128a2cdfcce4d&fid=1781815861-1572671-507828519741737&time=1497377001&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-nUctZzXUaed%2BeMCW0ZwbCxgjnHU%3D&to=qc2&fm=Yan,B,T,th&sta_dx=1649533475&sta_cs=23&sta_ft=gz&sta_ct=4&sta_mt=0&fm2=Yangquan,B,T,th&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=0000b356d1849deab4395b04ef6343d65528&sl=83034191&expires=8h&rt=pr&r=721677069&mlogid=3805609736739501783&vuk=-&vbdid=-&fin=kargo_images_v1.6.1.tar.gz&slt=pm&uta=0&rtype=1&iv=0&isw=0&dp-logid=3805609736739501783&dp-callid=0.1.1&hps=1&csl=300&csign=slSB%2FOSzazS66ymnE6TuHLwyuOA%3D&by=flowserver
<E> [02:03:21] HTTP Response Status Code: 403
<E> [02:03:21] Error JSON returned:{u'error_code': 4, u'error_msg': u'No permission to do this operation'}
Error code: 4
Error Description: No permission to do this operation
<E> [02:03:21] Website returned: {"error_code":4,"error_msg":"No permission to do this operation"}
<E> [02:03:21] Maximum number (5) of tries failed.

**Comment by shaozu** [comment]
同样的问题。。

**Comment by michael3770** [comment]
我也有同样的问题

<E> [21:50:19] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [21:50:19] 
<E> [21:50:19] Function: __downchunks_act
<E> [21:50:19] Website parameters: {u'path': u'/apps/bypy/Kong.Skull.Island.2017.1080p.BluRay.x264.DTS-HD.MA.7.1-FGT/Kong.Skull.Island.2017.1080p.BluRay.x264.DTS-HD.MA.7.1-FGT.mkv', u'method': u'download'}
<E> [21:50:19] Full URL: http://nb.cache.baidupcs.com/file/c9334b6adec702ed1179e210b7cd1cdd?bkt=p3-00001374c874a3a89dd4244a854fe53b12ab&xcode=ff1e3adb8ea72ce86f05a87b9572c54be0f8428f6f1d7db1&fid=3963397560-1572671-984324808006316&time=1500241818&sign=FDTAXGERBH-DCb740ccc5511e5e8fedcff06b081203-DWPi%2FRLH%2BoXTSKcKNokScqZaeQg%3D&to=nbc&fm=Yan,B,U,ny&sta_dx=11786308490&sta_cs=21&sta_ft=mkv&sta_ct=0&sta_mt=0&fm2=Yangquan,B,U,ny&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=00001374c874a3a89dd4244a854fe53b12ab&expires=8h&rt=pr&r=357017248&mlogid=4574628202306085547&vuk=-&vbdid=-&fin=Kong.Skull.Island.2017.1080p.BluRay.x264.DTS-HD.MA.7.1-FGT.mkv&slt=pm&uta=0&rtype=1&iv=0&isw=0&dp-logid=4574628202306085547&dp-callid=0.1.1&hps=1&csl=0&csign=TEXbDriRnvOMXarAK5QemFHKJf8%3D&by=flowserver
<E> [21:50:19] HTTP Response Status Code: 403
<E> [21:50:19] Error JSON returned:{u'error_code': 4, u'error_msg': u'No permission to do this operation'}
Error code: 4
Error Description: No permission to do this operation
<E> [21:50:19] Website returned: {"error_code":4,"error_msg":"No permission to do this operation"}
<E> [21:50:19] Waiting 40 seconds before retrying...
<E> [21:50:59] Request Try #5 / 5

**Comment by syg5201314** [comment]
# 没人维护了吗??我这也有这个问题
<E> [11:30:08] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [11:30:08] Function: __downchunks_act
<E> [11:30:08] Website parameters: {u'path': u'/apps/bypy/android-4.2.2_r1.7z', u'method': u'download'}
<E> [11:30:08] Full URL: http://219.144.69.88/d1.baidupcs.com/file/e8f0f13d2870b32706fb886fd11486fb?bkt=p3-0000528eef354a427445fda4138c9c454e9e&xcode=a40891d11509ace5efa9216dfc66b8e3f8f3c1b120adcf8c0b2977702d3e6764&fid=1090824986-1572671-107045807439649&time=1500521408&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-YQFFLTTWrJ4p6AqN2TIA5gEgmlI%3D&to=lc&fm=Nan,B,T,ny&sta_dx=1853982185&sta_cs=78&sta_ft=7z&sta_ct=7&sta_mt=0&fm2=Nanjing02,B,T,ny&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=0000528eef354a427445fda4138c9c454e9e&sl=76480590&expires=8h&rt=pr&r=511402102&mlogid=4649680137831473687&vuk=-&vbdid=-&fin=android-4.2.2_r1.7z&slt=pm&uta=0&rtype=1&iv=0&isw=0&dp-logid=4649680137831473687&dp-callid=0.1.1&hps=1&csl=80&csign=SifzgOpEehTVCHSIhJGNfccMClU%3D&by=flowserver&wshc_tag=0&wsts_tag=597023c0&wsid_tag=8bc47b6e&wsiphost=ipdbm
<E> [11:30:08] HTTP Response Status Code: 403
<E> [11:30:08] Error JSON returned:{u'error_code': 4, u'error_msg': u'No permission to do this operation'}
Error code: 4
Error Description: No permission to do this operation
<E> [11:30:08] Website returned: {"error_code":4,"error_msg":"No permission to do this operation"}
<E> [11:30:08] Waiting 10 seconds before retrying...

**Comment by houtianze** [comment]
@sunnysunny3145 看下上面我的评论——问题在百度，他们不改或故意为之的话，客户端无能为力。

**Comment by gocoolshj4** [comment]
我去啊，我也是不能下载，不会真的是百毒把第三方下载给封了吧 ，可恶啊

**Comment by laixintao** [comment]
我也遇到了同样的问题……

**Comment by liankun1994** [comment]
希望只是BUG…

**Comment by laixintao** [comment]
应该不是，百度这种垃圾公司api都没得一个还限速，吃枣药丸，现在App Store可以订阅google drive了，已入google drive。

**Comment by korewayume** [comment]
我也遇到了同样的问题
```bash
wget https://pcs.baidu.com/rest/2.0/pcs/file?method=download&access_token=${access_token}&path=/apps/bypy/cudnn-8.0-linux-x64-v7.tgz
```
这样没问题
但是用`bypy download`就会出现`{"error_code":4,"error_msg":"No permission to do this operation"}`

**Comment by houtianze** [comment]
> 我也遇到了同样的问题
> 
> wget https://pcs.baidu.com/rest/2.0/pcs/file?method=download&access_token=${access_token}&path=/apps/bypy/cudnn-8.0-linux-x64-v7.tgz
> 这样没问题
> 但是用bypy download就会出现{"error_code":4,"error_msg":"No permission to do this operation"}

感谢提供信息，如果是这样那可能是`bypy`自身问题。如果用`bypy --downloader aria2`来下载会有403问题吗？ @korewayume

**Comment by kanghua309** [comment]
allall01.baidupcs.com 也不行了

**Comment by korewayume** [comment]
```bash
[root@vps1 ~]# bypy upload test.py
[root@vps1 ~]# rm test.py
rm：是否删除普通文件 "test.py"？y
[root@vps1 ~]# bypy --downloader aria2 download test.py o.py
<E> [09:49:34] Exception occurred:
Exception:
<type 'exceptions.OSError'> - [Errno 2] No such file or directory
Stack:
  File "/root/.pyenv/versions/2.7.13/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/bypy/bypy.py", line 3674, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/bypy/util.py", line 73, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Abort
Traceback (most recent call last):
  File "/root/.pyenv/versions/2.7.13/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/bypy/bypy.py", line 3657, in main
    result = getattr(by, args.command[0])(*uargs)
  File "/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/bypy/bypy.py", line 2266, in download
    return self.downfile(remotepath, localpath)
  File "/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/bypy/bypy.py", line 2088, in downfile
    return self.__downfile(pcsrpath, localfile)
  File "/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/bypy/bypy.py", line 2053, in __downfile
    result = self.__down_aria2c(rfile, localfile)
  File "/root/.pyenv/versions/2.7.13/lib/python2.7/site-packages/bypy/bypy.py", line 1907, in __down_aria2c
    subret = subprocess.call(cmd)
  File "/root/.pyenv/versions/2.7.13/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/root/.pyenv/versions/2.7.13/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/root/.pyenv/versions/2.7.13/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[root@vps1 ~]#
```
用`bypy --downloader aria2`会出现异常，不知道我是不是用错了

**Comment by zhangysh1995** [comment]
```
zhangyushandeMacBook-Pro:Out KellyZhang$ bypy downdir KLEE
<E> [18:04:42] Waiting 10 seconds before retrying...
<E> [18:04:52] Request Try #2 / 5
<E> [18:04:53] Waiting 20 seconds before retrying...
<E> [18:05:13] Request Try #3 / 5
<E> [18:05:14] Waiting 30 seconds before retrying...
^CSignal 2 received, Abort
```

downdir download downfile 全都是一直重试。

**Comment by jtliaw** [comment]
目前无法使用了！百度限制住家ip使用pcs端口了！
经测试使用手机的移动数据能正常下载，住家wifi则完全无法链接（任何一带的住家wifi），只有不断的重试！其他同样使用pcs端口的百度客户端都同样无法登入！

**Comment by laixintao** [comment]
垃圾百度

**Comment by jtliaw** [comment]
我是国外用户，百度完全封锁了我国的住家ip登入，连游览器也不能登入百度网盘！然而我发现了绕过百度封锁的方法！
百度的封锁只是单纯的使我们无法使用住家ip登入而已，一旦登入了就能继续使用住家ip下载了！
所以我的方法是使用手机移动数据共享给电脑，当bypy开始下载时换回住家ip就能继续下载！

**Comment by jtliaw** [comment]
我这里已经可以重新使用bypy下载了！

**Comment by xiaxilin** [comment]
还是不行，垃圾百度！

**Comment by youqingxiaozhua** [comment]
北京鹏博士还是不行...

**Comment by lisupro** [comment]
有可能是bypy 云目录上有空文件 或者只有几个byte的文件会出现这种情况。  我干掉了这这样几个文件后，下载就正常了

**Comment by jimi1998** [comment]
我的也是和楼上一样的情况 我把几个字节的删掉以后就解决了

**Comment by houtianze** [comment]
@lisupro 
还有这种操作？。。。感谢提供信息。

**Comment by htc502** [comment]
测试楼上操作无效。。

**Comment by zinking** [comment]
@jtliaw 多谢， Linode上同步使用mirror亲测可用。  删掉空文件之类的黑魔法没有卵用。

**Comment by yucongo** [comment]
貌似前面加 `bypy  --select-fastest-mirror  syncdown` 有帮助

**Comment by lluxury** [comment]
限制大小了吧, 几M的可以,估计是大了要用他自家的客户端

**Comment by joyneop** [comment]
类似的问题。

```
Hash Cache File loaded.
Gathering local directory ...
Done
Gathering remote directory ...
Done
Comparing ...
Done
<I> [16:16:27] Local and remote file size DOESN'T match
<E> [16:16:29] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [16:16:29] Function: __downchunks_act
<E> [16:16:29] Website parameters: {u'path': u'/apps/bypy/somefile.rar', u'method': u'download'}
<E> [16:16:29] Full URL: http://112.84.34.46/r/d1.baidupcs.com/file/6ff83013684b242d546c7c7e8e850709?bkt=p3-000028ab0169b385b138a2cb3a80fb9f4008&xcode=9f4638cdaab24a4d0b6a3c8ae8943ee228cbec93797213a1316128a2cdfcce4d&fid=2753526547-1572671-222857784821151&time=1513872988&sign=FDTAXGERLBH-DCb740ccc5511e5e8fedcff06b081203-dHDbNdwkK5ETDaahaLatoIt92c0%3D&to=lc&fm=Nan,B,U,nc&sta_dx=2815315324&sta_cs=118&sta_ft=rar&sta_ct=5&sta_mt=0&fm2=Nanjing02,B,U,nc&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=000028ab0169b385b138a2cb3a80fb9f4008&sl=79364174&expires=8h&rt=pr&r=677243346&mlogid=8233717613294720335&vuk=-&vbdid=-&fin=somefile.rar&slt=pm&uta=0&rtype=1&iv=0&isw=0&dp-logid=8233717613294720335&dp-callid=0.1.1&hps=1&csl=100&csign=3jGVYYASHQbhGvneTvxf2DSEuc8%3D&by=flowserver
<E> [16:16:29] HTTP Response Status Code: 403
<E> [16:16:29] Error JSON returned:{u'error_code': 4, u'error_msg': u'No permission to do this operation'}
Error code: 4
Error Description: No permission to do this operation
<E> [16:16:29] Website returned: {"error_code":4,"error_msg":"No permission to do this operation"}
<E> [16:16:29] Waiting 10 seconds before retrying...
<E> [16:16:39] Request Try #2 / 5
```

网络环境：广东联通 4G。

如果换个思路，破解百度网盘客户端并模拟呢？
