### ISSUE TITLE
上传视频文件时,md5基本都会出错

### ISSUE THREAD

**Issue by cnritng** [houtianze/bypy#369]
同个文件本地和云端的文件md5值不一致,但文件大小却是一致的

ping服务器相关信息
PING c.pcs.baidu.com (117.185.17.109) 56(84) bytes of data.
64 bytes from c.pcs.baidu.com (117.185.17.109): icmp_seq=1 ttl=53 time=203 ms
64 bytes from c.pcs.baidu.com (117.185.17.109): icmp_seq=2 ttl=53 time=203 ms
64 bytes from c.pcs.baidu.com (117.185.17.109): icmp_seq=3 ttl=53 time=203 ms
64 bytes from c.pcs.baidu.com (117.185.17.109): icmp_seq=4 ttl=53 time=203 ms
64 bytes from c.pcs.baidu.com (117.185.17.109): icmp_seq=5 ttl=53 time=203 ms
64 bytes from c.pcs.baidu.com (117.185.17.109): icmp_seq=6 ttl=53 time=203 ms
64 bytes from c.pcs.baidu.com (117.185.17.109): icmp_seq=7 ttl=53 time=203 ms
^C
--- c.pcs.baidu.com ping statistics ---
7 packets transmitted, 7 received, 0% packet loss, time 6008ms
rtt min/avg/max/mdev = 203.499/203.652/203.915/0.563 ms

PING pcs.baidu.com (117.185.16.59) 56(84) bytes of data.
64 bytes from pcs.baidu.com (117.185.16.59): icmp_seq=1 ttl=53 time=192 ms
64 bytes from pcs.baidu.com (117.185.16.59): icmp_seq=2 ttl=53 time=190 ms
64 bytes from pcs.baidu.com (117.185.16.59): icmp_seq=3 ttl=53 time=191 ms
64 bytes from pcs.baidu.com (117.185.16.59): icmp_seq=4 ttl=53 time=190 ms
64 bytes from pcs.baidu.com (117.185.16.59): icmp_seq=5 ttl=53 time=192 ms
64 bytes from pcs.baidu.com (117.185.16.59): icmp_seq=6 ttl=53 time=191 ms
64 bytes from pcs.baidu.com (117.185.16.59): icmp_seq=7 ttl=53 time=191 ms
^C
--- pcs.baidu.com ping statistics ---
7 packets transmitted, 7 received, 0% packet loss, time 6009ms
rtt min/avg/max/mdev = 190.861/191.624/192.434/0.672 ms

部分文件上传日志:
<D> Slice MD5 match, continuing next slice
[===================_] 99% (1.4GB/1.4GB) ETA: 14s (382kB/s, 1h2m gone) <D> Updating slice upload progress for /mnt/volume-sfo2-01/dir/file.ts
<D> Uploading MD5 slice: 786bdf1f7b80cc4cf33e121df061007c, #71 / 71
<D> POST https://c.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/file.ts
<D> Params: {'method': 'upload', 'type': 'tmpfile'}
<D> Full URL: https://c.pcs.baidu.com/rest/2.0/pcs/file?method=upload&type=tmpfile&access_token=token
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> Uploaded MD5 slice: 786bdf1f7b80cc4cf33e121df061007c
'/mnt/volume-sfo2-01/dir/file.ts' >>==> '/apps/bypy/file.ts' OK.
<D> Request all goes fine
<D> Slice MD5 match, continuing next slice
[====================] 100% (1.4GB/1.4GB) ETA:  (382kB/s, 1h2m gone) <D> Updating slice upload progress for
 /mnt/volume-sfo2-01/dir/file.ts
Combining the following MD5 slices:
5f718797119946da7402de954a1f445d
5257bf4839a4e20608c6471604eeac0a
ade0440090135d552fae00da9be191bc
7ad77ffffe0057b6d63e55e68eecf24a
4caa2d63aa92282a633d319b048a79e4
37cc01e262ccedc8ad1f887dfe53c822
3cfe43e428b7865967ecd3b12ac85fa1
34cb9d9105ed61a12b478ed95bafce7d
17403742aaca5c54dfe4d6cf3cc24fc7
27e03a343ffda6670510721f17c148dd
942cabac03f52dd213d49880c954754a
7c0647250af9d82120d155b4be50584d
e07bcd73778146bfa7541cc922b554d6
e5d16be7f64d69bfddb287d6c5440d44
64cb243e6432d94219d3d37993bf4e4b
ab70a60b637a405ab53dc130f946ae07
f10e4ef804bbeb3560e02da470f44d3a
dbed40f9a0f5325f941deed24bedde6c
3ce77cac481b61b18870d67d2b42cbd7
640a0416fa0fd0da301c159edc75589e
badc35dc5dd7ea8e6fb622a52f8ae10c
164b85c58513434bdcdcc639c39bc35a
afd9dc9f44ba7027cf990375cfc350da
cd36050cd4a4bb2f54f2c3aae5d8387b
e6e8c7450e2d1450db29bd9b825c3d9a
c96c68378cf19996ca0374f5158f8847
fd382c0c39ff5e779a45b3114d8173ba
1d3196b76213fc19929d859cc9ddbaa3
f21a03f8f842482344b162a187103c78
3c1e0cf332a512568339e15c0a769270
d06663e4861ad3a84931881267ad076a
291790852e8eb9883e98789e06b2588b
39f0c8b885399ecf1b2c42b16a12220b
9508cf7ac7983e38c78447d2bf2266ef
2a74e0769c5b1af3ab11f6918e814696
68f655093d40aef9feb24bba1ae5daaf
a1736833c617617e00a36990f30aa53d
e0595b670149655612863d350dfb03a0
b53a14f58a427b54635ba22a61d11e5f
09773ca565c9ed4989b7dbc8d5b4971a
9f9cd681d13a90f05c1eac98cf305d84
f824655582a6c279619bea6febb53780
d77a400189fa98c8be27ab7cb370889f
413eeb29754fcb4a5ed6f92dcdc7b315
d547fd7d9877d96a7e97d4a844ebcdc5
4b0c185136845951a089d8503f3f301a
38a9a1be4174ba4aad964af25ffe654a
fc22c375c7ace75c97849123a9415616
703fc512dd32fe6a65c0e969e08f3851
8857b8a7fdd4e378ff154847df3c525b
f02a7bb8380d89940df78c35b21929ac
6e7677be095fcdee9e7a6263162e20fd
28703d48cee278f883330f27122fe5a3
378991260e95534b25cc5c995425644e
95add8f6f49e805819dd36295a7c0f72
6258248921f46d97c8e0fb79ba675385
26908703cea1675120db5d80f3a8d628
e1c12c788d7b012e9c9d2365e8c71254
faf6bb106ec418c3b3602609a43f07a6
2833fca840d9ede6673cf843ee4b4427
4fc9a14e8be43fbdc83c3f05aa766e55
c24c4a2326d1ef5e60d400473bf4c361
771f5bbf24adf045926c3a5968f74fe5
c64c5d7736120432fe671e292438f0f1
b342f0ffaf05fb91d4dfef1e7dbfd52c
948cf8c8b4c161470f6b72feb1bdce36
68d4f20b946ae580d82af9814c09c391
7774e8da7af5721abfcce8a11f726ddc
04552df0b2dc7f22a08f432c47254e28
109a6aa788c5ace81e707c13b8485738
786bdf1f7b80cc4cf33e121df061007c
<D> POST https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: /apps/bypy/file.ts
<D> Params: {'method': 'createsuperfile', 'path': '/apps/bypy/file.ts', 'ondup'
: 'overwrite'}
<D> Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?method=createsuperfile&path=%2Fapps%2Fbypy%2Ffile.ts&ondup=overwrite&access_token=token
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> Comparing local file '/mnt/volume-sfo2-01/dir/file.ts' and remote file '/ap
ps/bypy/file.ts'
<D> Local file size : 1473727864
<D> Remote file size: 1473727864
<D> Local and remote file size matches
'/mnt/volume-sfo2-01/dir/file.ts' =C=> '/apps/bypy/file.ts' OK.
<D> Request all goes fine
<D> Removing slice upload progress for /mnt/volume-sfo2-01/dir/file.ts

运行 bypy list
F file.ts 1473683308 2017-06-01, 21:28:54 b9d13a248dd3f129335efd4a7c64aeaa

运行md5sum file.ts
7f98eecf60f8126df0cad19f6b0057ce  file.ts

几乎所有的文件都是这样
可能要重传好几遍才能得到一致的md5值

**Comment by icehong** [comment]
呵呵   参见  #366

**Comment by houtianze** [comment]
嗯，和366是同一个问题。因为毛病出在百度端，没有特别好的解决方法，可以：
- 上传几遍，直到百度返回的md5正确（我自己测试的几十兆文件再传一次（秒传）就OK了。其实一般情况下，只要上传完，文件正确性基本就没有问题，只是这个返回不正确的MD5有点让人不放心，特别是重要文件）
- 像336里面那样加(`-s1T`停用分片上传，据反馈一次传完，MD5就正确了）。不过你首先要升级到最新版`1.5.3`（以前的版本会出现内存不够的错误而退出），然后你的网络要比较好而且百度服务器不要经常返回错误，否者5次重试也没传成的话就很郁闷了。
