### ISSUE TITLE
过大文件Syncup第二次无法秒传

### ISSUE THREAD

**Issue by DCsunset** [houtianze/bypy#376]
对于比较大的文件，例如几百M，上传时间半小时以内，第二次syncup可以秒传。
但是对于更大的文件，例如1G左右，上传时间大约1小时，第二次syncup会导致全部重新上传

十分感谢

**Comment by houtianze** [comment]
感谢反馈。

这个和 #361 基本是同一个问题，原因应该是百度那边的问题，目前没太好的解决方案。你可以参考一下那个issue。一个workaround是用`-s1T`参数，禁掉分片上传，前提是网络流畅，不会有太多重试。
