### ISSUE TITLE
请问作为包使用怎么起步？

### ISSUE THREAD

**Issue by korosu** [houtianze/bypy#378]
想结合其他工具一起使用
国外党对百度盘实在无力 只能借用VPS转存国外网盘
因为空间很小想弄个bypy下载完一个文件后上传到国外网盘删除本地继续下载如此重复

瞎折腾半天后猜主要猜函数应该是>>>from bypy.bypy import ByPy这样？
可是
>>> ByPy.list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: list() missing 1 required positional argument: 'self'

每个函数都缺少self的是什么？怎么解决？
已经在独立使用模式下授权，难道作为包要另外授权？

**Comment by houtianze** [comment]
刚刚在`README.md`里加入了简单的调用范例：

```python
from bypy import ByPy
bp=ByPy()
bp.list() # or whatever instance methods of ByPy class
```
调用`ByPy`实例的方法（例如`list()`）和直接在命令行下输入命令`bypy list`几乎是一样的效果，无需另外授权。可以产考一下`test/test.py`里的代码。

**Comment by korosu** [comment]
谢谢！
