### ISSUE TITLE
运行多个bypy,会出现所有bypy停止上传的情况

### ISSUE THREAD

**Issue by cnritng** [houtianze/bypy#379]
版本1.5.7, 内存1G,加了-dv参数,发现log一直没刷新,用nload看网络流量发现也没有了,重新运行bypy才会重新上传,难道是同时只能运行一个或两个bypy?

**Comment by houtianze** [comment]
感谢反馈。

试了一下，运行两个同时上传没有问题。你是几个bypy同时运行？程序本身并没有对运行多个实例做任何限制，如果出现这种情况，我才很可能是百度服务器那边做了检测，停止/阻塞返回数据了。

**Comment by cnritng** [comment]
1.5.11又出现了,可以增加检测机制吗?

**Comment by houtianze** [comment]
不好意思才回复。

这个应该是百度服务端的限制/限流，客户端我觉得基本没有什么办法能解决。。。
