### ISSUE TITLE
pkg_resources.VersionConflict

### ISSUE THREAD

**Issue by rogue1228** [houtianze/bypy#380]
Traceback (most recent call last):
  File "/usr/local/bin/bypy", line 7, in <module>
    from bypy.bypy import main
  File "/usr/local/bin/bypy.py", line 5, in <module>
    pkg_resources.run_script('bypy==1.0.17', 'bypy.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (bypy 1.5.7 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('bypy==1.0.17'))

In python3, an error occurs when executed with 'bypy [command]' command.

**Comment by houtianze** [comment]
Your version of `bypy` seems very low (1.0.17), can you try upgrade to the latest version (`pip install -U bypy`) and try again?

**Comment by houtianze** [comment]
I think maybe your Python2/Python3 `bypy` installation interwove - probably you installed some old version of `bypy` using Python2 pip, then you installed using Python 3 pip. I think the following should solve the problem:
- Uninstall existing `bypy` in both Python 3 and Python 2
- Install the latest version of `bypy` in Python3 **or** Python 2

Or you can use `virutalenv` to avoid the version mess.

**Comment by rogue1228** [comment]
The same error occurs. I used 'virtualenv'.
I think new config file has not overwrite old config file.

**Comment by houtianze** [comment]
But the log shows clearly that `bypy` was called from `/usr/local/bin/`, so I don't think it's like that `virtualenv` has been activated. Another point I don't understand is: the log also shows it's calling Python 2 installations, why do you think this is a problem in Python 3?

There is no config file to overwrite during installation, only the `bypy` wrapper script is generated from `setup.py`.

**Comment by houtianze** [comment]
Have you followed my first comment to uninstall all the existing `bypy` (both Python 2 & 3) and install cleanly for only one version of Python (2 **or** 3)?

**Comment by rogue1228** [comment]
There was an old version `bypy.py` file in the `/usr/local/bin/` path.
I deleted it and it works.

**Comment by houtianze** [comment]
I see, right. I didn't spot this line in the log:
`File "/usr/local/bin/bypy.py", line 5, in `

That `bypy.py` is the residue of some quite old version.
