### ISSUE TITLE
Website returned: {"error_code":4,"error_msg":"No permission to do this operation"}

### ISSUE THREAD

**Issue by hbhdwxf** [houtianze/bypy#381]
> 

> 当我后台执行：`bypy syncdown /  ./  True  -ddd `

> 时有些文件不能正常同步下来，我原以为只是偶然现象，但多次测试之后才发现不是的，更换不同的目录每次都有一些文件无法同步下来，而功能类似的download参数命令也有同样的问题 ，而这些不能download下来的文件我用bcloud client是可以正常下载来下的，我用的账号都是同一个账号，不存在权限不同的问题

> 而运行`bypy syncup /  ./  True  -ddd `则没有问题，都可以顺利同步上去
我把执行syncdown执行的报错贴上来：
<D> Full URL: http://220.243.253.28/hd.baidupcs.8686c.com/file/bbb8aae57c104cda40c93843ad5e6db8?bkt=p3-1400bbb8aae57c104cda40c93843ad5e6db831ea6fef000000000009&xcode=fbe84f0b488c50a52c5834339d624e57f7be55e5c1bfe8fc&fid=1040319784-1572671-465268913733698&time=1498198395&sign=FDTAXGERBH-DCb740ccc5511e5e8fedcff06b081203-HT2xgCoNEDJF3rJZbxKIck5%2FAqs%3D&to=qhb8&fm=Yan,B,U,ny&sta_dx=9&sta_cs=53&sta_ft=txt&sta_ct=0&sta_mt=0&fm2=Yangquan,B,U,ny&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400bbb8aae57c104cda40c93843ad5e6db831ea6fef000000000009&expires=8h&rt=pr&r=205001012&mlogid=4026100908238286487&vuk=-&vbdid=-&fin=%E6%96%B0%E5%BB%BA%E6%96%87%E6%9C%AC%E6%96%87%E6%A1%A3.txt&slt=solvecenter_whitelist&uta=0&rtype=1&iv=0&isw=0&dp-logid=4026100908238286487&dp-callid=0.1.1&hps=1&csl=0&csign=TEXbDriRnvOMXarAK5QemFHKJf8%3D&by=flowserver&wsiphost=local
<D> HTTP Status Code: 403
<D> Website returned JSON: {u'error_code': 4, u'error_msg': u'No permission to do this operation'}
<E> [14:13:15] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [14:13:15] 
<E> [14:13:15] Function: __downchunks_act
<E> [14:13:15] Website parameters: {u'path': u'/apps/bypy/\u65b0\u5efa\u6587\u672c\u6587\u6863.txt', u'method': u'download'}
<E> [14:13:15] Full URL: http://220.243.253.28/hd.baidupcs.8686c.com/file/bbb8aae57c104cda40c93843ad5e6db8?bkt=p3-1400bbb8aae57c104cda40c93843ad5e6db831ea6fef000000000009&xcode=fbe84f0b488c50a52c5834339d624e57f7be55e5c1bfe8fc&fid=1040319784-1572671-465268913733698&time=1498198395&sign=FDTAXGERBH-DCb740ccc5511e5e8fedcff06b081203-HT2xgCoNEDJF3rJZbxKIck5%2FAqs%3D&to=qhb8&fm=Yan,B,U,ny&sta_dx=9&sta_cs=53&sta_ft=txt&sta_ct=0&sta_mt=0&fm2=Yangquan,B,U,ny&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400bbb8aae57c104cda40c93843ad5e6db831ea6fef000000000009&expires=8h&rt=pr&r=205001012&mlogid=4026100908238286487&vuk=-&vbdid=-&fin=%E6%96%B0%E5%BB%BA%E6%96%87%E6%9C%AC%E6%96%87%E6%A1%A3.txt&slt=solvecenter_whitelist&uta=0&rtype=1&iv=0&isw=0&dp-logid=4026100908238286487&dp-callid=0.1.1&hps=1&csl=0&csign=TEXbDriRnvOMXarAK5QemFHKJf8%3D&by=flowserver&wsiphost=local
<E> [14:13:15] HTTP Response Status Code: 403
<E> [14:13:15] Error JSON returned:{u'error_code': 4, u'error_msg': u'No permission to do this operation'}
Error code: 4
Error Description: No permission to do this operation
<E> [14:13:15] Website returned: {"error_code":4,"error_msg":"No permission to do this operation"}
<E> [14:13:15] Waiting 40 seconds before retrying...
<E> [14:13:55] Request Try #5 / 5
<D> GET https://d.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/\u65b0\u5efa\u6587\u672c\u6587\u6863.txt', 0, 9, 1498198330.314429)

**Comment by houtianze** [comment]
感谢反馈。

最近百度PCS服务器那边的问题，和 #368 是一样，暂时无解。。。
bcloud应该是直接用的baidu web api，所以不受影响。
