### ISSUE TITLE
syncdown -Maxium number (5) of tries failed.

### ISSUE THREAD

**Issue by HXDAI** [houtianze/bypy#382]
Run syncdown  always ended up with 'Maxium number (5) of tries failed.'.  But run list, info both are fine?
<D> HTTP status code:206
<D> 206 Partial Content (this is OK) , processing action
<E> Maxium number (5) of tries failed.

**Comment by HXDAI** [comment]
The file was blocked by Baidu from downloading.

**Comment by houtianze** [comment]
Yes, it's the same as the one reported in #368 .
It's indeed very frustrating, as nothing we can do here..
