### ISSUE TITLE
windows 如何修改 System Locale to utf-8

### ISSUE THREAD

**Issue by lovelori** [houtianze/bypy#385]
跑不起来，要求修改System Locale ,找不到windows10的修改方法

**Comment by houtianze** [comment]
什么样的错误，贴个日志？

**Comment by lovelori** [comment]
不是错误，是提示要求修改编码，如下，不知道windows该怎么改
`PS C:\Users\cdcd> bypy list
<W> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
<W> You are running Python on Windows, which doesn't support Unicode so well
Files with non-ASCII names may not be handled correctly.
<W> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
<W> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
<W> WARNING: System locale is not 'UTF-8'.
Files with non-ASCII names may not be handled correctly.
You should set your System Locale to 'UTF-8'.
Current locale is 'cp936'
<W> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/apps/bypy ($t $f $s $m $d):`

**Comment by houtianze** [comment]
哦，这两个都是警告。

Windows下我没找到办法把Python运行环境下的Locale变成能使用的`UTF-8`，所以貌似无解。如果没有非ASCII字符的文件/目录名，应该没有什么影响；如果有程序会出错退出。这个警告就是讲这个。（第二个警告是程序后面检测触发的，有了第一个警告，可以忽略了）

**Comment by lovelori** [comment]
好的，多谢
