### ISSUE TITLE
请问能否通过requests[socks] 来支持socks5代理

### ISSUE THREAD

**Issue by mengyyy** [houtianze/bypy#387]
个人小鸡比较渣 就算下载前测速选择 实际下载速度也只有100K/S的样子
手头有国内代理但却是socks5的 
不知道要是通过国内代理下载是否能有效改善这个问题～～

**Comment by houtianze** [comment]
感谢建议。

搜了一下：
http://docs.python-requests.org/en/master/user/advanced/#socks
https://stackoverflow.com/a/15661226/404271

`requests`2.10.0以后的版本应该是支持socks代理了。
- 先装`pysocks`:
```bash
pip install requests[socks]
```
- 配置环境变量：
```bash
export HTTP_PROXY="socks5://user:pass@host:port"
export HTTPS_PROXY="socks5://user:pass@host:port"
```
按理再跑`bypy`就会用代理了。
不过，我怀疑速度可能还是快不了太多。
