### ISSUE TITLE
运行 downdir / 一直出错啊，

### ISSUE THREAD

**Issue by moerfutin** [houtianze/bypy#389]
如图 
![image](https://user-images.githubusercontent.com/9960618/28929837-a0378016-78a3-11e7-84b1-3c5cb66096bb.png)

如果是bypy downdir /apps/bypy/'[高清动画合集]Animation.BluRay.720P.高清片源 无字幕.Pack-TBmovie' /home/moterbbb/rtorrent/download/'[高清动画合集]Animation.BluRay.720P.高清片源 无字幕.Pack-TBmovie' 这样下载下来的全部是文件夹和子文件夹，里面的内容不会下载。

但如果用bypy downdir / -dv 命令呢，hash完之后，就出来一堆错误

> <E> [17:30:24] HTTP Response Status Code: 403
<E> [17:30:24] Error JSON returned:{u'error_code': 4, u'error_msg': u'No permission to do this operation'}
Error code: 4
Error Description: No permission to do this operation
<E> [17:30:24] Website returned: {"error_code":4,"error_msg":"No permission to do this operation"}

**Comment by houtianze** [comment]
感谢反馈。

这个就是 #368 的问题，貌似百度那边修改造成的，暂时无解。
