### ISSUE TITLE
请问能不能加入上传(upload)成功后删除本地文件的功能

### ISSUE THREAD

**Issue by xiaguobin** [houtianze/bypy#390]
因为我有个目录很大,几乎没有过一次upload成功的, 需要开启process 50 还要好久,如失败,对本地的文件还需要重新检查,浪费时间.不如加个成功的文件即删除,然后如果有些文件比较顽固(或不明原因),可以用其他方式去备份上传.
谢谢

**Comment by houtianze** [comment]
感谢建议。

嗯，这个场景加入这个功能还是比较实用的，我看看怎么加吧。

**Comment by houtianze** [comment]
最新版`1.5.8`加了`--move`这个命令行参数，上传/下载/同步如果传输成功会删除源文件（为了安全，这个参数会强制比较md5）。逻辑上应该是对的，但是为了数据安全，还是建议你先备份源文件夹，试几次后没有问题再放心不去备份。

`pypi`服务器可能因为缓存还是什么原因，`bypy`还显示是`1.5.7`版本，但`1.5.8`已经上传了，估计过段时间就会刷新。

**Comment by xiaguobin** [comment]
速度好快啊 我试试效果啊
