### ISSUE TITLE
Error_code 31233,read request body timeout

### ISSUE THREAD

**Issue by EricHerilan** [houtianze/bypy#393]
多个文件上传就偶尔遇到这个问题
1.5.9版本

> <E> [08:38:55] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [08:38:55] Function: __upload_one_file_act
<E> [08:38:55] HTTP Response Status Code: 408
<E> [08:38:55] Error JSON returned:{u'error_code': 31233, u'error_msg': u'read request body timeout'}
Error code: 31233
Error Description: read request body timeout
<E> [08:38:55] Website returned: {"error_code":31233, "error_msg":"read request body timeout"}
<E> [08:38:55] Waiting 40 seconds before retrying...

然后自动重试5次依旧没有上传成功
后来检查待上传文件没有损坏，也没有权限限制。

**Comment by houtianze** [comment]
感谢反馈。
看了一下，貌似这个是百度服务器新加的错误代码，与本地文件无关。应该就是服务器觉得操作超时，直接关掉连接了。所以这个客户端也做不了什么（按你说那样的话，重试逻辑正常），只能再传一遍或几遍知道文件能成功上传。
