### ISSUE TITLE
python3.5各种.import错误

### ISSUE THREAD

**Issue by dhqdqk** [houtianze/bypy#394]
/bypy/bypy.py", line 62, in <module>
    import pickle
  File "/usr/lib/python3.5/pickle.py", line 32, in <module>
    from struct import pack, unpack
ImportError: cannot import name 'pack'

**Comment by houtianze** [comment]
你贴的这个错误是出现在Python系统库`pickle`里面，和`bypy`无关，你要检查下你的Python 3安装是否完整。无论Python 2还是3，都按readme里面用pip安装就应该可以使用了。
