### ISSUE TITLE
pyby downfile quits without any error

### ISSUE THREAD

**Issue by colourful-land** [houtianze/bypy#395]
The file CC2017/'03 ae 2017中英文'/'03 ae 2017英文版.dmg' doesn't exist (the actual file name is CC2017/'03 ae 2017中英文'/'03 ae 2017 英文版.dmg')

$ bypy -v downfile CC2017/'03 ae 2017中英文'/'03 ae 2017英文版.dmg'
Loading Hash Cache File '/home/gulliver/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
$

Expected: an error like File not found.

Such an error message would be of great help in terms of usability.

**Comment by houtianze** [comment]
Thanks for the feedback.

Yes, printing the error message in the end (if there were any errors) improves the usability. I've added this to all actions.
