### ISSUE TITLE
how to change account?

### ISSUE THREAD

**Issue by JosephZZ** [houtianze/bypy#397]
Hi I find myself logged into a wrong account of mine, but I couldn't find a way to log out the current account and switch to a new one. How can i do that?

**Comment by houtianze** [comment]
Hi,

There seems no "log out" API for Baidu PCS, but you can always de-authorize the app by going to Baidu's account management.

To switch to another account, you can remove or rename the `~/.bypy/bypy.json` file (or run `bypy -c`), then the app will ask you to re-authorize again, where you can choose the correct account then.

**Comment by JosephZZ** [comment]
Great thanks!!
