### ISSUE TITLE
没看明白说明，/app/bypy目录在哪里？

### ISSUE THREAD

**Issue by linux0ne** [houtianze/bypy#398]
刚刚接触这个软件，没大看明白说明中讲得"/app/bypy"目录是指什么意思 ？

是需要我在网页版的云盘中  “全部文件“下建立一个app目录，再在其中建立一个bypy目录 ？

**Comment by linux0ne** [comment]
啊   知道了   在一个叫“我的应用数据”的文件夹下    这里有个bypy文件夹。

**Comment by houtianze** [comment]
对。
