### ISSUE TITLE
ERROR 31066

### ISSUE THREAD

**Issue by a327979579** [houtianze/bypy#401]
pi@YEYI:/ $ python3 -m bypy list
Please visit:
https://openapi.baidu.com/oauth/2.0/authorize?response_type=code&redirect_uri=oob&scope=basic+netdisk&client_id=xxxx
And authorize this app
Paste the Authorization Code here within 10 minutes.
Press [Enter] when you are done
920300ae4eee54a074bf0bb5a5733412
Authorizing, please be patient, it may take upto None seconds...
Authorizing/refreshing with the OpenShift server ...
OpenShift server failed, authorizing/refreshing with the Heroku server ...
Successfully authorized
<E> [17:45:37] ----------------------------------------------------------------
Error 31066

删除过TOKEN也没用，重新授权很多次，也还是不行~求大神解决这个问题

**Comment by a327979579** [comment]
我改了一下那个地址····id = xxxx

**Comment by houtianze** [comment]
感谢反馈。

查了一下错误代码，是不是你的百度云上面什么也没放？授权过后随便上传的东西再跑`bypy list`呢？
如果问题依旧，能贴一下加`-d`的输出吗？(`bypy -d list`)

**Comment by maoxuner** [comment]
第一次使用需要手动在百度云`我的应用数据`里面创建文件夹`bypy`
