### ISSUE TITLE
异常处理

### ISSUE THREAD

**Issue by jiangjiangflies** [houtianze/bypy#405]
您好， 我在自己的脚本中调用了bypy，但是有异常无法处理。如下代码，无论上传是否成功，up的值都为1，始终会执行try部分的代码，而不会去执行except。这是为啥哩？python小白求教咯
```
try:
    bp.upload(“test”)
    up = 1 
except:
    up = 0 

```

**Comment by houtianze** [comment]
你好，`bypy`实例一般情况下是不会抛出异常的，你要检查操作是否成功，可以看`bp.upload()`的返回值（0为成功，非零为出错）
