### ISSUE TITLE
百度PCS API

### ISSUE THREAD

**Issue by jiangjiangflies** [houtianze/bypy#407]
查了一天的资料，本来想着自己也学着写一点脚本，却发现百度PCS API接口已经关闭了。那么问题来了，bypy为何还能使用？是百度云仅禁止了新的PCS应用的创建吗？

**Comment by houtianze** [comment]
对。不知道何时开始，百度已经不开放PCS权限申请了，但目前还没禁止掉`bypy`的key。

中秋快乐！
