### ISSUE TITLE
百度会员也会被限速么

### ISSUE THREAD

**Issue by dukedhx** [houtianze/bypy#409]
已是百度会员，上海电信FTTB，baiduyunguanjia在10m上下，可是bypy用aria开十线程还是只有不到2m。。。
aria配置：-s10 -x10 -c
是有什么么配好还是api也限速会员？

**Comment by houtianze** [comment]
这个不确定，不过根据目前的反馈来看，百度好像没有把pcs和会员连起来，所以应该会员也是会限速的。
