### ISSUE TITLE
出错误了

### ISSUE THREAD

**Issue by 119977** [houtianze/bypy#410]
`<E> [07:34:11] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [07:34:11] Function: __downchunks_act
<E> [07:34:11] Website parameters: {u'path': u'/apps/bypy/NEW.part5.rar', u'method': u'download'}
<E> [07:34:11] Full URL: http://nj01ct01.baidupcs.com/file/f74b500d27108888527d6a3d3776c8d7?bkt=p3-0000c5865238680c70e0eab178511a99c3&fid=1085479236-15******71-2400210****90331&time=1507203252&sign=FDTAXGERLBH-DCb7*************fedcff06b081203-1c58tl***************3f2yU%3D&to=njhb&fm=Yan,B,U,ny&sta_dx=554108658&sta_cs=3&sta_ft=rar&sta_ct=1&sta_mt=0&fm2=Yangquan,B,U,ny&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=000********************0e0eab178511a99c3&sl=79364174&expires=8h&rt=pr&r=555710567&mlogid=64433239895871279&vuk=-&vbdid=-&fin=NEW.part5.rar&slt=pm&uta=0&rtype=1&iv=0&isw=0&dp-logid=64433238519**7271279&dp-callid=0.1.1&hps=1&csl=100&csign=3jGVY*****************uc8%3D&by=flowserver
`

**Comment by houtianze** [comment]
谢谢反馈，不过至少得提供个完整日志吧和运行的命令吧，这一小段什么也看不出。
