### ISSUE TITLE
Timeout设置

### ISSUE THREAD

**Issue by jiangjiangflies** [houtianze/bypy#414]
您好：
我目前用的这个SDK http://baidupcs.readthedocs.io/en/latest/api.html#id4， 这个上传PCS.upload并没有timeout的参数设置。因为是国外VPS，连接百度云，一旦网络抽风，程序就假死了，所以可能我需要设置一个timeout。所以请教您一下，我应该怎么设置超时呢？

**Comment by houtianze** [comment]
你好，

这个你应该去那个github项目里面去问一下啊，我不清楚那个api是怎么做的，百度pcs api文档可以看这里：

https://github.com/houtianze/bypy/tree/master/baidudoc
