### ISSUE TITLE
ssh 到树莓派 运行命令后 关闭ssh , 命令会继续执行么

### ISSUE THREAD

**Issue by msongz** [houtianze/bypy#416]
感谢提供了这么好的工具~
我用的树莓派
目的是挂着树莓派慢慢上传大文件
当我执行完 bypy upload 后
关闭这个ssh
文件夹会继续上传么?

**Comment by zminds** [comment]
├─sshd─┬─sshd───sshd───bash───sudo───su───bash
                  ├─sshd───sshd───bash───sudo───su───bash───pstree
                 └─sshd───sshd───bash───sudo───su───bash───bypy

看下进程树 你说呢？ nohup  crontab  这些都可以解决你的问题

**Comment by msongz** [comment]
謝謝，nohup可以
初接觸，不好意思
