### ISSUE TITLE
上传返回信息不正常

### ISSUE THREAD

**Issue by jiangjiangflies** [houtianze/bypy#417]
你好，我用bypy上传超过2G的文件，用返回值是否是0来判断是否成功上传，结果都是不正常，然而去百度云查看，明明已经上传成功了！ 但是查看log，也是提示的错误信息

<I> [15:55:03] Local and remote file hash DOESN'T match
<E> [15:55:03] 'Today_10_23_17.mkv' =C=> '/apps/bypy/NBC/Today_10_23_17.mkv' FAILED.

**Comment by houtianze** [comment]
感谢反馈。

你加了`-v`(verify)参数吧？这个貌似是百度api的问题，你可以再上传一两次（应该是所谓的“秒传”，很快的），一般问题就就解决了。
