### ISSUE TITLE
Multiprocess is not perfectly work

### ISSUE THREAD

**Issue by rexx6** [houtianze/bypy#419]
Hello..

I want syncdown with multiprocess. And I tried it with 4 processes. (bypy --processes 4 syncdown)

I have 1 "different file" and 6 "remote only files" on baidu server. 

I expected 4 files to be downloaded simultaneously. But after completed download of 1 "different file", download of 3 "remote only files" are started.

If "different file" is present on server, syncdown with multiprocess is not perfectly work.

Sincerely yours.

**Comment by houtianze** [comment]
Thanks for the feedback.

My understanding is that it's probably due to how the "multiprocessing" library schedule processes, and we don't have much control over it. On the other hand, what you described doesn't sound perfect, but I would say it's still something acceptable.
