### ISSUE TITLE
<I> [10:58:39] Local and remote file hash DOESN'T match

### ISSUE THREAD

**Issue by joeyulivecn** [houtianze/bypy#424]
什么原因会出现这个错误？有些文件上传没问题，有些文件上传失败。不知道规律在哪。

**Comment by houtianze** [comment]
这个貌似是分片上传百度服务器端哈希值计算有误，一般来说都是传好了。如果不放心可以再传一两遍，哈希值正确计算出来这个提示就会消失了。
