### ISSUE TITLE
难道只有我卡住不动吗?

### ISSUE THREAD

**Issue by ruan11223344** [houtianze/bypy#426]
从云盘同步到本地 日志就卡着不动,同步的文件夹被生成了,但是文件确没有.
是不是cookie 被百度识别了
要不要换cookie了?
![qq 20171229195904](https://user-images.githubusercontent.com/5679023/34436660-c0233a52-ecd2-11e7-8fb9-ba76cbb7d932.png)

**Comment by colourful-land** [comment]
这里又不是客服中心，来的什么快照呀。学习一下如何报BUG

**Comment by houtianze** [comment]
这个算是已知问题吧，应该是百度服务端给卡住了，除了等和再试基本无解。。
