### ISSUE TITLE
share 方法似乎不好用啊

### ISSUE THREAD

**Issue by CrazyStoneJy** [houtianze/bypy#429]
share 方法似乎不好用啊

**Comment by liushengsheng1990** [comment]
你好兄弟，运行时，老是出现ImportError: attempted relative import with no known parent package，你知道如何解决吗

**Comment by houtianze** [comment]
@CrazyStoneJy 
我之前试是可以的，这个不是百度的分享功能，是工具自己的（其实这个方法并未公开。。）

@liushengsheng1990 
按readme跑`pip install bypy`再运行`bypy`就可以了，不要直接跑源码。
