### ISSUE TITLE
授权失败

### ISSUE THREAD

**Issue by wjfriend** [houtianze/bypy#430]
If you are confident that your CA Bundle can verify Baidu PCS's certs, you can run the prog with the '--cacerts <your ca cert path>' argument to enable SSL cert verification.

However, most of the time, you can ignore this warning, you are not going to send sensitive data to the cloud plainly right?
Please visit:
https://openapi.baidu.com/oauth/2.0/authorize?scope=basic+netdisk&redirect_uri=oob&response_type=code&client_id=q8WE4EpCsau1oS0MplgMKNBn
And authorize this app
Paste the Authorization Code here within 10 minutes.
Press [Enter] when you are done
aa38d789e5ce8d21bce14ebb9720166b
Authorizing, please be patient, it may take upto 60.0 seconds...
Authorizing/refreshing with the OpenShift server ...
<E> [00:16:18] Maximum number (1) of tries failed.
OpenShift server failed, authorizing/refreshing with the Heroku server ...
/tmp/python/lib/python2.7/site-packages/urllib3-1.22-py2.7.egg/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
/tmp/python/lib/python2.7/site-packages/urllib3-1.22-py2.7.egg/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
/tmp/python/lib/python2.7/site-packages/urllib3-1.22-py2.7.egg/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Heroku server failed. Last resort: authorizing/refreshing with the GAE server ...
<E> [00:17:21] Maximum number (1) of tries failed.
<E> [00:17:21] Fatal: All server authorizations failed.
<I> [00:17:21] ----------------------------------------------------------------
<I> [00:17:21] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.
<E> [00:17:21] Program authorization FAILED.
You need to authorize this program before using any PCS functions.
Quitting...

**Comment by houtianze** [comment]
感谢反馈。

这种情况去 https://passport.baidu.com/accountbind 删除这个授权重头再来一次应该可以解决。

**Comment by quhanj** [comment]
我也有这个错误。去 https://passport.baidu.com/accountbind 发现只有人人网、新浪微博、飞信、腾讯、微信、腾讯微博。不知道应该删除哪个，咋办？

**Comment by houtianze** [comment]
那应该是你没有授权吧？看看有没有`~/.bypy`这个目录？有就删除再跑一遍。

**Comment by quhanj** [comment]
有。也删过。
以下这段错误我不用理吗？还是要升级什么东西？
OpenShift server failed, authorizing/refreshing with the Heroku server ...
/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Heroku server failed. Last resort: authorizing/refreshing with the GAE server ...

**Comment by quhanj** [comment]
ok了。我用bypy -V查看了下版本，是1.3.3。pip install的就是这个版本。然后手动安装了github上的，是1.6.3。我的.pip/pip.conf上是：
index-url=http://pypi.douban.com/simple/
是不是应该换一个url？

**Comment by houtianze** [comment]
注释掉就可以了。
