### ISSUE TITLE
无法认证

### ISSUE THREAD

**Issue by thank243** [houtianze/bypy#433]
Authorizing, please be patient, it may take upto None seconds...
Authorizing/refreshing with the OpenShift server ...
然后自动退出,运行bypy info继续让认证

**Comment by houtianze** [comment]
我刚试过可以。你的bypy版本（`bypy --version`）多少？升级到最新版（`pip install -U bypy`）应该可以解决问题。

**Comment by houtianze** [comment]
查了一下ZeroReturnError，应该是你的request版本太旧：
https://github.com/requests/requests/issues/2517

升级request和bypy应该可以解决问题。
