### ISSUE TITLE
bypy下载速度只有100K

### ISSUE THREAD

**Issue by dxsweet** [houtianze/bypy#434]
下载速度只有100K，问下，你们是通过第三方的服务器对吗？
服务器在美国吗？为什么下载速度如此之慢

**Comment by houtianze** [comment]
下载上传都是直连百度自己的服务器，只是授权需要连一下第三方服务器，与传输速度无关。
所以。。基本就是百度那边限速了。加`--select-fastest-mirror`参数也许会有帮助（不过我觉得很可能也没用。。）
