### ISSUE TITLE
建议添加通过共享链接添加文件的功能

### ISSUE THREAD

**Issue by oscar-c** [houtianze/bypy#435]
不知道是否可能，但是如果能把别人发布的共享链接所指向的文件（或者文件夹）添加到网盘中bypy的文件夹下面，再下载下来就好了。

**Comment by houtianze** [comment]
感谢建议。

应该不会加这个实现了：
- 貌似`pcs`没开放这个api接口
- 项目已经放到维护模式，除了修严重bug基本不会增加新功能了
- 个人觉得这个需求不是特别有用，添加别人网盘链接只是一次性操作，在网页上很容易就完成了，命令行优势不大。
