### ISSUE TITLE
不想更新新版本如何设置

### ISSUE THREAD

**Issue by milabobo** [houtianze/bypy#438]
bypy跑在服务端，每天定时上传资料，最近因为版本更新，会出现
<E> [12:26:38] Your current version (1.6.0) is too low, minimum required version is 1.6.1.
Please run 'pip install -U bypy' to update and try again.

我只想用旧版本，然后自己想升级的时候再升级，要如何设置？

**Comment by houtianze** [comment]
感谢反馈。

可以把`~/.bypy/bypy.setting.json`改成类似如下内容：
```json
{
  "lastUpdateCheck": 9876543210
}
```

但不推荐这样做，因为：
这个强制升级是后来加进去的，是因为发现了比较严重的bug，影响用户使用，大概有这么两次吧：
- 1.4还是哪个版本之前刷新令牌有问题（api地址写错。。。），会失败，所以每隔一个月就要从新授权，而且还会导致反复连授权服务器，但文件传输会一直失败，所以加入了强制更新到1.4版本。
- 1.6之前同步或比较只会上传/比较一个文件夹下面前1000个文件，其余的会被忽略。虽然一个文件夹下面超过1000个文件个可能性不是很大，但这个不完全/不一致会在极端情况下误导用户，所以又来了一次强制升级到1.6.0。
- 这个1.6.1升级是我一时偷懒，因为刚刚修复一个小bug，就想着大家都来最新版得了。不过看到你的反馈，我觉得这是对用户不太友好的做法，刚刚改回，现在强制升级到1.6.0即可。（所以你现在应该不会在被强制升级了）
- 所以以后除非发现重大问题（这个小工具已经进入维护模式），这个强制升级版本应该不会改了。但是真的再改（可能性很低），一般会是大问题，所以还是建议升级。

**Comment by milabobo** [comment]
@houtianze 感谢及时回复，现在已经正常了
