### ISSUE TITLE
ImportError: No module named contrib

### ISSUE THREAD

**Issue by pinggit** [houtianze/bypy#439]
报一个吧。。。虽然知道不打算支持cygwin。

pip一键安装顺利。只是运行时报错：

```
$ bypy
Traceback (most recent call last):
  File "/usr/bin/bypy", line 7, in <module>
    from bypy.bypy import main
  File "/usr/lib/python2.7/site-packages/bypy/__init__.py", line 17, in <module>
    from .bypy import ByPy
  File "/usr/lib/python2.7/site-packages/bypy/bypy.py", line 116, in <module>
    from requests_toolbelt import multipart
  File "/usr/lib/python2.7/site-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/lib/python2.7/site-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/lib/python2.7/site-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/usr/lib/python2.7/site-packages/requests_toolbelt/_compat.py", line 51, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: No module named contrib
```

虽然你说不打算支持cygwin，但是我实在想不出cygwin的python跟linux python有啥不同。。。
不支持没理由啊。。

**Comment by pinggit** [comment]
我看了下那个文件，貌似对requests的版本有concern，不懂。
直接把那段offending code粗暴注释掉就解决了。。。快别说不支持cygwin -- 支持的比linux好。

'''
   45 gaecontrib = None
   46 #if requests.__build__ < 0x021000:
   47 #    gaecontrib = None
   48 #else:
   49 #    try:
   50 #        from requests.packages.urllib3.contrib import appengine as gaecontrib
   51 #    except ImportError:
   52 #        from urllib3.contrib import appengine as gaecontrib
'''

$ bypy info
Please visit:
https://openapi.baidu.com/oauth/2.0/authorize?scope=basic+netdisk&redirect_uri=oob&response_type=code&cl...
And authorize this app
Paste the Authorization Code here within 10 minutes.
Press [Enter] when you are done
ff32c7...
Authorizing, please be patient, it may take upto infinite seconds...
Authorizing/refreshing with the OpenShift server ...
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Successfully authorized
Quota: 5.xxxTB
Used: 9xx.xxxGB
[2018-03-24 21:41:24]pings@pings-T470:~
$
[2018-03-24 21:41:25]pings@pings-T470:~
$ bypy list
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/apps/bypy ($t $f $s $m $d):
D abc 0 2018-03-24, 20:53:05
[2018-03-24 21:41:33]pings@pings-T470:~
$ bypy list abc
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/apps/bypy/abc ($t $f $s $m $d):
D done 0 2018-03-24, 20:53:05
D Friends Season 01-10 NTSC DD5.1 x264-Mixed 0 2018-03-24, 20:53:05
...
[2018-03-24 21:41:42]pings@pings-T470:~
$ bypy downfile 'abc/XXX.mp3'
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

[____________________] 1% (20.0MB/1.4GB)

**Comment by houtianze** [comment]
目测感觉是`requests`/`urllib3`版本问题，也许，只是也许，装一下新版的`requests`/`requests-toolbelt`/`urllib3`能解决。

pip包管理有点弱（主要是版本依赖/控制），有时候依赖的包有点问题就会出点错，不过貌似暂时没有太好的解决办法： https://stackoverflow.com/a/6572017/404271 ，可能不行就。。重装或上`virtualenv/pipenv`。。
