### ISSUE TITLE
速度。。。

### ISSUE THREAD

**Issue by pinggit** [houtianze/bypy#440]
这个速度实在是。。实测下载电影太慢。我在server上运行了一晚上卡在10%。
没办法跟网盘客户端（“”提速中”会员）比。
bypy没办法利用会员的提速特性吧？

**Comment by rikakomoe** [comment]
那就是卡了……我有个进程已经卡了6天了，现在还在那卡着😆

pinggit <notifications@github.com> 于 2018年3月26日周一 01:15写道：

**Comment by houtianze** [comment]
嗯，那是卡了，下载可以用`--downloader aria2`调用aria来下载，也许会有帮助（不过也许一样会卡/蹦掉。。）
