### ISSUE TITLE
在ubuntu mate上怎么运行，用pip安装成功了，但是找不到命令？

### ISSUE THREAD

**Issue by ChampaignLiu** [houtianze/bypy#442]
X-Series:~$ pip install requests
Collecting requests
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests)
  Using cached https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Using cached https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Installing collected packages: idna, urllib3, certifi, chardet, requests
Successfully installed certifi-2018.4.16 chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22
X-Series:~$ 

X-Series:~$ pip install bypy
Collecting bypy
  Using cached https://files.pythonhosted.org/packages/45/5a/d29d0ef526ba48a2eebc65c68211abb59933d942304ea85a0e29fc8d0048/bypy-1.6.3-py2.py3-none-any.whl
Collecting requests>=2.10.0 (from bypy)
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
Collecting multiprocess>=0.70.0 (from bypy)
Collecting requests-toolbelt>=0.8.0 (from bypy)
  Using cached https://files.pythonhosted.org/packages/97/8a/d710f792d6f6ecc089c5e55b66e66c3f2f35516a1ede5a8f54c13350ffb0/requests_toolbelt-0.8.0-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests>=2.10.0->bypy)
  Using cached https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.10.0->bypy)
  Using cached https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.10.0->bypy)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.10.0->bypy)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting dill>=0.2.6 (from multiprocess>=0.70.0->bypy)
Installing collected packages: idna, urllib3, certifi, chardet, requests, dill, multiprocess, requests-toolbelt, bypy
Successfully installed bypy-1.6.3 certifi-2018.4.16 chardet-3.0.4 dill-0.2.7.1 idna-2.6 multiprocess-0.70.5 requests-2.18.4 requests-toolbelt-0.8.0 urllib3-1.22

X-Series:~$ bypy

Command 'bypy' not found, did you mean:

  command 'pypy' from snap pypy
  command 'pypy' from deb pypy
  command 'mypy' from deb mypy

See 'snap info <snap name>' for additional versions.

**Comment by rikakomoe** [comment]
试试安装的时候加 sudo

ChampaignLiu <notifications@github.com> 于 2018年4月19日周四 22:19写道：

**Comment by houtianze** [comment]
试试`python -m bypy`有输出吗？换成`python3 -m bypy`呢？
如果有输出，但是`bypy`不行，那我就不知道为啥setuptools没把bypy放到PATH里去，但可以用上面的命令凑合着用。。

或者向楼上说的，加`sudo`，或者不加sudo，用`pip install --user bypy`
