### ISSUE TITLE
上传大文件失败

### ISSUE THREAD

**Issue by xxllp** [houtianze/bypy#444]
bypy upload XXX
[____________________] 0% (40.0MB/18.6GB)  <E> [04:21:05] Waiting 10 seconds before retrying...
<E> [04:21:15] Request Try #2 / 5
<E> [04:22:10] Waiting 20 seconds before retrying...
<E> [04:22:30] Request Try #3 / 5
<E> [04:22:57] Waiting 30 seconds before retrying...
<E> [04:23:27] Request Try #4 / 5
<E> [04:25:34] Waiting 40 seconds before retrying...
<E> [04:26:14] Request Try #5 / 5
<E> [04:27:00] Maximum number (5) of tries failed.
<E> [04:27:00] Slice MD5 mismatch, waiting 10 seconds before retrying...

**Comment by xxllp** [comment]
实在不懂，慢还有各种不行

**Comment by xxllp** [comment]
最新还有报错：No space left on device

**Comment by xxllp** [comment]
<class 'json.decoder.JSONDecodeError'> - Unterminated string starting at: line 548 column 7 (char 19372)

**Comment by xxllp** [comment]
重新授权后输入啥都报错：
Fail to load the Hash Cache, no caching.

这是啥意思

**Comment by houtianze** [comment]
这个要问百度的PCS API为啥这么慢。
