### ISSUE TITLE
Authorization failed

### ISSUE THREAD

**Issue by HarveyWang81** [houtianze/bypy#451]
I met an issue during authorization, the following are the detail info for this issue.

`Loading Hash Cache File '/home/lwang3/.bypy/bypy.hashcache.json'...
Hash Cache File '/home/lwang3/.bypy/bypy.hashcache.json' not found, no caching
Please visit:
https://openapi.baidu.com/oauth/2.0/authorize?client_id=q8WE4EpCsau1oS0MplgMKNBn&response_type=code&redirect_uri=oob&scope=basic+netdisk
And authorize this app
Paste the Authorization Code here within 10 minutes.
Press [Enter] when you are done
2c0d4d19f48cd7c63990508465882ec1
Authorizing, please be patient, it may take upto 300 seconds...
Authorizing/refreshing with the OpenShift server ...
OpenShift server failed, authorizing/refreshing with the Heroku server ...
Heroku server failed, authorizing/refreshing with the Heroku1 server ...
Heroku1 server failed. Last resort: authorizing/refreshing with the GAE server ...
<E> [19:25:48] Fatal: All server authorizations failed.
<I> [19:25:48] ----------------------------------------------------------------
<I> [19:25:48] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.
Skip saving Hash Cache since it has not been updated.`

I've tried everything above, but the problem still exists.

Please kindly help me to solve it.
Thanks in advance!

**Comment by houtianze** [comment]
Hi,

Have you tried:
- Remove `~/.bypy`
- Go to https://passport.baidu.com/accountbind and deauthorize the app?

**Comment by Aologe** [comment]
我遇到了同样的问题，按照@houtianze你的办法还是同样无法解决，请您抽空可以给个解决办法吗，十分感谢

**Comment by hitachinsk** [comment]
@houtianze I have tried your instructions many times, but things cannot get improved. It seems there is something wrong with your server, do you have another solution to this problem?

**Comment by houtianze** [comment]
@hitachinsk Thanks for feeding back. Can you try again now, the authorization server might be OK now.

**Comment by hitachinsk** [comment]
Thanks for your kindly help, authorization is successful, but my python raises an HTTPError, maybe the remote server is blocked by the Great Wall. Anyway, I really appreciate your fantastic work, thank you very much.
