### ISSUE TITLE
大于 4G 文件无法上传的问题

### ISSUE THREAD

**Issue by h2y** [houtianze/bypy#452]
我的 NAS 上 bypy 定期自动运行，最近发现总是运行错误，不断地尝试上传一个 7.1G 的文件，直到达到错误次数上限后退出进程。

经过错误排查后发现问题来源于我没百度会员，最大单文件只能是 4G，但 bypy 不管这么多，计算 hash 后，尝试秒传失败，然后进行正常上传，7.1G 辛苦传完后，目录中却不存在该文件，于是继续进行 4 次上传，然后达到错误次数上限后退出进程。剩下的文件传输也不会进行。

所以这是一个不易发觉的、很影响使用的问题。

解决方式是添加一个设置项，`--maxFileSize 4G` 可让 bypy 跳过处理尺寸大于 4G 的文件。

**Comment by houtianze** [comment]
感谢反馈。

能帮忙传个日志吗？5次上传失败会忽略该文件，但按理应该会继续传其他文件，如果直接退出，也许有其他bug，我看看。

不过文件4G大小限制这个问题我有点怀疑，如果没记错，我是上传过（也有人反馈过）10G左右的文件成功的。

**Comment by h2y** [comment]
刚刚我在 Windows 上测试了一下，4.2G 的文件上传正常。

稍等我再在 NAS 上测试一下。

**Comment by houtianze** [comment]
应该不是因为内存，有完整日志和运行参数吗？秒传成功再次上传这个有点奇怪，按理秒传成功应该是不会再传的。
