### ISSUE TITLE
VIP account

### ISSUE THREAD

**Issue by mariagibert** [houtianze/bypy#455]
Hello there, 
I have a problem. When I try to download a file it takes forever and an error appears: 

`<E> [15:19:45] Waiting 10 seconds before retrying...
<E> [15:19:55] Request Try #2 / 5
[=___________________] 5% (100.0MB/1.9GB)  <E> [15:27:23] Waiting 10 seconds before retrying...
<E> [15:27:33] Request Try #2 / 5
<E> [15:33:11] Waiting 20 seconds before retrying...
<E> [15:33:31] Request Try #3 / 5
<E> [15:41:09] Waiting 30 seconds before retrying...
<E> [15:41:39] Request Try #4 / 5
[=___________________] 6% (120.0MB/1.9GB)  <E> [15:50:56] Waiting 10 seconds before retrying...
<E> [15:51:06] Request Try #2 / 5
<E> [16:01:10] Waiting 20 seconds before retrying...
<E> [16:01:30] Request Try #3 / 5
<E> [16:07:31] Waiting 30 seconds before retrying...
<E> [16:08:01] Request Try #4 / 5
[=___________________] 8% (160.0MB/1.9GB)  <E> [16:15:10] Waiting 10 seconds before retrying...
<E> [16:15:20] Request Try #2 / 5
<E> [16:22:33] Waiting 20 seconds before retrying...
<E> [16:22:53] Request Try #3 / 5
<E> [16:29:14] Waiting 30 seconds before retrying...
<E> [16:29:44] Request Try #4 / 5
<E> [16:34:52] Waiting 40 seconds before retrying...
<E> [16:35:32] Request Try #5 / 5
<E> [16:43:30] Maximum number (5) of tries failed.
[====================] 100% (31.0B/31.0B) ETA:  (6B/s, 4s gone) <E> [16:43:46] Waiting 10 seconds before retrying...
<E> [16:43:56] Request Try #2 / 5
<E> [16:44:02] Waiting 20 seconds before retrying...
<E> [16:44:22] Request Try #3 / 5
<E> [16:44:27] Waiting 30 seconds before retrying...
<E> [16:44:57] Request Try #4 / 5
<E> [16:45:00] Waiting 40 seconds before retrying...
<E> [16:45:40] Request Try #5 / 5
<E> [16:45:46] Maximum number (5) of tries failed.
[====================] 100% (11.0B/11.0B) ETA:  (2B/s, 7s gone) <E> [16:45:58] ----------------------------------------------------------------
Error 140: Maximum retries reached`

I guess it's a speed problem. I have a VIP account which should be faster than a normal account, is there any chance the program doesn't check if the account is VIP or not?

Could you please help me!
Thanks :)

**Comment by houtianze** [comment]
Hi,

Thanks for the feedback.

The program does not (and could not) check if the account is VIP, as there is no API to do that. Theoretically, Baidu can do this transparently if they want (all controlled by their backend), but apparently, the PCS APIs are not associated with VIP, so it won't help with the speed..
