### ISSUE TITLE
同步上传文件夹出现异常

### ISSUE THREAD

**Issue by jiangjiangflies** [houtianze/bypy#457]
异常输出结果如下：
Exception:
<type 'exceptions.ValueError'> - Extra data: line 74 column 5 - line 76 column 2 (char 2180 - 2187)
Stack:
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 3700, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/local/lib/python2.7/dist-packages/bypy/util.py", line 73, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))
Abort
Saving Hash Cache...

只同步了部分文件，其他都没成功。这个是怎么回事？是某一个文件有问题导致其他文件都不能继续同步了吗？如果是这样，能否捕获异常，其他文件继续同步，不要终止程序？

**Comment by houtianze** [comment]
问题应该出在`~/.bypy/*.json`，不是合法json。
可能原因：
- 手动修改过这个/些json文件
- 不止一个bypy实例在运行？

**Comment by jiangjiangflies** [comment]
我没有修改过json文件，可能是我同时开了几个bypy吧~ 多谢 我再观察观察~感谢~
