### ISSUE TITLE
 All server authorizations failed.

### ISSUE THREAD

**Issue by Im-fengyin** [houtianze/bypy#459]
之前是可以认证通过的，但重装系统后不行了。按照fixs里的建议做了还是无法通过，加参数d后发现是openshift等认证没有响应，全部Time out了。

<E> [10:58:29] Error accessing 'https://bypyoauth-route-bypy.a3c1.starter-us-west-1.openshiftapps.com/auth'
<E> [10:58:29] 
<E> [10:58:29] Function: __server_auth_act
<E> [10:58:29] Website parameters: {u'redirect_uri': u'oob', u'code': '××××××××××××××××（打码）×××××××××××××', u'bypy_version': u'1.6.4'}
<E> [10:58:29] Full URL: https://bypyoauth-route-bypy.a3c1.starter-us-west-1.openshiftapps.com/auth?code=×××××××××××××（打码）××××××××××××××&redirect_uri=oob&bypy_version=1.6.4
<E> [10:58:29] HTTP Response Status Code: 504
<E> [10:58:29] Error parsing JSON Error Code from:
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>

**Comment by hundan2020** [comment]
今天在用这个脚本，遇到了同样的问题，检查了代码中的四个服务地址，其中一个是可用的，但是需要翻墙。

所以是可以通过翻墙的解决的，至于如何让进程翻墙，这个方法有很多，就不赘述了。

验证成功之后将.bypy文件夹里的配置备份一下，以后就不用重新验证了。

**Comment by updater1234** [comment]
我也遇到了，不知是不是百度那边更新了什么才会这样。

**Comment by houtianze** [comment]
感谢反馈，应该是heroku免费配额用完了。。。
而OpenShift我还没搞明白为什么不好用，上次修过一次貌似没有解决问题。

到下月1号就好了。。。有时间我看看openshift的怎么修一下。

**Comment by louiss007** [comment]
@houtianze ，请教大神，还会有免费配额吗？没有的话，翻墙能解决这个问题吗。多谢指点！

**Comment by updater1234** [comment]
翻墙的话可以连上GAE的服务器，我试过。

**Comment by updater1234** [comment]
只是在登录的时候需要翻墙而已，其他时候不用。

**Comment by StormFeng** [comment]
电脑翻墙了，但是pycharm还是访问不到，在浏览器可以访问，所以想把浏览器返回的参数手动写到C:\Users\Administrator\.bypy\bypy.setting.json，请问可行吗，如果可以，bypy.setting.json在正常情况下里面的数据结构能不能发下 @updater1234

**Comment by updater1234** [comment]
抱歉，目前我已经不用bypy了。我现在是用虚拟机来跑百度云。

**Comment by StormFeng** [comment]
刚回完贴去看源码就找到方法了，应该手动写到bypy.json也是可以的。多谢回帖。 @updater1234

**Comment by houtianze** [comment]
改了些Heroku的设置，从2018-10-01开始应该是不需要翻墙都可以直接授权/刷新令牌了。（吐个槽：红帽的OpenShift不知道为啥就是不稳定。。。）

**Comment by lll-j** [comment]
> 刚回完贴去看源码就找到方法了，应该手动写到bypy.json也是可以的。多谢回帖。 @updater1234

是/home/user1/.bypy下的 bypy.setting.json 文件吗？ 我的连接了几次了都是空的，cat一下只有一个大括号，请问手动应该怎么写，我已经有授权码了。

**Comment by lll-j** [comment]
刚回完贴去看源码就找到方法了，应该手动写到bypy.json也是可以的。多谢回帖。 @updater1234

是/home/user1/.bypy下的 bypy.setting.json 文件吗？ 我的连接了几次了都是空的，cat一下只有一个大括号，请问手动应该怎么写，我已经有授权码了。@StormFeng

**Comment by Feiyu-Zhang** [comment]
> 翻墙的话可以连上GAE的服务器，我试过。

现在不可以了

**Comment by Feiyu-Zhang** [comment]
> ```
> 刚回完贴去看源码就找到方法了，应该手动写到bypy.json也是可以的。多谢回帖。 @updater1234
> ```
> 是/home/user1/.bypy下的 bypy.setting.json 文件吗？ 我的连接了几次了都是空的，cat一下只有一个大括号，请问手动应该怎么写，我已经有授权码了。@StormFeng

在Press [Enter] when you are done后面粘贴你的授权码，接着按回车

**Comment by yinlu6** [comment]
> 刚回完贴去看源码就找到方法了，应该手动写到bypy.json也是可以的。多谢回帖。 @updater1234

bypy.json写什么，那个验证码吗
