### ISSUE TITLE
进度条在下载过程中不可见

### ISSUE THREAD

**Issue by PhoenixStarEclipse** [houtianze/bypy#461]
进度条在下载结束后突然出现，我推测下载过程中应该也有但是下载时啥都看不到。

**Comment by carloswear** [comment]
![image](https://user-images.githubusercontent.com/41362266/43687968-5ebb79ae-9912-11e8-88cb-af075ed1aa21.png)

上传的时候可以添加 -v命令

**Comment by carloswear** [comment]
我用的树莓派，下载文件的时候用 nohup bypy syncdown & 让程序后台运行
进度通过查看后台日志命令实现 tail -fn 50 nohup.out 
我觉得挺方便的

![image](https://user-images.githubusercontent.com/41362266/43696418-7fe56334-9970-11e8-9881-e68dce317487.png)
