### ISSUE TITLE
树莓派3B+下载速度过慢

### ISSUE THREAD

**Issue by carloswear** [houtianze/bypy#462]
你好，我的系统版本是Linux 4.14.34-2-osmc
树莓派3B+
长城20兆宽带
树莓派连接方式是Wifi
同步单视频文件的话速度大概在100-200kb/s之间徘徊，有时候就是70-80kb/s
没有开通百度网盘的超级会员
请问是超级会员的原因么还是需要配置其他文件？

我没有编程基础和树莓派基础~所以，如有时间，还请给出我需要朝着哪个方向改进，

![image](https://user-images.githubusercontent.com/41362266/43696636-89bb8aea-9971-11e8-9efd-70d97e3fde53.png)

**Comment by huzhou124** [comment]
我是开通了百度云的会员但是速度也只有150kb-300kb的样子

**Comment by The-Earth** [comment]
我无会员，Windows或Ubuntu，都稳定在80kB/s
