### ISSUE TITLE
下载到网盘报错

### ISSUE THREAD

**Issue by LittleMang** [houtianze/bypy#463]
前辈你好，下载到网盘出现报错。
尝试过卸载重装 重新授权 均失败
以下为错误内容：
Loading Hash Cache File '/root/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
----
Verbose level = 1
Debug level = 1
Config directory: '/root/.bypy'
Token file: '/root/.bypy/bypy.json'
Hash Cache file: '/root/.bypy/bypy.hashcache.json'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = ANSI_X3.4-1968
sys.stdout.encoding = ANSI_X3.4-1968
sys.stderr.encoding = ANSI_X3.4-1968
----

<D> Token loaded:
<D> {u'access_token': u'21.31db83cb153d1223a7d649a15eeb340d.2592000.1536397274.3383340719-1572671', u'expires_in': 2592000, u'session_secret': u'a4841b226fa07f3b92214f917a7aa034', u'scope': u'basic netdisk', u'session_key': u'9mnRdyERWBCUJ1LZoRnyLt7tALDpPUrKEeRTTy5GLNJz/zVK7+rFcLRcts9iNdLGu1JXueXBA9LNdRRwAnblz19kE3SexIPBVw==', u'refresh_token': u'22.98b3d1194d1224a9cec1ebcd725a5328.315360000.1849165274.3383340719-1572671'}
<D> localpath not set, set it to current directory ''
<D> Uploading directory '/youtube_' recursively
<D> Uploading directory '/youtube_' to '/apps/bypy'
<E> [18:23:33] Exception occurred:
Exception:
<type 'exceptions.UnicodeDecodeError'> - 'ascii' codec can't decode byte 0xe3 in position 1: ordinal not in range(128)
Stack:
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/bypy/bypy.py", line 3700, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/local/lib/python2.7/site-packages/bypy/util.py", line 73, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

系统：Centos 6 x86 
版本：ptyhon 2.7+ bypy 1.6.4

**Comment by houtianze** [comment]
你好，前辈不敢当：）

问题应该出在系统编码：
```
sys.stdin.encoding = ANSI_X3.4-1968
sys.stdout.encoding = ANSI_X3.4-1968
sys.stderr.encoding = ANSI_X3.4-1968
```
把系统设成utf-8的（网上搜下教程，大概是个`locales`的命令）应该可以解决。

**Comment by LittleMang** [comment]
前辈你好，系统编码是utf-8
`
LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=
`
这次我尝试上传 加了-v -d 
看到了full url到信息如下：
`
{"error_code":31079,"error_msg":"file md5 not found, you should use upload api to upload the whole file.","request_id":5145973216396155598}
`

**Comment by LittleMang** [comment]
前辈晚上好，这个问题还是没有解决掉。这是截图 使用root shell - interactive出现的错误
<img width="869" alt="qq20180811-202543 2x" src="https://user-images.githubusercontent.com/42237608/43991696-fba2dd7a-9da4-11e8-900c-86832f2833c6.png">

**Comment by houtianze** [comment]
`Connection reset by peer`
这个貌似现在没有什么解决方案，应该是百度服务端的问题。
勉强解决方法是：反复上传，知道`bypy compare`显示远近端相同。

**Comment by LittleMang** [comment]
好，我反复尝试看看。
非常感谢前辈的指导！**: )**
