### ISSUE TITLE
是否可以自建认证服务器

### ISSUE THREAD

**Issue by ddonline** [houtianze/bypy#467]
最近测试发现认证不上
可以自已建一个认证服务器么
Refreshing, please be patient, it may take upto 300 seconds...
Authorizing/refreshing with the OpenShift server ...
OpenShift server failed, authorizing/refreshing with the Heroku server ...
Heroku server failed, authorizing/refreshing with the Heroku1 server ...
Heroku1 server failed. Last resort: authorizing/refreshing with the GAE server ...
<E> [11:22:51] Token-refreshing on all the servers failed

**Comment by houtianze** [comment]
改了些Heroku的设置，从2018-10-01开始应该是不需要翻墙都可以直接授权/刷新令牌了。（吐个槽：红帽的OpenShift不知道为啥就是不稳定。。。）

服务端代码就在 https://github.com/houtianze/bypyoauth 不过需要AppSecret才能跑。。。（这个恕无法公布，否则根本就不会费这么大事来搭服务器了）
