### ISSUE TITLE
syncup命令无法同步根目录-Python2.7*-Debian

### ISSUE THREAD

**Issue by carloswear** [houtianze/bypy#468]
你好~

最近想为自己的树莓派做自动备份，使用了crontab的root账户添加的脚本，开始的时候使用如下命令备份整个根目录，没有问题：

> #!/bin/bash
umount /dev/sda
sleep 2
cd //
sleep 2
nohup /usr/local/bin/bypy upload / /backup -v &
read foo

最近发现syncup命令既可以同步，也能自动删除远程远程文件，所以更新命令如下：
> #!/bin/bash
umount /dev/sda
sleep 2
cd //
sleep 2
nohup /usr/local/bin/bypy syncup / /backup true -v &
read foo

然而：
> Loading Hash Cache File '/root/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
Gathering local directory ...
<E> [15:42:48] Exception occurred:
Exception:
<type 'exceptions.IOError'> - [Errno 38] Function not implemented
Stack:
  File "/usr/local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bypy/bypy.py", line 3700, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/usr/local/lib/python2.7/dist-packages/bypy/util.py", line 73, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))
Abort
Saving Hash Cache...
Hash Cache saved.

我尝试以root账户手动运行该命令：
> cd //
> bypy syncup / /backup true -v

错误结果仍旧如上。

尝试以下命令
>sudo bypy syncup /home /backup true -v
或者
>sudo bypy syncup ~ /backup ture -v
或者
>sudo bypy syncup ./ /backup true -v

都能正常运行，唯独 `sudo bypy syncup / /backup true -v` 无法运行

查看help帮助，两个命令的区别如下：

> syncup [localdir] [remotedir] [deleteremote] - sync up from the local directory to the remote directory
upload [localpath] [remotepath] [ondup] - upload a file or directory (recursively)

请问，如何实现syncup备份整个根目录'/'

补充系统参数如下：
4.14.34-4-osmc based on Debian
python2.7
树莓派3B+：1.4GHz 64位4核 ARM Cortex-A53 CPU

**Comment by houtianze** [comment]
你好，谢谢反馈。

这个问题我不确定原因，可能是因为/目录下有些特殊问题件？或者文件太多？选着性上传如何？

**Comment by carloswear** [comment]
谢谢，现在使用的是syncup的选择性同步，估计是特殊文件导致的问题~感谢
