### ISSUE TITLE
Error 31066

### ISSUE THREAD

**Issue by sidazhang123** [houtianze/bypy#469]
Authorizing/refreshing with the OpenShift server ...
OpenShift server failed, authorizing/refreshing with the Heroku server ...
Successfully authorized
<E> [22:58:25] ----------------------------------------------------------------
Error 31066

无错误信息，删除.bypy重新认证依旧

**Comment by idlqy** [comment]
遇到相同的问题，第一次使用，同问。发生在执行下载命令的时候：

pi@raspberrypi:~/Xware/downloads/TDDOWNLOAD $ sudo bypy downfile "apps/bypy/1.pdf"
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
<E> [16:00:36] ----------------------------------------------------------------
Error 31066

**Comment by houtianze** [comment]
错误是文件不存在。
下载路径不要加`/apps/bypy`，以它为根目录。
