### ISSUE TITLE
Progress bar ?

### ISSUE THREAD

**Issue by loicpirez** [houtianze/bypy#470]
Hello,

It would be nice to get a progress of a bypy task.
For exemple, an useful one, upload progress.

I know the app is in maintenance mode but I hope you'll consider it.

Thank you.

**Comment by houtianze** [comment]
Hello,

Thanks for the feedback. But currently, there is some progress (albeit in console mode / similar to curl) display when downloading (I forget for uploading if there is one).

Given that I've put it in maintenance mode, I probably won't have time to add more progress anytime soon..
