### ISSUE TITLE
exceptions.ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by wangx404** [houtianze/bypy#471]
Loading Hash Cache File '/home/ubuntu/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
<E> [06:44:54] Exception occurred:
Exception:
<type 'exceptions.ValueError'> - No JSON object could be decoded
Stack:
  File "/home/ubuntu/.local/bin/bypy", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/bypy/bypy.py", line 3700, in main
    perr("Exception occurred:\n{}".format(formatex(ex)))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/bypy/util.py", line 73, in formatex
    type(ex), ex, ''.join(traceback.format_stack()))

Abort
Skip saving Hash Cache since it has not been updated.

**Comment by houtianze** [comment]
Try `rm /home/ubuntu/.bypy/bypy.hashcache.json` and then run again?

**Comment by wangx404** [comment]
I reinstalled it, and the problem was solved. Though I still have no idea about this error.
