### ISSUE TITLE
pip install bypy failed.

### ISSUE THREAD

**Issue by esofar** [houtianze/bypy#475]
esofar@Esofar:~$ pip install bypy
Collecting bypy
  Using cached https://files.pythonhosted.org/packages/c9/c1/3b04879fba0311493a41c1cdd3cd46aa53a6b83d2f92efb4b16e999e2ff4/bypy-1.6.4-py2.py3-none-any.whl
Collecting requests>=2.10.0 (from bypy)
  Using cached https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl
Collecting multiprocess>=0.70.0 (from bypy)
  Using cached https://files.pythonhosted.org/packages/7a/ee/b9bf3e171f936743758ef924622d8dd00516c5532b00a1210a09bce68325/multiprocess-0.70.6.1.tar.gz
Collecting requests-toolbelt>=0.8.0 (from bypy)
  Using cached https://files.pythonhosted.org/packages/97/8a/d710f792d6f6ecc089c5e55b66e66c3f2f35516a1ede5a8f54c13350ffb0/requests_toolbelt-0.8.0-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests>=2.10.0->bypy)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests>=2.10.0->bypy)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.10.0->bypy)
  Using cached https://files.pythonhosted.org/packages/56/9d/1d02dd80bc4cd955f98980f28c5ee2200e1209292d5f9e9cc8d030d18655/certifi-2018.10.15-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.10.0->bypy)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting dill>=0.2.8.1 (from multiprocess>=0.70.0->bypy)
  Using cached https://files.pythonhosted.org/packages/6f/78/8b96476f4ae426db71c6e86a8e6a81407f015b34547e442291cd397b18f3/dill-0.2.8.2.tar.gz
Building wheels for collected packages: multiprocess, dill
  Running setup.py bdist_wheel for multiprocess ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-csKJpc/multiprocess/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp6zs59Gpip-wheel- --python-tag cp27:
  
  
  -----------------------------------------------------------------------
  WARNING: The C extensions could not be compiled
  -----------------------------------------------------------------------
  
  Maybe you do not have a C compiler installed on this system?
  The reason was:
    File "<string>", line 1, in <module>
  
    File "/tmp/pip-build-csKJpc/multiprocess/setup.py", line 415, in <module>
      msg = BUILD_WARNING % '\n'.join(traceback.format_stack())
  
  
  This is just a warning as most of the functionality will work even
  without the updated C extension.  It will simply fallback to the
  built-in _multiprocessing module.  Most notably you will not be able to use
  FORCE_EXECV on POSIX systems.  If this is a problem for you then please
  install a C compiler or fix the error(s) above.
  -----------------------------------------------------------------------
  
  
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for multiprocess
  Running setup.py clean for multiprocess
  Running setup.py bdist_wheel for dill ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-csKJpc/dill/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmptOkPGUpip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for dill
  Running setup.py clean for dill
Failed to build multiprocess dill
Installing collected packages: idna, urllib3, certifi, chardet, requests, dill, multiprocess, requests-toolbelt, bypy
  Running setup.py install for dill ... done
  Running setup.py install for multiprocess ... done
Successfully installed bypy-1.6.4 certifi-2018.10.15 chardet-3.0.4 dill-0.2.8.2 idna-2.7 multiprocess-0.70.6.1 requests-2.20.1 requests-toolbelt-0.8.0 urllib3-1.24.1

**Comment by cris122** [comment]
try 
pip install wheel

**Comment by esofar** [comment]
@cris122 thx
