### ISSUE TITLE
Error 31062

### ISSUE THREAD

**Issue by ahkimkoo** [houtianze/bypy#480]
bypy syncup . / True
<E> [12:20:02] ----------------------------------------------------------------
Error 31062

**Comment by beimengyeyu** [comment]
我这边是上传路径有问题，然后就报这个错误。
比如我这边，
错误的路径:  /usr/local/bin/bypy upload /backup/${backtar}.zip /{APP_DIR:-app}/${backtar}.zip
正确的路径: /usr/local/bin/bypy upload /backup/${backtar}.zip /${APP_DIR:-app}/${backtar}.zip

修改之后就好了。
