### ISSUE TITLE
请教: 登录成功但list出错，error code 31066

### ISSUE THREAD

**Issue by just4id** [houtianze/bypy#488]
Authorizing, please be patient, it may take upto 300 seconds...
Authorizing/refreshing with the OpenShift server ...
OpenShift server failed, authorizing/refreshing with the Heroku server ...
Successfully authorized
<E> [01:32:39] ----------------------------------------------------------------
Error 31066
osmc@osmc:~$ python -m bypy list
<E> [01:33:09] ----------------------------------------------------------------
Error 31066
osmc@osmc:~$ python -m bypy info
Quota: 2.005TB
Used: 849.024GB
osmc@osmc:~$ python -m bypy list
<E> [01:36:06] ----------------------------------------------------------------
Error 31066
osmc@osmc:~$ python -m bypy mkdir /app/bypy
osmc@osmc:~$ python -m bypy list
<E> [01:37:07] ----------------------------------------------------------------
Error 31066
osmc@osmc:~$

**Comment by Wo-Ki** [comment]
I have the save question, and don't know how to solve it.Maybe the file is too big?

**Comment by Eidosper** [comment]
# {u'error_code': 31066, u'error_msg': u'file does not exist'}

maybe some help

**Comment by 7449** [comment]
在 apps目录下手动创建个bypy文件夹

**Comment by mgai** [comment]
> 在 apps目录下手动创建个bypy文件夹

As @7449 mentioned - you need to manually create this `bypy` folder in your `My App Data` folder. I can't remember since when Baidu started to restrict App access to their own folders in the `/apps` folder. So all manipulation that `bypy` can do, is within this folder [`/apps/bypy`].

hth.
