### ISSUE TITLE
详细一点的manual

### ISSUE THREAD

**Issue by Irismoon** [houtianze/bypy#494]
即使看help，也不能确定每个函数如download，的几个问题：
1.是否如果本地和远程有同名文件就保持原状？还是即使同名也会以某种方式确认是否是完全相同的文件，如果完全相同就保持不动，不同就覆盖？那么具体以哪种方式判断呢？
楼主如果有时间的话，或者我们使用者可以组织写个manual:)

**Comment by aflyhorse** [comment]
你说的这几个问题自己做个测试就行了……
* 上传一个文本文件，本地改掉，再下载
* 上传一个文本文件，本地删掉，再删掉云端，再上传；然后拷贝文件内容，搞出新文件，覆盖掉本地文件，再下载

**Comment by Irismoon** [comment]
> 你说的这几个问题自己做个测试就行了……
> 
> * 上传一个文本文件，本地改掉，再下载（测试本地修改情况）
> * 上传一个文本文件，复制本地内容，拷贝出同名新文件，再下载（测试本地同文件不同时间戳情况）
> * 上传一个文本文件，再删掉云端，复制本地内容，拷贝出同名新文件，再通过其他windows/客户端上传，再下载（测试云端同文件不同时间戳情况）

哈！谢谢，我没想到用测试的办法解决。
good to know that.
