### ISSUE TITLE
上传速度特别慢，用客户端上传速度能达 几兆/S ，但是用代码只有 几十k/S。

### ISSUE THREAD

**Issue by MuSaCN** [houtianze/bypy#497]
如题，速度差距这么大， 是需要设置什么吗？
我上传的是一个20兆的压缩文件。

**Comment by yqs112358** [comment]
确实确实，同问

**Comment by yqs112358** [comment]
我把processes提升到了10发现也没有作用。。是百度API那边限速了吗

**Comment by hzhangxyz** [comment]
> 我把processes提升到了10发现也没有作用。。是百度API那边限速了吗

多进程是用来上传不同文件用的，单个文件不能提速
