### ISSUE TITLE
Linux同步上传，文件夹名称仅大小写不同，只能同步一个

### ISSUE THREAD

**Issue by kaloha** [houtianze/bypy#501]
Linux同步上传，文件夹名称仅大小写不同，只能同步一个。
比如上传的同个目录下有：    AAa文件夹和 AAA文件夹，同步上去后，只能看到一个 AAa文件夹，
不知道是否哪里设置或操作的问题？

**Comment by kaloha** [comment]
需要用到这个功能，看有没办法解决，谢谢

**Comment by kaloha** [comment]
知道情况的，麻烦帮忙解答下，谢谢，这个功能对我应用很重要

**Comment by houtianze** [comment]
这个我记得好像上传百度服务端的原因——API本来就不区分文件大小写，所以无法实现。

没记错的话，Windows和Mac的文件系统默认也是不区分大小写的，同名而只是大小写不同的文件传输也容易出问题。所以建议你可能在本地文件命名（或改名）上想些办法。

**Comment by kaloha** [comment]
> 这个我记得好像上传百度服务端的原因——API本来就不区分文件大小写，所以无法实现。
> 
> 没记错的话，Windows和Mac的文件系统默认也是不区分大小写的，同名而只是大小写不同的文件传输也容易出问题。所以建议你可能在本地文件命名（或改名）上想些办法。

ok，谢谢解答。
