### ISSUE TITLE
Connection Error 20191030

### ISSUE THREAD

**Issue by cypares** [houtianze/bypy#504]
![微信截图_20191030171945](https://user-images.githubusercontent.com/57174327/67845170-fb56fb00-fb39-11e9-9a26-3244e78e3436.png)

error type: ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /houtianze/bypy/master/update/update.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002965877F448>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

Issue: 

by = ByPy()

then, error comes out like pics above. 

I try different accounts on different computers, but the results are same. Is there anything wrong with your sever? or any suggestions for solving this? 

Thank you.

**Comment by davidkingzyb** [comment]
It's a temp solution.
edit lib/python3.7/site-packages/bypy/bypy.py
![bypy](https://user-images.githubusercontent.com/6694635/67916614-37896a80-fbd1-11e9-95b4-b1145e48d768.png)

**Comment by cypares** [comment]
> It's a temp solution.
> edit lib/python3.7/site-packages/bypy/bypy.py
> ![bypy](https://user-images.githubusercontent.com/6694635/67916614-37896a80-fbd1-11e9-95b4-b1145e48d768.png)

This is really helpful! Thanks a lot :)
