### ISSUE TITLE
upload接口在网络状况不好的时候会覆盖文件夹

### ISSUE THREAD

**Issue by bdus** [houtianze/bypy#505]
作者好
感谢

我想说#76 的这个bug貌似还在。。

> <I> [23:11:19] Local and remote file hash DOESN'T match
<E> [23:11:19] 'tmp/VCIBafLalv8.mp4' =C=> '/apps/bypy/tmp/VCIBafLalv8.mp4' FAILED.
ans:60;
VCIBafLalv8  uploaded. deleted
upload and delete  88ZSxIF2nW0
===== downloading...  IMCav362q60
downloading  IMCav362q60
<E> [23:11:50] Waiting 10 seconds before retrying...
<E> [23:12:00] Request Try #2 / 5
<E> [23:12:40] Waiting 20 seconds before retrying...
<E> [23:13:00] Request Try #3 / 5
<E> [23:13:08] Waiting 30 seconds before retrying...
<E> [23:13:38] Request Try #4 / 5
<E> [23:13:45] Waiting 40 seconds before retrying...
<E> [23:14:25] Request Try #5 / 5
<E> [23:14:32] Maximum number (5) of tries failed.
[====================] 100% (30.0MB/30.0MB) ETA:  (462kB/s, 1m6s gone) Combining the following MD5 slices:
906d2200414bc7a7ff24bcffd9fdcfbb
77442a14b35f238fda710a037df0a270
<I> [23:15:51] Local and remote file hash DOESN'T match
<E> [23:15:51] 'tmp/88ZSxIF2nW0.mp4' =C=> '/apps/bypy/tmp' FAILED.
ans:60;
88ZSxIF2nW0  uploaded. deleted

记录中在是想把目录tmp下的88ZSxIF2nW0.MP4传到远端tmp目录下 
一开始还是正常的
><E> [23:11:19] 'tmp/VCIBafLalv8.mp4' =C=> '/apps/bypy/tmp/VCIBafLalv8.mp4' FAILED.

但是在多次retry失败的时候
><E> [23:15:51] 'tmp/88ZSxIF2nW0.mp4' =C=> '/apps/bypy/tmp' FAILED.

不知道怎么就变成这样了
然后这样就会将整个文件夹覆盖掉 变成一个叫tmp的文件

目前我直接指定upload的remote地址+文件名 防止出现这个问题

**Comment by houtianze** [comment]
你好，谢谢反馈。这都快三年了，我也不知道还有这个问题没有，我以为 #76 已经解决。。
