### ISSUE TITLE
bypy syncup报错

### ISSUE THREAD

**Issue by g-glory-n** [houtianze/bypy#508]
<E> [12:31:52] Error accessing 'https://pcs.baidu.com/rest/2.0/pcs/file'
<E> [12:31:52] Function: __walk_proceed_remote_dir_act
<E> [12:31:52] Website parameters: {u'path': u'/apps/bypy/Backup/Projects/\u6d41\u5a92\u4f53/SDL2-test', u'order': u'asc', u'limit': u'0-1000', u'method': u'list', u'by': u'name'}
<E> [12:31:52] Waiting 10 seconds before retrying...
<E> [12:32:02] Request Try #2 / 5

**Comment by 1JioAcceleratorW1thNoBrake** [comment]
解决了吗？
