### ISSUE TITLE
一直提示 Local and remote file hash DOESN'T match

### ISSUE THREAD

**Issue by XxXStu** [houtianze/bypy#517]
1. 上传所有文件都出现这个报错
2. 实际去看了百度云盘，文件是上传成功的，看了下文件对比了下也是正确的
3. 计算hash的方式是md5吗，本地对文件用md5sum命令算出来确实和ByPy.list看到的不一样

**Comment by yqs112358** [comment]
同问题，一直未得到修复，希望作者可以关注

**Comment by houtianze** [comment]
参见 #575 ，搞不定 ☺️
