### ISSUE TITLE
你好。我想把目录中的文件下载回来后删除除了目录本身之外都删除如何操作？

### ISSUE THREAD

**Issue by boyyao** [houtianze/bypy#520]
我的目的是一台机器始终下载百度云中的某个目录中的文件（转存进去的文件）。所以用计划任务用如下命令间隔执行
bypy -v --move  downdir / /mnt/Public/download
但是发现--move命令会连通 bypy根目录一起删除。导致第二次执行命令的时候就出错了。有没有办法不要删除当前目录本身？或者有什么其他方法达到我的目的？
就是一直下载某个目录中新增的内容。下载完成后为了防止重复下载就删除已下载的文件和子目录

**Comment by bg4uvr** [comment]
远端建个子目录

bypy -v --move downdir /subdir/ /mnt/Public/download
