### ISSUE TITLE
一直停留在Hash Cache File loaded.不动超过1小时怎么处理

### ISSUE THREAD

**Issue by sw586** [houtianze/bypy#521]
#bypy -v upload /root/ftpbak/ /pw/
Loading Hash Cache File '/root/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.

感谢作者的bypy非常棒，昨天还能正常上传，今天如上一直卡转Hash Cache File loaded.

**Comment by sw586** [comment]
[root@VM_0_11_centos ~]# bypy -v upload /root/qijiftpbak/ /qiji_pw/
Loading Hash Cache File '/root/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
'/root/qijiftpbak/qiji.pw_bak20200326160248.zip' >>==> '/apps/bypy/qiji_pw/qiji.pw_bak20200326160248.zip' OK.
[========____________] 42% (20.0MB/46.9MB) ETA: 3m52s (119kB/s, 2m52s gone) '/root/qijiftpbak/qiji.pw_bak20200326160248.zip' >>==> '/apps/bypy/qiji_pw/qiji.pw_bak20200326160248.zip' OK.
[=================___] 85% (40.0MB/46.9MB) ETA: 59s (119kB/s, 5m45s gone) '/root/qijiftpbak/qiji.pw_bak20200326160248.zip' >>==> '/apps/bypy/qiji_pw/qiji.pw_bak20200326160248.zip' OK.
[====================] 100% (46.9MB/46.9MB) ETA:  (119kB/s, 6m44s gone) Combining the following MD5 slices:
866e56fa4f31ca49c4e7adb1581cc2ba
cbdc4ba85441bf2ac9e473c21adbd76e
549b02cdacde2c60a58f05931268aa70
<E> [16:31:39] Error accessing 'https://pcs.baidu.com/rest/2.0/pcs/file'
<E> [16:31:39] Function: __combine_file_act
<E> [16:31:39] Website parameters: {u'path': u'/apps/bypy/qiji_pw/qiji.pw_bak20200326160248.zip', u'ondup': u'overwrite', u'method': u'createsuperfile'}
<E> [16:31:39] Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=121.6aa2666ec8d3c780a1f13e3dafcb589e.Ymxxn1EI8CEjN8r9Ji0kavnSXFmimgRHRKD1Ilp.bUMFnA&path=%2Fapps%2Fbypy%2Fqiji_pw%2Fqiji.pw_bak20200326160248.zip&ondup=overwrite&method=createsuperfile
<E> [16:31:39] HTTP Response Status Code: 404
<E> [16:31:39] Error JSON returned:{u'error_code': 31066, u'error_msg': u'file does not exist', u'request_id': 1987361688441019059}
Error code: 31066
Error Description: file does not exist
<E> [16:31:39] Website returned: {"error_code":31066,"error_msg":"file does not exist","request_id":1987361688441019059}
<E> [16:31:39] ----------------------------------------------------------------
Error 31066
Skip saving Hash Cache since it has not been updated.

**Comment by houtianze** [comment]
`bypy -c`清除下缓存文件试试？
