### ISSUE TITLE
上传不了

### ISSUE THREAD

**Issue by sw586** [houtianze/bypy#522]
[root@VM_0_11_centos ~]# bypy -v   -f upload /root/qijiftpbak/ /qiji_pw/
<I> [19:36:33] Forced hash recalculation, hash cache won't be used
Loading Hash Cache File '/root/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
'/root/qijiftpbak/site-bak-2020-03-26.tar.gz' >>==> '/apps/bypy/qiji33_pw/site-bak-2020-03-26.tar.gz' OK.
[=====_______________] 29% (20.0MB/67.5MB) ETA: 6m40s (121kB/s, 2m48s gone) '/root/qijiftpbak/site-bak-2020-03-26.tar.gz' >>==> '/apps/bypy/qiji33_pw/site-bak-2020-03-26.tar.gz' OK.
[===========_________] 59% (40.0MB/67.5MB) ETA: 3m52s (121kB/s, 5m37s gone) '/root/qijiftpbak/site-bak-2020-03-26.tar.gz' >>==> '/apps/bypy/qiji33_pw/site-bak-2020-03-26.tar.gz' OK.
[=================___] 88% (60.0MB/67.5MB) ETA: 1m3s (121kB/s, 8m25s gone) '/root/qijiftpbak/site-bak-2020-03-26.tar.gz' >>==> '/apps/bypy/qiji33_pw/site-bak-2020-03-26.tar.gz' OK.
[====================] 100% (67.5MB/67.5MB) ETA:  (120kB/s, 9m34s gone) Combining the following MD5 slices:
bcb85a47c9e09ad435ea8cc90b84ca2a
d0efe80250e0375d62f22cb4364eff9b
3f3c974c4f152ccdcfe7205efd43f6f5
653f8d12845ce362cb94242b66f17bae
<E> [19:46:10] Error accessing 'https://pcs.baidu.com/rest/2.0/pcs/file'
<E> [19:46:10] Function: __combine_file_act
<E> [19:46:10] Website parameters: {u'path': u'/apps/bypy/qij33i_pw/site-bak-2020-03-26.tar.gz', u'ondup': u'overwrite', u'method': u'createsuperfile'}
<E> [19:46:10] Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=121.bae1a225f9e65ca24abda88e6306166d.YCrLeiDuQBmSgbC55MKtxB1GSL_FMGIMvILzaaT.ftu5yg&path=%2Fapps%2Fbypy%2Fqiji_pw%2Fsite-bak-2020-03-26.tar.gz&ondup=overwrite&method=createsuperfile
<E> [19:46:10] HTTP Response Status Code: 404
<E> [19:46:10] Error JSON returned:{u'error_code': 31066, u'error_msg': u'file does not exist', u'request_id': XXXXXXX}
Error code: 31066
Error Description: file does not exist
<E> [19:46:10] Website returned: {"error_code":31066,"error_msg":"file does not exist","request_id":XXXXXXX}
<E> [19:46:10] ----------------------------------------------------------------
Error 31066
Saving Hash Cache...
Hash Cache saved.
[root@VM_0_11_centos ~]#

**Comment by zhnivn** [comment]
同样 31066，上传压缩包，之前自动传没问题

**Comment by mango7404** [comment]
目前还是不行，有人解决了吗？

**Comment by cyklu** [comment]
@mango7404 应急小白办法: 它说"没文件"就先"有文件", 上传空文件是行的, 再上传文件取代空文件, <D> 200 OK, processing action...

**Comment by mango7404** [comment]
@cyklu 亲测可以，感谢呀兄弟！！

**Comment by ModernCrusade** [comment]
@cyklu 亲测可以，感谢！

**Comment by bg4uvr** [comment]
加"-s 1T"参数试试

**Comment by tizee** [comment]
> @mango7404 应急小白办法: 它说"没文件"就先"有文件", 上传空文件是行的, 再上传文件取代空文件, 200 OK, processing action...

确实可行👍的方法。
看起来错误不在于代码，而是[百度开放平台pcs](https://openapi.baidu.com/wiki/index.php?title=docs/pcs/rest/file_data_apis_list#.E5.88.86.E7.89.87.E4.B8.8A.E4.BC.A0.E2.80.94.E6.96.87.E4.BB.B6.E5.88.86.E7.89.87.E5.8F.8A.E4.B8.8A.E4.BC.A0)的接口的处理逻辑发生了变化，因为之前很长一段时间分片上传时没有这种情况发生。另外，而按照现在[百度网盘开放平台文件上传文档](https://pan.baidu.com/union/document/upload#通用参数)的说法:```文件上传分为三个阶段：预上传、分片上传、创建文件。只有完成这三步，才能将文件上传到网盘。```（虽然现在这个开放平台并不对个人用户开放）

我这里为了避免每次都需要手动操作，就稍微修改下源码。

### 添加一段预上传的逻辑处理
通过分片上传新文件时，分片合并阶段百度云端并没有实际的文件导致出错，因此可以采取预上传的思路，只要在分片合并之前上传一个同名空文件来简单修复这个bug。
在源文件bypy.py的[1548L](https://github.com/houtianze/bypy/blob/master/bypy/bypy.py#L1548)前添加一段上传同名空文件的逻辑处理即可。

```python
...
# workaround for issue#522
pars = { 
                'method' : 'upload',
	        'path' : remotepath,
		'ondup' : ondup }
# upload an empty file 
self.__stream_upload("",pars, self.__upload_one_file_act, remotepath)
ec = self.__combine_file(remotepath, ondup = 'overwrite')
...
```

可以再加一个预上传的信息处理来避免大小不一致的报错。
```python
def __preupload_file_act(self,r,args):
    self.pv("'{}' ==> '{}' preupload empty file".format(self.__current_file, args))

...
# workaround for issue#522
pars = { 
                'method' : 'upload',
	        'path' : remotepath,
		'ondup' : ondup }
# upload an empty file 
self.__stream_upload("",pars, self.__preupload_file_act, remotepath)
ec = self.__combine_file(remotepath, ondup = 'overwrite')
...
```

**Comment by bg4uvr** [comment]
@tizee 大侠帮我看看 #524 这个问题有没办法解决，感觉像是软件读取到的本地和远程文件MD5不同造成的，谢谢啦~

**Comment by tizee** [comment]
> @tizee 大侠帮我看看 #524 这个问题有没办法解决，感觉像是软件读取到的本地和远程文件MD5不同造成的，谢谢啦~

🤔实际上我也遇到这个问题，根据代码中的注释，看起来百度云接口返回的md5与本地不
不一致是[百度云方面的问题](https://github.com/houtianze/bypy/blob/master/bypy/bypy.py#L10)。

 本来打算pull request修复这个分片合并新文件的bug，但是运行测试脚本时发现non-slicing uploading（普通方式上传单个文件）用的a.txt的md5和接口返回的md5不一致，导致第一个测试无法通过（虽然已经成功上传到百度云）。让人疑惑的地方是，从百度云下载之前上传的a.txt的md5与原来本地的a.txt的md5一致（linux环境下使用md5sum得到），也与调试信息中的本地文件md5一致，这让我怀疑是百度云的md5算法的问题🧐。

#524 的问题我看了下[syncup函数](https://github.com/houtianze/bypy/blob/master/bypy/bypy.py#L2889).

```python
...
	def syncup(self, localdir = '', remotedir = '', deleteremote = False):
		''' Usage: syncup [localdir] [remotedir] [deleteremote] - \
sync up from the local directory to the remote directory
  localdir - the local directory to sync from if not specified, it defaults to the current directory.
  remotedir - the remote directory at Baidu Yun (after app's directory) to sync to. \
if not specified, it defaults to the root directory
  deleteremote - delete remote files that are not inside the local directory, default is Fals
...
```
默认情况`deleteremote = False`，这表示不会删除本地没有的远程文件。

而syncup函数底层也调用了[__upload_file函数](https://github.com/houtianze/bypy/blob/master/bypy/bypy.py#L1694)，上述修改的是[__upload_file中的__upload_file_slices方法](https://github.com/houtianze/bypy/blob/master/bypy/bypy.py#L1724)，即非RapidUpload或non-slicing upload方式，因此看起来之前的补救的措施可以对你的问题奏效，即通过预上传空文件的方式来解决31066文件不存在错误。
其中non-slicing upload方式针对的是小文件，而运行测试脚本时发现非空小文件的md5不一致，这导致的报错我也束手无策。

其中non-slicing upload针对的是小文件
> very small file, must be uploaded manually and no slicing is needed

**Comment by bg4uvr** [comment]
@tizee 感谢回复，现在31066无法上传的问题用你的方法已经解决，md5不一致看来目前无解。但上传好了已经可以了，只是浪费些时间而已，本来也是无人值守自动运行的，所以除了强迫症心里有点不舒服外没啥影响，谢谢你😄
