### ISSUE TITLE
Error 31066 上传大文件失败

### ISSUE THREAD

**Issue by milabobo** [houtianze/bypy#523]
最近出现的，上传任何一个大文件必现失败（大于1G左右），在最后上传100%结束的时候失败

bypy v1.6.7

bypy upload xxx.tar.gz

[===_________________] 17% (380.0MB/2.1GB) ETA: 1h5m (474kB/s, 13m40s gone) <E> [15:48:47] Waiting 10 seconds before retrying...
<E> [15:48:57] Request Try #2 / 5
<E> [15:53:57] Waiting 20 seconds before retrying...
<E> [15:54:17] Request Try #3 / 5
<E> [15:54:58] Waiting 30 seconds before retrying...
<E> [15:55:28] Request Try #4 / 5
<E> [15:56:09] Waiting 40 seconds before retrying...
<E> [15:56:49] Request Try #5 / 5
<E> [15:57:30] Maximum number (5) of tries failed.
<E> [15:57:30] Slice MD5 mismatch, waiting 10 seconds before retrying...
<E> [15:57:40] Retrying #2 / 5

[====================] 100% (2.1GB/2.1GB) ETA:  (400kB/s, 1h33m gone) Combining the following MD5 slices:
21e65d36f295e651dc2e05d14e9e92dd
3f96d0ee38fc021c2acfe8715bc0df83
d46d185a247798ac55d88196d010fe19
7f537c31af269b13113b3d451c36e515
44a0da32e061bdd44469f85374211855
c222cf7a62672847b744c042ec7e04b5
155eb335074247325c762ba881ccfe28
f5e9e83693d2299c367b979b1afd63a4
070ba7181458528e5bf8aca388493f54
746452c007ab7d3829cb2dd76b724cad
31612fc98949557c5a2a33b51393d48c
d727ef9736cf1c5de957f0efce1f2df6
8b39e3befa7326db0d8c1fb54ee1db2e
4d405d38835ebb3a75970f27e63f7276
a129542acc7308839d6113ec8dc47294
4203f03e615d8ba6a44a36604387c4eb
f4003f5ba8ab336c9b044cad05419069
1b128bf4682f9d73299b3afb0d83159a
277878f09d7d63e2167002e10a1b9bd3
5f008435bb5a71330a405cf92e5a28f8
5a52a3c9b624ad91227e818a5882594d
d6d6826ec8a67957444f138dd275f502
451fe0efa0f4132c6ae85e8d9dee31d9
5d204527bf9181decaa492d62ee40848
d813a0c5edddbec53b43d4253808fe6f
571a43b50f754cb69045f17c28d1685b
5b1bbfde9d95cdb9cff02a7db2bcb5f5
cd7c404957c9fd12a4a6a16f02f31e54
4c406909f37cc19293175346317721f9
380b13bacefdaef6ff5b915704f486c7
5eee90acdcc6ab355b3aabf4b1804318
b4b11243791f6f34002d7d1d155caf5d
24715e1205c2365e0b35d5dfd1a04b99
7ddb1eeeacf1a8ae07fc10a559b09764
b03b67a21920a6b9c7fe41d3a1eb88c9
937ddb51450eaebccd7a75c98fef023a
bf84fb70a1ce35cf65debf5fdfb05838
66b4d0bdb458b2e9bb1c87d9b4b183ab
79575b31637b9e8701b1f2e4f024e93b
1cccddcfc63433b9c3debc24ca4f1cec
5ccdd5b2a05c83a512f45cb01aa689aa
9d10c7739d0a2755db0d502357ca02d6
abb36afea5798cd92dd39a84549ccc94
2db4554bc1439dd773d35eb01dc7ffe4
65d7c00379794188921e274ad5426627
5a3fd5454b717ec2123f1abde53545e3
dcbce690181fb1e0571f816940893d2d
a62ffd3dbf805350ea8fc30f33c47823
fd8426454d5e30ffbcfe1085c2fd63f0
e5aeeeaddbfa4e6335e78edbe30a84cb
be5c2403a43057c7b8d4ca901ed98148
22980d279ecc13553e7804bf0e204cf4
23239e372d6a1464b68921ad0ca098d7
86024c7d88d98357036acd8d4ad9718d
498ba92e9be4c7b15d06f7dda28108c2
674664a337ac7c4198a31d8c727a921d
cce4b3a5dc645bfd5ffe882689a6f8c9
6c97554d627a7e690fcfa552157ac19b
6ce8095fd51fb97dcc18a784840e6d46
d7636ad6cd21d0548b8b5182ce8484a0
1f691f23a9a8e67bd9b410beeedbae42
9f885ea169efd67896ab235e24a2c4b5
5de6110834a42b198569f654b699cd67
9a43c2f4a5d3e6a7ee5bc456271abf39
e03e54702dbb98c11b690e31f2f5a1f5
c2686919f62f054177634b41b5a5c8e2
0b4c30458a380ff6a56df9000f5047e5
bc7114db2cf3c9a5eea793ba58f5ddb3
fafc45ec527fcdfe91c221fe6f505106
7a6c357ce55e28e0020ebe861bd764d5
b715ac65ae82d182db50b2d1e73dc836
b3ce55e3164def64d01a215ffd684890
656bf7cbb93fa6433bd1b9dd850556d7
1eab278b99cc4292484207f8427788f2
dc6cf4c535cd23e6de610f8f24f4564f
c7641654059775666634239366d607f7
e7f0a76d0d63b9672dbbf44213e8f773
0a03a422a9e63a61af011d70add6f9e3
95b6860321fbbfa611c1761cbfe46127
7c1f260c9c16dae616e4a6b39b5b8665
9dc5684252bbe0fc437a4776373bd511
ed32a243e00e59119db56a9a3893caaf
f9e58d0daa62899ebed9e9e708a4582f
509c936f9771cc06bb49086fc5376930
fe38d02387110a6f0fe5fe365f8a4e77
75136ea3cf85373fb8519c64ffb2d4a6
522cde27d4a46824969c9fd5ecb37bae
edc73ac5bbd54fe969c1eee7fc5c70e2
f40793a30b54d0c2ecaf2244363817e7
21eaa12f231254b68e4aec38ba69a55d
36b6b2c953a8be679ce907f716fc053e
ad986aa6823766177b6a5daf947c5330
6f91689bb3afc84ee0dbe2ac8456513c
0fcddb9ffefdc1556bb0e9843728481a
b8f3316f4a3be4b909b6e63742b9b6b1
f3a391fe68761ae5bba6868ab458566d
178685d37a71e33c038a03c9b45e9ae0
246970abeed54b1b315d6890a06b5e02
1aae97f648c2e0d5223f76590a292ef2
d7d17c30b119fe498afc081c57bea8d7
2f1a4f77d6b0aa7f9e88dfe4d163acda
b77797d1f7d41e435d35edc9997c6caa
0bb35fe8ce047dc0dfe092691a49195c
938a2e6e63c52a0a28906bb583adbd68
501d6867c2078f4c05243d210b552c96
ee8457bbeaeaa4dbbb013777f59601e5
5d7b73be34931344a26568b7aebe077d
3230c56e6961d3a8f8de90da073c182d
546733fe77ff48081d15699f1194d49c
a56c6fd501db7ad0d768fb260fe6358d
<E> [17:03:17] ----------------------------------------------------------------
Error 31066

**Comment by ModernCrusade** [comment]
我这才35M，上传也出错，肯定和大文件无关。

ming@raspberrypi:~/Videos$ ls -al
total 34904
drwx------  2 ming ming     4096 Mar 30 23:00 .
drwx------ 26 ming ming     4096 Mar 30 23:02 ..
-rwxr-xr-x  1 ming ming 35731768 Mar 30 22:37 News.mp4

ming@raspberrypi:~/Videos$ bypy upload News.mp4 
Combining the following MD5 slices:
f91c11cb0a1ded58bea7d5f8176d971f
649bd3961f04806f5f97567db00feee6
<E> [23:03:30] ----------------------------------------------------------------
Error 31066

**Comment by ModernCrusade** [comment]
参考编号#522的临时性方法绕过去吧，但是请作者尽快找到问题，做到代码里去。

**Comment by milabobo** [comment]
@ModernCrusade 确实可以，谢谢了。

**Comment by bg4uvr** [comment]
加 ”-s 1T“ 参数即可

**Comment by milabobo** [comment]
@bg4uvr -s1T 测试过，无法上传超过2G的文件，一上来就失败并重试直到重试用完

**Comment by bg4uvr** [comment]
> @bg4uvr -s1T 测试过，无法上传超过2G的文件，一上来就失败并重试直到重试用完

那我试试 -s 2G吧，哈哈

**Comment by bg4uvr** [comment]
> > @bg4uvr -s1T 测试过，无法上传超过2G的文件，一上来就失败并重试直到重试用完
> 
> 那我试试 -s 2G吧，哈哈

唉，经测试不行，出现其实错误。现在这个完全用起来了。
