### ISSUE TITLE
syncup会删除远端并未改变过的文件，重新RapidUpload上传（以及31066错误）

### ISSUE THREAD

**Issue by bg4uvr** [houtianze/bypy#524]
测试状态如下：

```
Hash Cache File loaded.
Gathering local directory ...
Done
Gathering remote directory ...
Done
Comparing ...
Done
Deletion request '****827236243856446' OK
Use 'list' command to confirm
RapidUpload: './WinXP_Nin1.iso' =R=> '/apps/bypy/test/WinXP_Nin1.iso' OK.
Skip saving Hash Cache since it has not been updated.
```

syncup会删除远端并未改变过的文件，重新RapidUpload上传。此问题产生估计有半个月左右了，我有大约90GB的文件，约13000个文件，450个文件夹，设置为每天自动syncup，在文件改动很少的情况下，执行一次大约20分钟左右，但最近发现每执行一次竟然需要约8个小时才能完成。一开始并未在意，但是后来发现云端会缺少最后编辑过的文件，造成云端文件越来越少。经过多次检查，发现是前面几位网友提到的31066错误的问题，新文件（即云端没有，不能RapidUpload的文件）无法上传。

感谢作者提供这么好的软件，若有时间希望早日修复，再次感谢~

**Comment by bg4uvr** [comment]
要么是我记错原来完成一次的时间了么？

**Comment by bg4uvr** [comment]
仔细研究了一段时间得出的个人理解，不一定正确，仅供参考：

1、为什么云端已存在的文件，会重新上传。
由于未知原因，软件读取到的本地文件和云端文件校验值不同，认为文件已经改变，所以重新上传。解决方法：无。

2、为什么会产生31066错误，无法上传文件。
默认传送时大文件以20MB分片传输，由于未知原因，合并后本地和云端校验不同，以至云端无法创建文件。解决方法：加 "-s 1T"参数即可。

**Comment by tjysdsg** [comment]
我遇到了同样的问题，希望开发者早日fix，谢谢！！

**Comment by yaodwwy** [comment]
同样问题，远程文件被不断覆盖！

**Comment by yaodwwy** [comment]
```
root@raspbian:/mnt/baiduyun/test# bypy ls /test

/apps/bypy/test ($t $f $s $m $d):
F test.jar 5 2020-06-12, 10:24:24 dd2ccc085h43314d0238e72e5e60815f
F 测试.jar 5 2020-06-12, 10:24:26 dd2ccc085h43314d0238e72e5e60815f
```
```
root@raspbian:/mnt/baiduyun/test# sha1sum -b *

4e1243bd22c66e76c2ba9eddc1f91394e57f9f83 *test.jar
4e1243bd22c66e76c2ba9eddc1f91394e57f9f83 *测试.jar
```
```
root@raspbian:~/.bypy# cat bypy.hashcache.json | grep d8e8fca2dc0f896fd7cb4cb0031ba249
      "md5": "d8e8fca2dc0f896fd7cb4cb0031ba249",
      "md5": "d8e8fca2dc0f896fd7cb4cb0031ba249",
root@raspbian:~/.bypy# cat bypy.hashcache.json | grep dd2ccc085h43314d0238e72e5e60815f

```

看起来是hash方法不一致了，总会被当作新的上传并替换远程文件。

**Comment by yaodwwy** [comment]
pi@raspbian:~$ bypy -V

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Baidu PCS currently gives totally WRONG MD5 hash for remote files, and I AM NOT GOING TO ADAPT TO IT!
So it if doesn't work, install version '1.6.10' using the following command:
pip install bypy==1.6.10
Version 1.6.10 has a workaround for this.
### Seeking maintainer fo this `bypy` project, if you are interested, please create an issue at github, thanks. ###
----------------------------------------------------------------
百度云盘返回的MD5全错了，鬼知道他们什么时候会改回来！现在代码是按照MD5值是正确的前提来写的，不会改。
所以你发现比较功能等不能正确工作时，请安装 1.6.10 版本：
pip install bypy==1.6.10
1.6.10版有个临时解决方案。
### 寻求这个`bypy`项目维护者，有意的话请去github上建issue，谢谢。###
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

bypy v1.6.11

**Comment by houtianze** [comment]
嗯，貌似现在百度把`md5`放到`block_list`里面去了，然后`md5`里面是啥我也不知道，可以试试上一个版本的临时解决方案：

`pip install bypy==1.6.10`

**Comment by bg4uvr** [comment]
一直只看了代码页的 README.md 说明，竟然没有注意到已经出了很多次新版了，试用了 v1.6.10 版本已经解决问题，感谢作者，也感谢楼上面的提醒。

现在满血复活，爽~
