### ISSUE TITLE
如何配置Aria2的RPC参数？

### ISSUE THREAD

**Issue by csyslabs** [houtianze/bypy#526]
已经翻遍了issue没有相关问题。只在help中看到可以为downloader指定arguments，但是具体使用方法不知道。默认参数是{'aria2': '-c -k10M -x4 -s4 --file-allocation=none'}，看不明白。
真心求助。

**Comment by ESP0xA** [comment]
这个默认参数搞明白了是aria的配置参数，但是RPC相关参数如何设置呢？
运行`bypy downfile "听风吹雨.rar" /home/bypyGo --downloader aria2`
出现如下错误
`[ERROR] IPv4 RPC: failed to bind TCP port 6800
Exception: [SocketCore.cc:312] errorCode=1 Failed to bind a socket, cause: Address already in use`

**Comment by zyOverture** [comment]
先设置一个环境变量 
export DOWNLOADER_ARGUMENTS="-c -k10M -x10 -s10 --file-allocation=none"
用aria2下载时会使用这个环境变量里面的参数
