### ISSUE TITLE
上传文件失败 HTTP Response Status Code: 408

### ISSUE THREAD

**Issue by railannad** [houtianze/bypy#529]
root@ip-172-26-XX-XXX:~# bypy -v -s 3MB upload kurumi.mkv 爷的服务器
Loading Hash Cache File '/root/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
'kurumi.mkv' >>==> '/apps/bypy/爷的服务器/kurumi.mkv' OK.
[____________________] 1% (18.0MB/1.4GB)  <E> [02:11:50] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [02:11:50] Function: __upload_slice_act
<E> [02:11:50] Website parameters: {u'type': u'tmpfile', u'method': u'upload'}
<E> [02:11:50] Waiting 10 seconds before retrying...
<E> [02:12:00] Request Try #2 / 5
<E> [02:12:21] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [02:12:21] Function: __upload_slice_act
<E> [02:12:21] Website parameters: {u'type': u'tmpfile', u'method': u'upload'}
<E> [02:12:21] Full URL: https://c.pcs.baidu.com/rest/2.0/pcs/file?access_token=121.33c8355f3517e42972345c6161e5353e.YnrL9vE5V8qpRIG8Zekr_DjBNgKgzWK2JCsDvRL.sFfIPQ&type=tmpfile&method=upload
<E> [02:12:21] HTTP Response Status Code: 408
<E> [02:12:21] Error JSON returned:{u'error_code': 31233, u'error_msg': u'read request body timeout'}
Error code: 31233
Error Description: read request body timeout
<E> [02:12:21] Website returned: {"error_code":31233, "error_msg":"read request body timeout"}
<E> [02:12:21] Waiting 20 seconds before retrying...
<E> [02:12:41] Request Try #3 / 5
<E> [02:13:22] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [02:13:22] Function: __upload_slice_act
<E> [02:13:22] Website parameters: {u'type': u'tmpfile', u'method': u'upload'}
<E> [02:13:22] Full URL: https://c.pcs.baidu.com/rest/2.0/pcs/file?access_token=121.33c8355f3517e42972345c6161e5353e.YnrL9vE5V8qpRIG8Zekr_DjBNgKgzWK2JCsDvRL.sFfIPQ&type=tmpfile&method=upload
<E> [02:13:22] HTTP Response Status Code: 408
<E> [02:13:22] Error JSON returned:{u'error_code': 31233, u'error_msg': u'read request body timeout'}
Error code: 31233
Error Description: read request body timeout
<E> [02:13:22] Website returned: {"error_code":31233, "error_msg":"read request body timeout"}
<E> [02:13:22] Waiting 30 seconds before retrying...
<E> [02:13:52] Request Try #4 / 5
<E> [02:14:35] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [02:14:35] Function: __upload_slice_act
<E> [02:14:35] Website parameters: {u'type': u'tmpfile', u'method': u'upload'}
<E> [02:14:35] Full URL: https://c.pcs.baidu.com/rest/2.0/pcs/file?access_token=121.33c8355f3517e42972345c6161e5353e.YnrL9vE5V8qpRIG8Zekr_DjBNgKgzWK2JCsDvRL.sFfIPQ&type=tmpfile&method=upload
<E> [02:14:35] HTTP Response Status Code: 408
<E> [02:14:35] Error JSON returned:{u'error_code': 31233, u'error_msg': u'read request body timeout'}
Error code: 31233
Error Description: read request body timeout
<E> [02:14:35] Website returned: {"error_code":31233, "error_msg":"read request body timeout"}
<E> [02:14:35] Waiting 40 seconds before retrying...

大佬你好，昨天晚上上传了个10+MB的小文件没问题，今天上传个1.44GB的视频就出错了，刚开始是在"Hash Cache File loaded"卡住了好久，然后CTRL+C中断了又重开，后来就报错了

**Comment by Joker-Ya** [comment]
我的问题跟你一样，不知道大佬现在解决了么？
小文件上传正常，上传视频就不行

**Comment by houtianze** [comment]
408 Request Time out。可能是网络问题。
