### ISSUE TITLE
<E> [20:05:54] Fatal: All server authorizations failed.

### ISSUE THREAD

**Issue by Goforitzjl** [houtianze/bypy#531]
Authorizing, please be patient, it may take upto 300 seconds...
Authorizing with the Heroku server ...
Heroku server failed, authorizing with the Heroku1 server ...
Heroku1 server failed, authorizing with the Vercel server ...
Vercel server failed. Last resort: authorizing with the GAE server ...
<E> [20:05:54] Fatal: All server authorizations failed.
<I> [20:05:54] ----------------------------------------------------------------
<I> [20:05:54] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.
-----------------------------------------------------------------------------------------------
I hava tried your advices,but they did't work.Can you give me other solutions?Thank you very much!

**Comment by houtianze** [comment]
Thanks for feeding back.

However, I just tried myself, both authorisation and token refreshing work fine. Are all these servers blocked at your network?

**Comment by Goforitzjl** [comment]
[root@iZwz990gu55chz6pucdrd5Z bin]# ./bypy info
Please visit:
https://openapi.baidu.com/oauth/2.0/authorize?client_id=q8WE4EpCsau1oS0MplgMKNBn&response_type=code&redirect_uri=oob&scope=basic+netdisk
And authorize this app
Paste the Authorization Code here within 10 minutes.
Press [Enter] when you are done
57dddd4420494d54995d511e40a7d46f
Authorizing, please be patient, it may take upto 300 seconds...
Authorizing with the Heroku server ...
Heroku server failed, authorizing with the Heroku1 server ...
Heroku1 server failed, authorizing with the Vercel server ...
Vercel server failed. Last resort: authorizing with the GAE server ...
<E> [23:12:16] Fatal: All server authorizations failed.
<I> [23:12:16] ----------------------------------------------------------------
<I> [23:12:16] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.
[root@iZwz990gu55chz6pucdrd5Z bin]# 
------------------------------------------------------------------------------------------------------------
**Thank you for your reply!The above are complete informations.I am in China.Are all these servers blocked by Great Wall?**

**Comment by houtianze** [comment]
Not sure. You can run `bypy -dv` and and post the result here.
