### ISSUE TITLE
大尺寸文件似乎无法实现秒传

### ISSUE THREAD

**Issue by bg4uvr** [houtianze/bypy#533]
我测试了1.6.10版和1.6.11版，发现我的私人文件（个人网盘中已有2个以上副本存在），超过分片传输尺寸的（20MB以上），很多 .ZIP 文件和 .MOV 文件，都无法秒，要实际慢慢上传。

**特别是1.6.10版，当前目录已经存在相同的文件的情况下，仍然会重新实际慢慢上传一次**

因为文件数量非常多，我没能确认是否所有20MB以上的文件都是这样，或是只有20MB以上的 .ZIP 和. MOV 文件这样。

我不知道这是因为是私人文件，云端副本很少的原因，还是 bypy 软件的原因。（不过我猜测这更可能又是百度的MD5错误造成的，因为出问题的文件全是需要分片传输的大尺寸文件）

**Comment by bg4uvr** [comment]
试着把.mov文件压缩成.7z文件，传过一次后，竟然就可以rapid上传了，看来和文件类型有关。

不过 v1.6.10版本，仍然会把这这类文件删除后重新rapidupload，感觉百度这个md5实在是乱套……

**Comment by bg4uvr** [comment]
经过反复测试，结果如下：
1、所有原来不能秒传的 .mov 文件（注意，这些文件是日常手机正常拍摄的视频，并非色情类的非法文件），经过压缩为 .7z文件，上传一次后，都可以秒传了。
这里需要注意一点，压缩为.7z文件，是使用的 CryptSync 软件自动进行的加密压缩。
2、分析了其他无法秒传的 .zip 文件，发现一个规律，就是这些文件中有一部分（并不是全部）是包括了软件注册机之类的压缩包。

个人猜测：
某些文件不能秒传，并非客户端软件问题，而是百度网盘存在某种判断机制机，认为这些文件不合规（认为有可能包含色情/破解/D版之类的内容），这个判断机制本身的正确率并不高，以致某些类型的文件会遭到误伤。

简便的解决方法就是，把这些不能秒传的文件，更改压缩类型或压缩参数，重新压缩一下即可。

**Comment by bg4uvr** [comment]
所有之前不能秒传的文件，经过重新压缩为.7z或.zipx格式，再上传一次后，都可以秒传了。这对于有每天都需要重复备份大量文件的需求的人很重要，可以避免浪费大量时间。

现在我确认百度对以下格式的文件类型存在审查（并且误判率非常高），以至于无法秒传：
.mov
.zip
.rar
.exe

**Comment by houtianze** [comment]
谢谢提供这些测试出来的信息 👍
