### ISSUE TITLE
访问超过1000个文件的目录仍然会显示不全？

### ISSUE THREAD

**Issue by HViktorTsoi** [houtianze/bypy#534]
下载或者ls超过1000个文件的目录时，仍然会在第1000文件后截断，请问这个问题在readme里说已经解决了，是这部分在最新的release里还没有更新进去嘛？

版本1.6.11和版本1.6.10都尝试过了，都存在这个问题；

问题截图：
![image](https://user-images.githubusercontent.com/25725035/84570852-85e72480-adc2-11ea-834f-da619057d3a7.png)
在第1000个文件后就截断了，这个目录下原本有2191个文件

**Comment by houtianze** [comment]
谢谢反馈。

能帮帖一下`bypy ls -dv <your dir>`的输出吗？想确认下`ls`是不是能列出全部文件。

**Comment by ffxisf** [comment]
加上指定返回数量比较好，经常有超过1000个文件的目录

**Comment by zhoujingyu13687306871** [comment]
> 加上指定返回数量比较好，经常有超过1000个文件的目录

这个该怎么加呢？你那边尝试成功了没？我这边超过4000个文件，下载1000个就下载不动了

**Comment by houtianze** [comment]
最新版应该已经修复这个问题。
