### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by lifeike** [houtianze/bypy#537]
helloworld 22:16:20 bypy --version
bypy v1.6.10
helloworld 22:16:23 uname
Linux
helloworld 22:16:27 uname -r
5.3.0-59-generic
helloworld 22:16:34 bypy list
/apps/bypy ($t $f $s $m $d):
F 07夜场.mp4 1264360969 2020-07-04, 21:25:56 dabde072337427fa157e856377a9165e
F hello 0 2020-07-04, 21:24:51 8e23f7635tb64136eddb0719602bc477
F nihao 0 2020-07-04, 21:30:15 8e23f7635tb64136eddb0719602bc477
helloworld 22:16:39 bypy compare
==== Same files ===
F - nihao
F - hello
==== Different files ===
==== Local only ====
==== Remote only ====
F - 07夜场.mp4

Statistics:
--------------------------------
Same: 2
Different: 0
Local only: 0
Remote only: 1
helloworld 22:16:57 bypy -dv downdir /
<D> [22:17:08] Using requests.packages.urllib3 to disable warnings
<D> [22:17:08] Using urllib3 to disable warnings
Loading Hash Cache File '/home/feeco/.bypy/bypy.hashcache.json'...
Hash Cache File loaded.
----
Verbose level = 1
Debug level = 1
Config directory: '/home/feeco/.bypy'
Token file: '/home/feeco/.bypy/bypy.json'
Hash Cache file: '/home/feeco/.bypy/bypy.hashcache.json'
App root path at Baidu Yun '/apps/bypy'
sys.stdin.encoding = UTF-8
sys.stdout.encoding = UTF-8
sys.stderr.encoding = UTF-8
----

<D> Token loaded:
<D> {u'access_token': u'121.ed4bc5138f16124871f96671e74178cc.Y52yk9mBOZUXOdmDMnZpcJB11Jw8yViHaGzRdIw.i3vM2Q', u'expires_in': 2592000, u'session_secret': u'', u'scope': u'basic netdisk', u'session_key': u'', u'refresh_token': u'122.b0d7b136cd5d23a51afbc7a48fcbf5a9.YmsAZr2Pj28FPSsMJkuGTtR8eOf5nfrdUkoYnmT.gglK8w'}
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: ([], [])
<D> Params: {u'path': u'/apps/bypy', u'order': u'asc', u'limit': u'0-1000', u'method': u'list', u'by': u'name'}
<D> Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=121.ed4bc5138f16124871f96671e74178cc.Y52yk9mBOZUXOdmDMnZpcJB11Jw8yViHaGzRdIw.i3vM2Q&order=asc&method=list&limit=0-1000&path=%2Fapps%2Fbypy&by=name
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> Request OK
<D> Downloading '/apps/bypy/07夜场.mp4' as '07夜场.mp4'
<D> Getting info of remote file '/apps/bypy/07夜场.mp4' for later verification
<D> __get_file_info(): rdir : /apps/bypy | rfile: 07夜场.mp4
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/07\u591c\u573a.mp4', [])
<D> Params: {u'path': u'/apps/bypy', u'order': u'asc', u'limit': u'0-1000', u'method': u'list', u'by': u'name'}
<D> Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=121.ed4bc5138f16124871f96671e74178cc.Y52yk9mBOZUXOdmDMnZpcJB11Jw8yViHaGzRdIw.i3vM2Q&order=asc&method=list&limit=0-1000&path=%2Fapps%2Fbypy&by=name
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> List json: {u'list': [{u'local_mtime': 1461016701, u'share': 0, u'app_id': 250528, u'oper_id': 3338694264, u'mtime': 1593919556, u'local_ctime': 1461016701, u's3_handle': u'', u'size': 1264360969, u'category': 1, u'user_id': 78104352, u'privacy': 1, u'unlist': 0, u'server_atime': 0, u'status': 0, u'server_filename': u'07\u591c\u573a.mp4', u'server_ctime': 1461016702, u'fs_id': 620485307578494, u'block_list': [u'dabde072337427fa157e856377a9165e'], u'path': u'/apps/bypy/07\u591c\u573a.mp4', u'md5': u'dabde072337427fa157e856377a9165e', u'isdir': 0, u'ctime': 1461016702, u'server_mtime': 1593919556}, {u'local_mtime': 1593919491, u'share': 0, u'app_id': 1572671, u'oper_id': 0, u'mtime': 1593919491, u'local_ctime': 1593919491, u's3_handle': u'', u'size': 0, u'category': 6, u'user_id': 78104352, u'privacy': 0, u'unlist': 0, u'server_atime': 0, u'status': 0, u'server_filename': u'hello', u'server_ctime': 1593919491, u'fs_id': 766123144686146, u'block_list': [u'd41d8cd98f00b204e9800998ecf8427e'], u'path': u'/apps/bypy/hello', u'md5': u'8e23f7635tb64136eddb0719602bc477', u'isdir': 0, u'ctime': 1593919491, u'server_mtime': 1593919491}, {u'local_mtime': 1593919815, u'share': 0, u'app_id': 1572671, u'oper_id': 0, u'mtime': 1593919815, u'local_ctime': 1593919815, u's3_handle': u'', u'size': 0, u'category': 6, u'user_id': 78104352, u'privacy': 0, u'unlist': 0, u'server_atime': 0, u'status': 0, u'server_filename': u'nihao', u'server_ctime': 1593919815, u'fs_id': 98604871236973, u'block_list': [u'd41d8cd98f00b204e9800998ecf8427e'], u'path': u'/apps/bypy/nihao', u'md5': u'8e23f7635tb64136eddb0719602bc477', u'isdir': 0, u'ctime': 1593919815, u'server_mtime': 1593919815}], u'request_id': 4325738430360500105}
<D> File info json: {u'local_mtime': 1461016701, u'share': 0, u'app_id': 250528, u'oper_id': 3338694264, u'mtime': 1593919556, u'local_ctime': 1461016701, u's3_handle': u'', u'size': 1264360969, u'category': 1, u'user_id': 78104352, u'privacy': 1, u'unlist': 0, u'server_atime': 0, u'status': 0, u'server_filename': u'07\u591c\u573a.mp4', u'server_ctime': 1461016702, u'fs_id': 620485307578494, u'block_list': [u'dabde072337427fa157e856377a9165e'], u'path': u'/apps/bypy/07\u591c\u573a.mp4', u'md5': u'dabde072337427fa157e856377a9165e', u'isdir': 0, u'ctime': 1461016702, u'server_mtime': 1593919556}
<D> Request OK
<D> Checking if we already have the copy locally
<D> GET https://d.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/07\u591c\u573a.mp4', 0, 1264360969, 1593922631.591573)
<D> Params: {u'path': u'/apps/bypy/07\u591c\u573a.mp4', u'method': u'download'}
<D> Full URL: http://www.baidupcs.com/403.html
<D> HTTP Status Code: 403
<D> Website returned JSON: {u'error_code': 31326, u'error_msg': u'anti hotlinking'}
<E> [22:17:16] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [22:17:16] 
<E> [22:17:16] Function: __downchunks_act
<E> [22:17:16] Website parameters: {u'path': u'/apps/bypy/07\u591c\u573a.mp4', u'method': u'download'}
<E> [22:17:16] Full URL: http://www.baidupcs.com/403.html
<E> [22:17:16] HTTP Response Status Code: 403
<E> [22:17:16] Error JSON returned:{u'error_code': 31326, u'error_msg': u'anti hotlinking'}
Error code: 31326
Error Description: anti hotlinking
<E> [22:17:16] Website returned: {
    "error_code":31326,
    "error_msg":"anti hotlinking"
}

<E> [22:17:16] Waiting 10 seconds before retrying...
<E> [22:17:26] Request Try #2 / 5
<D> GET https://d.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/07\u591c\u573a.mp4', 0, 1264360969, 1593922631.591573)
<D> Params: {u'path': u'/apps/bypy/07\u591c\u573a.mp4', u'method': u'download'}
<D> Full URL: http://www.baidupcs.com/403.html
<D> HTTP Status Code: 403
<D> Website returned JSON: {u'error_code': 31326, u'error_msg': u'anti hotlinking'}
<E> [22:17:31] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [22:17:31] 
<E> [22:17:31] Function: __downchunks_act
<E> [22:17:31] Website parameters: {u'path': u'/apps/bypy/07\u591c\u573a.mp4', u'method': u'download'}
<E> [22:17:31] Full URL: http://www.baidupcs.com/403.html
<E> [22:17:31] HTTP Response Status Code: 403
<E> [22:17:31] Error JSON returned:{u'error_code': 31326, u'error_msg': u'anti hotlinking'}
Error code: 31326
Error Description: anti hotlinking
<E> [22:17:31] Website returned: {
    "error_code":31326,
    "error_msg":"anti hotlinking"
}

<E> [22:17:31] Waiting 20 seconds before retrying...
<E> [22:17:51] Request Try #3 / 5
<D> GET https://d.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/07\u591c\u573a.mp4', 0, 1264360969, 1593922631.591573)
<D> Params: {u'path': u'/apps/bypy/07\u591c\u573a.mp4', u'method': u'download'}
<D> Full URL: http://www.baidupcs.com/403.html
<D> HTTP Status Code: 403
<D> Website returned JSON: {u'error_code': 31326, u'error_msg': u'anti hotlinking'}
<E> [22:17:55] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [22:17:55] 
<E> [22:17:55] Function: __downchunks_act
<E> [22:17:55] Website parameters: {u'path': u'/apps/bypy/07\u591c\u573a.mp4', u'method': u'download'}
<E> [22:17:55] Full URL: http://www.baidupcs.com/403.html
<E> [22:17:55] HTTP Response Status Code: 403
<E> [22:17:55] Error JSON returned:{u'error_code': 31326, u'error_msg': u'anti hotlinking'}
Error code: 31326
Error Description: anti hotlinking
<E> [22:17:55] Website returned: {
    "error_code":31326,
    "error_msg":"anti hotlinking"
}

<E> [22:17:55] Waiting 30 seconds before retrying...
<E> [22:18:25] Request Try #4 / 5
<D> GET https://d.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/07\u591c\u573a.mp4', 0, 1264360969, 1593922631.591573)
<D> Params: {u'path': u'/apps/bypy/07\u591c\u573a.mp4', u'method': u'download'}
<D> Full URL: http://www.baidupcs.com/403.html
<D> HTTP Status Code: 403
<D> Website returned JSON: {u'error_code': 31326, u'error_msg': u'anti hotlinking'}
<E> [22:18:31] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [22:18:31] 
<E> [22:18:31] Function: __downchunks_act
<E> [22:18:31] Website parameters: {u'path': u'/apps/bypy/07\u591c\u573a.mp4', u'method': u'download'}
<E> [22:18:31] Full URL: http://www.baidupcs.com/403.html
<E> [22:18:31] HTTP Response Status Code: 403
<E> [22:18:31] Error JSON returned:{u'error_code': 31326, u'error_msg': u'anti hotlinking'}
Error code: 31326
Error Description: anti hotlinking
<E> [22:18:31] Website returned: {
    "error_code":31326,
    "error_msg":"anti hotlinking"
}

<E> [22:18:31] Waiting 40 seconds before retrying...
<E> [22:19:11] Request Try #5 / 5
<D> GET https://d.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/07\u591c\u573a.mp4', 0, 1264360969, 1593922631.591573)
<D> Params: {u'path': u'/apps/bypy/07\u591c\u573a.mp4', u'method': u'download'}
<D> Full URL: http://www.baidupcs.com/403.html
<D> HTTP Status Code: 403
<D> Website returned JSON: {u'error_code': 31326, u'error_msg': u'anti hotlinking'}
<E> [22:19:15] Error accessing 'https://d.pcs.baidu.com/rest/2.0/pcs/file'
<E> [22:19:15] 
<E> [22:19:15] Function: __downchunks_act
<E> [22:19:15] Website parameters: {u'path': u'/apps/bypy/07\u591c\u573a.mp4', u'method': u'download'}
<E> [22:19:15] Full URL: http://www.baidupcs.com/403.html
<E> [22:19:15] HTTP Response Status Code: 403
<E> [22:19:15] Error JSON returned:{u'error_code': 31326, u'error_msg': u'anti hotlinking'}
Error code: 31326
Error Description: anti hotlinking
<E> [22:19:15] Website returned: {
    "error_code":31326,
    "error_msg":"anti hotlinking"
}

<E> [22:19:15] Maximum number (5) of tries failed.
<D> Downloading '/apps/bypy/hello' as 'hello'
<D> Getting info of remote file '/apps/bypy/hello' for later verification
<D> __get_file_info(): rdir : /apps/bypy | rfile: hello
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/hello', [])
<D> Params: {u'path': u'/apps/bypy', u'order': u'asc', u'limit': u'0-1000', u'method': u'list', u'by': u'name'}
<D> Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=121.ed4bc5138f16124871f96671e74178cc.Y52yk9mBOZUXOdmDMnZpcJB11Jw8yViHaGzRdIw.i3vM2Q&order=asc&method=list&limit=0-1000&path=%2Fapps%2Fbypy&by=name
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> List json: {u'list': [{u'local_mtime': 1461016701, u'share': 0, u'app_id': 250528, u'oper_id': 3338694264, u'mtime': 1593919556, u'local_ctime': 1461016701, u's3_handle': u'', u'size': 1264360969, u'category': 1, u'user_id': 78104352, u'privacy': 1, u'unlist': 0, u'server_atime': 0, u'status': 0, u'server_filename': u'07\u591c\u573a.mp4', u'server_ctime': 1461016702, u'fs_id': 620485307578494, u'block_list': [u'dabde072337427fa157e856377a9165e'], u'path': u'/apps/bypy/07\u591c\u573a.mp4', u'md5': u'dabde072337427fa157e856377a9165e', u'isdir': 0, u'ctime': 1461016702, u'server_mtime': 1593919556}, {u'local_mtime': 1593919491, u'share': 0, u'app_id': 1572671, u'oper_id': 0, u'mtime': 1593919491, u'local_ctime': 1593919491, u's3_handle': u'', u'size': 0, u'category': 6, u'user_id': 78104352, u'privacy': 0, u'unlist': 0, u'server_atime': 0, u'status': 0, u'server_filename': u'hello', u'server_ctime': 1593919491, u'fs_id': 766123144686146, u'block_list': [u'd41d8cd98f00b204e9800998ecf8427e'], u'path': u'/apps/bypy/hello', u'md5': u'8e23f7635tb64136eddb0719602bc477', u'isdir': 0, u'ctime': 1593919491, u'server_mtime': 1593919491}, {u'local_mtime': 1593919815, u'share': 0, u'app_id': 1572671, u'oper_id': 0, u'mtime': 1593919815, u'local_ctime': 1593919815, u's3_handle': u'', u'size': 0, u'category': 6, u'user_id': 78104352, u'privacy': 0, u'unlist': 0, u'server_atime': 0, u'status': 0, u'server_filename': u'nihao', u'server_ctime': 1593919815, u'fs_id': 98604871236973, u'block_list': [u'd41d8cd98f00b204e9800998ecf8427e'], u'path': u'/apps/bypy/nihao', u'md5': u'8e23f7635tb64136eddb0719602bc477', u'isdir': 0, u'ctime': 1593919815, u'server_mtime': 1593919815}], u'request_id': 4325772433848992217}
<D> File info json: {u'local_mtime': 1593919491, u'share': 0, u'app_id': 1572671, u'oper_id': 0, u'mtime': 1593919491, u'local_ctime': 1593919491, u's3_handle': u'', u'size': 0, u'category': 6, u'user_id': 78104352, u'privacy': 0, u'unlist': 0, u'server_atime': 0, u'status': 0, u'server_filename': u'hello', u'server_ctime': 1593919491, u'fs_id': 766123144686146, u'block_list': [u'd41d8cd98f00b204e9800998ecf8427e'], u'path': u'/apps/bypy/hello', u'md5': u'8e23f7635tb64136eddb0719602bc477', u'isdir': 0, u'ctime': 1593919491, u'server_mtime': 1593919491}
<D> Request OK
<D> Checking if we already have the copy locally
<D> Same-name local file 'hello' exists, checking if contents match
<D> Comparing local file 'hello' and remote file '/apps/bypy/hello'
<D> Local file size : 0
<D> Remote file size: 0
<D> Local and remote file size matches
<D> Same local file 'hello' already exists, skip downloading
<D> Downloading '/apps/bypy/nihao' as 'nihao'
<D> Getting info of remote file '/apps/bypy/nihao' for later verification
<D> __get_file_info(): rdir : /apps/bypy | rfile: nihao
<D> GET https://pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: (u'/apps/bypy/nihao', [])
<D> Params: {u'path': u'/apps/bypy', u'order': u'asc', u'limit': u'0-1000', u'method': u'list', u'by': u'name'}
<D> Full URL: https://pcs.baidu.com/rest/2.0/pcs/file?access_token=121.ed4bc5138f16124871f96671e74178cc.Y52yk9mBOZUXOdmDMnZpcJB11Jw8yViHaGzRdIw.i3vM2Q&order=asc&method=list&limit=0-1000&path=%2Fapps%2Fbypy&by=name
<D> HTTP Status Code: 200
<D> 200 OK, processing action
<D> List json: {u'list': [{u'local_mtime': 1461016701, u'share': 0, u'app_id': 250528, u'oper_id': 3338694264, u'mtime': 1593919556, u'local_ctime': 1461016701, u's3_handle': u'', u'size': 1264360969, u'category': 1, u'user_id': 78104352, u'privacy': 1, u'unlist': 0, u'server_atime': 0, u'status': 0, u'server_filename': u'07\u591c\u573a.mp4', u'server_ctime': 1461016702, u'fs_id': 620485307578494, u'block_list': [u'dabde072337427fa157e856377a9165e'], u'path': u'/apps/bypy/07\u591c\u573a.mp4', u'md5': u'dabde072337427fa157e856377a9165e', u'isdir': 0, u'ctime': 1461016702, u'server_mtime': 1593919556}, {u'local_mtime': 1593919491, u'share': 0, u'app_id': 1572671, u'oper_id': 0, u'mtime': 1593919491, u'local_ctime': 1593919491, u's3_handle': u'', u'size': 0, u'category': 6, u'user_id': 78104352, u'privacy': 0, u'unlist': 0, u'server_atime': 0, u'status': 0, u'server_filename': u'hello', u'server_ctime': 1593919491, u'fs_id': 766123144686146, u'block_list': [u'd41d8cd98f00b204e9800998ecf8427e'], u'path': u'/apps/bypy/hello', u'md5': u'8e23f7635tb64136eddb0719602bc477', u'isdir': 0, u'ctime': 1593919491, u'server_mtime': 1593919491}, {u'local_mtime': 1593919815, u'share': 0, u'app_id': 1572671, u'oper_id': 0, u'mtime': 1593919815, u'local_ctime': 1593919815, u's3_handle': u'', u'size': 0, u'category': 6, u'user_id': 78104352, u'privacy': 0, u'unlist': 0, u'server_atime': 0, u'status': 0, u'server_filename': u'nihao', u'server_ctime': 1593919815, u'fs_id': 98604871236973, u'block_list': [u'd41d8cd98f00b204e9800998ecf8427e'], u'path': u'/apps/bypy/nihao', u'md5': u'8e23f7635tb64136eddb0719602bc477', u'isdir': 0, u'ctime': 1593919815, u'server_mtime': 1593919815}], u'request_id': 4325772907391971802}
<D> File info json: {u'local_mtime': 1593919815, u'share': 0, u'app_id': 1572671, u'oper_id': 0, u'mtime': 1593919815, u'local_ctime': 1593919815, u's3_handle': u'', u'size': 0, u'category': 6, u'user_id': 78104352, u'privacy': 0, u'unlist': 0, u'server_atime': 0, u'status': 0, u'server_filename': u'nihao', u'server_ctime': 1593919815, u'fs_id': 98604871236973, u'block_list': [u'd41d8cd98f00b204e9800998ecf8427e'], u'path': u'/apps/bypy/nihao', u'md5': u'8e23f7635tb64136eddb0719602bc477', u'isdir': 0, u'ctime': 1593919815, u'server_mtime': 1593919815}
<D> Request OK
<D> Checking if we already have the copy locally
<D> Same-name local file 'nihao' exists, checking if contents match
<D> Comparing local file 'nihao' and remote file '/apps/bypy/nihao'
<D> Local file size : 0
<D> Remote file size: 0
<D> Local and remote file size matches
<D> Same local file 'nihao' already exists, skip downloading
<D> Remote dirs: []
<D> Remote files: [{u'local_mtime': 1461016701, u'share': 0, u'app_id': 250528, u'oper_id': 3338694264, u'mtime': 1593919556, u'local_ctime': 1461016701, u's3_handle': u'', u'size': 1264360969, u'category': 1, u'user_id': 78104352, u'privacy': 1, u'unlist': 0, u'server_atime': 0, u'status': 0, u'server_filename': u'07\u591c\u573a.mp4', u'server_ctime': 1461016702, u'fs_id': 620485307578494, u'block_list': [u'dabde072337427fa157e856377a9165e'], u'path': u'/apps/bypy/07\u591c\u573a.mp4', u'md5': u'dabde072337427fa157e856377a9165e', u'isdir': 0, u'ctime': 1461016702, u'server_mtime': 1593919556}, {u'local_mtime': 1593919491, u'share': 0, u'app_id': 1572671, u'oper_id': 0, u'mtime': 1593919491, u'local_ctime': 1593919491, u's3_handle': u'', u'size': 0, u'category': 6, u'user_id': 78104352, u'privacy': 0, u'unlist': 0, u'server_atime': 0, u'status': 0, u'server_filename': u'hello', u'server_ctime': 1593919491, u'fs_id': 766123144686146, u'block_list': [u'd41d8cd98f00b204e9800998ecf8427e'], u'path': u'/apps/bypy/hello', u'md5': u'8e23f7635tb64136eddb0719602bc477', u'isdir': 0, u'ctime': 1593919491, u'server_mtime': 1593919491}, {u'local_mtime': 1593919815, u'share': 0, u'app_id': 1572671, u'oper_id': 0, u'mtime': 1593919815, u'local_ctime': 1593919815, u's3_handle': u'', u'size': 0, u'category': 6, u'user_id': 78104352, u'privacy': 0, u'unlist': 0, u'server_atime': 0, u'status': 0, u'server_filename': u'nihao', u'server_ctime': 1593919815, u'fs_id': 98604871236973, u'block_list': [u'd41d8cd98f00b204e9800998ecf8427e'], u'path': u'/apps/bypy/nihao', u'md5': u'8e23f7635tb64136eddb0719602bc477', u'isdir': 0, u'ctime': 1593919815, u'server_mtime': 1593919815}]
<E> [22:19:20] ----------------------------------------------------------------
Error 140: Maximum retries reached
Skip saving Hash Cache since it has not been updated.

**Comment by lifeike** [comment]
list compare upload 都很没问题
同步文件夹出现问题
不能同步，下载失败。

**Comment by shijiantian** [comment]
下载不了超过大小限制的文件，好像是文件大小过了50M就报这个。一句话就是，能从网页端直接下载的可以用这个bypy下，需要安装客户端才能下的就下不了。

**Comment by lifeike** [comment]
> 下载不了超过大小限制的文件，好像是文件大小过了50M就报这个。一句话就是，能从网页端直接下载的可以用这个bypy下，需要安装客户端才能下的就下不了。

原来如此啊, 感谢回复. 那个 你有用什么其他的替代品嘛.

**Comment by shijiantian** [comment]
> > 下载不了超过大小限制的文件，好像是文件大小过了50M就报这个。一句话就是，能从网页端直接下载的可以用这个bypy下，需要安装客户端才能下的就下不了。
> 
> 原来如此啊, 感谢回复. 那个 你有用什么其他的替代品嘛.

可以用baidupcs-go,原作者好像删库跑路了，不过东西还能用，如果你用archlinux的话软件仓库里就有，可以直接用pacman安装上就行，不过速度也不快。

**Comment by lifeike** [comment]
> > > 下载不了超过大小限制的文件，好像是文件大小过了50M就报这个。一句话就是，能从网页端直接下载的可以用这个bypy下，需要安装客户端才能下的就下不了。
> > 
> > 
> > 原来如此啊, 感谢回复. 那个 你有用什么其他的替代品嘛.
> 
> 可以用baidupcs-go,原作者好像删库跑路了，不过东西还能用，如果你用archlinux的话软件仓库里就有，可以直接用pacman安装上就行，不过速度也不快。

奥， 哇咔咔， 谢谢啦～～～～
