### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by hrj5032188** [houtianze/bypy#548]
![image](https://user-images.githubusercontent.com/28888068/94399864-ba78c380-019a-11eb-96eb-6c2d7b32aa49.png)

**Comment by dwd11511** [comment]
附议。并且测试上传没问题。

**Comment by hrj5032188** [comment]
@dwd11511 你无法下载的资源有通过百度官方APP下载一下试试吗？

**Comment by dwd11511** [comment]
> @dwd11511 你无法下载的资源有通过百度官方APP下载一下试试吗？

官方app下载没问题

**Comment by byteslaves** [comment]
你还会报错，我回车后一直是空白，没有任何反馈

**Comment by yangsijie666** [comment]
> 你还会报错，我回车后一直是空白，没有任何反馈

+1
