### ISSUE TITLE
求教 所有server failed

### ISSUE THREAD

**Issue by swamlake** [houtianze/bypy#552]
Authorizing, please be patient, it may take upto 300 seconds...
Authorizing with the Heroku server ...
Heroku server failed, authorizing with the Heroku1 server ...
Heroku1 server failed, authorizing with the Vercel server ...
Vercel server failed. Last resort: authorizing with the GAE server ...
<E> [22:22:12] Fatal: All server authorizations failed.

试过Possible fixes 1&2 还是无法解决

**Comment by ald2004** [comment]
same problem

**Comment by ald2004** [comment]
worked for now
