### ISSUE TITLE
bypy list

### ISSUE THREAD

**Issue by Enn29** [houtianze/bypy#555]
bypy list 只能显示文件夹下的所有文件，我怎么获得这些文件名呢？
我在download时传入的是百度网盘下的文件夹名，下载文件时会导致程序未响应，所以我想得到文件夹下的文件名，拼成路径再遍历再去下载

**Comment by tkfanswind** [comment]
可以获得文件夹字节大小吗？

**Comment by slipperstree** [comment]
list 命令是可以传参数的 允许的参数有 $t $f $s $m $d
$f 是文件名
$s 是文件大小
其他的自己看看说明或代码

只返回文件名的调用方法
bypy list /yourdir/ '$f'
