### ISSUE TITLE
关于上传速度

### ISSUE THREAD

**Issue by haobinnan** [houtianze/bypy#557]
我用浏览器上传文件，基本上就是网络的上传带宽峰值，而用bypy好像被限速了，不到500kB/s，请问怎么处理。

**Comment by wangebcjd** [comment]
我也是这样，你解决了吗

**Comment by haobinnan** [comment]
> 我也是这样，你解决了吗

估计百度限制 我只能用浏览器继续上传了

**Comment by bones1234567** [comment]
有谁试过svip可以加快上传和下载速度的么？

**Comment by ESWZY** [comment]
> 有谁试过svip可以加快上传和下载速度的么？

20分钟上传了11MB...🌚

**Comment by bones1234567** [comment]
> > 有谁试过svip可以加快上传和下载速度的么？
> 
> 20分钟上传了11MB...🌚

svip也这么慢么。。。是不是你网络太慢了，感觉我这边还不至于这么慢一样。。。

**Comment by ESWZY** [comment]
> > > 有谁试过svip可以加快上传和下载速度的么？
> > 
> > 
> > 20分钟上传了11MB...🌚
> 
> svip也这么慢么。。。是不是你网络太慢了，感觉我这边还不至于这么慢一样。。。

亚马逊的服务器，下载能10MB+🌚

**Comment by bones1234567** [comment]
亚马逊有没有现成的客户端可以用？> > > > 有谁试过svip可以加快上传和下载速度的么？
> 
> > > 
> 
> > > 
> 
> > > 20分钟上传了11MB...🌚
> 
> > 
> 
> > svip也这么慢么。。。是不是你网络太慢了，感觉我这边还不至于这么慢一样。。。
> 
> 
> 
> 亚马逊的服务器，下载能10MB/s+🌚

**Comment by cfeeling** [comment]
> 亚马逊有没有现成的客户端可以用？> > > > 有谁试过svip可以加快上传和下载速度的么？
> 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 20分钟上传了11MB...new_moon_with_face
> > 
> > 
> > > 
> > 
> > 
> > > svip也这么慢么。。。是不是你网络太慢了，感觉我这边还不至于这么慢一样。。。
> > 
> > 
> > 亚马逊的服务器，下载能10MB/s+new_moon_with_face

SVIP 一样的速度，不超过500KB/s，14G的内容预计需要8小时。。。

**Comment by yes-github** [comment]
我这也是限速500kB/s，一会我用官方的api试试
