### ISSUE TITLE
无法授权

### ISSUE THREAD

**Issue by chickmy** [houtianze/bypy#559]
Authorizing, please be patient, it may take upto 300 seconds...
Authorizing with the Heroku server ...
Heroku server failed, authorizing with the Heroku1 server ...
Heroku1 server failed, authorizing with the Vercel server ...
Vercel server failed. Last resort: authorizing with the GAE server ...
<E> [12:42:52] Fatal: All server authorizations failed.
<I> [12:42:52] ----------------------------------------------------------------
<I> [12:42:52] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.

**Comment by sonichuang** [comment]
出现同样的问题，求解

**Comment by chickmy** [comment]
> 出现同样的问题，复兴

需要出墙

**Comment by sonichuang** [comment]
在windows上正常呢？我是在树莓派上就出现这个问题

**Comment by houtianze** [comment]
最新版1.8应该已经彻底解决授权问题。
