### ISSUE TITLE
Waiting seconds before retrying 问题

### ISSUE THREAD

**Issue by adamsliu** [houtianze/bypy#564]
今天在几台服务器上都出现了无法下载的问题，list和info都是正常的，但是下载文件或dir就不行，日志如下：

<E> [16:28:17] Waiting 10 seconds before retrying...
<E> [16:28:27] Request Try #2 / 5
<E> [16:28:30] Waiting 20 seconds before retrying...
<E> [16:28:50] Request Try #3 / 5
<E> [16:28:52] Waiting 30 seconds before retrying...
<E> [16:29:22] Request Try #4 / 5
<E> [16:29:25] Waiting 40 seconds before retrying...
<E> [16:30:05] Request Try #5 / 5
<E> [16:30:07] Maximum number (5) of tries failed.
<E> [16:30:07] ----------------------------------------------------------------
Error 140: Maximum retries reached

**Comment by StormFeng** [comment]
我也是，不能下载了
```
<E> [12:06:50] Maximum number (5) of tries failed.
<E> [12:06:51] Waiting 10 seconds before retrying...
<E> [12:07:01] Request Try #2 / 5
[====================] 100% (6.0kB/6.0kB) ETA:  (541B/s, 11s gone) <E> [12:07:04] Waiting 10 seconds before retrying...
<E> [12:07:14] Request Try #2 / 5
[====================] 100% (96.5kB/96.5kB) ETA:  (16kB/s, 6s gone) <E> [12:09:12] Waiting 10 seconds before retrying...
<E> [12:09:22] Request Try #2 / 5
<E> [12:09:23] Waiting 20 seconds before retrying...
<E> [12:09:43] Request Try #3 / 5
<E> [12:09:44] Waiting 30 seconds before retrying...
```

**Comment by lcslyh** [comment]
我也是这个问题，同问

**Comment by Xielq** [comment]
[root@myserver ~]# bypy ls
/apps/bypy ($t $f $s $m $d):
D oracledbBackup 0 2021-07-01, 09:54:48 
[root@myserver ~]# bypy mkdir /tmp
<E> [14:07:08] Waiting 10 seconds before retrying...
<E> [14:07:18] Request Try #2 / 5
<E> [14:07:18] Waiting 20 seconds before retrying...
<E> [14:07:38] Request Try #3 / 5
<E> [14:07:38] Waiting 30 seconds before retrying...
<E> [14:08:08] Request Try #4 / 5

**Comment by Xielq** [comment]
> 今天在几台服务器上都出现了无法下载的问题，list和info都是正常的，但是下载文件或dir就不行，日志如下：
> 
> [16:28:17] Waiting 10 seconds before retrying...
> [16:28:27] Request Try #2 / 5
> [16:28:30] Waiting 20 seconds before retrying...
> [16:28:50] Request Try #3 / 5
> [16:28:52] Waiting 30 seconds before retrying...
> [16:29:22] Request Try #4 / 5
> [16:29:25] Waiting 40 seconds before retrying...
> [16:30:05] Request Try #5 / 5
> [16:30:07] Maximum number (5) of tries failed.
> [16:30:07] ----------------------------------------------------------------
> Error 140: Maximum retries reached

我也一样的问题，请问有找到解决方法吗

**Comment by genzj** [comment]
遇到了相同问题，以下是-dd输出的相关log

```
ually 2003 1080p BluRay x264 AAC • CHAOSPACE.mp4', 'pl': 1, 'real_category': '', 's3_handle': '', 'server_atime': 1640333600, 'server_ctime': 1574419725, 'server_filename': 'Love Actually 2003 1080p BluRay x264 AAC • CHAOSPACE.mp4', 'server_mtime': 1640333634, 'share': 0, 'size': 3348140632, 'status': 0, 'tkbind_id': 0, 'unlist': 0, 'user_id': 213571, 'wpfile': 0}
<D> Request OK
<D> Checking if we already have the copy locally
<D> GET https://d.pcs.baidu.com/rest/2.0/pcs/file
<D> actargs: ('/apps/bypy/la/Love Actually 2003 1080p BluRay x264 AAC • CHAOSPACE.mp4', 0, 3348140632, 1640334535.8523226)
<D> Params: {'method': 'download', 'path': '/apps/bypy/la/Love Actually 2003 1080p BluRay x264 AAC • CHAOSPACE.mp4'}
<D> Full URL: <隐藏了文件实际地址>
<D> HTTP Status Code: 206
<D> 206 Partial Content (this is OK), processing action
<E> [08:29:01] Waiting 10 seconds before retrying...
```

**Comment by canna1998** [comment]
感觉是网络问题，我换了台服务器就可以用了。。。
