### ISSUE TITLE
用bypy --downloader aria2 download（Aria2改16线程下，速度50kb/s，是百度限速了吗？求大佬分享加速方法）

### ISSUE THREAD

**Issue by TophTab** [houtianze/bypy#565]

**Comment by TophTab** [comment]
求大佬分享加速方法

**Comment by whoareyou2021** [comment]
export DOWNLOADER_ARGUMENTS= '-c -k10M -x4 -s4 --file-allocation=none'

It doesn't feel that much faster though. mileage may vary.

**Comment by ESWZY** [comment]
插眼
