### ISSUE TITLE
如何自动删除本地文件

### ISSUE THREAD

**Issue by wangwei8828** [houtianze/bypy#566]
请问如何设置才能在上传成功后删除本地文件啊。
我的VPS容量很小，能不能上传2个文件后就自动删除，然后继续上传？
因为我想使用youtube-dl下载视频然后同时bypy上传到网盘。

**Comment by yy16** [comment]
写个脚本，把上传操作也放在脚本里，上传完删除

**Comment by houtianze** [comment]
`--move`选项？
