### ISSUE TITLE
有没有可能通过 cookie / bduss 进行授权啊 ？

### ISSUE THREAD

**Issue by trump-7575** [houtianze/bypy#568]
如果可以直接通过命令行输入 参数 cookie / bduss 完成授权就简单多了，可以吗 ？能否出个补丁啊 ？

**Comment by houtianze** [comment]
谢谢建议。我之前考虑过加入bduss支持，不过考虑到pcs接口和bduss接口不完全一样（主要是md5相关部分吧），后来作罢。
