### ISSUE TITLE
能不能增加 c++/C  接口啊 ？

### ISSUE THREAD

**Issue by trump-7575** [houtianze/bypy#569]
我想在 C/c++里面调用 bypy 可以吗 ？ 有没有人做过啊 ？

**Comment by bg4uvr** [comment]
`/*
 * 程序名：book266.cpp，此程序用于演示用execl函数执行程序。
 * 作者：C语言技术网(www.freecplus.net) 日期：20190525
*/

#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>

int main()
{
	// /bin/lss不存在，执行不能成功
	int iret = execl("/bin/lss", "/bin/ls", "-l", "/usr/include/stdio.h", 0);
	//int iret=execl("/bin/ls","/bin/ls","-l","/usr/include/stdio.h",0);

	// 可以调用成功的代码。
	printf("iret=%d\n", iret);
	if (iret == -1)
		printf("%d:%s\n", errno, strerror(errno));
}
`

**Comment by bg4uvr** [comment]
> 
/*
 * 程序名：book266.cpp，此程序用于演示用execl函数执行程序。
 * 作者：C语言技术网(www.freecplus.net) 日期：20190525
*/

#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>

int main()
{
	// /bin/lss不存在，执行不能成功
	int iret = execl("/bin/lss", "/bin/ls", "-l", "/usr/include/stdio.h", 0);
	//int iret=execl("/bin/ls","/bin/ls","-l","/usr/include/stdio.h",0);

	// 可以调用成功的代码。
	printf("iret=%d\n", iret);
	if (iret == -1)
		printf("%d:%s\n", errno, strerror(errno));
}

**Comment by bg4uvr** [comment]
用 execl 方法可以调用系统命令

`/*
 * 程序名：book266.cpp，此程序用于演示用execl函数执行程序。
 * 作者：C语言技术网(www.freecplus.net) 日期：20190525
*/

#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>

int main()
{
	// /bin/lss不存在，执行不能成功
	int iret = execl("/bin/lss", "/bin/ls", "-l", "/usr/include/stdio.h", 0);
	//int iret=execl("/bin/ls","/bin/ls","-l","/usr/include/stdio.h",0);

	// 可以调用成功的代码。
	printf("iret=%d\n", iret);
	if (iret == -1)
		printf("%d:%s\n", errno, strerror(errno));
}
`
