### ISSUE TITLE
请问支持转存功能吗

### ISSUE THREAD

**Issue by eeezae** [houtianze/bypy#578]
获取别人分享到连接，或者直接获取到文件的id，可以实现文件转存的功能吗，我看了一下有accept方法但是remotepath似乎是我网盘的路径

**Comment by houtianze** [comment]
哦，这个`accept`不是获取别人共享链接的，所以没有这个功能（不记得`pcs api`是否有这个功能）。
`accept`对应的是`share`命令，不过这个和百度盘自己的共享链接功能基本没关系。。

**Comment by eeezae** [comment]
好的感谢
