### ISSUE TITLE
bypy上传文件会被限制在500kB/s以下

### ISSUE THREAD

**Issue by redlert** [houtianze/bypy#579]
问题：
    我现在使用bypy上传文件， 我看了一下历史记录， 全部都没有超过500kB/s.  我是百度的超级VIP用户， 使用Windows上的客户端和网页端都没有这个限制。
    请问有办法可以解决吗？

我的环境：
python 3.6
bypy 版本是1.7.2
安装途径：
pip install bypy

**Comment by chengengliu** [comment]
同问题。上传非常慢，有没有解决方案？

**Comment by duchenpaul** [comment]
这个...应该是没有的吧 这个项目是合法调用百度的api, 而不是破解

**Comment by houtianze** [comment]
嗯，百度方面做了限速的话可能就没啥办法了。。

**Comment by Vimos** [comment]
超级会员，也无法突破500k，如果api开放会员身份识别也许能提升速度

**Comment by shiqishao** [comment]
百度网盘开放平台最新的API好像已经支持了会员身份识别，如果授权账号是超级会员，上传和下载可以到满带宽，https://pan.baidu.com/union/doc/

**Comment by Vimos** [comment]
![image](https://user-images.githubusercontent.com/2136700/149894541-e9afe960-f23e-4e70-ba83-be443b70c541.png)

**Comment by hzhangxyz** [comment]
我非会员，40个进程能把上传速度和提升到5MB/s
