### ISSUE TITLE
清空文件夹命令

### ISSUE THREAD

**Issue by lifeike** [houtianze/bypy#582]
感谢您提供的软件给我们使用
如果可能的话

在这里希望能够添加一个 清空bypy所有文件和文件夹的命令

非常感谢

**Comment by houtianze** [comment]
不客气。没记错类似`rm /`的命令应该可以吧。

**Comment by lifeike** [comment]
> 不客气。没记错类似`rm /`的命令应该可以吧。

根据您的提示，已经完美解决了。 再次感谢您的帮助！！
