### ISSUE TITLE
无法授权了

### ISSUE THREAD

**Issue by pswena** [houtianze/bypy#584]
Paste the Authorization Code here within 10 minutes.
Press [Enter] when you are done
6196ca186a8aa5e360cb762c7d0b37e3
Authorizing, please be patient, it may take upto 300 seconds...
Authorizing with the Heroku server ...
Heroku server failed, authorizing with the Heroku1 server ...
Heroku1 server failed, authorizing with the Vercel server ...
Vercel server failed. Last resort: authorizing with the GAE server ...
<E> [10:49:41] Fatal: All server authorizations failed.
<I> [10:49:41] ----------------------------------------------------------------
<I> [10:49:41] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.

**Comment by labulaka521** [comment]
终端加个http代理就可以了

**Comment by fuhao009** [comment]
这个需要翻墙吗？

**Comment by ldjdsc** [comment]
> 终端加个http代理就可以了

加了直接报上面的错误的。

**Comment by UVJkiNTQ** [comment]
遇到同样错误，在vps上执行的

**Comment by dfmjndm** [comment]
同样错误，所有服务器都失败

**Comment by tjyuyao** [comment]
加代理可以+1

**Comment by houtianze** [comment]
最新版1.8应该不会有授权问题了。
