### ISSUE TITLE
下载百度云盘里面4000个文件，但是最终也只能下载1000个

### ISSUE THREAD

**Issue by zhoujingyu13687306871** [houtianze/bypy#588]
通过bypy下载百度云盘里面超过4000个文件，最终只能下载1000个，我看了一下，都是第一页的内容。从第2页到第5页都没有下载，虽然加了一个 -d 参数作为调试，但是下载1000个文件后，bypy一直在校验云盘上剩余的3000个文件，只校验，不下载了。请教一下作者，这个有什么好办法吗？
      另外，我想把云盘上未下载的3000个文件，在云盘bypy目录下，建立4个子文件夹，然后将文件平均移动到这些子文件夹里面，然后一个一个文件夹下，不知道这样是否可行？ @houtianze

**Comment by houtianze** [comment]
建立4个子文件夹应该是可以解决问题的。
刚发布了最新版`1.7.4`，`list`显示不全的问题解决了。
下载超过一千个文件的目录的代码我看了看，感觉上好像没有什么问题。
你可以反复运行`bypy download`来试试是否会下载，另外你试试 `bypy --processes 4 download` 看看能不能解决下载的问题？

**Comment by ppoak** [comment]
list显示不全的问题解决了，但是下载仍然存在只能下前1000个文件的问题

**Comment by houtianze** [comment]
same as #612  @ppoak 谢谢反馈，最新版1.8应该解决了这个问题。
