### ISSUE TITLE
Please run 'pip install -U bypy' to update and try again.

### ISSUE THREAD

**Issue by shagle** [houtianze/bypy#598]
Your current version (1.7.4) is too low, minimum required version is 1.7.6. Please run 'pip install -U bypy' to update and try again.

ERROR: Could not find a version that satisfies the requirement importlib-resources>=5.4.0 (from bypy) (from versions: 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 1.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 2.0.0, 2.0.1, 3.0.0, 3.1.0, 3.1.1, 3.2.0, 3.2.1, 3.3.0, 3.3.1)
ERROR: No matching distribution found for importlib-resources>=5.4.0 (from bypy)

CentOS Linux release 7.9.2009 (Core)

**Comment by houtianze** [comment]
谢谢反馈，修复中。

**Comment by houtianze** [comment]
Fixed by commit 921d1279819f260793f282e8a71ccf1a6ad36ddc

请升级到最新版`1.7.7`，应该已经解决了。
