### ISSUE TITLE
下载文件夹，里面的内容下载了20MB就不再下载了

### ISSUE THREAD

**Issue by happysoul** [houtianze/bypy#600]
文件位置 /apps/bypy/欧姆社/
文件夹中存放的是一堆pdf文件
让程序后台下载，执行命令
`bypy downdir 欧姆社 >/dev/null &`
下载了几个文件后ls看到文件长度都是 20971520 也就是 20MB
但我的pdf文件都是70MB左右的大小
是不是文件按照20M分割，之后没有判断长度就直接结束了？

**Comment by houtianze** [comment]
谢谢反馈。

问题还存在？

**Comment by houtianze** [comment]
试了一下，可能是下载速度太慢？我试下载速度只有70kb/s...

**Comment by happysoul** [comment]
我一会儿再试试再反馈
当时是下载几十个文件 都在70M左右
可以看到单线程下载，但下载后的4-5个文件都是20M大小，也就是下载完20M就去结束去下载下面的文件了
下载速度确实是慢
怀疑的是：
是否跟中文文件夹和中文文件是否有关系？
切片20M是否有问题，是否是判断下载完成的地方有问题导致任务结束了？

**Comment by happysoul** [comment]
也许是文件源的问题，试了其他的中文目录下载暂时没问题了

**Comment by happysoul** [comment]
经过多次测试 中文目录，中文文件名，文件类型是pdf的文件（只有pdf有问题）
下载后就只有20M 就不再继续下载，同文件夹下的rar文件下载就没有问题600M+

**Comment by happysoul** [comment]
链接: https://pan.baidu.com/s/1mHqO7IOY0wFq48xxzfKcKA 提取码: sc3e 复制这段内容后打开百度网盘手机App，操作更方便哦
测试的是这个文件
刚细看了下 rar文件1.4G 只下载了600M

**Comment by houtianze** [comment]
有点奇怪，我去试一下，谢谢提供测试目录，下载与文件名无关的，除非百度那边有什么监测，或者你电脑上有什么软件会监测pdf文件？
现在`bypy`下载很慢，1.4G应该会很久。

**Comment by houtianze** [comment]
我试了一下子，下载一晚上只下载60M，然后一直这个错误... ：
`<class 'requests.exceptions.ConnectionError'> - HTTPConnectionPool(host='bjbgp01.baidupcs.com', port=80): Read timed out.`

**Comment by happysoul** [comment]
嗯 无奈了 我是跟斐讯N1盒子上安装的 aarch64 版本的
用最前面的命令ssh执行后，后台下载，小于20M的还好
感觉就是故意不好好提供服务，让人们去买会员。。。
问题是win不会一直开着机，linux的客户端还是x86能用但很难用，其他arm平台无法使用
看来玩死bd，转到189或者阿里盘才是未来的方向。。。

**Comment by fedstryale** [comment]
主要现在上传也慢，svip平均不到500k，也就自动增量备份可以接受，恢复备份用客户端全速下载倒还好

**Comment by aaxiyoook** [comment]
我这下载60多MB，是按20MB20MB的增加显示，下太大确实可能因为网络波动或者百度方面断掉。
<img width="761" alt="截屏2022-09-02 20 41 23" src="https://user-images.githubusercontent.com/79205062/188148997-ec4f7f0a-8a13-4f21-b734-1da8b7066a84.png">
