### ISSUE TITLE
上传错误

### ISSUE THREAD

**Issue by BeanKaKa** [houtianze/bypy#603]
<E> [22:12:19] Error accessing 'https://c.pcs.baidu.com/rest/2.0/pcs/file'
<E> [22:12:19] Function: __upload_slice_act
<E> [22:12:19] Website parameters: {'method': 'upload', 'type': 'tmpfile'}
<E> [22:12:19] Waiting 10 seconds before retrying...
<E> [22:12:29] Request Try #2 / 5

上传的是5m的小文件，服务器是国外的，已尝试忽略ssl证书，依旧无效

**Comment by houtianze** [comment]
刚才试了一下，上传5m文件没有问题。5m文件应该不需要分片，你的怎么出现了`__upload_slice_act`?

**Comment by BeanKaKa** [comment]
> 刚试了一下，上传了5m文件没有问题。5m文件不需要分片，你的出现了怎么`__upload_slice_act`办？

经过测试可能是与宝塔有冲突，我在新环境中取消使用宝塔使用lnmp一键宝后脚本正常的。未尝试复现，不知道能不能复现
