### ISSUE TITLE
How to download offline ？

### ISSUE THREAD

**Issue by samuelwhg** [houtianze/bypy#604]
It can be downloaded on SSH, but it seems to stop after closing

**Comment by samuelwhg** [comment]
![image](https://user-images.githubusercontent.com/86949076/147863573-b79b0692-c512-42ee-834f-b079322163b8.png)

**Comment by whoareyou2021** [comment]
tmux is your friend.

To start a new session:
```
tmux
```

To detach:
'ctrl+b, d'

To re-attach:
```
tmux attach
```
