### ISSUE TITLE
help 文档中存在单词拼写错误

### ISSUE THREAD

**Issue by sunkankanisme** [houtianze/bypy#605]
<img width="465" alt="image" src="https://user-images.githubusercontent.com/26246948/149468986-8de60631-5322-4a9e-8162-6693f4d4bd84.png">

- help 文档中存在单词拼写错误，这行应该是 whoami
whoeami - display the user information

**Comment by houtianze** [comment]
感谢反馈。

是个文档拼写错误（实际命令没错`whoami`）。修正了，等下次有什么其他问题一起发布新版本吧。
