### ISSUE TITLE
能否提供个百度网盘数据转存到阿里云盘的功能

### ISSUE THREAD

**Issue by lvtie** [houtianze/bypy#607]
能否提供个百度网盘数据转存到阿里云盘的功能

**Comment by binsgit** [comment]
[pip3 install b2a](https://github.com/yaronzz/BaiduYunToAliYun)

**Comment by hzhangxyz** [comment]
@houtianze 能不能把改关的issue关了，翻帖子累

**Comment by houtianze** [comment]
@hzhangxyz 哈哈，好吧，我有时间时清理一下。
