### ISSUE TITLE
下载速度问题

### ISSUE THREAD

**Issue by noxplus** [houtianze/bypy#61]
赞一下这个工具, 很不错, 就是速度有点慢.
我这边8M网络, 浏览器直接下载百度云里的文件, 速度接近1M. 但是用这个工具syncdown的时候, 10几分钟才下同步了不到10M.
手动试了下, 在__downtrunks函数里, 如果不加上Range参数, 直接header = '' ,可以观察到网卡上流量近乎1M, 但后面大小验证没通过, 文件也没能写到磁盘上.
是不是可以在这里做下优化, 分情况, 并不一定总要带上range参数?

**Comment by sunzhaoyang** [comment]
请问下载速度的问题找到了么？从百度云网页下载速度能到1M，bypy只能25k，而且重试很多，实在很崩溃。。。

**Comment by houtianze** [comment]
@sunzhaoyang 最新版也这样？这个是挺让人崩溃的，现在还不知道整洁在哪里。。。

只是下载慢，上传速度还可以？

**Comment by sunzhaoyang** [comment]
现在申请不到接口了，本来想学着写一个。不知道百度的接口返回的是一个下载的url还是别的？有没有可能用aria2c 来做下载和断点续传？现在用百度网盘的chrome插件可以直接添加到aria2c rpc，下载速度很快，唯一的弊端就是链接会1小时后失效，但重新添加也可以断点续传很方便。

**Comment by sunzhaoyang** [comment]
没试过上传，我这边基本就是拿来下电影

**Comment by houtianze** [comment]
哦。

我用的是PCS API的接口，下载就是一个简单的HTTP GET请求（需要授权后获得的access token）
http://developer.baidu.com/wiki/index.php?title=docs/pcs/rest/file_data_apis_list#.E4.B8.8B.E8.BD.BD.E5.8D.95.E4.B8.AA.E6.96.87.E4.BB.B6

这个链接也是很好构造，你下载时加上`-dv`参数就应该可以看到请求的url。你可以试试把这个url放入aria2c，看看速度改善是否明显。如果不明显那我推测那个chrome插件用的接口不一样。不过这个插件听起来有点意思，因为是html/js的，可以分析一下，说不定能用来改善下载。

**Comment by houtianze** [comment]
@sunzhaoyang ，你说的那个Chrome插件能给个链接吗？

**Comment by sunzhaoyang** [comment]
就是这个项目https://github.com/acgotaku/BaiduExporter
chrome插件 https://chrome.google.com/webstore/detail/baiduexporter/mjaenbjdjmgolhoafkohbhhbaiedbkno

**Comment by houtianze** [comment]
@sunzhaoyang ，感谢，我看看能挖出点东西不。

**Comment by houtianze** [comment]
服务器的顺序已更换（GAE的最后一个试）：

ac103aed77ab46e712bd44b83039aff73536996a

**Comment by houtianze** [comment]
看了一下，是用百度直接的请求方式（好像是BDUSS cookie验证的），一时半会儿没法直接用过来。。、

速度这个问题我猜应该是百度那面对PCS API做了限制吧。

**Comment by sunzhaoyang** [comment]
恩，应该就是pcs接口限速了。

**Comment by mckelvin** [comment]
DUP: https://github.com/houtianze/bypy/issues/170

我遇到类似的问题（上传太慢），应该是pcs的限制。有2个可以做的优化:

1.  https://github.com/houtianze/bypy/issues/127 提到的换个CDN节点，当前 bypy 还没原生支持这个feature, 我的做法是找到最快的，然后改hosts.

2. 减小chunk size, 对应参数 `--slice`(上传) 和 `--chunk`(下载)，在我的测试环境里， `--slice 5MB` 都很慢，只能  `--slice 2MB` 或者更小。

```
  -s SLICE, --slice SLICE
                        size of file upload slice (can use '1024', '2k',
                        '3MB', etc) [default: 20 MB]
  --chunk CHUNK         size of file download chunk (can use '1024', '2k',
                        '3MB', etc) [default: 20 MB]
```

**Comment by malsony** [comment]
我是年付会员，百度云管家能“加速”到差不多跑满我这边的带宽，但是bypy还是100k不到。

**Comment by houtianze** [comment]
我先把这个issue关了。

下载上传速度低暂时`bypy`也没什么改动能有明显改进。最新版要求要`requests` 2.10以上，不知道会不会有帮助`pip install -U bypy`
