### ISSUE TITLE
进度条

### ISSUE THREAD

**Issue by liziwei01** [houtianze/bypy#611]
希望可以添加上传下载进度条

大文件很长时间没有上传完会怀疑到底是 bug 了还是仅仅没有上传完成

**Comment by liziwei01** [comment]
似乎有进度条，但是偶尔会有进度条不显示的 bug？

**Comment by houtianze** [comment]
对，有进度条，但是要是每隔一段时间（忘了多久，可能是10秒吧）才会更新。
