### ISSUE TITLE
syncup or compare 显示文件不一致，但下载下来比较却是一致的

### ISSUE THREAD

**Issue by qiqjiao** [houtianze/bypy#616]
最近同步了一个文件夹（一共有几十个视频文件，总共29G），syncup老是说有个文件不一致，然后重新上传。试了几次还是这样。我下载下来和本地的比较MD5却显示是一致的。用compare一样，老是说这个文件不一致。我一开始怀疑是不是这个文件特殊，然后"echo 0 >> path/to/file"，然后重试，结果还是说文件不一致。

下面是命令还有一些输出：

$ bypy -e -v syncup /cygdrive/e/Movie.TV/Spartacus /Movie.TV/Spartacus true
…………
[===================_] 99% (880.0MB/881.3MB) ETA: 27s (48kB/s, 4h58m gone) '/cygdrive/e/Movie.TV/Spartacus/Spartacus.Vengeance.S02.EP07.720p.BluRay.x264.AAC-iSCG.mp4' >>==> '/apps/bypy/Movie.TV/Spartacus/Spartacus.Vengeance.S02.EP07.720p.BluRay.x264.AAC-iSCG.mp4' OK.
[====================] 100% (881.3MB/881.3MB) ETA:  (48kB/s, 5h1s gone) Combining the following MD5 slices:
cc40e276b4bd2008ba72aa615c811c07
f3456bd3238d8b8bd2fc7ace4d597c64
298f96b4ab06ad17c6dad70fb34e1e64
7dce768d0e29404e0c7671e61e3f7652
154c6498efee1b7fecdac104cff2611a
7b84aabd37fa51c0d63b041ecc36fc96
866ba30f0d6f38056d43aaec68acd07d
9d89cac6d312dab3c5a4fa123e60b949
de166434f3e178b21b53be8f5258c8e1
6add1968906f4d32e3121b7ea8086ea0
6c86376ce2fb68b94f9348324d82e832
98695b8b2d5a8c1662f0c687c835b45c
202f85272ca1cbdf3077e8683825a425
cab5e43f7a8b1fda2bc0d26c642a1eed
db62f02b67e9aceee979940e9c81973c
71b1b9e76a22b4379ff2316e192e67ee
9c576d4874f52d9ac45800cafc826e9b
da6a49e9b78d3ab8981d59c6e9ddb373
26975f6317193300bd224ed815a711c4
cdc150eb3fe15f31e83df1e2f7dd9a2d
4928fdd656d329ad75c2c8f2831ae01b
e7b464bb13c531b58de75adb4164be6f
282d606e43b8c9e9fde25a717728397a
b3326e5f35442e8a4ad0ad82dee8eba7
e636953112f503abf14eb50ce047d625
df019e136eaa288fa2da1a01b7e3d8fd
c28ea400494e8acc2931048e94bbb4c2
1e430042f2b1e3f406361d5b871c3efe
9ca4f62208eaa3792dc353142623b0da
6796187580c74147a63315006357e66d
012d328b391984f5f3cdd560998eb15d
5f12d0350e0c96eda2903c2a4cc218ff
e6d9bfaeb11615fa981b89643a120a3a
0a1291bdb5e2d9311ac3283b9ac41328
cf6738b1b873635674449fa72e38a75c
5ca2a9dc59bf17317406a6dcfac43d64
43ee664af6290a4a27e572d53697647d
c689906e66ebeb0e2e9a86f255336638
8b66ebd170b03cdbfe3a5af1a1e28c68
c83bd60efae7b9caee98c11a8594ac3b
42abd9554e55e2eb58bc57f2e0e3605b
272931bf632ec0b7009ad406ed5c17eb
cb3c45100d9e048a37cf8595fa6102ef
e24d720095bc29931b819a324fcfd8cf
5236cbfa9ae619b99c0b1d68dcea707e
<I> [22:36:39] Local and remote file hash DOESN'T match
<E> [22:36:39] '/cygdrive/e/Movie.TV/Spartacus/Spartacus.Vengeance.S02.EP07.720p.BluRay.x264.AAC-iSCG.mp4' =C=> '/apps/bypy/Movie.TV/Spartacus/Spartacus.Vengeance.S02.EP07.720p.BluRay.x264.AAC-iSCG.mp4' FAILED.
<E> [22:36:39] ----------------------------------------------------------------
Error 60: MD5 hashes of the local file and remote file don't match each other
Skip saving Hash Cache since it has not been updated.

**Comment by qiqjiao** [comment]
今天又同步了一个文件夹，一共18个文件传完后居然提示有10个文件不一致。手动下载下来比较md5却是一致的。看来这个问题发生的还相当频繁。

**Comment by houtianze** [comment]
这个貌似是因为百度那边的哈希算法有改动，之前有牛人分析过并合并了他提交的代码，但是如果百度再改哈希算法的话，这个问题可能还会出现。
