### ISSUE TITLE
'error_msg': 'app id is empty', 

### ISSUE THREAD

**Issue by wlxxyw** [houtianze/bypy#619]
![image](https://user-images.githubusercontent.com/37426540/182536382-6d6813f2-8e28-430e-9a8b-3fbc0211cc83.png)
![image](https://user-images.githubusercontent.com/37426540/182536722-8077e039-1f0e-41f5-8314-738ccb9efdf3.png)
这是百度更新了API参数列表么?

**Comment by wlxxyw** [comment]
refreshtoken 下
居然好了

**Comment by houtianze** [comment]
感谢反馈。这是令牌过期后百度又多出来一个莫名其妙的错误信息和代码，最新版1.8已经加入处理，会自动刷新令牌。
