### ISSUE TITLE
bypy info 输入授权码后失败

### ISSUE THREAD

**Issue by mumong** [houtianze/bypy#620]
Authorizing, please be patient, it may take upto 300 seconds...
Authorizing with the Vercel server ...
Vercel server failed, Authorizing with the cloudendpoint server ...
Vercel server failed. Last resort: authorizing with the Aliyun server ...
<E> [04:18:15] Fatal: All server authorizations failed.
<I> [04:18:15] ----------------------------------------------------------------
<I> [04:18:15] This is most likely caused by authorization errors.
Possible causes:
 - You didn't run this program for a long time (more than a month).
 - You changed your Baidu password after authorizing this program.
 - You didn't give this program the 'netdisk' access while authorizing.
 - ...
Possible fixes:
 1. Remove the authorization token by running with the parameter '-c', and then re-run this program.
 2. If (1) still doesn't solve the problem, you may have to go to:
    https://passport.baidu.com/accountbind
    and remove the authorization of this program, and then re-run this program.

是在linux上使用的失败，在同一台电脑上用windows的就可以

**Comment by mumong** [comment]
curl -L 那几个网站返回的是html结构体

**Comment by aflyhorse** [comment]
```
Authorizing, please be patient, it may take upto 300 seconds...
Authorizing with the Vercel server ...
Successfully authorized
```
我今天用着没啥问题，坐标：北京教育网

**Comment by houtianze** [comment]
最新版1.8应该授权没有问题了。
