### ISSUE TITLE
快速上传(RapidUploaded)经常失败，http error 404, 提示：code 31079, file md5 not found, you should use upload api to upload the whole file

### ISSUE THREAD

**Issue by clintonlover** [houtianze/bypy#622]
问题：2022-08-10至今(2022-09-01)，上传较大文件(20-100 MB)时，bypy默认先用RapidUploaded，每天开始的少数文件可以成功，但绝大多数文件都会失败；然后bypy再转用普通上传(normal upload)，此时就出现 链接中断 ConnectionResetError(104, 'Connection reset by peer'，或超时 timeout('The write operation timed out'，最终尝试了5次都失败后，终止。

环境与背景:
一直以来(超过1年时间）都在用bypy上传文件，同样的环境下，上传是很好的，很少出问题。我们的环境和上传程序一直没有变化，但从最近2022-08-10左右，开始出现上述问题。
ubuntu18.04, 
bypy v1.6.4, v1.7.12, v1.8 三个版本都碰到上述问题
server从usa 硅谷上传文件，速度限制10Mbit，速度相对较慢，单个文件的快速上传失败后，普通上传的耗时可能超过timeout 5分钟；
换了一个server从UK上传，没有速度限制，快速上传也是会失败，报同样的错误；但普通上传的成功率较高，可能是网速较快，未触及timeout。
bypy -cc重新刷新了token和清除了缓存，问题依然。

总之，快速上传(RapidUploaded)经常失败，试了多个bypy版本（含最新版本v1.8)和多个地域的server和IP，均是如此。
怀疑是badu云盘端的对快速上传RapidUploaded的支持配置或系统更新，出现了问题！

问题日志截图：
![1662003375(1)](https://user-images.githubusercontent.com/31026131/187826414-618526ba-be20-454f-9a32-c56c0a07f30b.png)

**Comment by houtianze** [comment]
谢谢反馈。试了一个普通50m文件，发现`rapidupload`没有问题，我还以为他们md5算法又改了，还好没有。
嗯，我之前放久了也是各种网络错误，可能最近百度服务端又有变化吧。

**Comment by clintonlover** [comment]
> 谢谢反馈。试了一个普通50m文件，发现`rapidupload`没有问题，我还以为他们md5算法又改了，还好没有。 嗯，我之前放久了也是各种网络错误，可能最近百度服务端又有变化吧。

问题找到了一个临时解决办法：我发现在USA和国内ping  c.pcs.baidu.com 和 pcs.baidu.com的反馈IP不同，而国内上传的成功率更高，猜测是baidu的server是按不同地区做分布的，于是把国内ping到的IP 和域名映射，配置USA bypy客户端 系统的/etc/hosts中；虽然RapidUpload还是失败，但后续的NormalUpload 基本都成功了，没有再报timeout和lost connection错误。
感谢@houtianze

**Comment by 1713172499** [comment]
我也是报这个错误，一个800M的带密码的压缩包传不上去。
![image](https://user-images.githubusercontent.com/32571618/188846851-55a39694-2759-48b3-a149-d6e3edbc64ea.png)

**Comment by houtianze** [comment]
@1713172499 你这个属于正常，加密过的文件第一次一般都无法快速上传。

**Comment by 1713172499** [comment]
> @1713172499 你这个属于正常，加密过的文件第一次一般都无法快速上传。

请问是不是压缩包没法传呢，我传一个44M的没密码的zip文件，也是一直返回这个。
