### ISSUE TITLE
Some problems when downloading and replacing files with the same name

### ISSUE THREAD

**Issue by qiqi520i** [houtianze/bypy#623]
If the remote file size is larger than the local file with the same name, it cannot be downloaded from the beginning.

**Comment by qiqi520i** [comment]
我以为国外作者了，不好意思，我说一下我遇到的一些问题。
首先我的下载程序是通过易语言写的，调用的aria2的模块。
起初任何问题都没有，最近几天我发现了一个很纠结的问题。就是当远程文件尺寸大于本地文件时。他并不是重新下载，而且接着本地文件的尺寸进行下载。比如远程文件是一个1.5G，名为123.zip的压缩包。本地文件是一个1G，名为123.zip的压缩包。那么aria2的下载是从1G开始下载的。这也就导致了压缩包出现错误。不存在.aria2控制文件。

**Comment by houtianze** [comment]
这个算是`aria2`的问题？
