### ISSUE TITLE
syncup前后文件名和文件大小一致，但因md5校验码不同被判定为不同文件

### ISSUE THREAD

**Issue by cppcute-pm** [houtianze/bypy#681]
![image](https://github.com/houtianze/bypy/assets/52815433/4b9435d9-cb93-4a76-b63b-bddb63ec7daf)

![image](https://github.com/houtianze/bypy/assets/52815433/55bef7d5-d4a2-494c-8cb3-c5501eeb5e56)

![image](https://github.com/houtianze/bypy/assets/52815433/6aa4dda7-c433-4c38-acf4-e2fbb32524f4)

我第一次syncup后在云盘成功上传了图2的几个文件，因为想用多进程的原因，将其中断，而后再进行syncup的时候，在compare过程中
似乎因为md5校验码不同导致bypy认为云盘的文件和本地文件不一致，而后将云盘文件逐个删除
在两次syncup之间没有任何对本地或者云端对应目录的人为改动，我想问一下校验码不一致是网络的问题还是bypy本身出了问题，应该如何解决。

**Comment by houtianze** [comment]
谢谢反馈。这个是百度那边的问题，他们（第一次）计算的md5就是错的，也没找到解决办法。
