### ISSUE TITLE
需要按下control c 以执行指令

### ISSUE THREAD

**Issue by CharlesNeilWilliams** [houtianze/bypy#703]
我在输入指令，包含bypy info，bypy list，bypy upload等指令时，都需要按下control c 指令才能运行，否则将会一直等待，且终端不返回任何提示消息。

**Comment by qwrazdf** [comment]
我也遇到这个问题，但是ctrl c不就终止命令了吗

**Comment by houtianze** [comment]
加个`-dv`可以输出更多信息：`bypy -dv ...`。`bypy -c`会清除登录信息。

**Comment by SCY-X** [comment]
都需要按下control c 指令才能运行，否则将会一直等待，且终端不返回任何提示消息。 我也是这个问题

**Comment by li-shuxian** [comment]
建议使用[BaiduPCS-Go](https://github.com/qjfoidnh/BaiduPCS-Go) 作为备选项。
他能够覆盖 bypy 的功能，并且现在仍在维护，而 bypy 的上次更新追溯到25年4月

**Comment by SCY-X** [comment]
谢谢，已经使用新的方式












谢懿
***@***.***


---原始邮件---
发件人: "Li ***@***.***&gt;
发送时间: 2026年4月22日(周三) 下午2:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [houtianze/bypy] 需要按下control c 以执行指令 (Issue #703)


li-shuxian left a comment (houtianze/bypy#703)
 
建议使用BaiduPCS-Go 作为备选项。
 他能够覆盖 bypy 的功能，并且现在仍在维护，而 bypy 的上次更新追溯到25年4月
