### ISSUE TITLE
好像是编码问题，无法启动

### ISSUE THREAD

**Issue by huhuang03** [houtianze/bypy#82]
或许不是文件本身的问题，但是能不能帮我看看怎么解决啊。不是很懂python。
python版本：2.6.6
启动的时候报：
Traceback (most recent call last):
  File "bypy.py", line 60, in <module>
    SystemLanguageCode, SystemEncoding = locale.getdefaultlocale()
  File "/usr/lib64/python2.6/locale.py", line 478, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/lib64/python2.6/locale.py", line 410, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

/usr/lib64/python2.6/locale.py, line 478内容:
478     return _parse_localename(localename)

"/usr/lib64/python2.6/locale.py", line 410内容：
    382 def _parse_localename(localename):
    383 
    384     """ Parses the locale code for localename and returns the
    385         result as tuple (language code, encoding).
    386 
    387         The localename is normalized and passed through the locale
    388         alias engine. A ValueError is raised in case the locale name
    389         cannot be parsed.
    390 
    391         The language code corresponds to RFC 1766.  code and encoding
    392         can be None in case the values cannot be determined or are
    393         unknown to this implementation.
    394 
    395     """
    396     code = normalize(localename)
    397     if '@' in code:
    398         # Deal with locale modifiers
    399         code, modifier = code.split('@')
    400         if modifier == 'euro' and '.' not in code:
    401             # Assume Latin-9 for @euro locales. This is bogus,
    402             # since some systems may use other encodings for these
    403             # locales. Also, we ignore other modifiers.
    404             return code, 'iso-8859-15'
    405 
    406     if '.' in code:
    407         return tuple(code.split('.')[:2])
    408     elif code == 'C':
    409         return None, None
    410     raise ValueError, 'unknown locale: %s' % localename

我不是很明白拿本地编码为什么回抛异常了。真是很奇怪啊
方法normalize：
def normalize(localname):
 fullname = localename.lower()
    334     if ':' in fullname:
    335         # ':' is sometimes used as encoding delimiter.
    336         fullname = fullname.replace(':', '.')
    337     if '.' in fullname:
    338         langname, encoding = fullname.split('.')[:2]
    339         fullname = langname + '.' + encoding
    340     else:
    341         langname = fullname
    342         encoding = ''
    343 
    344     # First lookup: fullname (possibly with encoding)
    345     norm_encoding = encoding.replace('-', '')
    346     norm_encoding = norm_encoding.replace('_', '')
    347     lookup_name = langname + '.' + encoding
    348     code = locale_alias.get(lookup_name, None)
    349     if code is not None:
    350         return code
    351     #print 'first lookup failed'
    352 
    353     # Second try: langname (without encoding)
    354     code = locale_alias.get(langname, None)
    355     if code is not None:
    356         #print 'langname lookup succeeded'
    357         if '.' in code:
    358             langname, defenc = code.split('.')
    359         else:
    360             langname = code
    361             defenc = ''
    362         if encoding:
    363             # Convert the encoding to a C lib compatible encoding string
    364             norm_encoding = encodings.normalize_encoding(encoding)
    365             #print 'norm encoding: %r' % norm_encoding
    366             norm_encoding = encodings.aliases.aliases.get(norm_encoding,
    367                                                           norm_encoding)
    368             #print 'aliased encoding: %r' % norm_encoding
    369             encoding = locale_encoding_alias.get(norm_encoding,
    370                                                  norm_encoding)
    371         else:
    372             encoding = defenc
    373         #print 'found encoding %r' % encoding
    374         if encoding:
    375             return langname + '.' + encoding
    376         else:
    377             return langname
    378 
    379     else:
    380         return localename

能帮忙看看这个是什么原因吗

**Comment by houtianze** [comment]
@cf020031308 感谢tip。
