### ISSUE TITLE
9月20日起，syncup 五次均无法秒传（好像是百度的问题）

### ISSUE THREAD

**Issue by xslidian** [houtianze/bypy#85]
每次 `syncup` 操作间隔 5 秒：

<pre>> cat ddbackuplog.20140922.txt | grep "can't be RapidUploaded" | grep www
<D> '/home/doraclub/bak/www.doraclub.cn.20140921.log.gz' can't be RapidUploaded, now trying normal uploading.
<D> '/home/doraclub/bak/20140921.www.doraclub.cn.tar.gz' can't be RapidUploaded, now trying normal uploading.
<D> '/home/doraclub/bak/20140921.www.doraclub.cn.tar.gz' can't be RapidUploaded, now trying normal uploading.
<D> '/home/doraclub/bak/20140921.www.doraclub.cn.tar.gz' can't be RapidUploaded, now trying normal uploading.
<D> '/home/doraclub/bak/20140921.www.doraclub.cn.tar.gz' can't be RapidUploaded, now trying normal uploading.
<D> '/home/doraclub/bak/20140921.www.doraclub.cn.tar.gz' can't be RapidUploaded, now trying normal uploading.</pre>

只有分片上传的大文件出现了这个异常情况。
根据百度云的删除日志，是从9月20日开始出现的（计划任务在北京时间 01:00 执行）。

暂时没来得及确认细节，先在这儿提一个 issue 备查~

-----

9月25日之前，可以通过重命名远程文件，再次秒传，得到正确的 MD5。

Patch 如下：
<pre>--- bypy/bypy.py   2014-09-09 03:19:05.000000000 +0800
+++ ddbackup/bypy.py    2014-09-23 10:05:45.000000000 +0800
@@ -2560,7 +2560,7 @@
            if self.shalloverwrite("Do you want to overwrite '{}' at Baidu Yun? [y/N]".format(p)):
                # this path is before get_pcs_path() since delete() expects so.
                #result = self.delete(rpartialdir + '/' + p)
-               result = self.__delete(rcpath)
+               result = self.move(remotedir + '/' + p, remotedir + '/' + p + '.deleteme.' + "{}".format(time.time()))#self.__delete(rcpath)
                if t == 'F' or t == 'FD':
                    subresult = self.__upload_file(lcpath, rcpath)
                    if subresult != ENoError:
</pre>

9月25日开始，即使按上面的方法，也无法秒传，得到的 MD5 永远是初次生成的那个。

---

29日起情况稍有好转，重传 2~4 次通常能得到正确的 MD5。
![image](https://cloud.githubusercontent.com/assets/127552/4477488/9a482e96-497e-11e4-90bc-327057d8be98.png)

**Comment by fy1128** [comment]
现在这情况我也遇到了。今天到百度云的回收站一看，好几个文件重复了，然后跑了bypy.py -d -v -e -f syncup 测试，确实得不到一致的MD5.

大文件默认分片syncup 到百度云后，sleep 一段时间，再一次syncup，然后发现无法秒传。
小文件上传到百度云后，检验MD5 是与本地一致的。就是分片上传的大文件，compare 也会different。

**Comment by xslidian** [comment]
现在百度那边好像非常不愿意返回完整文件的准确 md5。

目前 `bypy meta 远程文件` 得到的分片 md5 可能是准确的，建议作者添加一个“将就模式”，分片校验值一致就不再尝试。

---

我根据目前已知的分片上传接口增加了一些实现，秒传成功率稍高一些：xslidian/bypy@515e94ac26b7e7e8052ea399c898f200b730655e

但程序已经被改得乱糟糟了，不太适合提请合并。请作者有空时看看有没有可以采纳的地方。

**Comment by houtianze** [comment]
@xslidian 感谢。
等空了我看看是什么逻辑和如何合并。还没仔细看你的更改，据你所了解，`bypye meta`是“准确率高些”还是“近乎每次都准确”

**Comment by houtianze** [comment]
百度边的问题就不搞了，头大 😁
