### ISSUE TITLE
Hi I am using NAS of WD My Cloud

### ISSUE THREAD

**Issue by joutain** [houtianze/bypy#96]
Hi I am using the the NAS of WD My Cloud, there is no Monitor for this NAS, I would have to login with Putty every time to do all these operation, is it possible to package all these function in one WEB UI? that would be very helpful for all the NAS product, thank you very much!

**Comment by malsony** [comment]
oh, sorry, guys... I just started a new thread regarding WebUI before reading this... I know nothing about coding and the only thing I can help is to tell my friends about your project :D

**Comment by houtianze** [comment]
No problem, thanks for the encouraging words :smile:

As there seems to be some demand for this (and I now also think that is more convenient for the user, even compared to a native UI, especially in headless mode), I will consider a WebUI in the future, but it won't be so soon, as currently I plan to focus on refactoring the code and solve some existing issues. When the prog becomes stable and intuitive enough for novices, I _may_ proceed on it, but don't count on it :smile:

**Comment by houtianze** [comment]
Tracked under #180
